### ISSUE TITLE
top level file that includes entire repository

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1002]
We should have a top level file called `All.v` that loads all the packages' `All.v` files, so we can get the entire repository into Coq with just one line.

**Comment by DanGrayson** [comment]
Compiling it would also guard against the use of incompatible notations in two packages.

**Comment by peterlefanulumsdaine** [comment]
This is resolved by #1015 , right?  But see also #1025 .

**Comment by DanGrayson** [comment]
right!

**Comment by DanGrayson** [comment]
Right.
