### ISSUE TITLE
duplicate lemma

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1011]
The lemma at https://github.com/UniMath/UniMath/blob/ab8ae1ff4ec8446eed64108fd6542ebc908b37dc/UniMath/Induction/W/Fibered.v#L102 also occurs at https://github.com/UniMath/UniMath/blob/ab8ae1ff4ec8446eed64108fd6542ebc908b37dc/UniMath/MoreFoundations/Univalence.v#L6 , from which it appears to be copied.  It should be eliminated.

**Comment by siddharthist** [comment]
@DanGrayson Thanks for the catch! I'm happy to tackle this, since I introduced it. I think I just never found the one in `MoreFoundations`.

**Comment by benediktahrens** [comment]
Seems to be resolved, closing.
