### ISSUE TITLE
display of monoid operations

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1019]
It would be nice if there were some way to control how the operation of a monoid is displayed.
Currently, when it occurs in a term, it is always displayed as "x * y", regardless of which of
the two scopes below is open.

```
Notation "x + y" := (op x y) : addmonoid_scope.
Notation "0" := (unel _) : addmonoid_scope.

Delimit Scope addmonoid_scope with addmonoid.

Notation "x * y" := (op x y) : multmonoid_scope.
Notation "1" := (unel _) : multmonoid_scope.

Delimit Scope multmonoid_scope with multmonoid.
```

**Comment by mortberg** [comment]
You can control this by putting the notations in separate Module's:
```
Module add_monoid.
Notation "x + y" := (op x y) : addmonoid_scope.
Notation "0" := (unel _) : addmonoid_scope.

Delimit Scope addmonoid_scope with addmonoid.
End add_monoid.

Module mul_monoid.
Notation "x * y" := (op x y) : multmonoid_scope.
Notation "1" := (unel _) : multmonoid_scope.

Delimit Scope multmonoid_scope with multmonoid.
End mul_monoid.

Import add_monoid.

Goal (forall (X : monoid) (x y : X), x + y = y + x)%addmonoid.

Import mul_monoid.

Goal (forall (X : monoid) (x y : X), x + y = y + x)%addmonoid.
```

The notations in the Module that you import last will be the ones that gets displayed.

**Comment by mortberg** [comment]
Yes, this should work, but I don't think you even need the first Module as you are directly exporting it. Every Coq file is a Module so if you put the multiplication notations at the top-level then they are in the Module defined by the file. If one then wants to override this and have additive notation one just Import the AddNotation Module.
