### ISSUE TITLE
definition of additive category

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1035]
The definition of additive category is this:
```
Definition isAdditive (PA : PreAdditive) : UU := (Zero PA) × (BinDirectSums PA).
Definition Additive : UU := ∑ PA : PreAdditive, isAdditive PA.
```
Thus the zero object and the binary direct sums are given as structure, not as a property.  The customary definition in mathematics, as a property, would be this:
```
Definition isAdditive (PA : PreAdditive) : UU := hasZero PA × hasBinDirectSums PA.
```
We should probably fix this.

Here's the definition of `hasBinDirectSums`:
```
Definition hasBinDirectSums : UU := ∏ (a b : A), ∥ BinDirectSum a b ∥.
```
Here's the definition of `BinDirectSums`:
```
Definition BinDirectSums : UU := ∏ (a b : A), BinDirectSum a b.
```

**Comment by benediktahrens** [comment]
For univalent categories, the two are the same.

For non-univalent categories, I doubt that you can get anything done 
with just the properties, but I would enjoy being proved wrong.

**Comment by DanGrayson** [comment]
I wonder where the difficulty would lie, if there is one.  It might be worthwhile finding out.

On the other hand, the additive and abelian categories of interest in mathematics all come
with explicitly constructed direct sums, such as the Cartesian product of abelian groups.
Is there any example of an additive category whose direct sum operation is not explicit?

By the way, it was Mac Lane, in 1950, who showed that for a category to be additive or abelian
is a property, not a structure.  That includes the group operations on the Hom-sets.

**Comment by DanGrayson** [comment]
A theorem of the form `hasBinDirectSums M -> X` is stronger than one of the form `BinDirectSums M -> X`, so we should prefer to prove it when possible.  If X is not a proposition, we may want to prove both `hasBinDirectSums M -> ∥ X ∥` and `BinDirectSums M -> X`.

**Comment by DanGrayson** [comment]
If we adopt the right definition, then: to show that the category of bounded chain complexes over an additive category is additive will not involve the axiom of choice; to show that the category of chain complexes over an additive category is additive will involve the axiom of choice; and to show that direct sum makes an additive category into a monoidal category will not be possible, so instead one will just assume one has all direct sums given as a hypothesis.

I think I'll switch to using the right definition in my development of exact categories.

**Comment by DanGrayson** [comment]
Currently `isAdditive` doesn't adhere to the proposal in #214.

**Comment by DanGrayson** [comment]
As it happens, the K-theory preprint of mine that I intend to formalize uses only bounded chain complexes, so I won't have to resort to the axiom of choice.

**Comment by DanGrayson** [comment]
It took me about 4 hours to convert 1600 lines of exact category code to using the correct definition of additive category, see commit f811d6d12b83da43999e5244d59d41555ba137c8.

**Comment by benediktahrens** [comment]
On 04/11/2018 07:17, Daniel R. Grayson wrote:
> If we adopt the right definition, then: to show that the category of 
> bounded chain complexes over an additive category is additive will not 
> involve the axiom of choice; to show that the category of chain 
> complexes over an additive category is additive will involve the axiom 
> of choice; and to show that direct sum makes an additive category into a 
> monoidal category will not be possible, so instead one will just assume 
> one has all direct sums given as a hypothesis.
> 
> I think I'll switch to using the right definition in my development of 
> exact categories.

How do you decide what the "right" definition is?

I would think that for most constructions there are two variants: one 
with structure, and one with property.
I would also think that in some cases, the one with property is similar 
to the one with structure, but with one or more prop-eliminations and 
projections into truncations inserted in suitable places. In those 
cases, one might be able to provide both variants.

I believe that we had a discussion with Vladimir about that, in some 
Github issue, in the context of Tomi's work. Maybe it would be good to 
look at that discussion again.

**Comment by DanGrayson** [comment]
The right definition of a word is the one mathematicians customarily use.

**Comment by DanGrayson** [comment]
What about this terminology choice?
```
Definition hasZero := λ C : precategory, ∥ Zero C ∥.
Definition BinDirectSums : UU := ∏ (a b : A), BinDirectSum a b.
Definition hasBinDirectSums : UU := ∏ (a b : A), ∥ BinDirectSum a b ∥.
Definition AdditiveStructure (PA : PreAdditive) : UU := Zero PA × BinDirectSums PA.
Definition isAdditive (PA : PreAdditive) : UU := hasZero PA × hasBinDirectSums PA.
Definition CategoryWithAdditiveStructure : UU := ∑ PA : PreAdditive, AdditiveStructure PA.
Definition Additive : UU := ∑ PA : PreAdditive, isAdditive PA.
```

**Comment by benediktahrens** [comment]
On 04/11/2018 13:04, Daniel R. Grayson wrote:
> What about this terminology choice?
> 
> |Definition hasZero := λ C : precategory, ∥ Zero C ∥. Definition 
> BinDirectSums : UU := ∏ (a b : A), BinDirectSum a b. Definition 
> hasBinDirectSums : UU := ∏ (a b : A), ∥ BinDirectSum a b ∥. Definition 
> AdditiveStructure (PA : PreAdditive) : UU := Zero PA × BinDirectSums PA. 
> Definition isAdditive (PA : PreAdditive) : UU := hasZero PA × 
> hasBinDirectSums PA. Definition CategoryWithAdditiveStructure : UU := ∑ 
> PA : PreAdditive, AdditiveStructure PA. Definition Additive : UU := ∑ PA 
> : PreAdditive, isAdditive PA. |

Sounds good!

**Comment by DanGrayson** [comment]
Fixing the terminology can be easily done -- I'll do that.
