### ISSUE TITLE
precategories with homsets

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1045]
Precategories with homsets are called categories in our code, so we should rewrite code such as this to accept a single parameter of type category:
```
  Context {C : precategory} (hsC : has_homsets C).

  Definition isPushout {a b c d : C} (f : a --> b) (g : a --> c)
             (in1 : b --> d) (in2 : c --> d) (H : f · in1 = g · in2) : UU :=
    ∏ e (h : b --> e) (k : c --> e) (H : f · h = g · k),
    ∃! hk : d --> e, (in1 · hk = h) × (in2 · hk = k).
```

**Comment by siddharthist** [comment]
Which commit fixed this?

**Comment by DanGrayson** [comment]
Well, I looked at it, and since `isPushout` doesn't actually use `hsC`, it's not a problem for it.  But maybe others could be improved.

I'll take another look.  Reopening.

**Comment by siddharthist** [comment]
If `isPushout` doesn't use `hsC`, that hypothesis should be moved until after its definition.

**Comment by benediktahrens** [comment]
On 28/11/2018 20:17, Langston Barrett wrote:
> If |isPushout| doesn't use |hsC|, that hypothesis should be moved until 
> after its definition.

I prefer all section variables to be declared in one spot, namely at the 
beginning of the section. Otherwise they are hard to find.

**Comment by siddharthist** [comment]
Agreed! Perhaps `hsC` shouldn't be a section variable, but instead declared where it is used.

**Comment by benediktahrens** [comment]
On 28/11/2018 23:36, Langston Barrett wrote:
> Agreed! Perhaps |hsC| shouldn't be a section variable, but instead 
> declared where it is used.

Sounds good!

**Comment by benediktahrens** [comment]
This has been fixed, closing.
