### ISSUE TITLE
incorrect parsing precedence

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1048]
In light of Coq's parsing precedence:
```
Reserved Notation "x + y" (at level 50, left associativity).
Reserved Notation "x - y" (at level 50, left associativity).
Reserved Notation "x * y" (at level 40, left associativity).
```
it would be better if both of these were at level 40:
```
Reserved Notation "f · g"  (at level 40, format "f  ·  g", left associativity).
Reserved Notation "g ∘ f"  (at level 50, left associativity).
```

**Comment by benediktahrens** [comment]
On 16/11/2018 09:28, Daniel R. Grayson wrote:
> In light of Coq's parsing precedence:
> 
> |Reserved Notation "x + y" (at level 50, left associativity). Reserved 
> Notation "x - y" (at level 50, left associativity). Reserved Notation "x 
> * y" (at level 40, left associativity). |
> 
> it would be better if both of these were at level 40:
> 
> |Reserved Notation "f · g" (at level 40, format "f · g", left 
> associativity). Reserved Notation "g ∘ f" (at level 50, left 
> associativity). |
> 

Why?

**Comment by DanGrayson** [comment]
Two reasons:

- g ∘ f is "multiplicative".
- g ∘ f is a synonym for f · g

**Comment by benediktahrens** [comment]
Good!

**Comment by DanGrayson** [comment]
Thanks.  I noticed when I typed something like `g ∘ f + p ∘ q`.
