### ISSUE TITLE
Deprecation of Coq `Automatic Introduction` option

### ISSUE THREAD

**Issue by ejgallego** [UniMath/UniMath#1052]
Dear UniMath developers,

the `Unset Automatic Introduction` option has been deprecated in Coq upstream for a while. UniMath is the only development we are aware of that still makes use of this option.

We would indeed like to remove it in the 8.10, as we would prefer Lemma/Theorem statements to be uniform wrt parameter behavior, see https://github.com/coq/coq/pull/9001

What are you thoughts? Would you be OK to port UniMath to the default Coq style?

I guess that if you feel strongly against the porting we could undeprecate the option upstream, but IMHO the default style seems to be a bit cleaner.

**Comment by siddharthist** [comment]
Did that PR remove all uses of this feature, or is there still more to do (i.e. is this issue resolved)?

**Comment by benediktahrens** [comment]
On 17/11/2018 17:55, Langston Barrett wrote:
> Did that PR remove all uses of this feature, or is there still more to 
> do (i.e. is this issue resolved)?

I think it is resolved. We'll close it for now, and reopen it if necessary.
