### ISSUE TITLE
notations in a scope

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1082]
The notations in the file `UniMath/SubstitutionSystems/Notation.v` should be in a scope, so if someone loads all of UniMath, the notations don't become active.

**Comment by DanGrayson** [comment]
We could also add an item to the style guide: All notations should be in a scope, except for certain notations in the Foundations used by all the files.

**Comment by benediktahrens** [comment]
On 23/11/2018 13:03, Daniel R. Grayson wrote:
> The notations in the file |UniMath/SubstitutionSystems/Notation.v| 
> should be in a scope, so if someone loads all of UniMath, the notations 
> don't become active.

Nobody should ever load all of UniMath to do work. Loading all of 
UniMath is good for testing and searching, but nothing else.


Instead of scopes, it is much more useful, in my opinion, to but such 
specialized notations in a submodule. This is not contrary to putting 
notations in a scope, but perpendicular to scopes.

The problem with putting notations just in a scope is that even when a 
scope is not open, the notation is still used in printing.
Putting notations in a submodule means one can load the contents of a 
file without loading the notations.

**Comment by DanGrayson** [comment]
People have various ways of working, so I'd be hesitant to tell anyone how to work, but yes, submodules are good, too, and sometimes more effective.  We could make this change:
```
diff --git a/UniMath/README.md b/UniMath/README.md
index 5c51f27e..4a9e3041 100644
--- a/UniMath/README.md
+++ b/UniMath/README.md
@@ -114,6 +114,8 @@ less fragile and to make the files have a more uniform and pleasing appearance.
 * Use Unicode notation freely, but make the parsing conventions uniform across files.
   All notations, except for certain notations in the Foundations package used everywhere,
   should be local or in a scope.  All scopes, if opened, should be opened only locally.
+  Consider also putting them into a submodule, for then they won't be activated even
+  for printing.
 * Each line should be limited to at most 100 (unicode) characters.  The
   makefile target `enforce-max-line-length` can be used to detect nonconforming
   files, and the target `show-long-lines` can be used to display the
```

**Comment by benediktahrens** [comment]
On 23/11/2018 14:42, Daniel R. Grayson wrote:
> People have various ways of working, so I'd be hesitant to tell anyone 
> how to work, but yes, submodules are good, too, and sometimes more 
> effective. We could make this change:
> 
> |diff --git a/UniMath/README.md b/UniMath/README.md index 
> 5c51f27e..4a9e3041 100644 --- a/UniMath/README.md +++ 
> b/UniMath/README.md @@ -114,6 +114,8 @@ less fragile and to make the 
> files have a more uniform and pleasing appearance. * Use Unicode 
> notation freely, but make the parsing conventions uniform across files. 
> All notations, except for certain notations in the Foundations package 
> used everywhere, should be local or in a scope. All scopes, if opened, 
> should be opened only locally. + Consider also putting them into a 
> submodule, for then they won't be activated even + for printing. * Each 
> line should be limited to at most 100 (unicode) characters. The makefile 
> target `enforce-max-line-length` can be used to detect nonconforming 
> files, and the target `show-long-lines` can be used to display the |


Looks good!
