### ISSUE TITLE
Use of `nat_iso` in MonoidalCategories seems a bad choice

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1091]
The definition
```
Definition left_unitor : UU :=
nat_iso I_pretensor (functor_identity C).
```
in https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/Monoidal/MonoidalCategories.v#L75
seems a bad choice, the following definition of natural isomorphism (in pseudo code) would be easier to use:
```
Definition nat_iso' (F G : functor C D)
\sum (f : \prod (a : C), iso (F a) (G a)), is_natural f 
```
because it would directly give pointwise isomorphisms, which is what one wants.
@varkor : would you agree?

**Comment by varkor** [comment]
That seems like a reasonable definition, as long as it's possible (with some convenience definition) to extract a natural transformation from it. It would probably make constructions directly involving `nat_iso` simpler. I'd be happy with your proposed definition.

**Comment by benediktahrens** [comment]
@rmatthes : This issue seems to be resolved through your overhauling of monoidal categories - can you confirm?

**Comment by rmatthes** [comment]
Yes, there was also the move from `iso` to `z_iso`, and the currently used `nat_z_iso` requires pointwise `is_z_isomorphism`.
