### ISSUE TITLE
subtypeEquality vs subtypeEquality': the latter has better computational behaviour

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1106]
We have both
```
Print subtypeEquality.
subtypeEquality = 
λ (A : UU) (B : A → UU) (is : isPredicate B) (s s' : ∑ x : A, B x),
invmap (subtypeInjectivity (λ x : A, B x) is s s')
     : ∏ (A : UU) (B : A → UU), isPredicate B → ∏ s s' : ∑ x : A, B x, pr1 s = pr1 s' → s = s'

Print subtypeEquality'.
subtypeEquality' = 
λ (A : UU) (B : A → UU) (s s' : ∑ x : A, B x) (e : pr1 s = pr1 s') (is : isaprop (B (pr1 s'))),
total2_paths_f e (let X := λ x x' : B (pr1 s'), pr1 (is x x') in X (transportf B e (pr2 s)) (pr2 s'))
     : ∏ (A : UU) (B : A → UU) (s s' : ∑ x : A, B x), pr1 s = pr1 s' → isaprop (B (pr1 s')) → s = s'

```
@nmvdw has exhibited a situation where transporting along an identity produced using the latter computes while transporting along an idenitity using the former does not.
We are currently unable to produce a minimal working example of that behaviour. But maybe the names should be changed to make the better one look more like the default.

**Comment by mortberg** [comment]
Interesting! Neither seems to rely on any axioms, but if you run:

```
Eval compute in subtypeEquality'.
Eval compute in subtypeEquality.
```

you see how much more complicated `subtypeEquality` is when unfolded. 

Note that we can just change the proof of `subtypeEquality` into the one of `subtypeEquality'`:

```
Corollary subtypeEquality {A : UU} {B : A -> UU} (is : isPredicate B)
   {s s' : total2 (λ x, B x)} : pr1 s = pr1 s' -> s = s'.
Proof.
  intros e. apply (total2_paths_f e), is.
Defined.
```

**Comment by mortberg** [comment]
PS: maybe we should just change the proof as above and delete `subtypeEquality'`?
