### ISSUE TITLE
total2 as record, use of "primitive projections" ?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#111]
As far as I recall, total2 was, at some point, defined as a record type. At the moment, it is defined as an inductive type. (The comments in uuu.v still say that a record type is used.)
What was the reason for changing from record to an ordinary inductive? 

If we switched back to total2 being defined as a record type, we could use the "Set Primitive Projections" option which, as @JasonGross told me, would provide significant speedup of compilation (at least it did for HoTT/HoTT).
It would also provide eta for dependent pairs, which might or might not be something we want.

**Comment by vladimirias** [comment]
Here is from an email I wrote in Oct. 2014 when I changed from "record” to ‘Inductive” and removed “primitive projections”:

> Just a comment - the whole of UniMath (including RezkCompletion) compiles on my laptop 
> in about 5min30sec with primitive projections and for about 6min30sec without.
> 


I did it then with the trunk.  We should check how it is now with 8.5 before deciding anything.

**Comment by benediktahrens** [comment]
On 06/29/2015 02:35 PM, Vladimir Voevodsky wrote:
> Here is from an email I wrote in Oct. 2014 when I changed from
> "record” to ‘Inductive” and removed “primitive projections”:
>
>> Just a comment - the whole of UniMath (including RezkCompletion)
>> compiles on my laptop in about 5min30sec with primitive projections
>> and for about 6min30sec without.
>>
>
>
> I did it then with the trunk.  We should check how it is now with 8.5
> before deciding anything.

It is great to have these measures, thanks. It looks like the benefit 
would be small, then, judging from those numbers.

The context of my question is the following: in a development on top of 
UniMath [1], we are hitting a point where Qed (or Defined) takes very 
long: we have measured 34 minutes for one of them, before starting to 
refactor the code significantly. Now the longest Qed takes 11 minutes.

I am thus looking for ways to make UniMath and [1] faster - the 
primitive projections are one thing I should look at, is what Jason 
Gross said.
There are a few other things I should test, including Opacifying lemmas 
temporarily.


Testing primitive projections will need a few changes to UniMath - at 
least compilation fails at some point in uu0a for the first time.

Maybe what I would like to suggest is *not* having primitive projections 
in the master branch, but in another branch for testing purposes, with 
at least a significant part of UniMath compiling there.

[1] https://github.com/benediktahrens/substitution

**Comment by DanGrayson** [comment]
What about turning off sharing?  Would that speed up your substitution
project?

**Comment by DanGrayson** [comment]
I tried total2 as a record with primitive projections on, and the failure
point in uu0.v might be
a bug, since the error message includes a new variable, q0, and no new
context for it that tells
what it is.

**Comment by benediktahrens** [comment]
On 06/29/2015 04:25 PM, Daniel R. Grayson wrote:
> I tried total2 as a record with primitive projections on, and the failure
> point in uu0.v might be
> a bug, since the error message includes a new variable, q0, and no new
> context for it that tells
> what it is.

Interesting - time to start Jason's bug minimizer!

**Comment by benediktahrens** [comment]
On 06/29/2015 03:54 PM, Daniel R. Grayson wrote:
> What about turning off sharing?  Would that speed up your substitution
> project?

Thanks for the suggestion. I cannot test right now, being on a 
conference, but I'll report back as soon as I have any results.

**Comment by DanGrayson** [comment]
I'm trying to isolate the uu0a problem, but Jason's bug finder stops after
a certain point,
and it's hard to debug, since it doesn't retain the temporary file it ran
through coq, nor
does it display the command line for running it.

The complete status of what I'm doing is visible on my branch at
https://github.com/DanGrayson/UniMath/tree/primitive-projections ,
where I have a makefile target that will run the bug finder, as a
submodule.  Maybe submodules have to be update manually to bring it
in  ...

CC-ing Jason.

**Comment by vladimirias** [comment]
> On Jun 29, 2015, at 3:41 PM, Benedikt Ahrens <notifications@github.com> wrote:
> 
> The context of my question is the following: in a development on top of 
> UniMath [1], we are hitting a point where Qed (or Defined) takes very 
> long: we have measured 34 minutes for one of them, before starting to 
> refactor the code significantly. Now the longest Qed takes 11 minutes.

I would say that this means something is wrong in the approach. Probably more layers of abstraction (in the mathematical sense) are needed so that the proofs do not need to expand too many definitions (in proof assistant terms). 

This whole thing looks a bit strange to me since it is based on http://www.irit.fr/%7ERalph.Matthes/papers/MatthesUustalu-final.pdf <http://www.irit.fr/~Ralph.Matthes/papers/MatthesUustalu-final.pdf> and the later approach by Andre and Marco seem to be conceptually much better. 

In terms of locating where things start going wrong I would suggest that any proof that requires more than 30sec at the Qed is an indication that some bad choices have been made upstream and need to be corrected. 

Vladimir.

**Comment by JasonGross** [comment]
> since it doesn't retain the temporary file it ran
through coq, nor
does it display the command line for running it.


Try passing `-vv` or `-vvv` for more verbose output.  (If you pass `-vvv` or `-vvvv`, I think it might also print the full contents of each file it tries to run through coq.)  If you update to the latest version of the bug-minimizer, it should print the command lines it uses.  If you also pass a third argument (`find-bug.py in_file.v out_file.v temp_file.v`), and a particular coq run fails, it should save the attempt in that temporary file.

**Comment by benediktahrens** [comment]
On 06/29/2015 07:42 PM, Vladimir Voevodsky wrote:
>
> I would say that this means something is wrong in the approach.
> Probably more layers of abstraction (in the mathematical sense) are
> needed so that the proofs do not need to expand too many definitions
> (in proof assistant terms).

I agree. We are looking into that, too, in parallel to improvements we 
could do on the technical side.

> This whole thing looks a bit strange to me since it is based on
> http://www.irit.fr/%7ERalph.Matthes/papers/MatthesUustalu-final.pdf
> <http://www.irit.fr/~Ralph.Matthes/papers/MatthesUustalu-final.pdf>
> and the later approach by Andre and Marco seem to be conceptually
> much better.

The notion of signature in Matthes & Uustalu's paper is pretty similar 
to the one André and Marco are giving in [1].

The notion of model of a signature is different, and I agree that M&U's 
notion is unsatisfactory in some ways.
On the other hand, I have implemented monads and modules and all that 
stuff in my PhD thesis already (based on E-categories, i.e., categories 
with hom-setoids) [2], and it is fun to do something else for a change.

[1] http://arxiv.org/abs/1202.3499
[2] https://github.com/benediktahrens/monads

> In terms of locating where things start going wrong I would suggest
> that any proof that requires more than 30sec at the Qed is an
> indication that some bad choices have been made upstream and need to
> be corrected.

Yes, that sounds very reasonable.

**Comment by DanGrayson** [comment]
On Mon, Jun 29, 2015 at 3:25 PM Jason Gross <notifications@github.com>
wrote:

> since it doesn't retain the temporary file it ran
> through coq, nor
> does it display the command line for running it.
>
> Try passing -vv or -vvv for more verbose output. (If you pass -vvv or
> -vvvv, I think it might also print the full contents of each file it
> tries to run through coq.)
>

Thanks.  Hmm, -vv is already annoyingly verbose, and it doesn't
seem to display the file.  What about just keeping temporary files that are
unsuccessful, and always displaying the command line?

> If you update to the latest version of the bug-minimizer, it should print
> the command lines it uses.
>
We are up to date, at commit acbb5bf2f1ee3c050973ead4531be55efeec26cb.
Here's the part of the output with no command line echoed:

Done.  Splitting to definitions...

Non-fatal error: Failed to split file to definitions and preserve the
error.
The new error was:
File "/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/tmpKKShIU.v", line
4, characters 7-13:
Syntax error: '.' expected after [vernac:gallina_ext] (in [vernac_aux]).

Split not saved.
I will not be able to proceed.

**Comment by DanGrayson** [comment]
I'm ready to submit a bug report.  Does anyone here think it's not a bug?

```
(* 

Run this file with:

   coqc -indices-matter isolatedbug.v

Coq version:

    $ git describe --tags
    V8.5beta2-112-g03d1fa4

    $ git log -1
    commit 03d1fa42c17896cb9d767b509e05bd0db78cb7d2
    Author: Enrico Tassi <Enrico.Tassi@inria.fr>
    Date:   Wed Jun 17 10:34:08 2015 +0200

        Doc: Workers do check for guardedness before sending proofs back

Result:

    Toplevel input, characters 0-21:
    Error: Illegal application: 
    The term "@transportf" of type
     "forall (X : UU) (P : X -> UU) (x x' : X), x = x' -> P x -> P x'"
    cannot be applied to the terms
     "X" : "UU"
     "P" : "X -> UU"
     "pr1 (pr1 q0)" : "X"
     "x" : "X"
     "p" : "pr1 (pr1 q1) = x"
     "pr2 (pr1 q0)" : "P (pr1 (pr1 q0))"
    The 5th term has type "pr1 (pr1 q1) = x" which should be coercible to
     "pr1 (pr1 q0) = x".

The problem:

     q0 is unknown to the user

*)
Unset Automatic Introduction.
Notation UUU := Set .
Notation empty := Empty_set.
Notation empty_rect := Empty_set_rect.
Inductive paths {A:Type} (a:A) : A -> Type := paths_refl : paths a a.
Hint Resolve paths_refl : core .
Notation "a = b" := (paths a b) (at level 70, no associativity) : type_scope.
Notation idpath := paths_refl .
Notation coprod := sum .
Notation ii1fun := inl .
Notation ii2fun := inr .
Notation ii1 := inl .
Notation ii2 := inr .
Implicit Arguments ii1 [ A B ] .
Implicit Arguments ii2 [ A B ] .
Set Primitive Projections.
Record total2 { T: Type } ( P: T -> Type ) := tpair { pr1 : T; pr2 : P pr1 }.
Arguments tpair {T} _ _ _.
Arguments pr1 {_ _} _.
Arguments pr2 {_ _} _.
Definition UU := Type.
Identity Coercion fromUUtoType : UU >-> Sortclass.
Definition fromempty  : forall X : UU , empty -> X.
Proof.
  intro X.
  intro H.
  induction H.
Defined.
Arguments fromempty { X } _ .
Definition idfun (T : UU) := fun (t : T) => t.
Definition funcomp {X Y Z : UU} (f : X -> Y) (g : Y -> Z) :=
  fun (x : X) => g (f x).
Notation "g 'circ' f" := (funcomp f g) (at level 80, right associativity).
Definition pathscomp0 {X : UU} {a b c : X} (e1 : a = b) (e2 : b = c) : a = c.
Proof.
  intros.
induction e1.
apply e2.
Defined.
Notation "p @ q" := (pathscomp0 p q) (at level 60, right associativity).
Definition pathsinv0 {X : UU} {a b : X} (e : a = b) : b = a.
Proof.
  intros.
induction e.
apply idpath.
Defined.
Notation "! p " := (pathsinv0 p) (at level 50).
Definition maponpaths {T1 T2 : UU} (f : T1 -> T2) {t1 t2 : T1}
  (e: t1 = t2) : f t1 = f t2.
Proof.
  intros.
induction e.
apply idpath.
Defined.
Definition pathssec1 {X Y : UU} (s : X -> Y) (p : Y -> X)
  (eps : forall (x : X) , p (s x) = x)
    (x : X) (y : Y) (e : s x = y) : x = p y.
Proof.
  intros.
  apply (pathscomp0 (! eps x)).
  apply (maponpaths p e).
Defined.
Definition constr1 {X : UU} (P : X -> UU) {x x' : X} (e : x = x') :
  total2 (fun (f : P x -> P x') =>
    total2 (fun (ee : forall p : P x, tpair _ x p = tpair _ x' (f p)) =>
      forall pp : P x, maponpaths pr1 (ee pp) = e)).
Proof.
  intros.
induction e.
  split with (idfun (P x)).
  split with (fun p : P x => idpath _).
  unfold maponpaths.
simpl.
  intro.
apply idpath.
Defined.
Definition transportf {X : UU} (P : X -> UU) {x x' : X}
  (e : x = x') : P x -> P x' := pr1 (constr1 P e).
Lemma total2_paths {A : UU} {B : A -> UU} {s s' : total2 (fun x => B x)}
    (p : pr1 s = pr1 s')
    (q : transportf (fun x => B x) p (pr2 s) = pr2 s') : s = s'.
Proof.
  intros.
  induction s as [a b].
  induction s' as [a' b']; simpl in *.
  induction p.
  induction q.
  apply idpath.
Defined.
Lemma total2_paths2 {A : UU} {B : A -> UU} {a1 : A} {b1 : B a1}
  {a2 : A} {b2 : B a2} (p : a1 = a2)
    (q : transportf (fun x => B x) p b1 = b2) :
      tpair (fun x => B x) a1 b1 = tpair (fun x => B x) a2 b2.
Proof.
  intros.
  apply (@total2_paths _ _
    (tpair (fun x => B x) a1 b1) (tpair (fun x => B x) a2 b2) p q).
Defined.
Definition homot {X : UU} {P : X -> UU} (f g : forall x : X, P x) :=
  forall x : X , f x = g x.
Notation "f ~ g" := (homot f g) (at level 70, right associativity).
Definition homotcomp {X Y : UU} {f f' f'' : X -> Y}
  (h : f ~ f') (h' : f' ~ f'') : f ~ f'' := fun (x : X) => h x @ h' x.
Definition invhomot {X Y : UU} {f f' : X -> Y}
  (h : f ~ f' ) : f' ~ f := fun (x : X) => !(h x).
Definition funhomot {X Y Z : UU} (f : X -> Y) {g g' : Y -> Z}
  (h : g ~ g' ) : (g circ f) ~ (g' circ f) := fun (x : X) => h (f x) .
Definition homotfun {X Y Z : UU} {f f' : X -> Y} (h : f ~ f')
  (g : Y -> Z) : (g circ f) ~ (g circ f') := fun (x : X) => maponpaths g (h x).
 
Definition iscontr (T : UU) : UU :=
  total2 (fun (cntr : T)  => forall (t : T), t = cntr).
Lemma iscontrretract {X Y : UU} (p : X -> Y) (s : Y -> X)
  (eps : forall y : Y, p (s y) = y) (is : iscontr X) : iscontr Y.
Proof.
  intros.
  induction is as [x fe].
  split with (p x).
  intro t.
  apply (! (eps t) @ maponpaths p (fe (s t))).
Defined.
Definition hfiber {X Y : UU}  (f : X -> Y) (y : Y) : UU :=
  total2 (fun (pointover : X) => f pointover = y).
Definition hfiberpair {X Y : UU} (f : X -> Y) {y : Y}
  (x : X) (e : f x = y) : hfiber f y :=
    tpair (fun (pointover : X) => f pointover = y) x e.
Lemma hfibertriangle2 {X Y : UU} (f : X -> Y) {y : Y} (xe1 xe2: hfiber f y)
  (ee: pr1 xe1 = pr1 xe2) (eee: pr2 xe1 = maponpaths f ee @ (pr2 xe2)) :
    xe1 = xe2.
Proof.
  intros.
  induction xe1 as [t e1].
  induction xe2 as [t' e2].
  simpl in *.
  fold (hfiberpair f t e1).
  fold (hfiberpair f t' e2).
  induction ee.
  simpl in eee.
  apply (maponpaths (fun e: paths (f t) y => hfiberpair f t e) eee).
Defined.
Definition isweq {X Y : UU} (f : X -> Y) : UU :=
  forall y : Y, iscontr (hfiber f y).
Lemma idisweq (T : UU) : isweq (idfun T).
Proof.
  intros.
unfold isweq.
intro y.
  unfold iscontr.
  split with (tpair (fun (x : T) => idfun T x = y) y (idpath y)).
  intro t.
  induction t as [x e].
  induction e.
  apply idpath.
Defined.
Definition weq (X Y : UU) : UU :=
  total2 (fun (f : X -> Y) => isweq f).
Definition pr1weq {X Y : UU} := @pr1 _ _ : weq X Y -> (X -> Y).
Coercion pr1weq : weq >-> Funclass.
Definition weqccontrhfiber {X Y : UU} (w : weq X Y) (y : Y) : hfiber w y.
Proof.
  intros.
apply (pr1 (pr2 w y)).
Defined.
Definition weqccontrhfiber2 {X Y : UU} (w : weq X Y) (y : Y) :
  forall x : hfiber w y, x = weqccontrhfiber w y.
Proof.
  intros.
unfold weqccontrhfiber.
apply (pr2 (pr2 w y)).
Defined.
Definition weqpair {X Y : UU} (f : X -> Y) (is: isweq f) : weq X Y :=
  tpair (fun (f : X -> Y) => isweq f) f is.
Definition invmap {X Y : UU} (w : weq X Y) : Y -> X :=
  fun (y : Y) => pr1 (weqccontrhfiber w y).
Definition homotweqinvweq {X Y : UU} (w : weq X Y) :
  forall y : Y, w (invmap w y) = y.
Proof.
  intros.
  unfold invmap.
  apply (pr2 (weqccontrhfiber w y)).
Defined.
Definition homotinvweqweq0 {X Y : UU} (w : weq X Y) :
 forall x : X, x = invmap w (w x).
Proof.
  intros.
  unfold invmap.
  set (xe1 := weqccontrhfiber w (w x)).
  set (xe2 := hfiberpair w x (idpath (w x))).
  set (p := weqccontrhfiber2 w (w x) xe2).
  apply (maponpaths pr1 p).
Defined.
Definition homotinvweqweq {X Y : UU} (w : weq X Y) :
  forall x : X, invmap w (w x) = x :=
    fun (x : X) => ! (homotinvweqweq0 w x).
Lemma isweqtransportf {X : UU} (P : X -> UU) {x x' : X}
  (e : x = x') : isweq (transportf P e).
Proof.
  intros.
induction e.
unfold transportf.
simpl.
apply idisweq.
Defined.
Definition hfibersgftog {X Y Z : UU} (f : X -> Y) (g : Y -> Z) (z : Z)
  (xe : hfiber (g circ f) z) : hfiber g z :=
    hfiberpair g (f (pr1 xe)) (pr2 xe).
Lemma constr2 {X Y : UU} (f : X -> Y) (g : Y -> X)
  (efg: forall y : Y, f (g y) = y) (x0 : X) (xe : hfiber g x0) :
    total2 (fun (xe' : hfiber (g circ f) x0) => xe = hfibersgftog f g x0 xe').
Proof.
  intros.
  destruct xe as [y0 e].
  set (eint := pathssec1 _ _ efg _ _ e).
  set (ee := ! (maponpaths g eint) @ e).
  split with (hfiberpair (g circ f) x0 ee).
  unfold hfibersgftog.
  unfold hfiberpair.
  simpl.
  apply (total2_paths2 eint).
  induction eint.
  apply idpath.
Defined.
Lemma iscontrhfiberl1 {X Y : UU} (f : X -> Y) (g : Y -> X)
  (efg: forall y : Y, f (g y) = y) (x0 : X)
    (is : iscontr (hfiber (g circ f) x0)) : iscontr (hfiber g x0).
Proof.
  intros.
  set (f1 := hfibersgftog f g x0).
  set (g1 := fun (xe : hfiber g x0) => pr1 (constr2 f g efg x0 xe)).
  set (efg1 := fun (xe : hfiber g x0) => ! (pr2 (constr2 f g efg x0 xe))).
  apply (iscontrretract f1 g1 efg1).
  apply is.
Defined.
Definition homothfiber1 {X Y : UU} (f g : X -> Y)
  (h : f ~ g) (y : Y) (xe : hfiber f y) : hfiber g y.
Proof.
  intros.
induction xe as [x e].
  apply (hfiberpair g x (!(h x) @ e)).
Defined.
Definition homothfiber2 {X Y : UU} (f g : X -> Y)
  (h : f ~ g) (y : Y) (xe : hfiber g y) : hfiber f y.
Proof.
  intros.
induction xe as [x e].
  apply (hfiberpair f x (h x @ e)).
Defined.
Definition homothfiberretr {X Y : UU} (f g : X -> Y)
  (h : f ~ g) (y : Y) (xe : hfiber g y) :
    homothfiber1 f g h y (homothfiber2 f g h y xe) = xe.
Proof.
  intros.
  induction xe as [x e].
  simpl.
  fold (hfiberpair g x e).
  set (xe1 := hfiberpair g x (! h x @ h x @ e)).
  set (xe2 := hfiberpair g x e).
  apply (hfibertriangle2 g xe1 xe2 (idpath _)).
  simpl.
  assert (ee : forall a b c : Y, forall p : a = b, forall q : b = c,
    !p @ (p @ q) = q).
  { intros.
induction p.
induction q.
apply idpath.
}
  apply ee.
Defined.
Lemma iscontrhfiberl2 {X Y : UU} (f g : X -> Y)
  (h : f ~ g) (y : Y) (is : iscontr (hfiber f y)) : iscontr (hfiber g y).
Proof.
  intros.
  set (a := homothfiber1 f g h y).
  set (b := homothfiber2 f g h y).
  set (eab := homothfiberretr f g h y).
  apply (iscontrretract a b eab is).
Defined.
Theorem gradth {X Y : UU} (f : X -> Y) (g : Y -> X)
  (egf: forall x : X, g (f x) = x)
  (efg: forall y : Y, f (g y) = y) : isweq f.
Proof.
  intros.
  unfold isweq.
  intro y.
  assert (iscontr (hfiber (f circ g) y)).
  assert (efg' : forall y : Y, y = f (g y)).
  { intro y0.
    apply pathsinv0.
    apply (efg y0).
}
  apply (iscontrhfiberl2 (idfun _) (f circ g) efg' y (idisweq Y y)).
  apply (iscontrhfiberl1 g f egf y).
  apply X0.
Defined.
Theorem twooutofsixu {X Y Z K : UU}{u : X -> Y}{v : Y -> Z}{w : Z -> K}
        (isuv : isweq ( funcomp u v ))(isvw : isweq (funcomp v w)) : isweq u.
Proof.
  intros .
  set ( invuv := invmap ( weqpair _ isuv ) ) .
  set ( pu := funcomp v invuv ) .
  set (hupu := homotinvweqweq ( weqpair _ isuv ) : homot ( funcomp u pu ) ( idfun X ) ) .
  set ( invvw := invmap ( weqpair _ isvw ) ) .
  set ( pv := funcomp w invvw ) .
  set (hvpv := homotinvweqweq ( weqpair _ isvw ) : homot ( funcomp v pv ) ( idfun Y ) ) .
  set ( h0 := funhomot v ( homotweqinvweq ( weqpair _ isuv ) ) ) .
  set ( h1 := funhomot ( funcomp pu u ) ( invhomot hvpv ) ) .
  set ( h2 := homotfun h0 pv ) .
  set ( hpuu := homotcomp ( homotcomp h1 h2 ) hvpv ) .
  exact ( gradth u pu hupu hpuu ) .
Defined.
Definition sumofmaps {X Y Z:UU}(fx: X -> Z)(fy: Y -> Z): (coprod X Y) -> Z := fun xy:_ => match xy with ii1 x => fx x | ii2 y => fy y end.
Theorem onefiber' { X : UU } ( P : X -> UU ) ( x : X )
      ( c : forall x' : X , coprod ( x = x' ) ( P x' -> empty ) ) :
  isweq ( fun p : P x => tpair P x p ) .
Proof.
  intros .
  set ( f := fun p => tpair _ x p ) .
  set ( Q1 := hfiber ( @pr1 _ P ) x ) .
  set ( Q2 := total2 ( fun xp : total2 P => ( P ( pr1 xp ) -> empty ) ) ) .
  set ( toQ1Q2 := fun xp : total2 P => fun eorem : coprod ( x = ( pr1 xp ) )
                                                          ( P ( pr1 xp ) -> empty ) =>
                                         @sumofmaps _ _ ( coprod Q1 Q2 )
                                                    ( fun e => ii1 ( tpair _ xp ( ! e ) ) )
                                                    ( fun em => ii2 ( tpair _ xp em ) ) eorem ) .
  set ( ctot := fun xp : total2 P => toQ1Q2 xp ( c ( pr1 xp ) ) ) .
  set ( int1 := fun q1 : Q1 => transportf P  ( pr2 q1 ) ( pr2  ( pr1 q1 ) ) ) .
  set ( int2 := fun q2 : Q2 => @fromempty ( P x ) ( ( pr2 q2 ) ( pr2 ( pr1 q2 ) ) ) ) .
  set ( cint := fun xp : total2 P => ( sumofmaps int1  int2 ) ( ctot xp ) ) .
  apply ( @twooutofsixu _ _ _ _ f cint f ) .
  unfold funcomp .
unfold cint .
unfold f .
unfold ctot .
unfold toQ1Q2 .
simpl .
  induction ( c x ) as [ e | em ] .
  unfold int1 .
simpl .
apply isweqtransportf .
  simpl .
unfold isweq .
 intro p .
induction ( em p ) .
  assert ( efg : forall xp : total2 P , f ( cint xp ) = xp ) .
  set ( dpr := @sumofmaps Q1 Q2 _ pr1 pr1 ) .
  assert ( hint : forall xp : total2 P , dpr ( ctot xp ) = xp ) .
 intro xp .
  unfold ctot .
unfold toQ1Q2.
unfold dpr .
 simpl .
  induction ( c ( pr1 xp ) ) .
apply idpath .
apply idpath .
   intro xp .
  set ( ctotxp := ctot xp ) .
assert ( e : ctotxp = ctot xp ) .
apply idpath .
  unfold cint .
change ( ctot xp ) with ctotxp .
  induction ctotxp as [ q1 | q2 ] .
unfold sumofmaps .
 simpl .
  assert ( e1 : pr1 q1 = xp ) .
set  ( eint := maponpaths ( sumofmaps pr1 pr1 ) e ) .
  simpl in eint.
exact ( eint @ ( hint xp ) ) .
  assert ( e2 : tpair P x ( int1 q1 ) = pr1 q1 ) .
 unfold int1 .
 induction ( pr2 q1 ). 
```

**Comment by DanGrayson** [comment]
Hmm, I guess the "problem" is not just the error message, but also that there even is an error.

**Comment by DanGrayson** [comment]
I submitted a bug report here: https://coq.inria.fr/bugs/show_bug.cgi?id=4273

**Comment by vladimirias** [comment]
This is a very interesting place to discover a problem. The constructions of this theorem (onefiber’ as opposed to onefiber) were invented to avoid the use of a complex match (in the proof of onefiber) and to do everything with induction (eliminators) instead. As such it is an important place in uu0 and we should certainly investigate further.

**Comment by DanGrayson** [comment]
Matthieu fixed that bug last week, and since then I've reported two bugs:

https://coq.inria.fr/bugs/show_bug.cgi?id=4417
https://coq.inria.fr/bugs/show_bug.cgi?id=4418

The first one is in "apply" -- a work-around suggested by Matthieu is to use "refine" instead.  That helps.

The second bug report is more puzzling.  Also it shows the execution time of Coq increasing by a multiple of 5 when primitive projections are on, so we may never want to use them.

**Comment by DanGrayson** [comment]
Matthieu responded to the second bug here:

https://coq.inria.fr/bugs/show_bug.cgi?id=4418#c2

The interesting thing is that he gets dramatic speed-ups simply by replacing "apply"
by "refine".

**Comment by DanGrayson** [comment]
I took another stab at switching our code to using primitive projections (which would
provide eta for pairs) and ran into a bug on the trunk of Coq which I've reported here:

https://coq.inria.fr/bugs/show_bug.cgi?id=4876

Thanks to @JasonGross for his bug isolator!

Latest changes are here: https://github.com/DanGrayson/UniMath/tree/primitive-projections

**Comment by JasonGross** [comment]
I seem to recall `Set Keyed Unification` fixing a few issues with `rewrite` and `Set Primitive Projections`; does this setting (together with `Declare Equivalent Keys` when you need two head constants to be considered the same) help?

**Comment by DanGrayson** [comment]
No, Declare Equivalent Keys doesn't help, and I don't know which two head
constants you have in mind for me.

**Comment by JasonGross** [comment]
Try `Set Keyed Unification. Declare Equivalent Keys unel natmult.`?

**Comment by DanGrayson** [comment]
Nope, that didn't help.

**Comment by JasonGross** [comment]
Oh!  You were trying to rewrite on the LHS, not the RHS.  Try `Set Keyed Unification. Declare Equivalent Keys natmult op. Declare Equivalent Keys natmult unel.`?  I'm not quite sure if this'll work, though. 
@mattam82 might need to provide the right incantation to get `natmult (S 0) x` to unfold into `(op (pr1 X) x (natmult 0 x))` and then get `natmult 0 x` to unfold into `unel x` so that it matches with `op (pr1 ?M194) ?M195 (unel ?M194)`.

**Comment by DanGrayson** [comment]
Meanwhile, I've submitted https://github.com/UniMath/UniMath/pull/393

**Comment by DanGrayson** [comment]
No, that didn't work either.

I'm content to wait for the bug fix.

**Comment by DanGrayson** [comment]
The bug at https://coq.inria.fr/bugs/show_bug.cgi?id=4876 is fixed and the fix will appear in the next patch level for v8.5 of Coq.

**Comment by DanGrayson** [comment]
I tried again and got stuck with a Coq bug, reported here: https://coq.inria.fr/bugs/show_bug.cgi?id=5063

**Comment by DanGrayson** [comment]
I reported another Coq bug here: https://coq.inria.fr/bugs/show_bug.cgi?id=5064

**Comment by DanGrayson** [comment]
I reported another Coq bug here: https://coq.inria.fr/bugs/show_bug.cgi?id=5068

**Comment by DanGrayson** [comment]
I reported another coq bug here: https://coq.inria.fr/bugs/show_bug.cgi?id=5105
