### ISSUE TITLE
Rename EquivalenceExamples, reorganize Adjunctions

### ISSUE THREAD

**Issue by siddharthist** [UniMath/UniMath#1120]
The file EquivalenceExamples doesn't actually use any material on equivalences. It seems to be examples of adjunctions.

I propose that we make a new subdirectory `CategoryTheory/Adjunctions/` to house this file and the content in `Adjunctions.v` (with the latter possibly split up among a few files).

**Comment by benediktahrens** [comment]
On 02/12/2018 22:41, Langston Barrett wrote:
> The file EquivalenceExamples doesn't actually use any material on 
> equivalences. It seems to be examples of adjunctions.
> 
> I propose that we make a new subdirectory |CategoryTheory/Adjunctions/| 
> to house this file and the content in |Adjunctions.v| (with the latter 
> possibly split up among a few files).

Sounds good!
