### ISSUE TITLE
`Extraction` in UniMath

### ISSUE THREAD

**Issue by varkor** [UniMath/UniMath#1129]
I'd like to try using `Extraction` on a small UniMath proof. However, when I try importing `Extraction`, I get an error:
```coq
From Coq Require Extraction. (* Error: Unable to locate library Extraction with prefix Coq. *)
```
I imagine this is something to do with the version of Coq that UniMath builds, but I wasn't able to tell from the Makefile what might be going wrong.

Is there a way to locally enable extraction for UniMath?

**Comment by siddharthist** [comment]
@varkor I don't think anyone has tried this at all (in fact, I think `Extraction` is very seldom used in the wider Coq community, despite being pretty well-advertised). Have you tried using a vanilla version of Coq? UniMath works just fine with official builds of Coq 8.6+.

**Comment by varkor** [comment]
@siddharthist: thanks, I didn't realise UniMath worked with later versions of Coq — I tried with vanilla Coq 8.8.2 and `Extraction` works! (Now I'm running up against https://github.com/coq/coq/issues/6614, but it's progress.)

**Comment by siddharthist** [comment]
@varkor Very glad to hear it! What are you using this for?

**Comment by varkor** [comment]
I'm investigating using the proofs in `SubstitutionSystems` computationally to produce substitution implementations for term grammars automatically. Coq's built-in `Eval` seems to struggle, so I'm seeing whether extracting to OCaml or Haskell is any more successful.
