### ISSUE TITLE
silly lemma

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1135]
In light of
```   
@isofhlevelff
     : ∏ (n : ℕ) (X Y Z : UU) (f : X → Y) (g : Y → Z),
       isofhlevelf n (λ x : X, g (f x)) → isofhlevelf (S n) g → isofhlevelf n f
```
this lemma in `UniMath/Foundations/PartB.v` is silly:
```
@isincltwooutof3a
     : ∏ (X Y Z : UU) (f : X → Y) (g : Y → Z), isincl g → isincl (g ∘ f) → isincl f
```
It's only used twice, so we can easily remove it and its two-step proof.

**Comment by benediktahrens** [comment]
On 18/12/2018 02:04, Daniel R. Grayson wrote:
> In light of
> 
> |@isofhlevelff : ∏ (n : ℕ) (X Y Z : UU) (f : X → Y) (g : Y → Z), 
> isofhlevelf n (λ x : X, g (f x)) → isofhlevelf (S n) g → isofhlevelf n f |
> 
> this lemma in |UniMath/Foundations/PartB.v| is silly:
> 
> |@isincltwooutof3a : ∏ (X Y Z : UU) (f : X → Y) (g : Y → Z), isincl g → 
> isincl (g ∘ f) → isincl f |
> 
> It's only used twice, so we can easily remove it and its two-step proof.

I see good reasons to have the "silly" lemma:

- it will be listed when Search-ing for 'isincl';
- it is not a direct instance of the first.

**Comment by DanGrayson** [comment]
Anyone searching for lemmas involving `isincl` should know that it is the same as
`isofhlevelf 1`, so they should also search for lemmas involving `isofhlevelf`.  As for
your second point, adding almost trivial corollaries just adds bloat.

In any case, what's really silly about this lemma is that in classical mathematics there is
no 2 out of 3 lemma for inclusions.

**Comment by siddharthist** [comment]
I tend to agree with Benedikt on this one. It doesn't always occur to me in the moment to search for the more general lemma. It doesn't add much maintenance burden as long as they're listed one after the other in the same file. 

I agree that too many corollaries can cause an issue, but I think we should allow corollaries as long as they seem likely candidates for `Search`.

**Comment by benediktahrens** [comment]
I suggest we do not remove existing lemmas, unless they are strictly duplicates. I will close this issue.
