### ISSUE TITLE
Duplication: weqdirprod and weqdirprodf

### ISSUE THREAD

**Issue by siddharthist** [UniMath/UniMath#1171]
https://github.com/UniMath/UniMath/blob/da765ab6909c2072be6c1419844afb7dc9ff2d2a/UniMath/CategoryTheory/DisplayedCats/Constructions.v#L45-L51
and
https://github.com/UniMath/UniMath/blob/da765ab6909c2072be6c1419844afb7dc9ff2d2a/UniMath/Foundations/PartA.v#L2268-L2269

**Comment by benediktahrens** [comment]
solved, in #1173 , closing.
