### ISSUE TITLE
remove Circle.v

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1186]
Now that Circle2.v fulfills the goals of Circle.v, we may remove Circle.v

**Comment by arnoudvanderleer** [comment]
What does `Circle2.v` do to make it better than `Circle.v`? And are the differences so small to make it not worth the effort to preserve both files?

**Comment by arnoudvanderleer** [comment]
@benediktahrens @DanGrayson All right, since it is not possible to resolve this issue because a paper depends on Circle2, I will close it.
