### ISSUE TITLE
The All.v files should not export unnamed theorems from tests

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#1195]
The `UniMath.Foundations.All` file exports `UniMath.Foundations.Tests`. This has the consequence that a lot of `Unnamed_thm` shows up in searches and I've noticed that students at the school are then using these in their proofs. For example if I search for `isaset` then this shows up:
```
Unnamed_thm38: isaset = isofhlevel 2
```

Can we either make sure that the Tests file is not exported from the All file or change the Tests file so that it doesn't export all of these unnamed theorems?

**Comment by benediktahrens** [comment]
@DanGrayson : can you help with this?

**Comment by DanGrayson** [comment]
Sure!

**Comment by DanGrayson** [comment]
The purpose of `All.v` is to find out what theorems are usable in formalizations, so really, the best approach would be to just not include any file named `Test.v` or `Tests.v` in those files.
