### ISSUE TITLE
Compilation fails with Coq 8.8.2

### ISSUE THREAD

**Issue by co-dan** [UniMath/UniMath#1207]
I think [due to the recent changes to Coq](https://github.com/UniMath/UniMath/pull/1194) the compilation of UniMath fails for me.

Perhaps you do not want to support 8.8.2 at all, in which case please just close this issue.

```
$ coqc --version
The Coq Proof Assistant, version 8.8.2 (March 2019)
compiled on Mar 6 2019 18:39:19 with OCaml 4.07.1
$ make
make: command: Command not found
make -f build/CoqMakefile.make all
make[1]: Entering directory '/home/dan/ho/UniMath'
COQDEP VFILES
COQC UniMath/Foundations/Init.v
File "./UniMath/Foundations/Init.v", line 193, characters 5-14:
Error: Syntax error: 'Cut' '[' expected after 'Hint' (in [vernac:command]).
```

**Comment by DanGrayson** [comment]
Coq 8.9 is out.  Is there a reason you prefer not to use it?

**Comment by co-dan** [comment]
Sorry, apparently I forgot to reply to this.
I am using an older version of Coq, because there are some libraries that do not compile with 8.9 yet.

**Comment by DanGrayson** [comment]
Those lines seem to be required for UniMath to be compatible with 8.9, see https://github.com/UniMath/UniMath/pull/1194 .

Why not use 8.8 with those other libraries and use 8.9 with UniMath?  We make it easy for you, by building 8.9 and setting emacs up so it uses it automatically with proofgeneral.

**Comment by co-dan** [comment]
> Why not use 8.8 with those other libraries and use 8.9 with UniMath?

The problem arises only when you try to combine several libraries together.

Anyway, I know realize that this is mostly a feature and not a bug, so I am going to close this.

**Comment by DanGrayson** [comment]
Okay.

I don't see how you could combine any other libraries with UniMath, since the basic definitions would all be different, and thus the theorems of one would not be usable in the other.  Which other libraries did you have in mind?
