### ISSUE TITLE
Implicit Arguments settings slow down Coq by a huge factor

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1228]
In the code below, the last statement is accepted instantly.
Uncommenting the two `Local` settings regarding implicit arguments, the last definition takes a long time to be accepted - if it is accepted at all.

Can someone explain why?

```
Require Import UniMath.Foundations.All.
Require Import UniMath.MoreFoundations.All. Import PathsOverNotations.
Require Import UniMath.Algebra.Monoids. Import AddNotation.
Require Import UniMath.SyntheticHomotopyTheory.AffineLine.
Require Import UniMath.NumberSystems.Integers.
Require Import UniMath.Algebra.BinaryOperations.
Require Import UniMath.Algebra.GroupAction.
Require Import UniMath.Algebra.Groups.
Require Import UniMath.SyntheticHomotopyTheory.Circle2.

(*
Local Set Implicit Arguments.
Local Unset Strict Implicit.
*)

Definition circle_induction_function (C : circle → UU) (b : C pt) (l : PathOver b b loop)
  : ∏ x : circle, C x
  := pr1 (circle_induction C b l).

Definition circle_induction_pt (C : circle → UU) (b : C pt) (l : PathOver b b loop)
  : b = circle_induction_function C b l pt
  := pr1 (pr2 (circle_induction C b l)).
```

**Comment by benediktahrens** [comment]
In Circle2.v, the opposite effect happens: removing the local implicit argument settings, type-checking becomes very slow at `set (f := c p).` in 
```
Theorem circle_induction : CircleInduction circle pt loop.
Proof.
  unfold CircleInduction. intros A a p.
  set (f := c p). exists f.
```

**Comment by benediktahrens** [comment]
@DanGrayson : do you have any advice on this issue?

**Comment by DanGrayson** [comment]
It has nothing to do with implicit arguments, as this code triggers it:
```
Require Import UniMath.Foundations.All.
Require Import UniMath.MoreFoundations.All. 
Require Import UniMath.SyntheticHomotopyTheory.Circle2.
Section A.
  Context (circle_induction_function : ∏ (C : circle → Type) (b : C pt), PathOver b b loop → Type)
          (C : circle → Type) (b : C pt).
  Check (circle_induction_function C b C).
End A.
```
I think it's a bug that Coq doesn't more quickly detect that the expression to be checked is ill-typed.

If you agree, I'll report it.

**Comment by benediktahrens** [comment]
On 21/06/2019 17:11, Daniel R. Grayson wrote:
> It has nothing to do with implicit arguments, as this code triggers it:
> 
> |Require Import UniMath.Foundations.All. Require Import 
> UniMath.MoreFoundations.All. Require Import 
> UniMath.SyntheticHomotopyTheory.Circle2. Section A. Context 
> (circle_induction_function : ∏ (C : circle → Type) (b : C pt), PathOver 
> b b loop → Type) (C : circle → Type) (b : C pt). Check 
> (circle_induction_function C b C). End A. |
> 
> I think it's a bug that Coq doesn't more quickly detect that the 
> expression to be checked is ill-typed.
> 
> If you agree, I'll report it.

Yes, that would be great. Thanks a lot!

**Comment by benediktahrens** [comment]
When I do 
```
Time Variables (X : circle → Type) (x : X pt).
Time Variable (p : PathOver x x loop).
```
then the first is instantly, whereas the second takes more than a second:
```
p is declared
Finished transaction in 1.145 secs (1.148u,0.s) (successful)
```
How is this possible?

Is there a way to have more stuff about the type `circle` opaque?

**Comment by DanGrayson** [comment]
I don't know.

**Comment by DanGrayson** [comment]
I reported it as an issue in https://github.com/coq/coq/issues/10421

**Comment by benediktahrens** [comment]
On 23/06/2019 12:02, Daniel R. Grayson wrote:
> I reported it as an issue in coq/coq#10421 
> <https://github.com/coq/coq/issues/10421>

Thanks a lot!

**Comment by arnoudvanderleer** [comment]
@benediktahrens Since this is not really a problem that we can solve, shall we close the issue? Or do you want to document this somewhere on the wiki / in an md file?

**Comment by arnoudvanderleer** [comment]
I'll take that as a "yes". Feel free to reopen it.
