### ISSUE TITLE
add the statements proven by some definitions in Foundations.PartD

### ISSUE THREAD

**Issue by rmatthes** [UniMath/UniMath#1232]
`weqforalltototal` is defined by `make_weq` but the equivalence itself is not displayed as type of the defined notion. Same for `weqhfibertoforall`, `weqforalltohfiber` and `weqonsecfibers`. Something related happens for `weqtotaltoforall`. `foralltototal` is not very readable either with the lack of unicode notation (and `weq` appears too often in that file). One should expect something like  
`weqforalltototal {A : UU} (B : A -> UU) (C : ∏ a, B a -> UU):
    (∏ a : A, ∑ b : B a, C a b)
      ≃ (∑ b : ∏ a : A, B a, ∏ a, C a (b a))).`

**Comment by benediktahrens** [comment]
I agree that it would be great to improve that file a bit. It is certainly good style to add a typing annotation to each definition. The use of unicode is also uncontroversial.

Since this concerns Foundations, could @DanGrayson take care of this?

**Comment by DanGrayson** [comment]
Will do.
