### ISSUE TITLE
A Travis check for changes to sub/coq

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1239]
Frequently PRs accidentally change sub/coq. We should add a check for a change to that submodule to Travis, similar to the check for changes to Foundations.

@DanGrayson : would you mind doing this?

**Comment by DanGrayson** [comment]
I think I did that long ago.  I'll submit a pull request that tests the check.

**Comment by DanGrayson** [comment]
Yes, the check works.

```
Makefile:427: recipe for target 'check-for-submodule-changes' failed
make: *** [check-for-submodule-changes] Error 1
```

Was there a pull request recently where it didn't work?

**Comment by benediktahrens** [comment]
On 23/06/2019 12:58, Daniel R. Grayson wrote:
> Yes, the check works.
> 
> |Makefile:427: recipe for target 'check-for-submodule-changes' failed 
> make: *** [check-for-submodule-changes] Error 1 |
> 
> Was there a pull request recently where it didn't work?


Sorry, it was Marco's PR recently that made me think of it. I did not 
even check whether we had such a check already.

**Comment by benediktahrens** [comment]
Already there, closing.
