### ISSUE TITLE
UniMath/Foundations/Generalities/uuu.v: references to dependent sum as record

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#124]
There are comments in uuu.v saying:

"It contains some new notations for constructions defined in Coq.Init library as well as the definition of dependent sum as a record."

"One could use "Inductive" instead of "Record" here but using "Record" which is equivalent to "Structure" allows us later to use the mechanism of canonical structures with total2."

They give the impression that dependent sums will be defined as records. However the current definition of total2 uses Inductive, not Record.  Perhaps these comments can be removed or corrected.

**Comment by nyraghu** [comment]
I just now saw that these comments are mentioned in issue #111 too.  Apologies for reporting a known issue!

**Comment by benediktahrens** [comment]
Thanks for your comment! I updated the comment in #125 .

**Comment by nyraghu** [comment]
Thank you for the correction.

There's still one comment in line 3 which says that the file defines dependent sums as records:

"It contains some new notations for constructions defined in Coq.Init library as well as the definition of dependent sum as a record."

**Comment by benediktahrens** [comment]
Right, thanks. I updated #125.

**Comment by vladimirias** [comment]
Thanks for reminding us about this inconsistency anyway. I suggest that we remove the comment.

**Comment by benediktahrens** [comment]
Fixed with PR #125 .
