### ISSUE TITLE
Same notation ∃! x, P used for two different things

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1253]
see https://github.com/UniMath/UniMath/pull/1252#issuecomment-511357530

I believe this is a bug.

**Comment by DanGrayson** [comment]
It would make sense to put the hProp definition into the scope "logic".  That's what we do with the two notations for "¬".

**Comment by DanGrayson** [comment]
But is it really a bug?  Since there is a coercion from hProp to Type, how could it ever cause a problem?

**Comment by benediktahrens** [comment]
On 15/07/2019 12:16, Daniel R. Grayson wrote:
> But is it really a bug? Since there is a coercion from hProp to Type, 
> how could it ever cause a problem?

It is is problem when you expect to get the "stronger" thing, but get 
the weaker one.

But even the other way round it can cause problems, since unification 
works less well when working with an hProp that one projects out of via 
the coercion.

**Comment by DanGrayson** [comment]
Well, anyway, it would be good for the user to have control, so I'll put it into the scope "logic".
