### ISSUE TITLE
Travis out of memory when compiling CategoryTheory/Bicategories/DisplayedBicats/Fibration/Fibration2

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1261]
Travis currently fails on master with
```
COQC UniMath/CategoryTheory/Bicategories/DisplayedBicats/Fibration/Fibration2.v
Fatal error: out of memory.
Command exited with non-zero status 2
``` 
On my machine, the file compiles fine.

**Comment by DanGrayson** [comment]
Can you point to the test result on master?

**Comment by DanGrayson** [comment]
Probably the only way to debug this at home is under Linux, since Mac OS X has no way of limiting memory to processes.

**Comment by DanGrayson** [comment]
Pull request #1258 was merged, even though travis didn't pass it.

**Comment by DanGrayson** [comment]
I have an Ubuntu machine here, so if you don't I could try to debug it.

**Comment by benediktahrens** [comment]
On 23/07/2019 00:52, Daniel R. Grayson wrote:
> Pull request #1258 <https://github.com/UniMath/UniMath/pull/1258> was 
> merged, even though travis didn't pass it.

The failure is due to a limitation of Travis, not due to the code of the PR.

**Comment by DanGrayson** [comment]
That may be, but we depend solely on travis for checking pull requests, so pull requests have to pass the test before being accepted.

**Comment by benediktahrens** [comment]
I presume the culprit is `discrete_fiber_data_laws_lassociator_lassociator`, with high memory use at `Qed.` time. 
The easy fix would be to cut the proof in smaller pieces. This would be easy, since this is a proof of an equality, were it not for the `cbn.` at the beginning of the proof, which yields an unreadably large goal.

Any other ideas?

**Comment by DanGrayson** [comment]
I don't have any ideas at all.  How do you know memory use is high at Qed time for that particular result?

**Comment by benediktahrens** [comment]
On 23/07/2019 12:35, Daniel R. Grayson wrote:
> I don't have any ideas at all. How do you know memory use is high at Qed 
> time for that particular result?

Looking at `htop` when stepping through the file shows a peak in memory 
usage when doing the `Qed.`, and again when closing the section at the 
very end of the file.

Note that Travis has just succeeded compiling current master:
https://travis-ci.org/UniMath/UniMath/builds/562530181?utm_source=github_status&utm_medium=notification

This shows that it is not deterministic whether Travis fails or succeeds.

**Comment by DanGrayson** [comment]
I wonder what's making it non-deterministic.  That's bad.

**Comment by nmvdw** [comment]
It would be good to see whether the error can be replicated. Both pull requests were submitted around the time GitHub had problems yesterday (https://www.githubstatus.com/incidents/8x69vj1xyp9v), I think. The other one later that dayhad no problems.

**Comment by DanGrayson** [comment]
I'll take a look at it under Ubuntu 19.04.

**Comment by benediktahrens** [comment]
On 23/07/2019 19:31, Daniel R. Grayson wrote:
> I'll take a look at it under Ubuntu 19.04.

Great, thanks!

**Comment by DanGrayson** [comment]
The file `Fibration2.v` needs 3920000K to compile under Ubuntu 19.04, so it's no wonder it can die under travis.  

Perhaps the indeterminacy results from the demands of other processes running simultaneously.  If so, we could probably restore determinism by setting our own memory limit for the coqc process, somewhat smaller than the memory naturally available.  That seems desirable.  It would also help us, over time, decrease the memory requirement, for we could gradually crank it down if we become expert at reducing memory demand.

Is it possible that the frequent use of `etrans` in that file contributes to the memory use?

The proofs in the file are gigantic and monolithic, so if they were broken into coherent pieces, it might help understanding as well as memory use, but it might take someone who understands the idea of the proofs to do it in a way that makes sense to readers of the resulting proof.

**Comment by DanGrayson** [comment]
By the way, for Coq to use time and memory at the end of a section seems to be something easily avoidable by the designers of Coq.

**Comment by DanGrayson** [comment]
I'll see how much memory can be saved by eliminating the use of `Section`.

**Comment by DanGrayson** [comment]
I've just determined that `Fibration2.v` is the worst memory user, by far.  If it weren't for it, we could compile with 3000000K or less.

**Comment by DanGrayson** [comment]
Well, that's sad: removing the use of `Section` causes it to use more memory.

**Comment by nmvdw** [comment]
> The proofs in the file are gigantic and monolithic, so if they were broken into coherent pieces, it might help understanding as well as memory use, but it might take someone who understands the idea of the proofs to do it in a way that makes sense to readers of the resulting proof.

I have an idea, which might help to make this proof more efficient. I will try to work it out next week to see whether it helps.

**Comment by DanGrayson** [comment]
Good, have a go at it.  I tried putting the three definitions into separate files, but things just got worse (?).  I'm currently out of ideas.

**Comment by DanGrayson** [comment]
Avoiding the use of `cbn` would probably help a lot.

**Comment by DanGrayson** [comment]
If, when single stepping through the proof in ProofGeneral, the current goal would always fit on the screen and be readable and understandable, that would be great advantage.

**Comment by nmvdw** [comment]
This or next week, @maggesi and I will do a pull request where this problem is solved.

**Comment by DanGrayson** [comment]
That would be great!

**Comment by benediktahrens** [comment]
This issue seems to be resolved, closing.
