### ISSUE TITLE
UniMath/Foundations/Generalities/uu0a.v: comment text

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#127]
In uu0a.v, in the comment

   "Note that we do no need [pathscomp0lid] since the corresponding
     two terms are convertible to each other due to our definition of
     [pathscomp0].  If we defined it by inductioning [q] and applying
     [p] then [pathsinv0rid] would be trivial but [pathsinv0lid] would
     require a proof."

I think [pathsinv0rid] and [pathsinv0lid] need to be replaced with [pathscomp0rid] and [pathscomp0lid], respectively.

**Comment by benediktahrens** [comment]
Yes, well spotted!

**Comment by nyraghu** [comment]
I've submitted a pull request for this issue.
