### ISSUE TITLE
compiling under debian 10

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1274]
I can't figure out how to compile under Debian 10 with BUILD_COQIDE=yes any longer.  The library `liblablgtk-extras-ocaml-dev`, mentioned in the install file, is no longer there.  Installing the libraries `liblablgtk2-ocaml-dev liblablgtk2-ocaml liblablgtk2-gl-ocaml-dev liblablgtk2-gl-ocaml` doesn't seem to help.  Upgrading sub/coq to the latest commit on the master branch requires lablgtk3 now, but installing the libraries `liblablgtk3-ocaml-dev liblablgtksourceview3-ocaml-dev` still prevents the configuration script from find the library.

I'm giving up for now ...

**Comment by SnarkBoojum** [comment]
I'm the Debian maintainer for many Coq-related packages.

What is your problem exactly? The coq package does build coqide, and it does so using liblablgtk3-ocaml-dev and liblablgtksourceview3-ocaml-dev, so perhaps it's just a question of documenting this change?

**Comment by benediktahrens** [comment]
@SnarkBoojum : thanks a lot for looking at this. 

I think that Debian 10 has been outdated for a while, and thus this issue might not be relevant any more. I will close this issue - if anybody still using Debian 10 is interested in this, please reopen.
