### ISSUE TITLE
Create new package "BicategoryTheory"

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1276]
Travis cannot compile UniMath/TypeTheory any more:

https://travis-ci.org/UniMath/TypeTheory/builds/569739915?utm_source=github_status&utm_medium=notification

One of the reasons is the growth of the material on bicategories, which makes CategoryTheory long to compile.

I suggested before to split out Bicategories into a separate package (which is not required for UniMath/TypeTheory). I herewith suggest it again.

**Comment by DanGrayson** [comment]
Sounds good to me.  Let's call it "BicategoryTheory".

**Comment by benediktahrens** [comment]
@maggesi : Could you take care of this?

**Comment by maggesi** [comment]
> @maggesi : Could you take care of this?

Yes, I will do it.

**Comment by co-dan** [comment]
This issue is fixed already>

**Comment by benediktahrens** [comment]
@co-dan : yes, it is fixed, thanks for notifying me. Closing.
