### ISSUE TITLE
a warning

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1279]
```
COQC UniMath/Bicategories/DisplayedBicats/Examples/Monads.v
File "./UniMath/Bicategories/DisplayedBicats/Examples/Monads.v", line 330, characters 0-86:
Warning: bigmonad_to_monad does not respect the uniform inheritance condition
[uniform-inheritance,typechecker]
```

**Comment by DanGrayson** [comment]
Maybe we should change this warning to an error message.

**Comment by nmvdw** [comment]
If you want, we can remove this coercion. We kept it in, because we didn't have problems with it.

**Comment by DanGrayson** [comment]
Yes, let's get rid of it.

Doesn't the warning imply that the coercion doesn't "work"?

**Comment by nmvdw** [comment]
Upon further inspection, we didn't need that particular coercion. Just removing it, didn't give any errors. In addition, it seems that it doesn't work and that it doesn't get invoked:
```
Definition a_function {C : bicat} (X : C) : monad C X → monad C X.
Admitted.

Fail Definition do_a_coercion {C : bicat} (m : bigmonad C)
  : a_function _ m = a_function _ m.
```

Hence, it is better to remove it.

**Comment by benediktahrens** [comment]
Seems fixed, closing.
