### ISSUE TITLE
UniMath/Foundations/Generalities/uu0a.v: precedence levels of circ and ~

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#128]
The current precedence levels are

Notation "g 'circ' f" := (funcomp f g) (at level 80, right associativity).

and

Notation "f ~ g" := (homot f g) (at level 70, right associativity).

Perhaps it would be better to give circ a smaller precedence level than ~, so that we can write, e.g.,

p circ s ~ idfun X

instead of 

(p circ s) ~ idfun X.

**Comment by benediktahrens** [comment]
Yes, in general it seems reasonable to give "~" a very high level. Can we also think of an upper bound,
e.g., should it be lower than "->"?

In theories/Init/Notations, we have 
Reserved Notation "x -> y" (at level 99, right associativity, y at level 200).

**Comment by nyraghu** [comment]
I think the precedence level of ~ should be smaller than that of infix operators which act on two types and produce another type, e.g., × and ≃ from UniMath.RezkCompletion.UnicodeNotations, where they are given  a precedence level of 80. Perhaps the precedence level of ~ should be smaller than that of = also ---  I wonder if one needs to write things like (f ~ g) = (h ~ k), in which case, it is easier to write f ~ g = h ~ k. The infix operator = is given a precedence level of 70 in UniMath.Foundations.Generalities.uuu.  So I suggest a precedence level strictly less than 70 for ~.

The precedence level of circ then has to be even smaller.  Was there a serious reason to change it from the level 40 that is specified in Coq.Program.Basics?

**Comment by nyraghu** [comment]
I can live with writing parentheses around the arguments of ~ whenever it's needed.  Therefore, I suggest that the authors close this issue.

**Comment by DanGrayson** [comment]
I think it's a good idea to think carefully about parsing precedence, and I like the original
suggestion, which will eliminate some parentheses.  So I'm in favor of keeping this open.

**Comment by DanGrayson** [comment]
This appears to have been fixed, as the parsing precedence is now lower:

```
Notation "g ∘ f" := (funcomp f g) (at level 50, left associativity).
```

**Comment by vladimirias** [comment]
Can we have a comment in README that we want to phase it out? I mean any notation for funcomp f g that permutes f and g?

**Comment by DanGrayson** [comment]
No, this notation is standard mathematical notation:
```
Notation "g ∘ f" := (funcomp f g) (at level 50, left associativity).
```

**Comment by vladimirias** [comment]
Actually, I was thinking more about morphisms in precategory_data. What do we have for composition there? Do we also have two notations for two orderings?

**Comment by DanGrayson** [comment]
There is just this silly thing for composition in a category in UnicodeNotations.v:
```
Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g", left associativity).
```

**Comment by vladimirias** [comment]
Is there something very similar to \cdot ?

**Comment by DanGrayson** [comment]
How about this: ⊙

**Comment by DanGrayson** [comment]
There is also this: ⊚

**Comment by DanGrayson** [comment]
And this : • , already in use for functor composition.
