### ISSUE TITLE
UniMath/Foundations/Generalities/uu0a.v: pretty-printing of ~

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#129]
Coqdoc wrongly pretty-prints the homotopy infix operator ~ as the negation symbol ¬ in the HTML documentation created by "make doc".  [Section 15.4.1 of the Coq manual](https://coq.inria.fr/distrib/V8.5beta2/refman/Reference-Manual017.html#coqdoc) says that this translation is specified by the current pretty-printing table.  To correct it, it appears that one has to write

(** printing ~ #~# *)

or perhaps

(** remove printing ~ *)

in each file that uses the ~ notation.

**Comment by benediktahrens** [comment]
I find all the entries of the whole pretty-printing table unnecessary and confusing. More specifically:

* it breaks copy-and-paste from HTML into vernacular files
* the benefit is minimal
* the right solution to this problem (if one considers it to be one) is Unicode, in my opinion
* in particular, the "star" is also used in proof mode as one of the "bullet" levels, and there should not be translated to "times" at all anyway, but is nevertheless.

I am thus suggesting to remove all pretty-printing, not just the one for tilde.

Do you know of a global option to remove all pretty-printing?

**Comment by DanGrayson** [comment]
There doesn't seem to be such a command line option.  I bet they'd accept a pull request from us that implemented one.

**Comment by nyraghu** [comment]
A heavy-handed way to do this is to remove "-utf8" from COQDOCFLAGS and from COQDOC in the UniMath Makefile.  But this would destroy all Unicode text in comments, e.g., non-breaking space between two identifiers in a Coq code snippets like [foo&nbsp;x].

**Comment by benediktahrens** [comment]
On 08/14/2015 04:56 PM, N. Raghavendra wrote:
> A heavy-handed way to do this is to remove "-utf8" from COQDOCFLAGS
> and from COQDOC in the UniMath Makefile.  But this would destroy all
> Unicode text in comments, e.g., non-breaking space between two
> identifiers in a Coq code snippets like [foo&nbsp;x].

Note that there are a few files in UniMath/RezkCompletion that make use
of Unicode not just in comments, but in the actual code.

**Comment by nyraghu** [comment]
Sorry, I didn't know that.  So anyway this isn't a way out.

**Comment by nyraghu** [comment]
As an experiment, I've generated the docs with the command

`make COQDOC=sub/coq/bin/coqdoc COQDOCFLAGS=-interpolate ENHANCEDDOCTARGET=~/nyraghu-github-io/unimath doc`

I've kept the files on [GitHub](http://nyraghu.github.io/unimath/toc.html).  As far as I can see, the Unicode text seems to be rendered properly,  see, e.g., [UniMath.RezkCompletion.UnicodeNotations](http://nyraghu.github.io/unimath/UniMath.RezkCompletion.UnicodeNotations.html).  Is it satisfactory?

**Comment by DanGrayson** [comment]
Thanks, I've fixed our makefile, following your suggestion.

**Comment by nyraghu** [comment]
Thanks for the fix.

**Comment by nyraghu** [comment]
By the way, what do proofs-toggle.js and proofs-toggle.sed do?  Do they allow one to show and hide proofs in the HTML pages.  If so, it isn't working for me.

**Comment by benediktahrens** [comment]
On 08/15/2015 11:27 AM, N. Raghavendra wrote:
> By the way, what do proofs-toggle.js and proofs-toggle.sed do?  Do
> they allow one to show and hide proofs in the HTML pages.  If so, it
> isn't working for me.

Yes, that is what they should do.
I have filed a bug report [1].

[1] https://github.com/gverdier/coqdoc-overlay/issues/1

**Comment by benediktahrens** [comment]
On 08/15/2015 11:27 AM, N. Raghavendra wrote:
> By the way, what do proofs-toggle.js and proofs-toggle.sed do?  Do
> they allow one to show and hide proofs in the HTML pages.  If so, it
> isn't working for me.

Can you please check if PR #138 works for you?

**Comment by nyraghu** [comment]
Yes, it does!  Thanks.

**Comment by benediktahrens** [comment]
Thanks for pointing the problem out!

Am 15. August 2015 16:35:17 MESZ, schrieb "N. Raghavendra" <notifications@github.com>:

**Comment by benediktahrens** [comment]
Was resolved by PR #135 , closing.

**Comment by nyraghu** [comment]
At 2015-08-25T02:07:17-07:00, Benedikt Ahrens wrote:

> Was resolved by PR #135 , closing.

The -utf8 flag is still there in the form of

COQDOC := $(COQDOC) -utf8 --charset utf-8

in the Makefile, `make -n doc' gives

"sub/coq/bin/coqdoc" -utf8 --charset utf-8 -toc -interpolate -html ...

and the files that `make doc' creates still have pretty printing.  So I
don't think the issue is resolved.  I guess the above definition should
be just

COQDOC := $(COQDOC) --charset utf-8

if one doesn't want pretty-printing in the files created by `make doc'.

Cheers,
Raghu.

-- 
N. Raghavendra <raghu@hri.res.in>, http://www.retrotexts.net/
Harish-Chandra Research Institute, http://www.hri.res.in/

**Comment by DanGrayson** [comment]
See https://github.com/UniMath/UniMath/pull/141

**Comment by DanGrayson** [comment]
I think a conflicting merge got me hornswoggled.

**Comment by nyraghu** [comment]
Thanks!

At 2015-08-25T04:59:37-07:00, Daniel R. Grayson wrote:

> See #141
>
> -
> Reply to this email directly or view it on GitHub.Web Bug from https:
> //github.com/notifications/beacon/
> AK0tJ0tMh-gGSYeVzHi4K-xRRNrpGOY1ks5orFApgaJpZM4FqiJI.gif
>
>
>

-- 
N. Raghavendra <raghu@hri.res.in>, http://www.retrotexts.net/
Harish-Chandra Research Institute, http://www.hri.res.in/
