### ISSUE TITLE
CoqIDE 8.10 requires Gtk3

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1290]
```
You have native-code compilation. Good!
You have the Num library installed. Good!
LablGtk3 not found:
=> cannot build requested CoqIde
Configuration script failed!
Makefile:234: recipe for target 'sub/coq/config/coq_config.ml' failed
make: *** [sub/coq/config/coq_config.ml] Error 1
```
Requires update to 
- Travis configuration file
- Installation instructions

**Comment by DanGrayson** [comment]
I've just spent 2 hours trying to figure this out without success.  Probably someone who knows the details of how to use "opam" could figure it out.  Maybe we should just not bother to support coqide.

**Comment by DanGrayson** [comment]
The Mac OS X user could just use brew to install Coq and CoqIDE, currently at version 8.10.0.  Under the latest Ubuntu, which is at version 19, coq and coqide are available at version 8.6.

**Comment by maggesi** [comment]
Why not use the binary codes distributed by the Coq team directly?

It would save time during testing with Travis. 

Also, the use of submodule in git is sometimes tricky, and people get easily confused when they upgrade an existing installation.

That said, I don't know anyone using CoqIde.

**Comment by DanGrayson** [comment]
The binary coq releases at https://github.com/coq/coq/releases/tag/V8.10.0 don't include Ubuntu 16.04 as a target.  (That's what travis runs under.)

**Comment by DanGrayson** [comment]
Meanwhile, I've figured out how to build it on Mac OS X.

**Comment by DanGrayson** [comment]
... and under Ubuntu.

**Comment by langston-barrett** [comment]
Travis CI also supports Ubuntu 18.04: https://docs.travis-ci.com/user/reference/bionic/ 

I agree with @maggesi, since we don't use a modified version of Coq anymore it makes sense just to use the pre-built binaries. I don't know of another large Coq project that includes Coq itself in its build system.

**Comment by DanGrayson** [comment]
It makes sense to keep coq as a submodule so we know exactly what coq our target is when developing proofs, and it will help immensely if we are using a new feature or bug fix.   Also, it prevents us having to deal with bug reports that come from users using various versions of coq.  Moreover, we may return to using a modified version of coq.

**Comment by DanGrayson** [comment]
As an example, the coq that comes with Ubuntu 19.04 is back at version 8.6 still, from 2 years ago.

**Comment by DanGrayson** [comment]
And now I've learned how to make a new docker container and set up opam in it so UniMath will build both on the master branch and with v8.10 of coq.  Here's my current recipe:
```
make the docker container:

   docker create --privileged --name ubuntu19 --hostname ubuntu19 --tty --interactive ubuntu:19.04 /bin/bash

set it up:

   docker start ubuntu19
   docker exec -it --privileged ubuntu19 bash -c 'stty -echo -onlcr ; cd /root ; exec bash -l'
   apt-get update
   apt-get upgrade -y
   apt-get install -y --quiet --no-install-recommends opam pkg-config libcairo2-dev libexpat1-dev libgtk-3-dev libgtksourceview-3.0-dev libexpat1-dev libgtk2.0-dev mccs m4 git ca-certificates camlp5 libgtksourceview2.0-dev
   opam init --bare
   opam switch create --empty empty
   opam install -y --solver=mccs num lablgtk conf-gtksourceview lablgtk3-sourceview3 camlp5
```

**Comment by DanGrayson** [comment]
... and here it is: https://cloud.docker.com/repository/docker/danielgrayson/unimath

**Comment by benediktahrens** [comment]
Done, closing.

Thanks a lot, @DanGrayson !

**Comment by DanGrayson** [comment]
@palmskog --- we've started using a docker image I just created, so probably you can safely delete the one you created for us a few years ago.  Thanks for all the help!
