### ISSUE TITLE
TAGS file empty

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#1296]
I am on commit 072045cded.  When I try to make the tags for the project, I get an empty file.

``` bash
$ make TAGS
ETAGS
$ etags --version
etags (GNU Emacs 27.0.50)
```
The file TAGS looks like this (just file names, no identifiers):

```
^L
UniMath/All.v,0
^L
UniMath/Induction/All.v,0
...
UniMath/Foundations/Preamble.v,0
^L
UniMath/Foundations/Init.v,0
```

**Comment by DanGrayson** [comment]
I wonder if there's some difference between etags 27.0.50 and etags 26.3.  It doesn't come from a stable release of emacs, so perhaps the first thing to try is the older version.

Also, make sure you have no local changes to the Makefile: your TAGS file has the files listed in reverse order!  Are the files listed in reverse order on the command line now?  `make VERBOSE=1`

**Comment by nyraghu** [comment]
I'll try to find if the Emacs version is the problem.  About the other points, no local changes, and yes the tags file has the files in the reverse order with respect to the etags command.

``` bash
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ make VERBOSE=1 TAGS
etags --language=none -r '/^[[:space:]]*\(\(Canonical\|Monomorphic\|Global\|Local\|Private\|Program\|\)[[:space:]]+\)?\(Axiom\|Class\|Coercion\|CoFixpoint\|CoInductive\|Corollary\|Definition\|Example\|Fact\|Fixpoint\|Function\|Identity[[:space:]]+Coercion\|Inductive\|Instance\|Lemma\|Ltac\|Module[[:space:]]+Import\|Module\|Notation\|Proposition\|Record\|Remark\|Scheme[[:space:]]+Equality[[:space:]]+for\|Scheme[[:space:]]+Induction[[:space:]]+for\|Scheme\|Structure\|Theorem\|Universe\)[[:space:]]+\([[:alnum:][:nonascii:]'\''_]+\).?.?.?.?/\4/' -r "/^[[:space:]]*Notation.* \"'\([[:alnum:][:nonascii:]'\''_]+\)'/\1/" -r '/^[[:space:]]*Tactic[[:space:]]+Notation.*[[:space:]]"\([[:alnum:][:nonascii:]'\''_]+\)"[[:space:]]/\1/' -r '/^[[:space:]]*Delimit[[:space:]]+Scope[[:space:]]+[[:alnum:][:nonascii:]'\''_]+[[:space:]]+with[[:space:]]+\([[:alnum:][:nonascii:]'\''_]+\)[[:space:]]*\./\1/' UniMath/Foundations/Init.v UniMath/Foundations/Preamble.v UniMath/Foundations/PartA.v ... UniMath/Induction/All.v UniMath/All.v
```

**Comment by nyraghu** [comment]
As you said, it seems to be a problem with the Emacs version.  The tags table is as expected when I try it with etags from Emacs 26.3.

``` bash
$ export PATH=/tmp/emacs-26.3/lib-src:${PATH}
$ etags --version
etags (GNU Emacs 26.3)
$ rm -f TAGS
$ make TAGS
ETAGS
$ cat TAGS
^L
UniMath/Foundations/Init.v,268
Notation "'∏'^?∏^A12,422
Notation "'λ'^?λ^A16,618
Ltac contradicts a b^?contradicts^A160,6142
Ltac simple_rapply p :^?simple_rapply^A164,6265
...
```

**Comment by nyraghu** [comment]
Commit https://github.com/emacs-mirror/emacs/commit/d904cc83f3036db seems to be relevant, as well as this quote [from the emacs-devel mailing list](https://lists.gnu.org/archive/html/emacs-devel/2018-07/msg00735.html)  discussion of that change:

> Perhaps 'etags' users are using GNU extensions in their regular expressions, and if we switch to the libc API their usage will break. 

Anyway I'll try to find regexps which work for my version of etags.
