### ISSUE TITLE
UniMath/Foundations/Generalities/uuu.v: arguments declaration of tpair

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#130]
I think the Arguments declaration for tpair in uuu.v is superfluous, because T is already declared implicit in the definition of total2.  Perhaps it can be removed.

**Comment by benediktahrens** [comment]
On 08/13/2015 09:38 PM, N. Raghavendra wrote:
> I think the Arguments declaration for tpair in uuu.v is superfluous,
> because T is already declared implicit in the definition of total2.
> Perhaps it can be removed.

Right, the statement is superfluous.

Would you be interested in filing a pull request?

**Comment by nyraghu** [comment]
Sure, will do that.

**Comment by nyraghu** [comment]
I've submitted a pull request for this issue.

**Comment by benediktahrens** [comment]
On 08/14/2015 12:03 PM, N. Raghavendra wrote:
> I've submitted a pull request for this issue.

Great, thanks a lot!
