### ISSUE TITLE
How does the Google group work?

### ISSUE THREAD

**Issue by JuhoKupiainen** [UniMath/UniMath#1306]
It says that I don't have permission to view the group. How does the mailing list work? Do I just send an email? Should I add my email to the message body? What I wanted to say in the group was that for a project like this it could be really useful to have a virtual machine (like docker or something) that has everything installed on it and working.

**Comment by DanGrayson** [comment]
I guess you're referring to this group: https://groups.google.com/forum/#!forum/univalent-mathematics -- it seems to be "shared privately", whereas other groups are "shared publicly".  I suppose that means only members get to see it.  Benedikt, should we change that?

About a docker machine, try this one: https://hub.docker.com/repository/docker/danielgrayson/unimath , and let us know how close it comes to your needs.  This machine was made as a base for testing pull requests, without human users in mind.

**Comment by benediktahrens** [comment]
On 04/12/2019 16:21, Daniel R. Grayson wrote:
> I guess you're referring to this group: 
> https://groups.google.com/forum/#!forum/univalent-mathematics -- it 
> seems to be "shared privately", whereas other groups are "shared 
> publicly". I suppose that means only members get to see it. Benedikt, 
> should we change that?

Yes, it was unintentionally set to "shared privately". I have now 
changed that setting, and the group should be visible publicly.

**Comment by benediktahrens** [comment]
Fixed, closing.
