### ISSUE TITLE
Several files: terminal white space

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#131]
There are several files which contain instances of terminal white space, i.e., white space after periods, etc.  Perhaps these can be removed.

**Comment by benediktahrens** [comment]
I fear that even if we remove them now, there will always be some new terminal white spaces introduced when editing files. So the removal should be done via a script that can be run periodically, maybe before submitting a pull request. 
I don't know how to implement such a script, but if you do, I'll happily use it.

**Comment by nyraghu** [comment]
I can try running Emacs in batch mode to execute the "whitespace-cleanup" function on all .v files.  Alternatively, one can use sed, but the advantage of Emacs whitespace-cleanup is that it removes a variety of white space, and it may be tedious to write sed commands for all that.

**Comment by DanGrayson** [comment]
It's one command in emacs...

**Comment by nyraghu** [comment]
Great!  How did you do it  for all the files with one command in Emacs?

**Comment by DanGrayson** [comment]
I used M-x tags-query-replace with the search string [ ^I]+$ and pressed Y
as my response.
Run "make TAGS" first to get the tags file made.

**Comment by nyraghu** [comment]
Thanks, I might need to use it sometime.

**Comment by DanGrayson** [comment]
Note that ^I means TAB.

**Comment by DanGrayson** [comment]
The consensus seems to be that removing white space is not worth the trouble, so I'm closing the issue.
