### ISSUE TITLE
github actions instead of travis

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1324]
We've just started using "github actions" for Macaulay2, see our first result here: https://github.com/Macaulay2/M2/actions/runs/132744336 -- much more CPU time is provided than with travis, so we may want to switch and stop using a docker image, which adds a complication.

**Comment by DanGrayson** [comment]
"GitHub runs jobs in parallel, by default, up to a limit of 20 for a free account. (Note that there is further limit of 5 for macOS jobs.) Each job can run for up to 6 hours, and the workflow itself is limited to 72. Details [here](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits)."

**Comment by benediktahrens** [comment]
That sounds good! If I understand correctly, the action is also configured via a .yml file that is part of the repository, and the file format is similar to that for travis?

If UniMath/UniMath transitions to a new CI, it would make sense to transition also UniMath/TypeTheory and UniMath/largecatmodules.

**Comment by DanGrayson** [comment]
Yes, here's our action file now: https://github.com/Macaulay2/M2/blob/master/.github/workflows/test_build.yml

**Comment by benediktahrens** [comment]
When making the switch, we could also rename the `master` branch: https://www.theregister.com/2020/06/15/github_replaces_master_with_main/
I would suggest `trunk` instead of `main`.

**Comment by DanGrayson** [comment]
It could cause confusion when people do "git pull", and it no longer works.

**Comment by peterlefanulumsdaine** [comment]
Just for reference, here’s the issue thread from [the HoTT library](https://github.com/HoTT/HoTT) for its migration from Travis to Github Actions: https://github.com/HoTT/HoTT/issues/1247

**Comment by benediktahrens** [comment]
FYI: 

1. There is a documentation page at https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions explaining some of the differences between travis and github actions.
2. We will need to switch from travis-ci.org to travis-ci.com if we want to continue using travis, see https://blog.travis-ci.com/2021-05-07-orgshutdown.

@DanGrayson : what do you think, is it time to switch to Github actions? It might be sufficient to slightly adapt the travis configuration file and move it to a subdirectory. There is also a quickstart button on https://github.com/UniMath/UniMath/actions/new.

**Comment by benediktahrens** [comment]
Update: I migrated the repos from travis-ci.org to travis-ci.com, but have not checked if that has worked - we'll see soon enough, I guess.

**Comment by DanGrayson** [comment]
Yes, I think it would be good to switch to github actions.  Then we could probably have just one build, as the time limit is more generous.  And maybe we could drop the docker image, since we'd have time to build coq.

**Comment by benediktahrens** [comment]
Done, closing.
