### ISSUE TITLE
Update to Coq 8.15

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1340]
Coq 8.13 is out: https://github.com/coq/coq/releases/tag/V8.13.0

Compilation of Coq 8.13 requires libzarith in version at least 1.10. On Debian stable, I have libzarith-ocaml-dev/stable,stable 1.7-1. Hence I cannot currently test the upgrade to Coq 8.13 on UniMath.

**Comment by DanGrayson** [comment]
I wonder whether you can get it through OPAM.

**Comment by DanGrayson** [comment]
PS: Ubuntu 20.10 offers 1.9.1-1.  Better, but not good enough.

**Comment by benediktahrens** [comment]
Ubuntu 22.04 is now available on Github Actions: https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

That might mean that we could update the Coq submodule to the most recent version, which seems to be 8.15.1.

See also https://github.com/UniMath/UniMath/issues/1538#issuecomment-1216652877 for more information on how to compile recent versions of Coq (not sure it applies to 8.15).

**Comment by benediktahrens** [comment]
@DanGrayson : could we work on updating the Coq submodule? It will require some changes to `Makefile`, in particular, the `CONFIGURE_OPTIONS` need to be adapted.

**Comment by DanGrayson** [comment]
Sure.

**Comment by benediktahrens** [comment]
Done in #1541 , closing.
