### ISSUE TITLE
Move some files

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#1349]
Okay, we can discuss it later.  Or maybe I'll just do it.

Maybe Dcpo.v should be moved, too.  By the way, "Dcpo" is a horrible name for a file.

Thanks!

Benedikt, merging this is okay with me.

_Originally posted by @DanGrayson in https://github.com/UniMath/UniMath/issues/1348#issuecomment-845963056_

**Comment by benediktahrens** [comment]
@DanGrayson @nmvdw @peterlefanulumsdaine : Is this issue done with @nmvdw ' s recent reorganization of OrderTheory?

**Comment by arnoudvanderleer** [comment]
This has indeed been resolved by #1726
