### ISSUE TITLE
Travis-specific check fails in Github action

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1355]
We have the following Travis-specific stuff in `Makefile`, which is also checked (and fails) in the Github Action:
```
# here we ensure that the travis script checks every package
check-travis:.check-travis.okay
clean::; rm -f .check-travis.okay
.check-travis.okay: Makefile .travis.yml
	@echo --- checking travis script ---
	@set -e ;													\
	for p in $(PACKAGES) ;												\
	do grep -q "PACKAGES=.*$$p" .travis.yml || ( echo "package $$p not checked by .travis.yml" >&2 ; exit 1 ) ;	\
	done
	touch "$@"
```

**Comment by benediktahrens** [comment]
I think this code is only relevant when we check on a per-package basis. I suggest to remove the target `check-travis` from the `sanity-checks` target.

**Comment by DanGrayson** [comment]
> I think this code is only relevant when we check on a per-package basis. I suggest to remove the target `check-travis` from the `sanity-checks` target.

Done in commit daec56a21d31a677d839f746fa642f9b3ac42354
