### ISSUE TITLE
Editing COQBIN variable in Makefile doesn't seem to work correctly

### ISSUE THREAD

**Issue by paigenorth** [UniMath/UniMath#1361]
I want to point to a different installation of Coq in the Makefile. I've edited the relevant part of the Makefile to the following:

```
############################################
# other user options; see also build/Makefile-configuration-template
BUILD_COQ ?= no
BUILD_COQIDE ?= no
DEBUG_COQ ?= no
COQBIN ?= /Applications/Coq_Platform_2021.02.1.app/Contents/Resources/bin/
MEMORY_LIMIT ?= 2500000
LIMIT_MEMORY ?= no
############################################
```

(I changed the value of `BUILD_COQ` from `yes` to `no` and changed the value of `COQBIN` from empty to the path above.) When I run `make`, it complains that there's no `COQC` etc. But when I added that path above to my path variable, `make` runs fine. Is the syntax that I'm using correct here, or is there something wrong?

Thanks!

**Comment by DanGrayson** [comment]
Fixed in commit aec82b8425c41d3e5aaf70e18b0713e3f8e17df7
