### ISSUE TITLE
Making a more beautiful entry page to UniMath

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1374]
Github allows one to create automatically, using Jekyll, a website from the README.md.
For example, see https://unimath.github.io/Schools/, created from https://github.com/UniMath/Schools#readme.

I would like to set this up for UniMath as well, but there is currently a problem when building the website:
```
 Your site is having problems building: The variable {{available} on line 53 in README.md was not properly closed with }}. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#tag-not-properly-terminated. 
```
(Visible from https://github.com/UniMath/UniMath/settings/pages)

The problem is that the `{{` is interpreted as a Jekyll command, and then is lacking a closing pair of braces. The page https://stackoverflow.com/questions/45124380/github-page-build-failure-due-to-in-code-block gives a possible solution, but the suggested `{% raw %}` and `{% endraw %}` are displayed in the rendered markdown.

A workaround would be to avoid the double braces in the bibtex entry, e.g., by inserting a space between them.

@DanGrayson : could you take a look at this with us?

**Comment by DanGrayson** [comment]
I'd be happy to help look at it.   Shall I modify it?  I could even move the second brace to the next line.

**Comment by benediktahrens** [comment]
Awesome, we now have a more readable entry page at http://unimath.github.io/UniMath/. I will point to this page in the future when pointing people to UniMath.

Closing this issue.

**Comment by DanGrayson** [comment]
It looks great, thank you.

Should I redirect "unimath.org" to point there?

**Comment by benediktahrens** [comment]
> Should I redirect "unimath.org" to point there?

Good idea!

**Comment by DanGrayson** [comment]
Okay, I've done it -- it will take a while to take effect, though.  Maybe if you try , it will work for you.

**Comment by benediktahrens** [comment]
It works - thanks a lot!

**Comment by DanGrayson** [comment]
Hmm, it doesn't work for me yet.  The result must be cached somewhere ...

**Comment by maggesi** [comment]
Perhaps you should add the unimath.org in the About section (click on the gear near the title About on the main page, there you can find a section for webpage).

**Comment by DanGrayson** [comment]
Okay, done, thanks for the suggestion.

**Comment by benediktahrens** [comment]
This is done, thanks to @paigenorth!
