### ISSUE TITLE
Change CI to use OPAM for installation of ocaml stuff

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1399]
Our Coq submodule is stuck on 8.12.2, because Coq 8.13 requires a more recent zarith than Ubuntu 20.04 delivers.

It would be good if we could use OPAM on the CI to install the ocaml dependencies of UniMath, in order to switch to a more recent Coq submodule.

Background: many people who install ocaml via homebrew find themselves with too recent an ocaml version to compile Coq 8.12. 

Alternatively, the homebrew installation instructions need to be made more precise or replaced by OPAM instructions.

@peterlefanulumsdaine @DanGrayson Can you voice a preference for either changing the CI or the MacOS installation instructions?

**Comment by peterlefanulumsdaine** [comment]
Relevant note: one of the CI jobs, the build on Mac OS with our own Coq, now uses opam (since a59fde36).

**Comment by arnoudvanderleer** [comment]
I believe we now just install a docker container from the coq devs/community, which uses opam. (Except for the MacOS CI. That one uses OPAM).
So can I conclude that this has been solved?

**Comment by benediktahrens** [comment]
@arnoudvanderleer : yes, I am closing this - thanks a lot!
