### ISSUE TITLE
Github setting "Require branches to be up to date before merging" does not seem to be active

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1412]
The Github setting "Require branches to be up to date before merging" does not seem to be active.
This could have to do with the following explanation: 
"This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take effect unless at least one status check is enabled (see below)."
The Github CI does not seem to be one of these status checks, at least I cannot seem to select them.

@DanGrayson : do you see anything else to do at https://github.com/UniMath/UniMath/settings/branch_protection_rules/552516 ?

**Comment by DanGrayson** [comment]
I wasn't aware of these options before, but it does seem to be a good idea to require pull requests to be up to date.  (Alternatively, we could merge with master as part of the CI script.)

I don't understand "status checks", described here: https://docs.github.com/en/rest/reference/repos#statuses

Maybe we don't have any of them.  Or maybe we have to add a line at the end of the CI script to announce a status.

**Comment by benediktahrens** [comment]
We had this check while using Travis CI, and it worked fine: any PR had to be updated before merging it into `master`. The check stopped working when we switched to Github Actions for CI.

**Comment by benediktahrens** [comment]
See also https://stackoverflow.com/questions/68554735/github-action-status-check-missing-from-the-list-of-checks-in-protected-branch-s 
The PR #1433 is related.

**Comment by benediktahrens** [comment]
fixed, closing.
