### ISSUE TITLE
Broken pipe in sanity checks on Github CI

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1420]
The Github Action CI shows the following lines:
```
--- checking the ordering prescribed by the files UniMath/*/.packages/files ---
sed: couldn't write 387 items to stdout: Broken pipe
grep: write error: Broken pipe
touch .check-prescribed-ordering.okay
```
Is that reason for concern?

**Comment by DanGrayson** [comment]
Yes, that's worrisome.  It indicates it may not be checking the ordering of the files.  I can't reproduce the problem at home.  Why not restart the jobs and see if it happens again?  Which pull request were you looking at?

**Comment by benediktahrens** [comment]
> Yes, that's worrisome. It indicates it may not be checking the ordering of the files. I can't reproduce the problem at home. Why not restart the jobs and see if it happens again? Which pull request were you looking at?

I think it happens in all the recent PRs, see, e.g., here: https://github.com/UniMath/UniMath/runs/4359935245?check_suite_focus=true#step:5:9

**Comment by peterlefanulumsdaine** [comment]
I’ve put together a proposed fix for this issue (at least as far as I’ve tested it on my own system) — you can review it in the branch [`fix-sanity-checks`](https://github.com/peterlefanulumsdaine/UniMath/tree/fix-sanity-checks) (fixing just the check itself) or, better, [`test-fixed-check`](https://github.com/peterlefanulumsdaine/UniMath/tree/test-fixed-check) (fixing the library to pass the check).

I would issue a PR based on [`test-fixed-check`](https://github.com/peterlefanulumsdaine/UniMath/tree/test-fixed-check), but that branch also incorporates the open PR #1445 so it shouldn’t be pulled until #1445 is accepted.  Just in case #1445 is rejected for some reason, then we can make a PR based on [`fix-sanity-checks`](https://github.com/peterlefanulumsdaine/UniMath/tree/fix-sanity-checks) instead.

**Comment by peterlefanulumsdaine** [comment]
On second thoughts, I think there’s no real reason to wait on making a PR for this — I’ll just add a note to wait on #1445 before merging.

**Comment by benediktahrens** [comment]
I think this issue is fixed, closing.
