### ISSUE TITLE
Long installation time

### ISSUE THREAD

**Issue by clarus** [UniMath/UniMath#1459]
Hello,

It seems that the UniMath package takes a long time to compile. For example, on this test machine, it takes more than 4 hours https://coq-bench.github.io/clean/Linux-x86_64-4.13.1-2.0.10/released/8.13.2/unimath/20220204.html (timeout). Most other packages take a few minutes to install. I wonder if this is an issue for users wanting to try this library and if this is simple to optimize.

**Comment by benediktahrens** [comment]
The hardware specs are given on https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners. We are compiling UniMath with `-j2` (https://github.com/UniMath/UniMath/blob/master/.github/workflows/build-unimath.yml#L39).
