### ISSUE TITLE
iso_disp uses iso instead of z_iso.

### ISSUE THREAD

**Issue by Kfwullaert** [UniMath/UniMath#1468]
In section "Isos" of the file "UniMath.CategoryTheory.DisplayedCats.Isos", the notion of iso_disp is defined using iso instead of z_isomorphism. These are defined using precategories, but also in definitions and lemmas after that (where one uses categories instead of precategories) also use iso instead of z_isomorphism.

**Comment by benediktahrens** [comment]
fixes in #1507 , closing.
