### ISSUE TITLE
Undefined reference to weqgf and weqgf00 in uu0a.v

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#148]
uu0a.v has the comment

`We now define different homotopies and maps between the paths spaces corresponding to a weak equivalence. What may look like unnecessary complexity in the definition of weqgf is due to the fact that the "naive" definition, that of weqgf00 , needs to be corrected in order for lemma weqfgf to hold. '

The identifiers weqgf and weqgf00 don't seem to occur anywhere in the library, and can perhaps be removed.

**Comment by DanGrayson** [comment]
resolved in https://github.com/UniMath/UniMath/pull/149
