### ISSUE TITLE
coqdoc and proofs-toggle

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#153]
The toggling of the display of proofs behaves miserably on my machine, for when the proofs
are hidden, many other parts of the page are hidden, too, if there's just one proof in
the file, such as Magma.v.  Here's the view with proofs hidden:

![proof hidden](https://cloud.githubusercontent.com/assets/700228/10076759/154b8ed0-62ab-11e5-9d91-fb0e93e06367.png)

And here's the view with proofs shown:

![proof shown](https://cloud.githubusercontent.com/assets/700228/10076760/154d5080-62ab-11e5-82cb-b1340e716bd6.png)

**Comment by benediktahrens** [comment]
On 09/24/2015 10:58 AM, Daniel R. Grayson wrote:
> The toggling of the display of proofs behaves miserably on my machine, for when the proofs
> are hidden, many other parts of the page are hidden, too.  See the two pictures:
>
> ![proof hidden](https://cloud.githubusercontent.com/assets/700228/10076759/154b8ed0-62ab-11e5-9d91-fb0e93e06367.png)
>
> ![proof shown](https://cloud.githubusercontent.com/assets/700228/10076760/154d5080-62ab-11e5-82cb-b1340e716bd6.png)

What browser are you using?
What file are the example screenshots from?

**Comment by benediktahrens** [comment]
On 09/24/2015 10:58 AM, Daniel R. Grayson wrote:
> The toggling of the display of proofs behaves miserably on my machine, for when the proofs
> are hidden, many other parts of the page are hidden, too.  See the two pictures:
>
> ![proof hidden](https://cloud.githubusercontent.com/assets/700228/10076759/154b8ed0-62ab-11e5-9d91-fb0e93e06367.png)
>
> ![proof shown](https://cloud.githubusercontent.com/assets/700228/10076760/154d5080-62ab-11e5-82cb-b1340e716bd6.png)


I cannot reproduce the problem shown in the screenshots, using current 
master and firefox 38.2.1 (the one installed on the IAS Springdale Linux).

**Comment by DanGrayson** [comment]
The file is src/UniMath/enhanced-html/UniMath.Ktheory.Magma.html and the browser is chrome
on my office machine.

**Comment by benediktahrens** [comment]
On 09/24/2015 11:24 AM, Daniel R. Grayson wrote:
> The file is src/UniMath/enhanced-html/UniMath.Ktheory.Magma.html and the browser is chrome
> on my office machine.

The file looks fine on my office machine in both firefox and chrome.

Do you have any plugins installed, e.g., a javascript blocker?
Maybe start the browser with clean settings?

**Comment by DanGrayson** [comment]
The javascript runs, hence the behavior.  But indeed, if I start chrome this way:
```
dublin$ mkdir /tmp/asdfasdf
dublin$ google-chrome --args --user-data-dir=/tmp/asdfasdf
```
then it works.  Sigh.
