### ISSUE TITLE
Set up alectryon for UniMath?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1530]
We could try to set up alectryon for UniMath. The source of alectryon is at https://github.com/cpitclaudel/alectryon.

**Comment by DanGrayson** [comment]
It's aimed at making interactive textbooks!  The best math textbook would be one where the students are provided with formalized and runnable proofs of everything.

**Comment by rmatthes** [comment]
We use it a lot for teaching Coq in our university. One steps through the proof scripts by hovering over the special symbols appearing between the tactic applications. Would be very good to have a UniMath tutorial in that style.

**Comment by DanGrayson** [comment]
Vladimir envisioned the Foundations itself as a tutorial.  So we should just try stepping through it.

**Comment by benediktahrens** [comment]
Alectryion is like stepping through the file, but without the hassle of installing Coq. It seems great as a first step.

**Comment by arnoudvanderleer** [comment]
Closing this, since the discussion has been continued in #1672.
