### ISSUE TITLE
MacOS CI actions being queued

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/UniMath#1536]
Hi!

Over at agda-unimath, the CI is queueing the actions to check our pull requests, because of the following:

```
The agent pool assigned to this job has hit their MacOs concurrency limits
Requested labels: macOS-latest
Job defined at: UniMath/agda-unimath/.github/workflows/ci.yaml@refs/pull/277/merge
Waiting for a runner to pick up this job...
```

I was quite puzzled with this, because we rarely have more than two CI checks running at any moment. So I was wondering what was going on, and then I noticed that here at the Coq Unimath you also have a lot of pending CI actions (for pull requests that go a long way back). Could it be that because we are on the same `UniMath` account, that we share the same limited pool of available CI action slots?

Anyway, it is not a big deal. It will probably resolve itself overnight as the CI actions get resolved, but I thought I'd raise the issue over here. Perhaps one of you knows more than I do.

**Comment by benediktahrens** [comment]
@DanGrayson could you take a look?

**Comment by DanGrayson** [comment]
Sure, I'll take a look.

**Comment by DanGrayson** [comment]
Egbert, which action or pull request should I look at?

**Comment by EgbertRijke** [comment]
Hi Dan! It seems that all the github actions (here and on agda-unimath) have been resolved since I opened the issue. So it is not really an issue anymore. So my only question that remains is that if we have lots of actions running here and on agda-unimath, does that queue each other's actions?

**Comment by DanGrayson** [comment]
It could well be that scheduling is done on a per-user basis, rather than on a per-repository basis, but I don't know.
