### ISSUE TITLE
INSTALL_COQIDE.md is out of date

### ISSUE THREAD

**Issue by Cypher1** [UniMath/UniMath#1537]
I'm trying to use UniMath (without prior knowledge of emacs, coming from vim) and I'm unsure how to set it up (I get errors with Unimath not being found, though I've tried to `make install` it).

I found `INSTALL_COQIDE.md` which refers to a file that is deleted and supposedly generated by the `make` process, but is emacs script?

Thanks in advance for the help

**Comment by DanGrayson** [comment]
If you're referring to `sub/coq/bin/coqide`, that's a program optionally built when compiling coq from sources.  Nowadays, though, it usually suffices to just install coq on your computer and let the makefile use the installed coq, instead of building it from scratch.

**Comment by Cypher1** [comment]
True, though, in my opinion, this does not resolve the issue of the out of
date file.

**Comment by benediktahrens** [comment]
@Cypher1 thanks a lot for filing this issue.

The file linked to has been renamed, that's why it looks like it has been deleted. It is this one: https://github.com/UniMath/UniMath/blob/master/UniMath/.dir-locals.el.in

@DanGrayson : do you know why the file has been renamed?

**Comment by DanGrayson** [comment]
I renamed it, so we can make the real file, `.dir-locals`, from it, and have the contents depend on whether we build coq.  If we build coq, then proof general should use the one we build; otherwise, not.

**Comment by benediktahrens** [comment]
@Cypher1 : does #1542 solve this issue for you?
