### ISSUE TITLE
Please create a tag for Coq 8.16 in Coq Platform 2022.09

### ISSUE THREAD

**Issue by MSoegtropIMC** [UniMath/UniMath#1538]
The Coq team released Coq `8.16+rc1` on June 01, 2022.
The corresponding Coq Platform release `2022.09` should be released before **September 15, 2022**.
It can be delayed in case of difficulties until October 15, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (preview) **does not work** with Coq `8.16+rc1`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 8529067b81f245fbfc6cb2c58b8f47651543aaed on repository https://github.com/UniMath/UniMath - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.16, **preferably before August 31, 2022**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before August 17, 2022, it will be included in an early Coq Platform beta release of the for Coq 8.16+rc1.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.16+rc1~2022.09~preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.16~2022.09~preview1.sh) which already supports Coq version `8.16+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/274

**Comment by benediktahrens** [comment]
@MSoegtropIMC : thanks for filing this PR.

@DanGrayson @peterlefanulumsdaine @rmatthes @nmvdw @maggesi : I am struggling to build Coq 8.16. Could anybody try building it, and building current UniMath/UniMath on top of it?

**Comment by DanGrayson** [comment]
I'll take a look.  I may have to modify our UniMath makefile to take differences into account.

**Comment by benediktahrens** [comment]
@DanGrayson : I managed to build Coq 8.16 and UniMath/UniMath on top of it - just had to remind myself how it is done...

I'll make a new tag from current master.

**Comment by benediktahrens** [comment]
@MSoegtropIMC : could you please use tag v20220816 (https://github.com/UniMath/UniMath/releases/tag/v20220816) for Coq Platform 2022.09?

**Comment by DanGrayson** [comment]
> @DanGrayson : I managed to build Coq 8.16 and UniMath/UniMath on top of it - just had to remind myself how it is done...
> 
> I'll make a new tag from current master.

Okay, great!

**Comment by benediktahrens** [comment]
Some notes for compiling Coq 8.16 and UniMath/UniMath on top of it:
- to compile coq 8.16 on Debian, I had to install package `ocaml-dune`
- `configure` does not have the `-local` option any more. Instead, one can (less conveniently) use `-prefix /foo/bar` to make a local installation
- after `make`ing Coq, one also needs `make install` now (i think this was not necessary with `-local`)

**Comment by benediktahrens** [comment]
@MSoegtropIMC : the tag created for https://github.com/coq/platform/issues/274 is 

https://github.com/UniMath/UniMath/releases/tag/v20220816

Thanks a lot for your work on the Coq platform!

**Comment by MSoegtropIMC** [comment]
@benediktahrens : can you please create an opam package for this version? If you want, I can also do this.

**Comment by benediktahrens** [comment]
@MSoegtropIMC : it would be fantastic if you could create a suitable opam package.

**Comment by MSoegtropIMC** [comment]
@benediktahrens : sure, no issue. Can you please review (https://github.com/coq/opam-coq-archive/pull/2285). Things which change from time to time are authors (say a new Ph.D. student) and you also might want to check the minimum Coq version - I did not test this. I just adjusted the download URL and SHA.

**Comment by MSoegtropIMC** [comment]
I switched to the public opam package now and close this issue.

**Comment by benediktahrens** [comment]
@MSoegtropIMC : thanks for falling back on the last released OPAM package. We have not been able to establish that your prepared OPAM package (https://github.com/coq/opam-coq-archive/pull/2285) works - compilation failed with an error suggesting that the `tar.gz` was never actually unpacked and changed into.
Sorry for the hassle!

**Comment by benediktahrens** [comment]
@DanGrayson tried to test https://github.com/coq/opam-coq-archive/pull/2285 locally on his machine, but did not seem to be successful. If the package worked in your tests, then that's fantastic - it is the right package to use.
(We are all not very familiar with OPAM, I am afraid.)
Sorry for the confusion!

**Comment by benediktahrens** [comment]
@MSoegtropIMC : thanks a lot for your explanation. I think @DanGrayson ' s goal was to add the OPAM package that you had prepared to a local repository of OPAM packages, so that he could test installation.
