### ISSUE TITLE
file sequence

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#155]
The files UniMath/*/.package/files specify a linear ordering of the *.v files in our formalization, crafted by hand, whereas "make" computes a partial ordering of the files based on dependencies.  We should verify, in the Makefile, whether the two orderings are compatible.

(The linear ordering is used for making the TAGS file and for displaying line and word counts in the files.)

**Comment by benediktahrens** [comment]
I think this is done, closing.
