### ISSUE TITLE
Not all sanity checks can be run locally

### ISSUE THREAD

**Issue by nmvdw** [UniMath/UniMath#1552]
If I run `make sanity checks` on my laptop (Mac OS 12.2.1), I get
```
--- checking the ordering prescribed by the files UniMath/*/.packages/files ---
make: *** skipping checking the linear ordering of packages, because 'bash' is too old
--- checking every proof file is listed in one of the packages ---
make: *** skipping checking the listing of proof files, because 'bash' is too old
```
As such, I can only see whether the sanity checks are satisfied after doing a pull request.

**Comment by benediktahrens** [comment]
@DanGrayson : could you take a look at this?

**Comment by DanGrayson** [comment]
Yes, bash is too old on mac os x.  On my system it's stuck at version 3.2.57, which is why I use homebrew to install a modern version, 5.1.16.  Since /usr/local/bin is ahead of /bin on my PATH, the modern one gets used instead.

**Comment by nmvdw** [comment]
That helped! Thank you

**Comment by benediktahrens** [comment]
This issue seems to be resolved, closing.
