### ISSUE TITLE
CI should check if CONTENTS.md is up-to-date.

### ISSUE THREAD

**Issue by m-lindgren** [UniMath/UniMath#1565]
Maybe `make sanity-checks` could include a check to see if CONTENTS.md is up-to-date?

**Comment by benediktahrens** [comment]
Tentatively assigning this to @DanGrayson...

**Comment by DanGrayson** [comment]
Good idea, I'll take care of it.

**Comment by DanGrayson** [comment]
Okay, commit b2f478730fdd4d975062dee30bb9ac77e6ca1257 ought to take care of it.

**Comment by peterlefanulumsdaine** [comment]
thanks @m-lindgren , @DanGrayson !  Further minor improvement in #1566 , plus committing the outstanding update to `CONTENTS.md` which I guess motivated this issue.
