### ISSUE TITLE
Improve CI for satellite repos

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1575]
- put compilation of each satellite repo in a separate "step"
- continue CI upon failure of a step (see https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f)

**Comment by rmatthes** [comment]
I looked into the [YAML file](https://github.com/UniMath/UniMath/blob/master/.github/workflows/build-libs.yml). It does not mention GrpdHIT in the step description (trivial to add). Why are the satellites not compiled with `make -j2`? Way over 3h running time look extreme. And there are 16kloc of output, mostly with warnings. Is there a way to avoid those warnings? Maybe, at least to assess the time consumption, the make commands could be timed with `\time -v`?

**Comment by benediktahrens** [comment]
- Instead of editing the step description, it would be better to have separate steps for each compilation.
- `make`ing with several threads would be good, as long as the error messages are still readable (but I think that they would be), that is, that output of different threads is not mixed too much
- I don't know how to suppress the warnings, I am afraid.
- `time` is a great idea!

**Comment by m-lindgren** [comment]
I've been experimenting with using dune cache in CI, and I think UniMath can benefit from it. I'll see If I can build the satellites with it as well.

**Comment by m-lindgren** [comment]
In #1590 the satellites finish in 15-25 minutes, and in my own tests they finish in about 5min if their dependencies are not changed, i.e. if they have everything cached.

**Comment by rmatthes** [comment]
Concerning the warnings I mentioned three days ago: compiling `GrpdHITs` according to the instructions produces an enormous number of warnings of the same type that can be suppressed with the simple line `-arg "-w -notation-overridden"` in file `_CoqProject`. Other warnings will still appear (and could be dealt with by easy code changes). I filed a PR.

**Comment by benediktahrens** [comment]
@arnoudvanderleer : yes, this is obsolete, closing - thanks!
