### ISSUE TITLE
Difference between coq options -Q and -R

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#159]
from what I understand, -Q only adds one directory to the search path under the given name, whereas -R adds the directory and all its subdirectories.

Maybe it would be safer to use -Q ? 
As a consequence, Imports would always need to use the fully qualified name UniMath.Package.file, but we are doing this anyway.

This would allow having files of the same name in different packages without the risk of confounding them.

**Comment by DanGrayson** [comment]
Great!  I will implement it.
