### ISSUE TITLE
Error in satellite CIs

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1591]
I keep seeing
```
make[2]: *** No rule to make target 'UniMath/Tactics/EnsureStructuredProofs.vo', needed by 'UniMath/PAdics/lemmas.vo'.  Stop.
make[1]: *** [build/CoqMakefile.make:387: all] Error 2
```
e.g., in 
https://github.com/UniMath/largecatmodules/actions/runs/3396211054/jobs/5647017543
and 
https://github.com/UniMath/TypeTheory/actions/runs/3395828366/jobs/5646192771

It might be a known issue, but I have not kept up with recent developments. Could somebody clarify?

**Comment by nmvdw** [comment]
The main line in https://github.com/UniMath/UniMath/blob/master/UniMath/Tactics/EnsureStructuredProofs.v is `Export Set Default Goal Selector "!".`: this requires all subgoals to be focussed. Ralph and I adjusted several subdirectories to adhere to this style, and among those, is PAdics.

In PAdics, there was a lemma (not related to p-adic numbers) that was used in TypeTheory, and as a result, TypeTheory was forced to adhere to the particular style. However, the relevant file did not do so, and that caused that particular error. This was solved with this PR: https://github.com/UniMath/TypeTheory/pull/224

For LargeCatModules, it is probably the same, although I did not check that one.

**Comment by m-lindgren** [comment]
I don't think that's the case, because it's UniMath that fails to build -- but only when built in the satellites CI. The satellites themselves never even starts building. This confuses me.

**Comment by m-lindgren** [comment]
Or I mean it might be the case, but I'm confused by why it only happens when building UniMath in the satellites CI.

**Comment by nmvdw** [comment]
> I don't think that's the case, because it's UniMath that fails to build -- but only when built in the satellites CI. The satellites themselves never even starts building. This confuses me.

Oh good point. You are right. I had some old PRs in mind (https://github.com/UniMath/UniMath/pull/1582), but the errors in the links are indeed different.

**Comment by m-lindgren** [comment]
I think UniMath/TypeTheory#227 fixed it.

I think it was because `make PACKAGES="Foundations ..."`didn't include the `Tactics` package.

**Comment by benediktahrens** [comment]
Seems fixed - closing this issue.
