### ISSUE TITLE
Confusion about CI sanity checks

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1611]
I am confused by the output of the sanity check to a (draft) PR: https://github.com/UniMath/UniMath/actions/runs/3903770065/jobs/6668606428
It says that the CI run has failed, but I don't see which of the sanity checks has failed. I am probably missing something obvious...

**Comment by JasonGross** [comment]
https://github.com/UniMath/UniMath/actions/runs/3903770065/jobs/6668606428#step:4:36
make[1]: *** No rule to make target 'UniMath/CategoryTheory/ZigZag.v', needed by '..coq_makefile_output.d'.
