### ISSUE TITLE
https://unimath.org is timing out

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1616]
https://unimath.org is timing out. @DanGrayson : could you take a look?
Thanks to @tomdjong for the notification!

**Comment by benediktahrens** [comment]
http://unimath.org works.

**Comment by DanGrayson** [comment]
Will do!

**Comment by DanGrayson** [comment]
I've run into this problem before, in connection with "macaulay2.com".  I was never able to figure it out.  It has something to with the fact that our domain name server, joker.com, forwards "unimath.org", and that forwarding must interfere with the security checking somehow.

I suggest we just use http://unimath.org/

**Comment by tomdjong** [comment]
A downside of non-working https is that many browser default to https, e.g. if I type unimath.org in Firefox, then it goes to https://unimath.org and I'm greeted by a warning and the option to continue to the http site.

**Comment by arnoudvanderleer** [comment]
I'm closing this as something that is not currently a problem, and seems to be an unsolvable mystery in the case that it is a problem.
