### ISSUE TITLE
CI should check satellites with dev version of Coq

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1620]
Currently, the satellites are not checked by the Coq CI, and we only check them with released versions of Coq. This means that we catch problems with Coq only when the problems has entered a released version.

Instead, we should also check the satellites with Coq dev, so that problems can be caught early.

@m-lindgren : could you implement this?

**Comment by m-lindgren** [comment]
This is a good idea! I'll fix it.
