### ISSUE TITLE
Terminology: power category

### ISSUE THREAD

**Issue by nmvdw** [UniMath/UniMath#1637]
In UniMath, we use the terminology 'power_category' for a product of categories over a type:
https://github.com/UniMath/UniMath/blob/7d0cf5acb3388aaab5cfa4b457d5e8f63b979ec6/UniMath/CategoryTheory/ProductCategory.v#L88
This came up in https://github.com/UniMath/UniMath/pull/1633#discussion_r1121696020.

Personally, I am not too fond of that terminology. Powers (https://ncatlab.org/nlab/show/powering) are some kind of weighted limit used frequently in the context of enriched category theory and higher category. Powers in the bicategory of categories would be functer categories, but this does not hold in an arbitrary bicategories (the same can be said for enriched categories). 

I think a more suitable name would be something like `type_indexed_product_cat`.

**Comment by peterlefanulumsdaine** [comment]
“Power” here seems reasonable to me — this surely doesn’t conflict with the enriched-categorical sense, it’s just an instance of a further generalisation of the term?  E.g. you can (in a classical foundation) view 1-categories as simplicially enriched; then the power of a category by a space will be something very analogous to this.  In our setting, categories form a “(type-enriched) wild category”; seen there, these “powers” satisfy a universal property very analogous to the enriched-category one.  And one can imagine that categories should form something like a “weakly type-enriched category”, and that there, too, it looks like these powers would probably satisfy the right universal property (though weak enrichment is of course notoriously hard to use precisely).

**Comment by arnoudvanderleer** [comment]
I agree with Peter in this (although I don't know a lot about . The term "power" here is used in the same sense as "x to the power n is x \cdot x \cdot \dots \cdot x", which to me seems like a logical name. Unfortunately, in mathematics, it sometimes happens that names clash.
It might be useful to add a comment to `ProductCategory` (just above power category, or at the top of the file, if power category is mentioned there) that explains the difference ("The power category, not to be confused with ..."). Could you maybe do that, somewhen after your vacation, @nmvdw ?

**Comment by nmvdw** [comment]
It is not that important of a change and, if it is not universally accepted, then it is necessary to do.
