### ISSUE TITLE
Compile TypeTheory with Coq 8.16 and dev

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1640]
Since https://github.com/UniMath/TypeTheory/pull/231 has been merged, we could compile TypeTheory with 8.16 and latest in the CI.

@m-lindgren : would you take care of this?

**Comment by m-lindgren** [comment]
Let's keep our fingers crossed that TypeTheory compiles with coq-dev.

**Comment by m-lindgren** [comment]
Fixed by #1641.
