### ISSUE TITLE
renaming basic things

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#166]
Here are some things I'd like to rename:
```
setwithbinop -> magma
invmaponpathsincl -> an_inclusion_is_injective
total2 -> totalSpace
```

I didn't know it before, but "magma" is used that way in Bourbaki's Algebra.

Does anyone else have proposals?

Can we agree on any of them?

**Comment by vladimirias** [comment]
I suggest to introduce the new names as notations for the old ones. This way nothing gets broken and anyone who wants to use new names can.

I also suggest it as the general procedure for changing and streamlining the notations.

**Comment by cathlelay** [comment]
As the old names will not be kept, I propose instead to use the old names
as notations for new ones.

2015-09-28 13:48 GMT-04:00 Vladimir Voevodsky <notifications@github.com>:

**Comment by benediktahrens** [comment]
On 09/28/2015 02:23 PM, cathlelay wrote:
> As the old names will not be kept, I propose instead to use the old names
> as notations for new ones.

But then the old names will be used for printing instead of the new ones.

**Comment by cathlelay** [comment]
Indeed ... I noticed it after pressing "send"

2015-09-28 14:45 GMT-04:00 Benedikt Ahrens <notifications@github.com>:

**Comment by DanGrayson** [comment]
Having the old name as a "parsing only" notation for the new name would be
the way to go,
as explained in the manual:

"Remark: Sometimes, a notation is expected only for the parser. To do so,
the option only parsing is
allowed in the list of modifiers of Notation."

**Comment by DanGrayson** [comment]
Changing something like "setwithbinop" implies changing names containing that string, too:
```
setwithbinop: Type
setwithbinoppair: ∀ X : hSet, binop X -> setwithbinop
pr1setwithbinop: setwithbinop -> hSet
issubsetwithbinop: ∀ X : hSet, binop X -> hsubtypes X -> Type
isapropissubsetwithbinop:
  ∀ (X : hSet) (opp : binop X) (A : hsubtypes X),
  isaprop (issubsetwithbinop opp A)
totalsubsetwithbinop: ∀ X : setwithbinop, subsetswithbinop
carrierofasubsetwithbinop:
  ∀ X : setwithbinop, subsetswithbinop -> setwithbinop
setwithbinopquot: ∀ X : setwithbinop, binopeqrel -> setwithbinop
setwithbinopdirprod: setwithbinop -> setwithbinop -> setwithbinop
setwithbinop1: setwith2binop -> setwithbinop
setwithbinop2: setwith2binop -> setwithbinop
```

**Comment by DanGrayson** [comment]
I'd also like to rename all identifiers with "coconus" in them.  Here the first use:
```
Definition coconusfromt (T : UU) (t : T) := Σ t':T, t = t'.
```
The name here has an additional problem, the use of "t", which conveys no information, and is 
there only because it is the name of a parameter.  I suggest renaming ```coconusfromt``` to ```path_to```.

Here is the complete list:
```
iscontrcoconustot_comp:
  ∀ (X : Type) (x : X), the (iscontrcoconustot X x) = x,, idpath x
coconusfromt: ∀ T : UU, T -> Type
coconusfromtpair: ∀ (T : UU) (t t' : T), t = t' -> coconusfromt T t
coconusfromtpr1: ∀ (T : UU) (t : T), coconusfromt T t -> T
coconustot: ∀ T : UU, T -> Type
coconustotpair: ∀ (T : UU) (t t' : T), t' = t -> coconustot T t
coconustotpr1: ∀ (T : UU) (t : T), coconustot T t -> T
connectedcoconustot: ∀ (T : UU) (t : T) (c1 c2 : coconustot T t), c1 = c2
iscontrcoconustot: ∀ (T : UU) (t : T), iscontr (coconustot T t)
connectedcoconusfromt: ∀ (T : UU) (t : T) (c1 c2 : coconusfromt T t), c1 = c2
iscontrcoconusfromt: ∀ (T : UU) (t : T), iscontr (coconusfromt T t)
coconusf: ∀ X Y : UU, (X -> Y) -> Type
fromcoconusf: ∀ (X Y : UU) (f : X -> Y), coconusf f -> X
tococonusf: ∀ (X Y : UU) (f : X -> Y), X -> coconusf f
homottofromcoconusf:
  ∀ (X Y : UU) (f : X -> Y) (yxe : coconusf f),
  tococonusf f (fromcoconusf f yxe) = yxe
homotfromtococonusf:
  ∀ (X Y : UU) (f : X -> Y) (x : X), fromcoconusf f (tococonusf f x) = x
isweqtococonusf: ∀ (X Y : UU) (f : X -> Y), isweq (tococonusf f)
weqtococonusf: ∀ (X Y : UU) (f : X -> Y), X ≃ coconusf f
isweqfromcoconusf: ∀ (X Y : UU) (f : X -> Y), isweq (fromcoconusf f)
weqfromcoconusf: ∀ (X Y : UU) (f : X -> Y), coconusf f ≃ X
```

**Comment by vladimirias** [comment]
I would request for the time being not to change old names. There is a certain order in their choice that is easy to lear and use after some initial period and changing it all will be a lot of work with very little usefulness.

If someone wants another name for a particular object or objects then introducing ones own notations for this object or objects is a perfectly good way of doing it and it won’t affect anybody else.

Vladimir.

**Comment by DanGrayson** [comment]
Okay; they're your files, after all.

May we add readable notations, such as this one, to files of yours?:
```
Definition iscontrpr1 {T : UU} : iscontr T -> T := pr1.
Notation thePoint := iscontrpr1.
```
The point of this particular example is that one way to read type theory is to read identity as a path.  The other way is to read identity as equality.  The latter way makes our proofs readable
a different way.

If not, do you permit us to include a file of basic notations in Basics/.?
