### ISSUE TITLE
Should we replace `-type-in-type` with `Unset Universe Checking` in some way?

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [UniMath/UniMath#1696]
(This is proposed by @Bigstep22 in #1671 as it’s a prerequisite for adding Alectryon, but seems worth splitting out for separate discussion since it’s conceptually its own thing, and potentially impactful for the whole library.)

For at least a few years now, Coq has had the flag `Universe Checking`; [according to the documentation](https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:flag.Universe-Checking), `Unset Universe Checking` is equivalent to `-type-in-type`.  **So we could replace our use of `-type-in-type` with `Unset Universe Checking` in `Foundations/Init.v`.  Should we?**

I see one significant and one very small upside, and no clear downsides.  Positives:

- having it in file(s) rather than command-line flags seems like it could really help with incrementally removing reliance on it, i.e. making progress on #648, and integrating partial progress from there into master
- less reliance on command-line flags seems good in general, although this doesn’t really give much payoff unless we could eliminate them entirely, which seems unlikely (currently we use `-type-in-type`, `-noinit`, and `-indices-matter`)

Possible downsides:

- I see none — but this possibility has been available for at least a few years now, so was there a reason we didn’t switch over to it sooner?  Or did we just never consider it?

**Comment by DanGrayson** [comment]
That's a good suggestion.  I wasn't aware of the new flag.

**Comment by benediktahrens** [comment]
@peterlefanulumsdaine : thanks a lot for the summary. I was not aware of this option until #1672 . The change Peter is suggesting seems beneficial.

**Comment by m-lindgren** [comment]
Possible downside: Universe checking would be disabled for all packages importing Foundations.Init. If this is the case then this has the complete opposite effect of the intended goal to incrementally remove `-type-in-type`.

Example: SetHITs builds without `-type-in-type` today. I suspect that the above flag would disable universe checking for SetHITs as well, and that would be a shame.

**Comment by nmvdw** [comment]
> Constants relying on "type in type" are printed by [Print Assumptions](https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:cmd.Print-Assumptions).

I think this is a big upside. This way it is easier to detect what precisely relies on type-in-type and what not.

**Comment by nmvdw** [comment]
> Right, I just tested the change and it will definitely disable universe checking for any project using UniMath that today have universe checking enabled, and it will do so in secret. That's a pretty big downside in my opinion. This would unfortunately make more code rely on universe checking being disabled, not less.

I tried the following:

I made the following file (which I called `Univ.v`):
```coq
Definition identity {A : Type} (a : A) := a.

Fail Definition selfid := identity (@identity).

Unset Universe Checking.

Definition selfid := identity (@identity).
```
By importing it in another file, I don't automatically get this flag turned off:
```coq
Require Import Univ.

Fail Definition selfid := identity (@identity).

Unset Universe Checking.

Definition selfid := identity (@identity).
```
However, if I used `Export Unset Universe Checking.` instead of `Unset Universe Checking.`, then this flag is turned off in all files that import `Univ.v`.

There might be a way around the problem you described, namely that we use `Unset Universe Checking.` in every file for which that is needed instead of unsetting it globally in `Init.v` (which is not a very nice alternative).

**Comment by JasonGross** [comment]
> which seems unlikely (currently we use `-type-in-type`, `-noinit`, and `-indices-matter`)

I don't think there's any hope of removing `-noinit`, but `-indices-matter` could be turned into a flag as well.

**Comment by nmvdw** [comment]
> > > Constants relying on "type in type" are printed by [Print Assumptions](https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:cmd.Print-Assumptions).
> > 
> > 
> > I think this is a big upside. This way it is easier to detect what precisely relies on type-in-type and what not.
> 
> This is true for both `-type-in-type` and `Unset Universe Checking`, right?

I was unaware that `Print Assumptions` also detects what was compiled with `-type-in-type`. However, there seems to be a difference. If one compiles a file with `-type-in-type`, then all the constants rely on an unsafe hierarchy, whereas with `Unset Universe Checking` you have more control over which ones precisely rely on an unsafe hierarchy. I think that is an advantage of `Unset Universe Checking`.

**Comment by m-lindgren** [comment]
> whereas with `Unset Universe Checking` you have more control over which ones precisely rely on an unsafe hierarchy. I think that is an advantage of `Unset Universe Checking`.

I know this is the case with the `bypass_check(universes)` attribute, but is it really the case with `Unset Universe Checking`? Doesn't sound right to me.

**Comment by nmvdw** [comment]
To explain my statement. If I make the following file:
```coq
Definition identity {A : Type} (a : A) := a.

Unset Universe Checking.

Definition selfid := identity (@identity).
```
Then
```coq
Print Assumptions identity.
```
gives
```
Closed under the global context
```
whereas
```coq
Print Assumptions selfid.
```
gives
```coq
Axioms:
selfid relies on an unsafe hierarchy.
```

**Comment by peterlefanulumsdaine** [comment]
Interesting… so there seem to be subtle differences, not clearly documented.  Regarding the “contagiousness” Michael points out

> […] it will definitely disable universe checking for any project using UniMath that today have universe checking enabled, and it will do so in secret. 

this can at least be countermanded by putting `Set Universe Checking` somewhere that’s imported later — so you’d have:

```
Require Import UniMath.Foundations.All.  (* unsets universe checking *)
Require Import MyProject.Base.  (* re-enables it with [Set Universe Checking.] *)
```

As far as I can see from a few tests, definitions imported from files compiled with “-type-in-type” behave identically to definitions checked within a `Unset Universe Checking` […] `Set Universe Checking.` block.  In particular, they all get marked as “relies on an unsafe hierarchy”, whether they needed it or not.  So as far as I can tell,

- the approaches are “equivalent” insofar as they both act by setting/unsetting the same typechecker option `Universe Checking` (whose state can be seen with `Print Options`)
- they differ just in their scope: `-type-in-type` just changes the state in which `coqtop` *starts* processing a file, but issuing or importing `Set`/`Unset` will override that (in either direction).  

Having it set/unset from within the Coq files seems less “secret” to me than having it in the command-line flags, and more easily+finely controllable.  But on the other hand it seems more *fragile* — if someone imports files in a different order, then they may get an unexpected value of the option.

On the other other hand, when you have universe-checked definitions using a lot of un-checked imports (as in `SetHITs`), I’m not sure how much security that later universe-checking really gives — I suspect it might be possible to define innocuous-looking things within an un-universe-checked file, then import them to a universe-checked file and derive false.  The following test at least seems to show that in that situation, type-checking isn’t stable under Delta-expansion, which is a little unnerving:

```
Unset Universe Checking.

Definition identity {A : Type} (a : A) := a.

Definition selfid {A : Type} (a : A) := identity (@identity) A a.

Set Universe Checking.

Lemma test1 : @selfid = @selfid.
Proof.
  apply eq_refl.
Defined.

Lemma test2 : @selfid = @selfid.
Proof.
  unfold selfid.
  apply eq_refl.
Fail Defined.
Abort.
```

**Comment by benediktahrens** [comment]
I think we can simply try out the change; if it turns out to have consequences we are not anticipating right now, the change can easily be reverted.

**Comment by peterlefanulumsdaine** [comment]
Overall I agree, let’s try it out — I think it’s a net positive, mainly because it makes reducing use of type-in-type (#648) *much* more feasible going forward.  But as @m-lindgren emphasised, its effects downstream may be a bit subtle/hidden, so it seems worth being a little watchful.

I’ve prepared a PR of this for TypeTheory in UniMath/TypeTheory#237.

**Comment by JasonGross** [comment]
> On the other other hand, when you have universe-checked definitions using a lot of un-checked imports (as in `SetHITs`), I’m not sure how much security that later universe-checking really gives — I suspect it might be possible to define innocuous-looking things within an un-universe-checked file, then import them to a universe-checked file and derive false

This is pretty easy in general, but I think the principled way to use unset universe checking is to define something like
```
#[local] Unset Universe Checking.
Defining hprop_resizing@{i j} (T : Type@{i}) (_ : is_hprop T) : Type@{j} := T.
```
And have this be the only unchecked constant.

**Comment by m-lindgren** [comment]
> #[local] Unset Universe Checking.
> Defining hprop_resizing@{i j} (T : Type@{i}) (_ : is_hprop T) : Type@{j} := T.

Using something similar to this I got `Foundations` to build without `-type-in-type` at least, but I used `#[bypass_check(universes)]` instead.

**Comment by peterlefanulumsdaine** [comment]
I’ve renamed the issue to a more general title, since the PR’s #1697, #1698 implement specific approaches, and this issue seems to have become a home to the general discussion.

**Comment by arnoudvanderleer** [comment]
Closing this issue, to revive the discussion in #1925.
