### ISSUE TITLE
New package: order theory

### ISSUE THREAD

**Issue by nmvdw** [UniMath/UniMath#1716]
What do people think of adding a new package called 'OrderTheory' whose contents are as follows:
- The Lattice folder (https://github.com/UniMath/UniMath/tree/master/UniMath/Algebra/Lattice)
- The DCPOs folder (https://github.com/UniMath/UniMath/tree/master/UniMath/Combinatorics/DCPOs)
- The Posets folder (https://github.com/UniMath/UniMath/tree/master/UniMath/Combinatorics/Posets)

I think that this way, the filers are ordered more logically.

**Comment by benediktahrens** [comment]
Good with me!

**Comment by rmatthes** [comment]
For me, this proposal implies that the work leading to Pataraia's fixed-point theorem (monotone endofunctions on a DCPO have a fixed point - no continuity needed) in https://github.com/UniMath/UniMath/blob/master/UniMath/Algebra/FixedPointTheorems.v is declared as obsolete - since it will not belong to the package. Currently, I do not see Pataraia's theorem.  Is it maybe hidden through more abstraction?

**Comment by nmvdw** [comment]
> For me, this proposal implies that the work leading to Pataraia's fixed-point theorem (monotone endofunctions on a pointed DCPO have a fixed point - no continuity needed) in https://github.com/UniMath/UniMath/blob/master/UniMath/Algebra/FixedPointTheorems.v is declared as obsolete - since it will not belong to the package. Currently, I do not see Pataraia's theorem. Is it maybe hidden through more abstraction?

Good point. That file should be moved as well to that folder.

**Comment by rmatthes** [comment]
And what about the prerequisites for that file?

**Comment by m-lindgren** [comment]
I like this idea. I would also be in favor of moving the definitions of `po` (we should give this a more descriptive name IMO), `Poset` etc, and their associated functions out of `Foundations` and `MoreFoundations` into this new package.

**Comment by nmvdw** [comment]
> And what about the prerequisites for that file?

See https://github.com/UniMath/UniMath/pull/1726 for a concrete suggestion on this.

**Comment by m-lindgren** [comment]
Related: #1067.

**Comment by arnoudvanderleer** [comment]
@nmvdw If I understand this correctly, there are exactly two (parts of) files that still need to be moved?

**Comment by nmvdw** [comment]
Yes. The easiest change is to move https://github.com/UniMath/UniMath/blob/master/UniMath/Combinatorics/WellOrderedSets.v and https://github.com/UniMath/UniMath/blob/master/UniMath/Combinatorics/OrderedSets.v, and a more complicated change would be to move the stuff on posets.

**Comment by arnoudvanderleer** [comment]
The posets are more complicated because they are scattered through multiple files, or because their file has more references pointing to it?

**Comment by nmvdw** [comment]
I think both.

**Comment by arnoudvanderleer** [comment]
I think I'll also move `Subposets.v`.
Would it also be good to move [StructureIdentity.v](https://github.com/UniMath/UniMath/blob/master/UniMath/MoreFoundations/StructureIdentity.v)?
