### ISSUE TITLE
Get rid of UU : UU warning?

### ISSUE THREAD

**Issue by paigenorth** [UniMath/UniMath#1722]
Is there a way to get rid of the warning: "x relies on an unsafe universe hierarchy"? I know I'm using an unsafe universe hierarchy, and having it print all the time is kind of cluttering my output pane.

**Comment by arnoudvanderleer** [comment]
@paigenorth Just to check:
 - Is this still relevant?
 - Which command line arguments are you feeding to coq?
 - Can you give an example of a file where this occurs?

**Comment by arnoudvanderleer** [comment]
Closing this as no longer active. Please reopen if it is still relevant.
