### ISSUE TITLE
identifier names, a proposal going forward

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#176]
It would be nice to have a consistent style in future for the naming of exported identifiers.  Here's one, which I like:
- identifiers should be obtained by concatenating English words, capitalizing the word to 
  the right of each border between two words, without underscores;
- one may also use previously defined identifiers as components of a name, with an underscore
  as the border to the left of an identifier is not capitalized;
- the first letter must be capitalized if the identifier refers to a type;
- the first letter may be capitalized if the identifier refers to a function returning a type;
- otherwise, elements should start with lower case;
- a function that returns a proposition may begin with "has" or "is";
- If "Foo" is the name of a type, then "hasFoo" is its propositional truncation.

**Comment by cathlelay** [comment]
If I understand,

   - hnnr must be renamed as NonNegativeReals.
   - hnnq become NonNegativeRationals.
   - Dcuts (the future type for Dedekind cuts) become DedekindCuts.

Is it correct ?

2015-09-30 13:03 GMT-04:00 Daniel R. Grayson <notifications@github.com>:

**Comment by DanGrayson** [comment]
Yes.  Or hnnr could be PositiveReals, using the French convention for "positive".  That would be
much prettier.

Long names might be a bit of a hassle for users, but then notations can be introduced, and word completion in emacs with M-/ works well, too.

**Comment by vladimirias** [comment]
No, positive means >0 and non-negative means >=0 whether it is pretty or not.

**Comment by DanGrayson** [comment]
Point taken.

**Comment by vladimirias** [comment]
I am not sure what Dan calls “exported” identifiers but renaming hz into Integers and hnat in NaturalNumbers and using such long names all over the place does not seem to be a good idea.

**Comment by DanGrayson** [comment]
This proposal is for the future names.

**Comment by DanGrayson** [comment]
It can't be NonNegativeReals, because Non is not a word.  So it must be NonnegativeReals.

**Comment by vladimirias** [comment]
I guess one can use these long names and then immediately introduce a short notation for it and then use this short notation.

**Comment by cathlelay** [comment]
And for functions ?

   - leNonnegativeRationals to replace hnnq_le
   - plusNonnegativeRationals to replace hnnq_plus

Is it correct ?

2015-09-30 14:35 GMT-04:00 Vladimir Voevodsky <notifications@github.com>:

**Comment by DanGrayson** [comment]
A nonexported symbol is one not visible to those who import your file.  The way to make one
is with ```Local Definition foo := ...```.   Such symbols need obey no common style.  Proper use
of ```Local``` means you can have as many nonconforming symbols as you like.  For example, 
```hnnq_le``` could be replaced by a local ```le```.

**Comment by DanGrayson** [comment]
I should add that nonexported and nonimported symbols are visible, but only in their qualified form.  For example, the function "add" in Coq's Nat.v is visible only as Nat.add, not as add.  So they can still be referred to, when necessary, in proofs.

**Comment by varkor** [comment]
This should probably be closed in favour of https://github.com/UniMath/UniMath/issues/687 (or vice versa).

**Comment by DanGrayson** [comment]
Okay, let's continue this discussion on #687, closing.
