### ISSUE TITLE
how to keep track of which .v files of UniMath are being compiled?

### ISSUE THREAD

**Issue by rmatthes** [UniMath/UniMath#1785]
In the not so distant past, this was easy on my Linux systems (Ubuntu and Debian): I combined `ps aux`, `grep` and `watch` to filter out the processes running `coqc` every 20 seconds (for example), and I could see which were the UniMath library files that were compiled currently. The option `--verbose` to Dune does not help me since this floods me with the data on the quick compilations that do not need my attention (I typically compile with 6 or 8 cores).

Now with the current Coq version 8.17, the output of `ps aux` for each compilation process is excessively long. Even on a dual-screen installation, the end of the line is still showing command-line arguments. I can make a nice snapshot with
`ps aux | grep bin/coqc | sed 's/coqc.*UniMath UniMath /coqc ... /' | sed '/grep/d'`,
but this is only good for one inspection. However, when launching this command through `watch` (after turning the line into a shell script, properly starting with `#!/bin/bash`, it just does not do its job.

Are there good generic solutions for this problem?

Of course, I could program an infinite loop that waits for some seconds between the iterations, but I would like to have the `watch` functionality that *rewrites* the displayed data instead of flooding the terminal (or, on the contrary, deleting the output history of that terminal). And, again, I would greatly favour a generic solution.

**Comment by arnoudvanderleer** [comment]
According to [this stackexchange post](https://unix.stackexchange.com/questions/673396/watch-command-displays-different-ps-results-than-when-running-script-by-itself), you need to add the argument `-ww` to `ps`, in order to have it not truncate its output. I quickly tested it, and the following seems to work quite well:
```bash
watch -n 0 "ps -ww aux | grep bin/coqc | sed 's/coqc.*UniMath UniMath /coqc ... /' | sed '/grep/d'"
```

**Comment by arnoudvanderleer** [comment]
Sure. So does this resolve this issue?
Also, is there a place where we collect such scripts? Would it be useful to do so in the repository or on the wiki?

**Comment by rmatthes** [comment]
Yes, the issue will be resolved by documenting the solution. The Wiki is not much used but should be more. I consider it the right place.

**Comment by arnoudvanderleer** [comment]
All right, see [Scripts and snippets](/UniMath/UniMath/wiki/Scripts-and-snippets).
