### ISSUE TITLE
Presburger algorithm

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#18]
Someone should port omega (see http://coq.inria.fr/refman/Reference-Manual023.html) to unimath.

It would clean up hnat.v and my code considerably.

**Comment by abooij** [comment]
What would be involved in doing this? Is it simply a matter of replacing Coq's integers with the UniMath integers?

**Comment by DanGrayson** [comment]
I'm not sure what you mean, but if you want to see how Omega is written, look at the files in the directory `sub/coq/plugins/omega`.  It's written in a combination of Ocaml and Coq.  Once one has understood the internals of Coq well enough, it might be straightforward.

This goal conflicts with the goal of having UniMath run under the latest version of Coq without patches, unless there's a way to compile our tactic against an installed Coq binary.

**Comment by DanGrayson** [comment]
This would still be worth doing.

**Comment by arnoudvanderleer** [comment]
@DanGrayson @benediktahrens 
Is this still desirable?
 - Would this be used? (This is not necessary, but definitely nice ^^)
 - How does this interact with the `ban on automation`?
 - Presburger, called `omega` in coq, has been replaced by a newer, faster, complete algorithm called `lia` now. Which would we want to have in the library?

**Comment by benediktahrens** [comment]
I don't see anybody investing time in this right now. The main areas UniMath is growing in are category theory and pl-related topics using ct. Other material is very welcome, of course, but there is no need to open an issue for everything that is currently not in UniMath. Let's close this issue.
