### ISSUE TITLE
Fixpoint

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#183]
We should probably add `Fixpoint` to the list of forbidden constructs at https://github.com/UniMath/UniMath/tree/master/UniMath#unimath-coding-style , since it adds `fix` to the type theory needing to be semantically verified.  Discussion?

**Comment by DanGrayson** [comment]
... and "match" and "destruct" and the implicit "destruct" that happens with something like ```intros [a b]```?

**Comment by vladimirias** [comment]
Ideally yes. Ideally we should only use the eliminators.

I once re-wrote all of the uu0 removing all “destructs” and therefore all “matches” and doing everything as induction. This slowed the compilation time approximately 2 times. The problems arise with eliminators for the “disjoint” types - types with more than one constructor. I see no reason for it other than some quirks in the way Coq is written but decided for the time being not to do it. So we do continue to use “destruct” and “match” and “fix” but with the idea that it would be better not to and that ideally we should keep an eliminatror-only versions available as well.

**Comment by DanGrayson** [comment]
Fixpoint use was proscribed in commit eee2ee18f, closing.
