### ISSUE TITLE
Updating names with "wrong capitalization"

### ISSUE THREAD

**Issue by arnoudvanderleer** [UniMath/UniMath#1842]
#687 calls for uniformity in naming. It seems that in the last year(s), naming has become a lot more consistent, with almost all new code using `snake_case` for names. However, there is still a bunch of old names in old code that uses `UpperCamelCase` (for example, the definitions in `CategoryTheory/Limits`). Would it be an idea to update them?

**Comment by arnoudvanderleer** [comment]
I wrote two python scripts to maybe make this a bit easier. They utilize the `.glob` files that are generated on compilation:
 * One script that, given a directory, generates a file containing all names in files in this directory that should be changed, for example:
 ```
 UniMath.CategoryTheory.Limits.Coequalizers coequalizer_eq_ar CoequalizerEqAr
UniMath.CategoryTheory.Limits.Coequalizers coequalizer_eq_ar' Coequalizer_eq_ar
UniMath.CategoryTheory.Limits.Coequalizers coequalizer_object CoequalizerObject
UniMath.CategoryTheory.Limits.Coequalizers coequalizer_out CoequalizerOut
UniMath.CategoryTheory.Limits.Coequalizers coequalizer_out_comp CoequalizerOutComp
UniMath.CategoryTheory.Limits.Coequalizers coequalizer_outs_eq CoequalizerOutsEq
UniMath.CategoryTheory.Limits.Coequalizers coequalizers Coequalizers
UniMath.CategoryTheory.Limits.Coequalizers from_coequalizer_to_coequalizer from_Coequalizer_to_Coequalizer
UniMath.CategoryTheory.Limits.Coequalizers has_coequalizers hasCoequalizers
UniMath.CategoryTheory.Limits.Cokernels has_cokernels hasCokernels
UniMath.CategoryTheory.Limits.Cokernels identity_is_cokernel_out identity_is_CokernelOut
UniMath.CategoryTheory.Limits.Cokernels is_cokernel isCokernel
UniMath.CategoryTheory.Limits.Cokernels is_cokernel_paths isCokernel_paths
UniMath.CategoryTheory.Limits.Cokernels iso_from_cokernel_to_cokernel iso_from_Cokernel_to_Cokernel
UniMath.CategoryTheory.Limits.Cokernels make_cokernel make_Cokernel
UniMath.CategoryTheory.Limits.Cokernels make_is_cokernel make_isCokernel
UniMath.CategoryTheory.Limits.Cokernels make_is_cokernel_uniqueness make_isCokernel_uniqueness
UniMath.CategoryTheory.Limits.Cones base_paths_isotoid_cone base_paths_isotoid_CONE
UniMath.CategoryTheory.Limits.Cones con_epre CONEpre
UniMath.CategoryTheory.Limits.Cones cone CONE
UniMath.CategoryTheory.Limits.Cones cone Cone
UniMath.CategoryTheory.Limits.Cones cone_comp Cone_comp
UniMath.CategoryTheory.Limits.Cones cone_connect ConeConnect
 ```
 * Another script that, given a directory, applies all the changes listed in the file to all names and references in files in this directory.

**Comment by nmvdw** [comment]
One important thing here, is merging order. There are a couple of PRs that will be affected:
- For https://github.com/UniMath/UniMath/pull/1843 and https://github.com/UniMath/UniMath/pull/1840: I think they can be merged rather quickly
- For https://github.com/UniMath/UniMath/pull/1822: here the merging will be a bit slower (and conflicts are caused by the previous refactor). So, this oen requires some more thought.

**Comment by DanGrayson** [comment]
Why bother with a wholesale renaming of identifiers?  We'll get a reputation for making breaking changes, if we do that.

**Comment by arnoudvanderleer** [comment]
> Why bother with a wholesale renaming of identifiers? We'll get a reputation for making breaking changes, if we do that.

I think there are good reasons to bring old code up to standard.
 * **Example**. If we want new users to adhere to a new standard (i.e. use `snake_case` in all identifiers), the old code, especially the code that they encounter early, should give the right example. I ran into a similar problem with my first PR, because I had a directory called `examples` (after the example that `CategoryTheory/categories` set), but then was requested to rename this to `Examples`, because the new standard was to write file and directory names in `UpperCamelCase`.
 * **Consistency**. This is a mix of a functional and an aesthetic benefit:
   * Currently, we have names in the library like `ProductPrCommutes`, `Product_endo_is_identity` and `product_nat_trans_pr_data`. This is confusing and hard to remember, so one will need to copy-paste these identifiers, even if only for the capitalization.
   * Sidenote: it is weird to have two identifiers that differ only in capitalization: `Cone` / `CONE`, `CoequalizerEqAr` / `Coequalizer_eq_ar`.
   * Also, this leads to more inconsistency down the line, because there are multiple ways to create new identifiers that refer these: should it be `nat_trans_to_isProduct` (preserving the capitalization of the old identifier) or `nat_trans_to_is_product` (making the new identifier adhere to the standard)?
   * Personally, I also find it very ugly to have this weird mix of styles in the collection of identifiers and even in the identifiers themselves.

I appreciate your concern about the impact that this has on people who use the library, or pending contributions to the library. I tend (in my optimism, naivete and enthousiasm about progress) to glance over such impact. On the other hand, I think breaking changes cannot be avoided alltogether.
This library, like any software project, needs to be maintained and updated, if we want to prevent old mistakes from continually impeding progress in the future. This maintainance will occasionally involve changes that break code that falls outside our sphere of influence[1].
If the changes we do have the potential to break code elsewhere, we need to be very careful, take our time to do get it right the first time (to prevent creating the necessity for another breaking change down the line), and try to support the people involved as best we can in getting their code up and running again.
I think that the two scripts I mentioned will do a very good job here: we can distribute the second script, together with the file with substitutions, which should allow anyone to update the identifiers in their code to once again match the identifiers in the library.

I still don't really have a clear picture of who would be impacted by this change. You mention a breaking change, but could you please elaborate a bit more on what you think this change will break? Who are the people involved and what are their ties to the UniMath library? How much of the problem do you think would be alleviated by my scripts?

[1] Note there is a very recent precedent: #1838 updated the names of a dozen (semi-central) files and I am not sure whether code outside UniMath was affected by this.

**Comment by arnoudvanderleer** [comment]
And I know that we can probably not do this change overnight. I just hope that we can at least prepare such a change, finalize the list of substitutions, notify people that are using the library, and pick a moment when it is possible to actually make the change.

**Comment by arnoudvanderleer** [comment]
I will close this issue because of a lack of enthousiasm.
