### ISSUE TITLE
Compile times for model categories

### ISSUE THREAD

**Issue by nmvdw** [UniMath/UniMath#1855]
The compile times are due to some changes I had to make for this package to work with the recent changes in UniMath. If I recall correctly, the definitions for monads have changed slightly, and those for comonads have been added. These are apparently significantly slower somehow...

_Originally posted by @DenSinH in https://github.com/UniMath/UniMath/issues/1851#issuecomment-1969129759_

**Comment by DenSinH** [comment]
Working on this in #1858

**Comment by DenSinH** [comment]
I feel like this issue can be closed now, or does the package need to be optimized further?

**Comment by nmvdw** [comment]
Yes, it can be closed
