### ISSUE TITLE
Please pick the version you prefer for Coq 8.19 in Coq Platform 2024.01

### ISSUE THREAD

**Issue by rtetley** [UniMath/UniMath#1863]
The Coq team released Coq `8.19.0` on January 24th, 2024.
The corresponding Coq Platform release `2024.01` should be released before **April 30th, 2024**.
It can be delayed in case of difficulties until May 15th, 2024, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI **works fine** with Coq `8.19.0`.

Coq Platform CI is currently testing opam package `coq-unimath.20231010`
from official repository https://coq.inria.fr/opam/released/packages/coq-unimath/coq-unimath.20231010/opam. 

**In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Coq Platform `2024.01`, please inform us as soon as possible and before **March 31st, 2024**!

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.19~2024.01+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.19~2024.01+beta1.sh) which already supports Coq version `8.19.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/405

**Comment by nmvdw** [comment]
We would like to use the version with tag `v20240321`.

**Comment by rtetley** [comment]
Are you going to do a PR on the opam repo soon ?

**Comment by rmatthes** [comment]
@rtetley : Is the workflow different from last time for the Coq Platform 2023.10 (issue #1788)?

**Comment by rtetley** [comment]
Ah yeah :-) I think in general it is better if the package owners handle the opam releases.
If it doesn't happen we usually handle it ourselves as a curtesy. Last time I was in the middle of doing several of these PRs and I did yours as well for expediency purposes. I can still do it if you won't but I do think it is better practice that you guys do it.

**Comment by rmatthes** [comment]
We have made revisions to older material in the meantime. Therefore, the tag to use should now be `v20240331` (with March 31 instead of March 21).

**Comment by rmatthes** [comment]
I still do not understand what is involved in proposing a PR for OPAM. In October 2023, there was the .tar.gz of the tag, there was a hash - probably calculated locally, and the dependency on Coq >= 8.16.1, which should probably now be >= 8.19.0, and there was a file renaming. And this should now go into `~8.19~2024.01+beta1` if I understood the original post in this issue well. Am I right? I am asking since there was the question of checking the OPAM package, but I do not see such a package.

**Comment by rmatthes** [comment]
I give me one answer myself: for the October '23 version, the given sha512 hash is the one of the source .tar.gz file. Here is the sha512 hash for the March '24 version of today:
`2bbab9d169714f0f98afb5e9a0a3a567efcc28a9e1c9bc4743bc41b5a530941f93a18c1861889041422439a4ffebc4392f10ed607f519b7e7040101567882b62`

**Comment by rmatthes** [comment]
See now my PR https://github.com/coq/opam/pull/3001 and https://github.com/coq/platform/pull/408 .

**Comment by rmatthes** [comment]
I updated the first of these two PR after doing a local Ubuntu 22.04 compilation with Coq 8.18.0 - so the requirement is now `>= "8.18"`.

**Comment by rtetley** [comment]
Thanks ! I will close the issue following the merge of https://github.com/coq/platform/pull/408
