### ISSUE TITLE
Remove undesired axiom

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1876]
Does `Parameter` yield an axiom? The documentation seems to say so: https://coq.inria.fr/doc/V8.19.0/refman/language/core/assumptions.html#coq:cmd.Parameter

In this case, we do not want `Parameter`.

_Originally posted by @benediktahrens in https://github.com/UniMath/UniMath/issues/1874#issuecomment-2050168552_

**Comment by benediktahrens** [comment]
@maggesi @amato-gianluca : It is likely not intended that this parameter is treated like an axiom. Would it be ok to wrap it into a section?

**Comment by amato-gianluca** [comment]
Sure ! The lack of a section is actually a bug in the current code.

**Comment by arnoudvanderleer** [comment]
@rmatthes @benediktahrens So this issue is resolved then?

**Comment by benediktahrens** [comment]
@arnoudvanderleer : Yes, thanks for the reminder! Closing.
