### ISSUE TITLE
Mirroring UniMath

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#192]
Recent outage of bitbucket (a github-like service) made me think about having a mirror of the UniMath repository.
A mirror is a copy of the UniMath repository that is synced regularly (e.g., after any push to UniMath). For it to be useful, it is important that it is stored on a server that is not github.com.
Is that something we should have?

**Comment by arnoudvanderleer** [comment]
Is this the same as #191 ?

**Comment by arnoudvanderleer** [comment]
Closing this, as having an online mirror will function both as a mirror and a backup.
