### ISSUE TITLE
`RezkCompletion.v` and `rezk_completion.v`

### ISSUE THREAD

**Issue by arnoudvanderleer** [UniMath/UniMath#1927]
Because of historical reasons, there are now two files, with names that only differ in capitalization. Currently, `rezk_completion` contains the specific construction via the Yoneda embedding, whereas `RezkCompletion` is about Rezk completions (fully faithful and essentially surjective functors to a univalent category).

How about we put them together in the folder `CategoryTheory/RezkCompletion`, and rename `rezk_completion` to `Construction`?

What do you think, @benediktahrens ?

_Originally posted by @nmvdw in https://github.com/UniMath/UniMath/issues/1926#issuecomment-2333572193_

**Comment by benediktahrens** [comment]
That's an excellent suggestion!
