### ISSUE TITLE
Wiki vs README files

### ISSUE THREAD

**Issue by arnoudvanderleer** [UniMath/UniMath#1931]
On GitHub, there are two common ways for documentation. We can document things in `.md` files, like `README.md` or `USAGE.md`, or we can add documentation on the wiki. UniMath has done both for a long time. In many directories, there is a `README.md`, there are `INSTALL_blah.md` and `USAGE.md` files, we have a `CONTENTS.md` file, and there has been a wiki with a couple of pages for a long time, which has recently seen some updates. #1929 highlighted the confusion that this scattering of documentation files (partially mea culpa) causes.

Now, I would like to establish a policy on which instructions we want to go where. Personally, I would propose the following:
 - The GitHub repository needs a front page. This page will contain a short welcoming message, a short description of what UniMath is, and some links (as a list, or embedded in some text) to more detailed documentation, in order of relevance for a user who lands there ("getting help" should be higher up, IMHO. But that is outside the scope of this discussion).
 - Some files need to be hard to change (like a constitution). I have mainly one in mind, containing the (almost) non-negotiable rules of UniMath: We do not allow inductive types, nor do we allow new axioms. Do not make mathematically significant changes to Foundations. And maybe a handful of other rules.
 - It can be argued that semi-detailed documentation about individual packages (the package `README` files) should be close to the source code that it documents. At the same time, I think it would be good to have a page about the packages of UniMath with a short introduction about what each package is and isn't about.

Anything not in these categories is better put on the wiki, because that is easier to maintain.

What do you think of this, @benediktahrens @rmatthes @nmvdw?

**Comment by nmvdw** [comment]
I think that the most important information should be in `.md` files, and that the wiki should only be supplementary information. If I look for something, then I check `.md` files, and I think that in other libraries, `.md` files contain the most relevant information. In addition, if you clone UniMath, you have access to the `.md` files, while the wiki can only be accessed via Github.

**Comment by arnoudvanderleer** [comment]
Can you give a couple of examples of "most important" and "supplementary"?

**Comment by nmvdw** [comment]
The following are subsets:

Most important:
- Installation instructions
- Style guide
- Links to Zulip
- Citation and link to Zenodo

Supplementary material:
- Exact formulation of the resizing rules
- Papers using UniMath

The most important is what a contributor would need to contribute to UniMath. Supplementary is everything that is interesting but not strictly necessary to contribute.

**Comment by benediktahrens** [comment]
I think a practical reason for having everything in the main repository (and not in the wiki) is that it's easy to clone and get a local copy. (Note that the wiki can also be cloned: https://stackoverflow.com/questions/15080848/how-do-i-clone-a-github-wiki)

We could make a "doc" subdirectory, and move everything into there.

**Comment by arnoudvanderleer** [comment]
@benediktahrens @nmvdw 
Thank you both for the input. Then I think making a `doc`, `docs`, `documentation`, `instructions` (or something like that) folder would be a good idea, to at least have everything more or less in the same place. The style guide on the wiki should then go into the repository, and the style guide of the repository should be updated (for example, `never use Qed` feels very outdated).

Do you think that there is other material that currently resides on the wiki, which should be in the repository (or vice versa)?

**Comment by benediktahrens** [comment]
I think all the documentation from the wiki could be moved to doc/docs/documentation/instructions/information/whatever.

**Comment by arnoudvanderleer** [comment]
That is also fine with me :-)

**Comment by arnoudvanderleer** [comment]
This has been more or less resolved by #1941
