### ISSUE TITLE
Publish a release compatible with Coq 8.20

### ISSUE THREAD

**Issue by SnarkBoojum** [UniMath/UniMath#1937]
(I'm trying to update the Coq ecosystem in Debian, so I'm looking for a set of coherent upstream releases)

**Comment by nmvdw** [comment]
The latest version of UniMath is compatible with Coq 8.20. I didn't try compiling https://github.com/UniMath/UniMath/releases/tag/v20240331 with Coq 8.20, and I am not 100% sure whether it would work (there were some changes that could affect compilation).

**Comment by SnarkBoojum** [comment]
Compilation of version 20240331 fails with Coq 8.20.0 here, and the error message is:
```
COQC UniMath/CategoryTheory/Categories/Universal_Algebra/EqAlgebras.v
File "./UniMath/CategoryTheory/Categories/Universal_Algebra/EqAlgebras.v", line 16, characters 0-22:
Error: Use of "Context" outside sections behaves as "#[local] Parameter" or
"#[local] Axiom" followed by "Existing Instance" for typeclasses.
[context-outside-section,vernacular,default]

make[4]: *** [build/CoqMakefile.make:818: UniMath/CategoryTheory/Categories/Universal_Algebra/EqAlgebras.vo] Error 1
```

**Comment by arnoudvanderleer** [comment]
@nmvdw Can we just take the current state of the repository as a "release"? (Or should we maybe fix some problems that you indicated in an issue, a couple of days back)

**Comment by arnoudvanderleer** [comment]
@SnarkBoojum Do you need an official release? Some parts of the library are still in a somewhat unpreferable state (Some things that come to mind are #[reversible=no] annotations that are no longer needed, and warnings about notations that should be resolved), but overall, it is in a fine state, so you could just take the current version

**Comment by arnoudvanderleer** [comment]
@nmvdw @benediktahrens @rmatthes What are our requirements for publishing a next release? Or do we just do that whenever we feel lik creating a new release?

**Comment by nmvdw** [comment]
I just created a new version: [v20240923](https://github.com/UniMath/UniMath/releases/tag/v20240923), and this version is compatible with Coq 8.20.

**Comment by SnarkBoojum** [comment]
Thanks!

**Comment by arnoudvanderleer** [comment]
@nmvdw Thanks!

**Comment by SnarkBoojum** [comment]
Ah, I closed too fast : compilation went well, but when I try to import, it doesn't work ; `From UniMath Require Import All` fails with:
```
Error: Universe inconsistency. Cannot enforce
UniMath.MoreFoundations.PathsOver.3 <=
UniMath.MoreFoundations.PathsOver.21 because
UniMath.MoreFoundations.PathsOver.21 < UniMath.MoreFoundations.PathsOver.3.
```

**Comment by nmvdw** [comment]
This error is caused by the fact that UniMath must be compiled using `type-in-type`, which, by default, is off in Coq.

**Comment by benediktahrens** [comment]
@nmvdw : I think that compilation has worked fine here?

But the file that imports UniMath also needs to activate `-type-in-type`, either by passing this as a command-line argument or by unsetting universe checking through a command in the importing file.

**Comment by SnarkBoojum** [comment]
The compilation went fine and I used your Makefile, so hopefully everything is covered ; but with the previous version I could just do the import, there was nothing more to do... is it different now?

**Comment by benediktahrens** [comment]
> The compilation went fine and I used your Makefile, so hopefully everything is covered ; but with the previous version I could just do the import, there was nothing more to do... is it different now?

Yes, due to a change in the behaviour of Coq, you need to use `type-in-type` in all files that import UniMath.

**Comment by SnarkBoojum** [comment]
I'm using `coqtop` to check my package for basic sanity -- how do I enable this `type-in-type` parameter?

**Comment by SnarkBoojum** [comment]
Just `coqtop -type-in-type`... ok!
