### ISSUE TITLE
computing with weq's

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#194]
One may sometimes define an equivalence as a composite of a chain of weq's and inverses of weq's.  Here is an example:
```
Definition total2_step {n} (X:stn (S n) -> UU) :
  (Σ i, X i) ≃ (Σ (i:stn n), X (dni _ (lastelement _) i)) ⨿ X (lastelement _).
Proof.
  intros. set (f := weqdnicoprod n (lastelement _)).
  intermediate_weq (Σ x : stn n ⨿ unit, X (f x)).
  { apply invweq. apply weqfp. }
  intermediate_weq ((Σ i, X (f (ii1 i))) ⨿ Σ t, X (f (ii2 t))).
  { apply weqtotal2overcoprod. }
  apply weqcoprodf. { apply weqfibtototal; intro i. apply idweq. }
  apply weqtotal2overunit.
Defined.
```

Now suppose you want to compute something about it.  Then it becomes a problem that the various weq's used and their inverses don't always compute immediately.  Here are two lemmas showing the situation with ```weqfp```:
```
(* Learn how to compute with
      weqfp { X Y : UU } ( w : X ≃ Y )(P:Y-> UU) : (Σ x : X, P (w x)) ≃ (Σ y, P y)  
   and its inverse. *)

Definition weqfp_compute_1 { X Y : UU } ( w : X ≃ Y )(P:Y-> UU) (xp: Σ x,P(w x)) :
  weqfp w P xp = (w (pr1 xp),,pr2 xp).
Proof. reflexivity. Defined.

Definition weqfp_compute_2 { X Y : UU } ( w : X ≃ Y )(P:Y-> UU) (yp:Σ y,P y) :
  invmap (weqfp w P) yp = (invmap w (pr1 yp),,transportf P (! homotweqinvweq w (pr1 yp)) (pr2 yp)).
Proof. intros. induction yp as [y p].
  intermediate_path (invmap (weqfp w P) (_,,transportf P (! homotweqinvweq w y) p)).
  { apply maponpaths. eapply total2_paths; reflexivity. }
  exact (homotinvweqweq _ (_,,_)).
Defined.
```

I propose improving the definition of ```weqfp``` by adding a step at the end where we replace the inverse map by the simple formula for it, displayed above.  I think that would make computations easier, because then one could just unfold ```invmap``` and ```weqfp``` to reveal the result, instead of rummaging around for a computation proposition.

This procedure might help with computability of lots of weq's in the system.

Comments?

**Comment by vladimirias** [comment]
Dan, have you use the fact that to compare two weq’s it is sufficient to compare the corresponding functions, i.e., if (f, is) and (g, is’) are weqs then f=g implies that (f,is)=(g,is1). Similarly one can prove a lemma that the same holds for the function components of invweq.

Vladimir.

**Comment by DanGrayson** [comment]
Yes, that's always the first step of such a proof.

**Comment by DanGrayson** [comment]
It turns out that it's simple to give a direct, computable, proof of weqfp:

```
Definition transport_f_f {X : UU} (P : X ->UU) {x y z : X} (e : x = y) (e' : y = z)
           (p : P x) : transportf P e' (transportf P e p) = transportf P (e @ e') p.
Proof. intros. induction e'. induction e. reflexivity. Defined.

Definition weqfp_map { X Y : UU } ( w : X ≃ Y ) (P:Y->UU) : (Σ x,P(w x)) -> (Σ y, P y).
Proof. intros ? ? ? ? xp. exact (w (pr1 xp),,pr2 xp).
Defined.

Definition weqfp_invmap { X Y : UU } ( w : X ≃ Y ) (P:Y->UU) : (Σ y, P y) -> (Σ x,P(w x)).
Proof. intros ? ? ? ? yp. exact (invmap w (pr1 yp),,transportf P (! homotweqinvweq w (pr1 yp)) (pr2 yp)).
Defined.

Definition weqfp {X Y : UU} (w : X ≃ Y) (P:Y->UU) : (Σ x : X, P (w x)) ≃ (Σ y, P y).
Proof. intros. exists (weqfp_map w P). refine (gradth _ (weqfp_invmap w P) _ _).
  { intros xp. refine (total2_paths _ _).
    { simpl. apply homotinvweqweq. }
    simpl. rewrite <- weq_transportf_adjointness. rewrite transport_f_f. rewrite pathsinv0l. reflexivity. }
  { intros yp. refine (total2_paths _ _).
    { simpl. apply homotweqinvweq. }
    simpl. rewrite transport_f_f. rewrite pathsinv0l. reflexivity. }
Defined.

Definition weqfp_compute_1 { X Y : UU } ( w : X ≃ Y ) (P:Y->UU) : weqfp w P ~ weqfp_map w P.
Proof. intros. intros xp. reflexivity. Defined.

Definition weqfp_compute_2 { X Y : UU } ( w : X ≃ Y ) (P:Y->UU) : invmap (weqfp w P) ~ weqfp_invmap w P.
Proof. intros. intros yp. reflexivity. Defined.
```

**Comment by vladimirias** [comment]
>  I propose improving the definition of weqfp by adding a step at the end
> > where we replace the inverse map by the simple formula for it, displayed
> > above.

You mean to apply it to your definition of an equivalence where the inverse map is part of the structure?

**Comment by DanGrayson** [comment]
No, just to make a weq whose invmap is the one wanted.  (It is a part of
the structure, since
it appears as the first component of the center of the contraction of the
homotopy fiber.)

**Comment by vladimirias** [comment]
I see. Cool.

**Comment by DanGrayson** [comment]
This change to `weqfp` was done in commit 3481d5ab.
