### ISSUE TITLE
Helping Travis

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#210]
http://docs.travis-ci.com/user/speeding-up-the-build/ mentions parallelizing builds.
We could use that by building the packages individually, as in
env:

- PACKAGE=Foundations
- PACKAGE=Ktheory
- PACKAGE=CategoryTheory
- PACKAGE=Dedekind
- PACKAGE=SubstitutionSystems
- PACKAGE=Tactics

script: "make $PACKAGE"

Does that sound reasonable?

**Comment by benediktahrens** [comment]
There is a first attempt here:
https://travis-ci.org/benediktahrens/UniMath/builds/87580609

**Comment by DanGrayson** [comment]
That probably won't save all that much time, since SubstitutionSystems has
to build most of the rest of it, anyway.  I see it took 40 minutes, whereas
we're usually under 50 for the whole thing.

**Comment by benediktahrens** [comment]
On 10/27/2015 08:08 AM, Daniel R. Grayson wrote:
> That probably won't save all that much time, since
> SubstitutionSystems has to build most of the rest of it, anyway.  I
> see it took 40 minutes, whereas we're usually under 50 for the whole
> thing.

It won't save much time - in fact, it will maybe even take longer, since
a lot of compilation is duplicated.

But at least it will (I hope) continue to work: I fear that without that
split, we will more frequently run into Travis timeouts, since we add
more stuff to UniMath outside the SubstitutionSystems package.

**Comment by DanGrayson** [comment]
Maybe we should plan to replace travis with a job on one of our own
machines that monitors
pull requests and tests them.  The github API is fairly complete, so it
wouldn't be
hard to do.  Perhaps there's even a way to receive a notice when a pull
request
is submitted, or after the merge-test is complete.

**Comment by benediktahrens** [comment]
done in #212
