### ISSUE TITLE
nested induction produces a match

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#217]
I was not aware that induction with nested brackets leads to a match.

```

Definition f X Y Z (p : X × Y × Z) : Y.
  intros.
  induction p as [x [y z]].
  exact y.
Defined.

Definition g X Y Z (p : X × Y × Z) : Z.
  intros.
  induction p as [x yz]; induction yz as [y z].
  exact z.
Defined.

Print f.
Print g.
```

We are trying to avoid `match`, so I'll mention this in the style guide.

**Comment by benediktahrens** [comment]
Also, in your examples one would get better computational behaviour by
using the projections.

**Comment by DanGrayson** [comment]
This is in the style guide already:
```
* Do not use `destruct`, `match`, square brackets with `intros`, or
  nested square brackets with `induction`.
```
Closing.

**Comment by vladimirias** [comment]
This is unclear. What "nested square brackets with `induction`” mean? Nested [] followed by “induction” tactic?

**Comment by DanGrayson** [comment]
It means brackets within brackets.  Such as in `induction [[]]`.

**Comment by vladimirias** [comment]
There is also intro [[]] and probably something else. I think anything with nested brackets should be said to be …. of lesser quality/better to avoid.

**Comment by DanGrayson** [comment]
Yes, that's in our style guide already:
```
* Do not use `destruct`, `match`, square brackets with `intros`, or
  nested square brackets with `induction`.
```
The precise reason is that those things produce terms with `match` in them.

**Comment by vladimirias** [comment]
Should we avoid “fixpoint” as well? We probably should. Everything has to eb expressed in terms of the _rec(t) until we construct at least a model of these other language constructs - match and fixpoint.

**Comment by DanGrayson** [comment]
We say that already:
```
* Do not use `Fixpoint`.
```
