### ISSUE TITLE
Slowness when formalizing coproducts as special colimits

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#229]
more precisely, when implementing the fact that coproducts lift to functor categories (from the target category) via a general result of lifting of colimits, instead of a direct proof.

For code, see https://github.com/benediktahrens/UniMath/tree/coprod-lift-functors and observe slowness in the first files that use this lifting, SubstitutionSystems.v and SumOfSignatures.v .
The lifting of coproducts is formalized in FunctorsPointwiseCoproducts.v.

**Comment by DanGrayson** [comment]
The first slow point in SubstitutionSystems.v is in the proof of `bracket_property`, where it
takes 3 seconds to unify the types of the two sides of the equation.  That's the same
point where it thinks forever if we replace your coproducts with mine.  One type is
```
[C, C, hs] ⟦ (pre_composition_functor_data C C C hs hs (U Z)) (Id_H `T), `T ⟧
```
and the other type is
```
[C, C, hs] ⟦ CoproductObject ([C, C] hs) (CPEndC (U Z) ((θ_source C hs H) (`T ⊗ Z))), U p T ⟧
```

Is it possible to code things so they turn out to be the same?

**Comment by benediktahrens** [comment]
On 12/14/2015 04:14 PM, Daniel R. Grayson wrote:
> The first slow point in SubstitutionSystems.v is in the proof of `bracket_property`, where it
> takes 3 seconds to unify the types of the two sides of the equation.  That's the same
> point where it thinks forever if we replace your coproducts with mine.  One type is
> ```
> [C, C, hs] ⟦ (pre_composition_functor_data C C C hs hs (U Z)) (Id_H `T), `T ⟧
> ```
> and the other type is
> ```
> [C, C, hs] ⟦ CoproductObject ([C, C] hs) (CPEndC (U Z) ((θ_source C hs H) (`T ⊗ Z))), U p T ⟧
> ```
>
> Is it possible to code things so they turn out to be the same?


The targets should be convertible.



I am less sure about the sources.


The first should reduce to

(Id_H `T) \bu (U Z)

where \bu is composition of functors ("U Z applied before (Id_H `T)"),
which should reduce to

( Id + H (`T) ) \bu (U Z)

which maybe does not reduce to

U Z + ( H (`T) \bu (U Z) )

which is the source of the second thing.


However, on every object those functors should be (definitionally) the same.


Why are you asking that question?

**Comment by DanGrayson** [comment]
Because it's slow there (3 seconds), and I'm trying to find out why.  It's the same place where my 
replacement bogged down totally.

**Comment by benediktahrens** [comment]
On 12/14/2015 04:14 PM, Daniel R. Grayson wrote:
> The first slow point in SubstitutionSystems.v is in the proof of `bracket_property`, where it
> takes 3 seconds to unify the types of the two sides of the equation.  That's the same
> point where it thinks forever if we replace your coproducts with mine.  One type is
> ```
> [C, C, hs] ⟦ (pre_composition_functor_data C C C hs hs (U Z)) (Id_H `T), `T ⟧
> ```
> and the other type is
> ```
> [C, C, hs] ⟦ CoproductObject ([C, C] hs) (CPEndC (U Z) ((θ_source C hs H) (`T ⊗ Z))), U p T ⟧
> ```
>
> Is it possible to code things so they turn out to be the same?


Oh, ok, sorry. In order to compare two natural transformations of the 
aforementioned types, it is sufficient that source and target functors 
are *convertible on any object*.

That is, given

alpha : nat_trans F G
alpha' : nat_trans F' G'

one can ask whether

alpha = alpha'

if (and only if)

Fx \conv F'x

and

Gx \conv G'x

for any x. Here, \conv means "convertible", and "=" is identity type.

This is because

nat_trans F G \conv \Sigma (p : \forall x, Fx -> Gx), ...

by unfolding, which only depends on Fx and Gx.

**Comment by benediktahrens** [comment]
On 12/14/2015 04:34 PM, Daniel R. Grayson wrote:
> Because it's slow there (3 seconds), and I'm trying to find out why.  It's the same place where my
> replacement bogged down totally.

As I mentioned in the previous email, testing for well-typedness of the 
equality of transformations involves checking whether

pre_composition_functor_data C C C hs hs (U Z)) (Id_H `T)

is pointwise (i.e., on any object of the source category, whatever that 
is) convertible to

  CoproductObject ([C, C] hs) (CPEndC (U Z) ((θ_source C hs H) (`T ⊗ Z)))

which it definitely is.

However, that check involves checking that

(F + G)(x)  \conv  Fx + Gx

which might be difficult to discover in your formulation.

**Comment by DanGrayson** [comment]
No, the problem with my formulation is that it's checking that two types, Hom X Y, and Hom U V, say, are equal.  It turns out that X and U are easily seen to be not equal, but then it spends forever thinking about proving the types are equal anyway.

**Comment by benediktahrens** [comment]
On 12/14/2015 05:52 PM, Daniel R. Grayson wrote:
> No, the problem with my formulation is that it's checking that two
> types, Hom X Y, and Hom U V, say, are equal.  It turns out that X
> and U are easily seen to be not equal, but then it spends forever
> thinking about proving the types are equal anyway.

Mmh, that's a problem.
In the SubstitutionSystems files, we use that we can compare natural 
transformations that are not strictly parallel, all the time.
Checking whether the two functors X and U are convertible is too strict 
for our purposes.

**Comment by DanGrayson** [comment]
Well, maybe I'm wrong about that...

**Comment by DanGrayson** [comment]
Re: " we can compare natural transformations that are not strictly parallel"

Do you mean that you allow yourself to make a comparison f=g when the underlying Hom-types turn out to be equal by accident, even though the source and target are not equal?

**Comment by benediktahrens** [comment]
On 12/14/2015 09:29 PM, Daniel R. Grayson wrote:
> Re: " we can compare natural transformations that are not strictly
> parallel"
> 
> Do you mean that you allow yourself to make a comparison f=g when the
> underlying Hom-types turn out to be equal by accident, even though
> the source and target are not equal?

Yes, that is brilliantly put!

**Comment by DanGrayson** [comment]
Isn't that fishy?  It goes against the grain.

**Comment by benediktahrens** [comment]
On 12/14/2015 11:21 PM, Daniel R. Grayson wrote:
> Isn't that fishy?  It goes against the grain.

I don't think so. Let me give you two informal arguments:

a) Convertibility of source and target functors is too much to ask for,
since you would ask for convertibility of functor axioms, in particular.
So unless you have strict propositions, that would not give you what you
want.

b) If you insist on only comparing really parallel natural
transformations, you could always make them parallel by composing with a
natural isomorphism that is pointwise the identity:
Suppose
a : F -> G
and
a' : F' -> G
such that F not convertible to F', but
Fx convertible to F'x for any x.
Then
a'' = a' o i : F -> G
with i pointwise identity on Fx (or F'x) is parallel to a, and you can
ask whether a = a''.
But
(a = a'') = (forall x, ax = a''x) = (forall x, ax = a'x o id(x)) =
(forall x, ax = a'x) = (a = a')
so it is not quite clear why insisting on the insertion of i should be
useful.

Put differently: you don't gain anything by being able to compare two
natural transformations that are not truly parallel, since you can
always make them parallel by inserting a formal thing (here called i).
That is, if you believe that equality of transformations should be
pointwise equality, i.e., if you believe in funextsec.

**Comment by DanGrayson** [comment]
But, couldn't the repeated need for the type checker to verify that two types are equal explain all the slow-down you are experiencing?  Especially if it compounds in larger expressions?  In that case, insisting on the insertion of i above would save time.

**Comment by DanGrayson** [comment]
Re: "However, that check involves checking that
(F + G)(x)  \conv  Fx + Gx
which might be difficult to discover in your formulation."

That lemma is true by definition in my formulation.  But what about F+G on morphisms.  Must it
agree with the function called CoproductOfArrows?

**Comment by vladimirias** [comment]
Can it be explained by the fact that Mor(F,G) actually depends only on the functor_data of F and G and if the functor data of F’ and G’ is convertible to the functor_data of F and G then Mor(F,G) is convertible to Mor(F’,G’) as a type.

**Comment by DanGrayson** [comment]
Yes, in retrospect, it's perhaps not so fishy: the type of morphisms in a functor category is:
```
Definition is_nat_trans {C C' : precategory_data}
  (F F' : functor_data C C')
  (t : forall x : ob C, F x -->  F' x) :=
  forall (x x' : ob C)(f : x --> x'),
    #F f ;; t x' = t x ;; #F' f.

Definition nat_trans {C C' : precategory_data}
  (F F' : functor_data C C') := total2 (
   fun t : forall x : ob C, F x -->  F' x => is_nat_trans F F' t).
```
For two such types to be identified one needs both targets and both sources to agree on
the object actions and on the arrow actions.  I.e., as Benedikt has said, it's just the proofs
that are ignored, the targets are equal functors, and the sources are equal functors.

**Comment by benediktahrens** [comment]
This issue seems to be resolved, closing.
