### ISSUE TITLE
Minimize dependencies

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#233]
We should check the "Require"s of our files upon whether they are really necessary or not.
Minimizing the dependencies among files leads to shorter (re)compilation times, and can avoid formal loops in the dependency graph.

Jason Gross' bug minimizer [1] can maybe be adapted to do this for us automatically.

[1] https://github.com/JasonGross/coq-tools

**Comment by DanGrayson** [comment]
"make" will inform us of any dependency loops, by the way.

**Comment by DanGrayson** [comment]
The line

"Require Export UniMath.Foundations.Basics.PartC."

at the top of PartD take 0.014 seconds.

**Comment by benediktahrens** [comment]
On 11/08/2015 05:50 PM, Daniel R. Grayson wrote:
> The line
>
> "Require Export UniMath.Foundations.Basics.PartC."
>
> at the top of PartD take 0.014 seconds.

I am not sure what you want to say.
Changing a file will result in recompilation of all its reverse 
dependencies. My goal is to keep the number of reverse dependencies small.
I am not saying that the Require's themselves take a long time.

**Comment by DanGrayson** [comment]
Oh, I didn't understand.  You have a good point.

**Comment by JasonGross** [comment]
> Jason Gross' bug minimizer [1] can maybe be adapted to do this for us automatically.

There's now [a script](https://github.com/JasonGross/coq-tools/blob/master/minimize-requires.py) that should let you do this automatically, with something like
```bash
git ls-files "*.v" | xargs /path/to/minimize-requires.py -i .bak
```
Let me know if you try it and find any bugs.  (Note that all of the dependencies have to be pre-compiled.)

**Comment by benediktahrens** [comment]
I am getting an error message as follows on some of the files:

~/git/benediktahrens/UniMath/UniMath$ ../sub/coq-tools/minimize-requires.py --arg " -indices-matter -type-in-type" -Q . UniMath -i .bak Foundations/Basics/UnivalenceAxiom.v
getting Foundations/Basics/UnivalenceAxiom.v
Traceback (most recent call last):
  File "../sub/coq-tools/minimize-requires.py", line 184, in <module>
    refs = get_references_for(name, types=('lib',), update_globs=True, **env)
  File "/home/ahrens/git/benediktahrens/UniMath/sub/coq-tools/import_util.py", line 279, in get_references_for
    globs = get_glob_file_for(filename, **kwargs)
  File "/home/ahrens/git/benediktahrens/UniMath/sub/coq-tools/import_util.py", line 269, in get_glob_file_for
    make_globs([libname], **kwargs)
  File "/home/ahrens/git/benediktahrens/UniMath/sub/coq-tools/import_util.py", line 253, in make_globs
    (stdout, stderr) = get_makefile_contents(tuple(sorted(list(filenames_v) + list(extra_filenames_v))), **kwargs)
  File "/home/ahrens/git/benediktahrens/UniMath/sub/coq-tools/import_util.py", line 239, in get_makefile_contents
    return get_makefile_contents_helper(coqc=kwargs['coqc'], coq_makefile=kwargs['coq_makefile'], libnames=tuple(kwargs['libnames']), non_recursive_libnames=tuple(kwargs['non_recursive_libnames']), v_files=v_files, coqc_args=kwargs['coqc_args'], verbose=kwargs['verbose'], log=kwargs['log'])
  File "/home/ahrens/git/benediktahrens/UniMath/sub/coq-tools/memoize.py", line 10, in __getitem__
    return dict.__getitem__(self, (tuple(key), tuple((k, kwkey[k]) for k in sorted(kwkey.keys()))))
TypeError: unhashable type: 'list'

**Comment by JasonGross** [comment]
@benediktahrens thanks for the report!  It should be fixed now.  (Note that there's [not yet support for excluding the `Export` lines](https://github.com/JasonGross/coq-tools/issues/29).)

**Comment by benediktahrens** [comment]
@JasonGross  I am having some trouble understanding the tool.
When calling it on a single file, it reads as follows:
```
~/git/benediktahrens/UniMath/UniMath$  ../sub/coq-tools/minimize-requires.py --arg " -indices-matter -type-in-type" -Q . UniMath -i .bak SubstitutionSystems/SubstitutionSystems_Summary.v
getting SubstitutionSystems/SubstitutionSystems_Summary.v
getting SubstitutionSystems/SubstitutionSystems_Summary.glob
Running coq on initial contents...
Successful change
Saving final version of SubstitutionSystems/SubstitutionSystems_Summary.v...
```
When calling it on all the *.v files using
```
~/git/benediktahrens/UniMath/UniMath$ git ls-files "*.v" | xargs ../sub/coq-tools/minimize-requires.py --arg " -indices-matter -type-in-type" -Q . UniMath -i .bak 
```
I get similar output for many files, until I hit
```
WARNING: Unrecognized arguments to coq_makefile: [' -indices-matter -type-in-type']
```
and subsequently
```
"coqdep" -c -Q "." UniMath "PAdics/z_mod_p.v" > "PAdics/z_mod_p.v.d" || ( RV=$?; rm -f "PAdics/z_mod_p.v.d"; exit ${RV} )
*** Warning: in file PAdics/z_mod_p.v, library lemmas is required and has not been found in the loadpath!
```
In the end, the tool bails out with
```
*** Warning: in file CategoryTheory/limits/products_from_pullbacks.v, library RezkCompletion.limits.terminal is required and has not been found in the loadpath!
coqc  -q  -Q "." UniMath   Foundations/Basics/Preamble
0 = 0
     : Prop
coqc  -q  -Q "." UniMath   Foundations/Basics/PartA
File "./Foundations/Basics/PartA.v", line 890, characters 7-8:
Error:
In environment
X : UU
P : X → UU
Q : X → UU
The term "P" has type "X → UU" while it is expected to have type
 "∀ x : X, ?P x" (unable to find a well-typed instantiation for 
"?P": cannot ensure that "X → Type" is a subtype of 
"?X1165 → UU").
/tmp/GmgGQj3c:391: recipe for target 'Foundations/Basics/PartA.vo' failed
make: *** [Foundations/Basics/PartA.vo] Error 1
make: Target 'Foundations/Combinatorics/SimplicialSets.glob' not remade because of errors.
Traceback (most recent call last):
  File "../sub/coq-tools/minimize-requires.py", line 200, in <module>
    annotated_contents = mark_exports(insert_references(contents, ranges, refs, **env), env['keep_exports'])
  File "../sub/coq-tools/minimize-requires.py", line 49, in insert_references
    bad = [(start, end, loc, append, ty) for start, end, loc, append, ty in references
TypeError: 'NoneType' object is not iterable
```

**Comment by JasonGross** [comment]
Try `--arg " -indices-matter" --arg " -type-in-type"` or `--arg=-indices-matter --arg=-type-in-type`; The minimizer passes internal spaces along to `coq_makefile` (for, e.g., if your path has spaces in it), so you need to separate the arguments.  I'll improve the error message, and set up a mode for continuing even when a file errors.

**Comment by JasonGross** [comment]
@benediktahrens Error messages should now be prettier, and you can pass `-k` to have it update all the files it can rather than erroring early.

**Comment by arnoudvanderleer** [comment]
Closing this, because of the newer issue #1664, which does the same suggestion, but also has a valuable policy discussion.
