### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by andrejbauer** [UniMath/UniMath#236]
[Travis CI](https://travis-ci.org) is a GitHub appendage which automagically checks whether committed or proposed code compiles. We use it for HoTT, the HoTT book and Andromeda. It is a very useful sanity check. You might be interested in setting it up for UniMath.

For starters you could scavange the settings in the [HoTT library](https://github.com/HoTT/HoTT) which also has to compile its own Coq before it proceeds with the library proper. However, Travis recently switched to a new platform, while the HoTT library still uses the old one, so perhaps this would be better for UniMath to go with the new thing.

**Comment by DanGrayson** [comment]
We've already done that and depend on it.

I'm not sure what you mean by a new platform, but travis recently introduced a feature where they could stash part of your build in your repository.  I don't much like that idea, because it will bloat the repository.

Thanks, closing.
