### ISSUE TITLE
Subdirectories

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#243]
We have many files that are in the UniMath directory instead of a subdirectory of it. I suggest some subdirectory names:

1. Number_systems
for naturals, integers and rationals. Maybe it makes sense to put Dedekind there as well.
2. Combinatorics
for standard finite sets, finite sets and sequences (which would be better to call finite_sequences)
3. Functionalextensionality should probably be renamed into the Univalence_Axiom and put into Basics.

I don't have a good idea about the rest yet.

**Comment by cathlelay** [comment]
The number_systems sub-directory seams to me a good idea.
Perhaps, p-adic numbers should also go in this sub-directory.

**Comment by DanGrayson** [comment]
The only file there is the README:
```bash
$ pwd
/Users/dan/src/ProofChecking/UniMath/UniMath
$ ls -F
CategoryTheory/  Foundations/  PAdics/	  SubstitutionSystems/
Dedekind/	 Ktheory/      README.md  Tactics/
```

**Comment by vladimirias** [comment]
I meant UniMath/UniMath/

**Comment by DanGrayson** [comment]
I like the idea, with minor amendments to suggest: NumberSystems instead of Number_systems, UnivalenceAxiom instead of Univalence_Axiom, FiniteSequences instead of finite_sequences.

**Comment by vladimirias** [comment]
Yes, it is better this way.

**Comment by DanGrayson** [comment]
I'll also put Sets and Propositions in Basics and remove All.v.

**Comment by benediktahrens** [comment]
All points seem to have been addressed, closing.
