### ISSUE TITLE
computability of the rational numbers

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#244]
My theory about why computations don't work well with rational numbers is that the following
definition uses `funextempty` (via `isapropneg`) unnecessarily:

```
Definition intdomnonzerosubmonoid ( X : intdom ) : @subabmonoids ( rngmultabmonoid X ) .
Proof . intros . split with ( fun x : X => hProppair _ ( isapropneg ( paths x 0 ) ) ) . split .
```

I will work on a replacement for this.

**Comment by DanGrayson** [comment]
I got the computation of 1+1=2 to work in hq today, but it took 22 seconds:
```
  Goal hztohq(nattohz 1) + hztohq(nattohz 1) = hztohq(nattohz 2).
    reflexivity.                  (* fixed, 11 seconds *)
  Defined.                        (* fixed, 11 seconds *)
```

**Comment by mortberg** [comment]
Wow, still cool that it worked! I wonder how long it takes in cubicaltt...

Did you try:

Time Eval vm_compute in (hztohq(nattohz 1) + hztohq(nattohz 1)).

If native_compute works on the version of Coq we are using we should also try it.

**Comment by DanGrayson** [comment]
That's strange: the computation works when the lines are at the end of
the file RationalNumbers.v, but it doesn't work when the lines are in another
file that imports RationalNumbers.vo.  What could cause that?

**Comment by DanGrayson** [comment]
Oh, it's whether kernel term sharing is on...

**Comment by benediktahrens** [comment]
On 12/09/2015 11:23 AM, Daniel R. Grayson wrote:
> That's strange: the computation works when the lines are at the end of
> the file RationalNumbers.v, but it doesn't work when the lines are in another
> file that imports RationalNumbers.vo.  What could cause that?

Can you tell us how the computation fails?

**Comment by DanGrayson** [comment]
It failed by going too long.  But turning kernel term sharing off fixes it.

**Comment by DanGrayson** [comment]
By the way, here's the error message before my recent work:
```
Toplevel input, characters 0-12:
Error: Unable to unify "hztohq (nattohz 2)" with
 "hztohq (nattohz 1) + hztohq (nattohz 1)".
```

**Comment by vladimirias** [comment]
What if you try 1 + 2 = 3 and 2 + 1 = 3 . Is the computation time substantially greater?

**Comment by DanGrayson** [comment]
No, even with 200+300 it takes the same time.

**Comment by vladimirias** [comment]
Great! How about 1/2+1/3=5/6 ?

**Comment by DanGrayson** [comment]
A little longer:

```
Definition n2 : (2 ≠ 0)%nat := tt.
Definition n3 : (3 ≠ 0)%nat := tt.
Definition n6 : (6 ≠ 0)%nat := tt.
Definition nz2 : (nattohz 2 != 0)%hz := nattohzandneq 2 0 (negProp_to_neg
n2).
Definition nz3 : (nattohz 3 != 0)%hz := nattohzandneq 3 0 (negProp_to_neg
n3).
Definition nz6 : (nattohz 6 != 0)%hz := nattohzandneq 6 0 (negProp_to_neg
n6).

Goal (
    (hzhzneztohq (nattohz 1) (nattohz 2) nz2)
    +
    (hzhzneztohq (nattohz 1) (nattohz 3) nz3)
    =
    (hzhzneztohq (nattohz 5) (nattohz 6) nz6)
      ).
  Time reflexivity.             (* 12 seconds *)
Time Defined.                   (* 12 seconds *)
```

**Comment by vladimirias** [comment]
Cool!!

This should become useful to Cath at some point.

**Comment by DanGrayson** [comment]
I just found out that this worked even before my work:
```
  Goal true = hqbooleq (hztohq(nattohz (S O)) + hztohq(nattohz (S O)))
                       (hztohq(nattohz (S (S O)))).
    reflexivity.
  Qed.
```
And presumably it is easy to prove that hqbooleq x y = true implies x = y.

**Comment by andrejbauer** [comment]
Are you guys serious about calling a thing `hzhzneztohq`?

**Comment by DanGrayson** [comment]
I named that recently, but it fits in with the pattern firmly initiated by VV.

**Comment by DanGrayson** [comment]
I have implemented the following way for Catherine to verify identities:
``

Lemma hzone_neg_hzzero : (1 ≠ 0)%hz.
Proof.
  exact (neg_to_negProp (confirm_neg (deceq_to_decrel isdeceqhz, 1%hz, 0%hz))).
Qed.

Lemma hq2eq1plus1 : 2 = 1 + 1.
Proof.
  exact (confirm_pos (hqdeceq, 2, 1+1)).
Qed.

Lemma hq2_gt0 : 2 > 0.
Proof.
  exact_op (confirm_pos (hqgthdec, 2, 0)).
Qed.

Lemma hq1_gt0 : 1 > 0.
Proof.
  exact_op (confirm_pos (hqgthdec, 1, 0)).
Qed.

Lemma hq1ge0 : (0 <= 1)%hq.
Proof.
  exact (confirm_pos (hqlehdec, 0, 1)).
Qed.
```

**Comment by vladimirias** [comment]
Shouldn’t the first lemma be called “hzone_ap_hzzero”?

**Comment by DanGrayson** [comment]
I'd like to downplay the use of the word "apart" and just think of apartness
as the proposition we use for inequality in this context.  Introducing a separate
word makes it sound too alien.

But it's Catherine's choice.

**Comment by DanGrayson** [comment]
In other words, in a constructive approach, using the negation of a proposition
as a proposition is always a last resort.

**Comment by vladimirias** [comment]
Mixing up apartness and inequality is, I think, a bad idea that will confuse people (it confuses me). There is nothing to be ashamed about in using a new concept, to the contrary it emphasizes that what we are doing is new mathematics.

**Comment by vladimirias** [comment]
It won’t be as soon as the type theories with computational univalence will become common.

**Comment by DanGrayson** [comment]
There's nothing new about apartness, in the constructive world.  It's long been realized that the
negation of equality is not a good operator for inequality.  Calling it something else is the way to
convey bashfulness about it, whereas calling it inequality is the way to make it mainstream
and to ease its acceptance.

**Comment by DanGrayson** [comment]
That's a good point.

**Comment by vladimirias** [comment]
Dan,

1. it has a very good name and changing it will only lead to confusion.

2. Calling it inequality is wrong since there is already inequality - the negation of equality.

3. The work we do is new in constructive world as well as in the classical (if we project there).

Vladimir.

**Comment by andrejbauer** [comment]
Some constructivists (Bridges, I think) call apartness inequality and write it as ≠. I personally do not like this terminology and I think it is better to call it apartness. But I think what you're doing here is not really new. It is a variant of things that have been considered by constructivists. However, it is very valuable because you're much closer to standard mathematical community that they could ever hope to be.

**Comment by DanGrayson** [comment]
Well, in any case, I don't insist on my point of view -- it's just a
preference.  What
about "inequality" and "unequality"?  The two notions are so similar!:
given a proposition
P one may consider either its negation "not P" or its "unnegation" Q, by
which I mean any proposition
Q such that "not Q" is logically equivalent to P.

**Comment by vladimirias** [comment]
As far as I understand, the definition of a Dedekind cut that Catherine has invented is new, even when transported into a more usual context such as constructive set theory. It is not a “variant” of any other definition of a Dedekind cut. A variant would be something that is easily seen as being equivalent to the original.

**Comment by DanGrayson** [comment]
Yes, I think her definition of Dedekind cut is new.  Our discussion was more oriented around the  notion of apartness itself and its newness.

**Comment by andrejbauer** [comment]
How does it relate to teh version of constructive single-sided Dedekind cuts by Peter Aczel? I will try to find a reference, but he had a single-sided version which was constructive.

**Comment by andrejbauer** [comment]
Here we go, Peter's [Notes on constructive set theory](http://www.cs.man.ac.uk/~petera/cst.ps.gz), section 3.9. I did not look closely at Catherine's cuts but I did look close enough to get the feeling that they were like Peter's cuts. Are they "essentially the same"? I'd be delighted to see a definition that isn't one of the known ones.

**Comment by vladimirias** [comment]
To me the term unnegation looks Ok, but not for the use instead of apartness because apartness is a particular choice of unnegation that is a part of the structure of the object just like, for example, addition is, and that must satisfy many additional properties to be called “apartness” besides being an unnegation. All possible unnegations of a relation form a set.

The fact that there is a unique unnegation satisfying a certain property in the definition of an apartness field is a lemma particular to this type of objects.

“unnegation” also provides us with a good name for the property of apartness that (not(isap x y) -> (x=y)). This can be now called “isunneg” by analogy with “istras” “isref” etc.

Vladimir.

**Comment by vladimirias** [comment]
My computer can not read the file, says that it is locked.

**Comment by vladimirias** [comment]
I was able to read it with TexShop and then to print it into a usual pdf. Thanks!

**Comment by vladimirias** [comment]
Yes, Lelay’s definition is very different.

Also, Peter’s definition can not count as anything more then an idea of a definition since he does not prove anything at all about it. The same applies to Theorem 3.15 (p.3.15). In fact I have no reason to believe that this theorem is true as stated even under the assumption of the axiom of countable choice (for any surjection from a type to nat there exists (weakly) a section).

Mathematics is about *proving* theorems not about stating theorems. What we do is new mathematics.

**Comment by DanGrayson** [comment]
The problem is that the browser uncompresses it without renaming it.  So
rename it to cst.ps first.
