### ISSUE TITLE
don't use "rewrite"

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#247]
Rewrite is fragile and uses "match", so it is best not to use it.  If people agree,
I'll add that to our guidelines.

See this diff for an example of how to eliminate it:
https://github.com/DanGrayson/UniMath/commit/eb1ed1dd58fe84050f1e47e4385249d01d180b0d

**Comment by benediktahrens** [comment]
I think that this guideline does not apply without qualification. There are many situations where "rewrite" works well (even though there are too many where it doesn't) and where we Qed the proof anyway. 
I am not aware of a reasonable replacement for the rewrite tactic - one involving underscores certainly qualifies as fragile.

**Comment by DanGrayson** [comment]
I think what I meant by "fragile" is that it often stops working when definitions upstream change.

"refine", by contrast, even with blanks, seems robust.

**Comment by DanGrayson** [comment]
Closing.
