### ISSUE TITLE
Questions about the real numbers

### ISSUE THREAD

**Issue by andrejbauer** [UniMath/UniMath#259]
I am looking at the reals in UniMath to understand what is going on. It looks very interesting, as it is not actually any of the known constructive definitions. I am hoping @cathlelay can answer some questions, so I don't have to wade through the code. (I did look, but maybe I missed some points.)

1. **Locatedness** do you anywhere prove the following about a cut `X`: `forall p q, p < q -> X p \/ neg (X q)`? It should somehow follow from your definition.

2. **Dedekind completeness**: there is a proof that the reals are Cauchy complete. Are they also Dedekind complete? This means: if we perform the construction of Dedekind reals starting with the Dedekind reals (instead of rationals), then we will get back Dedekind reals (and not something bigger).

Have you thought about these questions?

**Comment by andrejbauer** [comment]
Here is another kind of completeness that is desirable (for instance, in showing that a uniformly continuous image of a closed interval has a supremum): suppose `S` is a subset of the reals which is inhabited, has an upper bound, and located (for every `x < y` either `x` is below some element of `S` or `y` is an upper bound of `S`). Then `S` has a supremum.

Do you prove such a theorem somewhere? Or plan to?

**Comment by andrejbauer** [comment]
@cathlelay just gave a talk at MAP 2016 meeting about this and she answered some of the questions. In particular, she said that her construction gives Cauchy completeness (every Cauchy sequence converges) but for Dedekind completeness she needs excluded middle. 

This makes me think that her definition of cuts is not constructively equivalent to the usual one. Is this known? Can we get the usual two-sided Dedekind cut from one of Catherine's cuts, without excluded middle? If we can, then we will also get Dedekind completeness. I tried to to do it once but I failed, perhaps Catherine already knows the answer.

**Comment by andrejbauer** [comment]
After talking to @cathlelay and sketching out some proofs on the blackboard, we are (at least I am) sufficiently convinced that her construction is equivalent to the usual construction of two-sided cuts. This implies that the reals in the UniMath library are Dedekind complete *without* use of excluded middle. And both questions in this issue are answered affirmatively, which is excellent.

**Comment by cathlelay** [comment]
Hi,

After reading your formalisation of Dedekind cuts, it seems to me that
there is a similar problem for your cuts and for mines to prove the
completeness: you also suppose that the bounded set of cuts can be
transform into a cut of cuts.
To define such cut for an arbitrary bounded set of cuts, you also need the
excluded middle to prove the property "located".

I will need more work to prove the Dedekind completeness without the
excluded middle.

2016-01-14 8:01 GMT-05:00 Andrej Bauer <notifications@github.com>:

**Comment by andrejbauer** [comment]
It is well known that Dedekind reals are Dedekind complete, intuitionistically.

For a proof have a look at [`Completeness.v`](https://github.com/andrejbauer/dedekind-reals/blob/master/Completeness.v) in my repository on Dedekind reals. I just updated it so that the proof is finished (and I cleaned up after my students), so you could just pull from my repository to update your fork.

**Comment by cathlelay** [comment]
My problem is not that it is well known, my problem is to prove it.

In your proof, you only look a cut of cuts. I have already proved this
particular case in my formalization.

Do you have an idea to prove that an arbitrary non-empty set which is
bounded can be convert in such cut?

2016-01-19 18:46 GMT-05:00 Andrej Bauer <notifications@github.com>:

**Comment by andrejbauer** [comment]
The statement I proved is called Dedekind completeness because it says that if you try to complete the Dedekind reals then you do not get anything new.

The statement "an inhabited bounded set has a supremum" is not Dedekind completeness, it's rather a different form of completeness. It is possible to complete the rationals so that this is the case, see [MacNeille completion](https://ncatlab.org/nlab/show/MacNeille+completion). I think Johstone's elephant has good information about this.

You are right that to prove that an inhabited bounded set has a supremum in the Dedekind reals you need a form of excluded middle. (This is also well known.) However, a lot of analysis can be done without this particular theorem, although not everything.

What is the policy of the UniMath project about using excluded middle?

**Comment by cathlelay** [comment]
Then, I already had Dedekind completeness (with less hypotheses)... I was
just too perfectionist.
Due to my definition, Cauchy completeness will be more useful for further
applications.

About the excluded middle, it is an additional axiom which don't aim to be
use for main developments.

2016-01-19 19:30 GMT-05:00 Andrej Bauer <notifications@github.com>:

**Comment by vladimirias** [comment]
> What is the policy of the UniMath project about using excluded middle?
> 

We have never used it yet.

I look forward to the creation of a branch (in the sense of file structure not in the sense of github) of the library that will be devoted to the classical mathematics but it has not been started yet.

**Comment by andrejbauer** [comment]
Ok. Feel free to use my brain as a reference to constructive math (although a lot of things are "known" but difficult to find in print).
