### ISSUE TITLE
Add unicode symbol(s) for latex introduced by last PR from DG

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#272]
Place to edit is the COQDOCLATEXOPTIONS (or similar) variable in Makefile.

! Package ucs Error: Unknown Unicode character 9726 = U+25FE,
(ucs)                possibly declared in uni-37.def.
(ucs)                Type H to see if it is available with options.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.400 \coqdockw{Notation} "F ◾
                                 b" := (\coqdocvar{functor\_object\_applicat...

?

**Comment by DanGrayson** [comment]
What command did you run to provoke the error?

**Comment by benediktahrens** [comment]
On 01/19/2016 10:33 AM, Daniel R. Grayson wrote:
> What command did you run to provoke the error?

"make world" compiles the LaTeX documentation.

This is a common error when introducing previously unused unicode
notation, and simple to fix in the Makefile.

**Comment by benediktahrens** [comment]
closed by #275
