### ISSUE TITLE
Size of normal forms of terms involving gradth

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#274]
I've been experimenting a bit with computing normal forms of terms in UniMath and noticed some strange things. This was all started by some problem that we had when computing the normal form of univalence in cubicaltt around Christmas which is now solved, for details see:

https://github.com/mortberg/cubicaltt/issues/26

When I was computing the normal form of various terms in cubicaltt it struck me that I should try with the corresponding results in UniMath as well just to see if the slowness was due to cubicaltt or not. What I noticed was that it was not at all possible to compute the normal form of some terms in UniMath, for example subtypeEquality:

```
Eval compute in subtypeEquality. (* This makes my computer run of of memory *)
```

I can compute the normal form of this in cubicaltt, but the output is huge. I also managed to track down some interesting complexity increase when normalizing `isweqinvmap`. This lemma relies on four different things which all normalize in no time:

```
Time Eval compute in gradth.
(* Finished transaction in 0.141 secs (0.116u,0.s) (successful) *)
Time Eval compute in invmap.
(* Finished transaction in 0.004 secs (0.u,0.s) (successful) *)
Time Eval compute in homotweqinvweq.
(* Finished transaction in 0.003 secs (0.u,0.s) (successful) *)
Eval compute in homotinvweqweq.
(* Finished transaction in 0.01 secs (0.u,0.s) (successful) *)
```

but when one combines all of these in `isweqinvmap` things get quite slow:

```
Time Eval compute in isweqinvmap.
(* Finished transaction in 19.739 secs (18.499u,0.266s) (successful) *)
```

So it seems like `gradth` makes the computation slow even for small input. Interestingly we managed to compute the normal form of univalence in cubicaltt only after proving it in a different way not using gradth, for details see:

https://github.com/mortberg/cubicaltt/blob/master/examples/univalence.ctt

Have anyone else experienced similar things when using `gradth`? And does anyone have some intuition for why this happens?

**Comment by mortberg** [comment]
I managed to send this issue prematurely, I've now finished it so I will reopen it.

**Comment by mortberg** [comment]
Vladimir and I did some tests today and noticed why the normal form of `gradth` can become so huge and slow to compute. The reason seems to be that the arguments to gradth gets duplicated very many times in the normal form. More precisely:

`f` occurs 5220 times
`g` occurs 1778 times
`efg` occurs 50 times
`egf` occurs 138 times

so if any of these are large things will explode. In the case of `isweqinvmap` which takes about 30s to normalize on my computer the `f` in `gradth` is instantiated to `invmap w` whose normal form is about 20 lines which might explain why it is so slow to normalize. I think this issue can be considered resolved now.

**Comment by DanGrayson** [comment]
It might be useful to see whether Kernel Term Sharing is on or off.  We had to turn it
off long ago to get certain things to work, but this might be a case where having it on
would be a big win.

Let' reopen this for that experiment.

**Comment by benediktahrens** [comment]
I think that @mortberg did some testing. Any interesting results?

**Comment by DanGrayson** [comment]
Oh, yes, he sent me an email.  The changes were not significant.  Closing.

**Comment by mortberg** [comment]
Here is what I wrote to Dan and forgot to post here:

I now normalized `isweqmaponpaths` where the input is much larger than for `isweqinvmap`. I tried with both kernel term sharing and primitive projections and here are the results:

(* Nothing: *)
(* Finished transaction in 137.929 secs (126.149u,2.623s) (successful) *)

(* Kernel term sharing: *)
(* Finished transaction in 125.69 secs (115.046u,1.62s) (successful) *)

(* Primitive projections: *)
(* Finished transaction in 131.208 secs (121.873u,0.273s) (successful) *)

(* Kernel term sharing and primitive projections *)
(* Finished transaction in 127.914 secs (118.089u,0.25s) (successful) *)

As you can see the fastest seems to be with only kernel term sharing.
