### ISSUE TITLE
equivalence obtained using weqbandf does not compute 

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#278]
[ all of that in file functor_categories ]
In PR #277 I prove an equivalence 
weq (iso a b) (iso (F a) (F b))
using weqbandf, called weq_ff_functor_on_iso. 
An equivalence of same type has previously been defined more directly.
In lemma "ff_is_inclusion_on_objects" the direct definition works well, whereas the definition using weqbandf does not: indeed, the inverse seems to not compute as I had hoped.
If anybody has a thought on that, I'd love to hear it.

**Comment by DanGrayson** [comment]
I'd be happy to take a look if you would provide code for the two computations, one that works
well and one that doesn't.

**Comment by benediktahrens** [comment]
On 01/24/2016 03:22 AM, Daniel R. Grayson wrote:
> I'd be happy to take a look if you would provide code for the two computations, one that works
> well and one that doesn't.

Right. See PR #281, and more specifically compare

weq_ff_functor_on_iso_compute

and

weq_ff_functor_on_iso_weqbandf_compute .
