### ISSUE TITLE
Travis moves to new infrastructure

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#283]
I am starting to collect information on new travis infrastructure, see also #282 .

An explanation of the options is given on:
https://gist.github.com/meatballhat/d0c8aab9e3bd8a8bcacd#file-00-intro-md

**Comment by andrejbauer** [comment]
Ah, once you're done you can help with the HoTT library as well :-)

**Comment by benediktahrens** [comment]
This does not seem to cause any problems for the time being, hence I am closing this issue.
