### ISSUE TITLE
UniMath packages with OPAM

### ISSUE THREAD

**Issue by clarus** [UniMath/UniMath#288]
As I understand it, UnitMath includes many interdependent sub-packages, built with Coq. Would it make sense to distribute UniMath on OPAM? OPAM is a package manager for (in particular) distributing Coq libraries; here is the list of currently available packages: [coq.io/opam](http://coq.io/opam/).

**Comment by benediktahrens** [comment]
On 01/30/2016 12:15 PM, Guillaume Claret wrote:
> As I understand it, UnitMath includes many interdependent
> sub-packages, built with Coq. Would it make sense to distribute
> UniMath on OPAM?

One advantage of having UniMath packaged in OPAM would be that people 
could use an existing Coq installation - at least from my limited 
understanding of what Opam is and how it works.

Our current Makefile pulls Coq 8.5 as a submodule and compiles (a 
minimum of) it. Also, our Git repository comes with some extra stuff 
like agda input mode for emacs and so on.
This is convenient for development, but maybe not so much for people who 
want to have a look at UniMath.

> OPAM is a package manager for (in particular)
> distributing Coq libraries; here is the list of currently available
> packages: [coq.io/opam](http://coq.io/opam/).

UniMath is free software (or at least it is our intention for UniMath to 
be free software), so anybody should feel free to upload packages to 
OPAM. The license would need to be part of the package(s), but that 
should not be an obstacle.

**Comment by clarus** [comment]
> UniMath is free software (or at least it is our intention for UniMath to be free software), so anybody should feel free to upload packages to OPAM.

Yes, I would be interested in making a package. What I would need is a Git tag with a version number (such as `v1.0.0`), since packages should follow Git tags rather than Git branches.

> The license would need to be part of the package(s), but that should not be an obstacle.

Exactly, the OPAM packages are meta-data with a download link, but do not include the source code itself.

**Comment by benediktahrens** [comment]
On 01/30/2016 01:32 PM, Guillaume Claret wrote:
>> UniMath is free software (or at least it is our intention for
>> UniMath to be free software), so anybody should feel free to upload
>> packages to OPAM.
>
> Yes, I would be interested in making a package. What I would need is
> a Git tag with a version number (such as `v1.0.0`), since packages
> should follow Git tags rather than Git branches.

See https://github.com/UniMath/UniMath/releases .

Let us know if there is anything else we can do.

**Comment by clarus** [comment]
OK, thanks, I will see what I can do!

**Comment by benediktahrens** [comment]
The UniMath team would like to avoid spending time on packaging, and would like to keep the repository free of packaging artefacts.
According to our license, packaging can of course be done by anyone, outside the main repository, provided that the license is observed. (In particular, this means that any OPAM package should ship the license file, since a package constitutes a "significant portion".)
I am closing this issue. In case you continue packaging UniMath in your fork, please consider using the issue tracker of your fork for any question regarding packaging. When doing so, you can use Github's "@" feature to keep me in the loop.
Thanks a lot for your interest in UniMath.

**Comment by DanGrayson** [comment]
Reopening.

Karl Palmskog has suggested that he might be willing to package UniMath into a single opam package for us.  That might make installation much simpler for our users.

I don't see a problem with having "packaging artifacts" in our repository.  What would it be?  A single opam package building script file?

**Comment by palmskog** [comment]
I created a bunch of experimental OPAM packages that build directly against the UniMath Git repository, and that carefully note the actual Coq releases they are compatible with (e.g., 8.6.1, 8.7.0).

The best way to maintain these packages (metadata files) would be in a GitHub repository under the `UniMath` organization, e.g., `UniMath/opam-repository`. If someone could create this repo I could move the packages there; for now they live [elsewhere](https://github.com/proofengineering/opam-repository-dev). Github provides a way to directly expose the metadata via HTTP from the repo (`gh-pages` branch).

Here are some examples.

Activate the packages:
```
opam repo add proofengineering-dev http://opam-dev.proofengineering.org
```

Install everything in UniMath into Coq's `user-contrib` to make it globally accessible:
```
opam install UniMath
```

Install only `HomologicalAlgebra` and its dependencies, skipping, e.g., `Topology` (mutually exclusive with having the generic `UniMath` package installed):
```
opam install UniMath-HomologicalAlgebra
```

**Comment by benediktahrens** [comment]
We now have a UniMath package for OPAM - thanks everyone for making it happen. Closing this issue.
