### ISSUE TITLE
License terms are weird

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#289]
The second bullet point of the license is weird:
"If UniMath is used in a paper, please cite it. If you use latex with \usepackage{hyperref} in the preamble of your paper, you may use the following bibtex item."
Asking people to do this and that should not be part of a license.
I am not against the content and spirit of the second bullet point, but it should not be part of the license.

**Comment by vladimirias** [comment]
I am not sure what you think should be there instead. Should we say “The authors of the papers using UniMath are required to do this and that” instead of “please do this and that”. Or “must do this and that”. There is in the license the requirement that the license has to be reproduce with any substantial part of the code, what is the difference?

**Comment by benediktahrens** [comment]
On 01/30/2016 02:41 PM, Vladimir Voevodsky wrote:
> I am not sure what you think should be there instead. Should we say
> “The authors of the papers using UniMath are required to do this and
> that” instead of “please do this and that”. Or “must do this and
> that”. There is in the license the requirement that the license has
> to be reproduce with any substantial part of the code, what is the
> difference?

The first thing is to clarify what it means to "use UniMath in a paper".

**Comment by DanGrayson** [comment]
There is a difference between "please do it" and "you must do it".  If we choose the latter, we should say it.  If we choose the former, it might as well be moved to the README, since it isn't a license requirement.

**Comment by benediktahrens** [comment]
On 01/30/2016 03:24 PM, Daniel R. Grayson wrote:
> There is a difference between "please do it" and "you must do it".
> If we choose the latter, we should say it.  If we choose the former,
> it might as well be moved to the README, since it isn't a license
> requirement.

Right, that was the point I wanted to make in the first post. But even 
before, the premise of that point does not seem well-defined to me.
