### ISSUE TITLE
A tactic for "simple refine (foo _ _ _ ...)"

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#295]
we use "simple refine (foo ...)" a lot, which needs guessing the number of underscores to put after foo.
The wrong number of underscores usually gives an error (instead of leading to unprovable goals or such), which should make it possible to write a tactic a call of which looks like
"sref foo" or such, and which calls "simple refine (foo...)" with the right number of underscores.

This would hopefully make proof scripts more robust vis-a-vis changes in the behaviour of refine and its variants.

**Comment by benediktahrens** [comment]
As a special case which merits separate treatment, I suggest a tactic "mkpair" ("make pair") as
Ltac mkpair := (simple refine (tpair _ _ _ )).
to be introduced directly after the definition of total2.

**Comment by JasonGross** [comment]
Do you want a variant of [`rapply`](https://github.com/HoTT/HoTT/blob/master/theories/Basics/Overture.v#L651)?  Something like
```coq
Ltac simple_rapply p :=
  simple refine p ||
  simple refine (p _) ||
  simple refine (p _ _) ||
  simple refine (p _ _ _) ||
  simple refine (p _ _ _ _) ||
  simple refine (p _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _ _ _ _ _ _) ||
  simple refine (p _ _ _ _ _ _ _ _ _ _ _ _ _ _ _).

Tactic Notation "simple" "rapply" uconstr(p) := simple_rapply p.
```

**Comment by benediktahrens** [comment]
Interesting. What does the "uconstr" do here?

**Comment by JasonGross** [comment]
It allows the term passed to have holes in it, which, and delays things like canonical structure resolution and typeclass inference and coercions to the point of `simple refine`.  (Technically, it says that the argument should be interpreted as an untyped galina preterm.)

**Comment by benediktahrens** [comment]
It is well possible that your stuff here is exactly what I want.
I'll do some testing to see if it works the way I like in some of the now awful-looking places.
Thanks a lot!

**Comment by JasonGross** [comment]
You're welcome!  If it does something that's almost but not quite right, you might find that reversing the order of the attempts in `simple_rapply` is beneficial (they have slightly different behavior when you have something basically looks like an eliminator).

**Comment by benediktahrens** [comment]
In the cases I have tried so far, the order you pasted worked fine, so I am going to go with it.

Since I am at it, could I also copy your code for transparent assert? I have been writing the let statement directly, which works fine, but it does not seem a very robust solution.

**Comment by JasonGross** [comment]
Sure!  But first you should test this version; I think a number of Coq bugs have been fixed:
```coq
Tactic Notation "transparent" "assert" "(" ident(name) ":" constr(type) ")" :=
  simple refine (let name := (_ : type) in _).
```

**Comment by vladimirias** [comment]
Sounds like a good idea.

**Comment by vladimirias** [comment]
Good idea too and having it after the definition of total2 will make it easy for a new user to find.

**Comment by vladimirias** [comment]
> (they have slightly different behavior when you have something basically looks like an eliminator).

Who “they”?

**Comment by DanGrayson** [comment]
Perhaps @JasonGross means that  'simple refine (p _)' and 'simple refine (p _ _)' might both succeed in certain situations, depending on what 'p' is, but I don't know how to make an example of that.

**Comment by JasonGross** [comment]
Simplistic example: `p : forall T, T` and a goal `forall A, A`.  Then `simple refine p` works, as does `simple refine (p _)`, which fills in `T` with `forall A, A`.
