### ISSUE TITLE
license

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#299]
LICENSE.md contains this line:

"This copyright and license shall be included in all copies or substantial portions of the Software."

It seems that "or" should be "of".

**Comment by benediktahrens** [comment]
The MIT license does have the "or" there, see e.g.
https://programmers.stackexchange.com/questions/178486/what-exactly-does-the-condition-in-the-mit-license-imply

**Comment by DanGrayson** [comment]
Still, it makes no sense that way.  To see that, remove the first alternative:

"This copyright and license shall be included in substantial portions of the Software."

**Comment by benediktahrens** [comment]
On 02/12/2016 10:26 PM, Daniel R. Grayson wrote:
> Still, it makes no sense that way.  To see that, remove the first alternative:
> 
> "This copyright and license shall be included in substantial portions of the Software."

I feel that the intent is sufficiently clear, despite the wording being
poor. If you want to suggest a different formulation, I would be happy
to look at it.

**Comment by DanGrayson** [comment]
My initial comment included a proposal.

**Comment by benediktahrens** [comment]
Right. 
I can see that the current wording is weird, but I am weary to change to wording from something that has been accepted/adopted widely to something new. I don't want to form an opinion on this issue, I think.

**Comment by DanGrayson** [comment]
Okay.  I think it's just a persistent misprint that we copied, and am eager to fix it.  Perhaps others will chime in.
