### ISSUE TITLE
Proviola

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#304]
Adding Proviola to our html documentation would be cool, see http://mws.cs.ru.nl/proviola/.

Bas Spitters suggested it, and it's already been done for https://github.com/HoTT/HoTT , so we can mimic what they did.

**Comment by benediktahrens** [comment]
Nobody has shown interest in doing this, closing.

**Comment by rmatthes** [comment]
This lack of interest may also have something to do with 
http://mws.cs.ru.nl/proviola/examples.html
only providing a broken link to a single example.
