### ISSUE TITLE
Use ssreflect documentation style: summary at the beginning of the file, explain the important constants

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#32]
Goal: make the definitions and results of a file accessible to a new user without the user having to read the whole file.
Possible solution: use ssreflect's documentation style, as e.g. shown here:
http://ssr.msr-inria.inria.fr/doc/mathcomp-1.5/MathComp.poly.html
The beginning of the file explains the important constants of the file.
Improvement compared to shown example: In a comment, enclosing an identifier in brackets as in [ident] will turn it into a link in the html documentation. This allows jumping from the summary to the implementation of ident.

**Comment by arnoudvanderleer** [comment]
@benediktahrens This "guideline" has already been added to the wiki. Would you also like to have it added to the official style guide?

**Comment by benediktahrens** [comment]
Yes, I think that would be good.
