### ISSUE TITLE
[CategoryTheory.UnicodeNotations] incompatible with [Ktheory.Precategories], due to notation level/associativity clashes

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [UniMath/UniMath#322]
It is currently impossible to simultaneously import these two libraries together:
```
Require Import UniMath.CategoryTheory.UnicodeNotations.
Require Import UniMath.Ktheory.Precategories.
```
fails, with error
```
Error: Notation _ ;; _ is already defined at level 50 with arguments
at level 50, at next level while it is now required to be at level 50
with arguments at next level, at next level.
```

In other words, they define this notation with different associativities.  Importing them in the other order gives a similar problem with a different notation; I guess there are other points they clash on.

If desired, I’m happy to try to prepare a pull request making them compatible — I’ll probably have time to do so this weekend, or early next week. However, I don’t know the conventions of (much of) the library very well, so if the developers would prefer me to leave this to someone who knows the library better, I’ll stay off it!

**Comment by DanGrayson** [comment]
I'll take a look at it...

**Comment by benediktahrens** [comment]
That error message is certainly amusing when one has some time to kill, but for everyone else the Coq developers should implement a more useful message.
Have you checked if there is a bug report for this message? How did you find out what the problem is?

**Comment by JasonGross** [comment]
The issue is that Coq's parser cannot handle the same notation being declared at different levels / with different associativity; this seems to be an inherent limitation in the camlpX parsers.  You have the following declarations of `;;`:
```bash
$ git grep 'Notation' | grep ';;'
UniMath/CategoryTheory/UnicodeNotations.v:Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g", left associativity).
UniMath/CategoryTheory/equivalences.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/equivalences_lemmas.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/functor_categories.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/limits/cones.v:Local Notation "f ;; g" := (compose f g)(at level 50).
UniMath/CategoryTheory/limits/products_from_pullbacks.v:Local Notation "f ;; g" := (compose f g)(at level 50).
UniMath/CategoryTheory/limits/terminal.v:Local Notation "f ;; g" := (compose f g)(at level 50).
UniMath/CategoryTheory/precategories.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/precomp_ess_surj.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/precomp_fully_faithful.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/slicecat.v:Local Notation "f ;; g"  := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/sub_precategories.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/whiskering.v:Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
UniMath/CategoryTheory/yoneda.v:(* Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").*)
UniMath/Ktheory/Utilities.v:Notation "f ;; g" := (funcomp f g) (at level 50).
```
Might I suggest that you make a top-level file called something like `ReservedNotations.v`, in which you reserve all notations you're planning on using, with things like
```coq
Reserved Notation "f ;; g" (at level 50).
```
etc, and then import that file whenever you declare notations?  Declaring all of the levels in a single file will ensure that there are no clashes.

**Comment by JasonGross** [comment]
Looking at that list, it seems like `UnicodeNotations` is already incompatible with a number of files in the category theory library, such as `equivalences.v`.

**Comment by benediktahrens** [comment]
On 03/17/2016 11:54 PM, Jason Gross wrote:
> Looking at that list, it seems like `UnicodeNotations` is already
> incompatible with a number of files in the category theory library,
> such as `equivalences.v`.

Even considered that in all of those files, the Notation is Local ?

**Comment by JasonGross** [comment]
Oh, sorry, I missed the `Local`.  No, I suppose that is okay, assuming that `Local Reserved Notation` actually works as it should (I'm always wary when messing with Coq's parser).  Is there any reason to have left associativity in UnicodeNotations?  I suspect it'll be confusing if `;;` generally associates one way, but sometimes associates the other way, depending on what file you're in.

**Comment by benediktahrens** [comment]
On 03/18/2016 12:02 AM, Jason Gross wrote:
> Is there any reason to have left associativity in UnicodeNotations?
> I suspect it'll be confusing if `;;` generally associates one way,
> but sometimes associates the other way, depending on what file
> you're in.

No, there is no reason. At least I don't remember why it is the way it is.

To unify, I suggest adding left associativity to the files using Local
Notation.

**Comment by mortberg** [comment]
How about having Reserved Notation in the beginning of each file where a new notation is introduced? It should be easier to maintain precedence, associativity and format rules if you only have them declared once and for all. 

I would be in favour of having a category theory scope as well instead of redefining notations locally in every file, especially for things like "_ ;; _".

**Comment by benediktahrens** [comment]
On 03/18/2016 07:54 AM, Anders Mörtberg wrote:
> How about having Reserved Notation in the beginning of each file
> where a new notation is introduced? It should be easier to maintain
> precedence, associativity and format rules if you only have them
> declared once and for all.
> 
> I would be in favour of having a category theory scope as well
> instead of redefining notations locally in every file, especially for
> things like "_ ;; _".

The reason for not making this particular notation global was that
others might prefer writing composition the other (wrong?) way round.

This problem would persist when putting this notation in a scope, at
least when you want to put other CT notations in that scope as well.

**Comment by mortberg** [comment]
But just having the Reserved part globally will not make the notation global but just the behavior of the notation (wrt precedence, associativity, formatting, etc.)?

**Comment by benediktahrens** [comment]
On 03/18/2016 08:16 AM, Anders Mörtberg wrote:
> But just having the Reserved part globally will not make the notation
> global but just the behavior of the notation (wrt precedence,
> associativity, formatting, etc.)?

That might be quite (too?) restrictive already, e.g., for commonly used
infix symbols.

**Comment by mortberg** [comment]
Yes, that's why I think we should use scopes.
