### ISSUE TITLE
Officializing "→" ?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#325]
The following notation is declared in CT/UnicodeNotations:

Notation "x → y" := (x -> y)
  (at level 90, y at level 200, right associativity): type_scope.
(* written \to in Agda input method *)

It is currently used in files in CT, Ktheory, SubstitutionSystems, and Folds.

Should the notation be declared globally in Foundations/Basics/Preamble ?

**Comment by vladimirias** [comment]
What is it the notation for?

**Comment by benediktahrens** [comment]
On 03/18/2016 10:47 AM, Vladimir Voevodsky wrote:
> What is it the notation for?

It is the notation for the function type.

**Comment by JasonGross** [comment]
Alternatively, you can `Require Export Coq.Unicode.Utf8.` to get that notation; it's in the Coq standard library.

**Comment by benediktahrens** [comment]
On 03/25/2016 02:31 PM, Jason Gross wrote:
> Alternatively, you can `Require Export Coq.Unicode.Utf8.` to get that
> notation; it's in the Coq standard library.

We only compile very little of the Coq standard library, and this 
particular file is not among those we compile.

**Comment by vladimirias** [comment]
I think we only compile or at least only import Coq.init

**Comment by benediktahrens** [comment]
On 03/25/2016 03:03 PM, Vladimir Voevodsky wrote:
> I think we only compile or at least only import Coq.init

Yes, we only make the target "states", which depends on 
Coq.Init.Prelude, which itself depends on the files in Coq.Init.

 From what I understand, the module Prelude is loaded by default when 
Coq is started, and the flag -noinit would need to be used to avoid that.

**Comment by benediktahrens** [comment]
Done in #330 , closing.
