### ISSUE TITLE
A UniMath mailing list?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#327]
Should we have a UniMath mailing list, where people can ask questions concerning installation, contents etc. of UniMath?

**Comment by DanGrayson** [comment]
... or a google group?

**Comment by benediktahrens** [comment]
Yes, that's what I was thinking about.
The name "UniMath" is already taken - any other suggestions?

**Comment by benediktahrens** [comment]
I created 
https://groups.google.com/forum/#!forum/univalent-mathematics
and sent you invites.

For the moment, everyone can join without approval, and everybody can send messages to the list. If it turns out that a lot of spam comes through, we will restrict sending to members, and membership will need approval.

**Comment by andrejbauer** [comment]
Please advertise it on the HoTT mailing list.
