### ISSUE TITLE
Put "Proof." and "Qed."/"Defined." on its own line

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#33]
Suggestion: put Coq commands 
- Proof 
- Qed and 
- Defined 

on their own line.
Advantages:
- provides visual separation between statement (type) and proof (term).
- allows postprocessing of HTML to allow for collapsing and expanding of proofs. See for example
  https://benediktahrens.github.io/coinductives/html/Cat.Category.TriMat.Terminality.html
  for this feature

**Comment by DanGrayson** [comment]
The proof expanding feature makes this well worthwhile.

**Comment by DanGrayson** [comment]
I'll add this advice to the README.  I'll also put in something against using `Qed`, on the grounds that it may prevent a later computation.

**Comment by benediktahrens** [comment]
Done, closing.
