### ISSUE TITLE
About destructing pairs, once again

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#336]
The equivalences following total2asstol and total2asstor in Basics.PartA look like they have been designed to prevent computation, by destructing pairs rather than projecting out of them.
Is that on purpose?

(For the third component, destructing the tuples may be unavoidable, but at least for the first and second components, one could improve computation.)

**Comment by DanGrayson** [comment]
That's Vladimir's code, but it's certainly not intentional.  We should really get primitive projections
working instead of futzing with these little things, but if you need it, go ahead and change it.

**Comment by JasonGross** [comment]
What's stopping you from having working primitive projections projections / eta for sigma types and pairs?

**Comment by DanGrayson** [comment]
I'm working on other things at the moment, and it was my project.
Switching to primitive
projections makes lots of uses of "apply" break, and they have to be
replaced by "refine".

**Comment by JasonGross** [comment]
Does anything break if you replace `apply` with `rapply` everywhere?

```coq
Tactic Notation "rapply" uconstr(p) :=
  refine p ||
  refine (p _) ||
  refine (p _ _) ||
  refine (p _ _ _) ||
  refine (p _ _ _ _) ||
  refine (p _ _ _ _ _) ||
  refine (p _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _ _ _ _ _ _) ||
  refine (p _ _ _ _ _ _ _ _ _ _ _ _ _ _ _).
```

**Comment by DanGrayson** [comment]
Probably.  Often "refine" works worse than "simple refine", since it
introduces pseudovariables for
some things.

**Comment by benediktahrens** [comment]
On 03/26/2016 06:47 PM, Daniel R. Grayson wrote:
> That's Vladimir's code, but it's certainly not intentional.  We
> should really get primitive projections working instead of futzing
> with these little things, but if you need it, go ahead and change
> it.

There are also weqtotal2dirprodcomm and its variants, which don't look
like Vladimir's code.

**Comment by DanGrayson** [comment]
Yes, those are mine.  Again, unintentional.

By the way, "git blame" is accessible in pg with C-x v g.

**Comment by vladimirias** [comment]
No, not intentional. It was written in the early days and I did not think very much about such matters.

**Comment by vladimirias** [comment]
It’s not so much we as the Coq team who should get the primitive projections working in such a way that they don’t slow things down.

**Comment by DanGrayson** [comment]
No, I think it's up to us.  I'm working on it today.  Here is the corresponding issue : https://github.com/UniMath/UniMath/issues/111 .

**Comment by DanGrayson** [comment]
I got everything to compile today with primitive projections.  I'll see whether I can make some more speedups and then submit it.

See https://github.com/DanGrayson/UniMath/tree/primitive-projections

**Comment by benediktahrens** [comment]
On 04/07/2016 03:06 PM, Daniel R. Grayson wrote:
> I got everything to compile today with primitive projections.  I'll
> see whether I can make some more speedups and then submit it.

Peter, Vladimir and I have a large body of code which will have to be
converted.
We would be grateful for any help with that. For instance, if there is a
pattern in the necessary modifications, could you describe it briefly?

**Comment by DanGrayson** [comment]
The only pattern is to try replacing any nearby "apply" by "refine" or "simple refine". But then there were several times where I had to turn off primitive projections, remake everything, Set Printing All, print out the entire proof of the problem lemma, incorporate the appropriate subterm into the proof with "exact", turn on primitive projections, and then trim the subterm as much as possible (replacing bits of it by underscores), possibly replacing "exact" by "refine".

**Comment by vladimirias** [comment]
Does it on the whole makes the library to compile faster or slower?

**Comment by DanGrayson** [comment]
I'm hoping it will be faster.  I'll tell you when I know ...

On Thu, Apr 7, 2016 at 4:09 PM, Vladimir Voevodsky <notifications@github.com

**Comment by DanGrayson** [comment]
I may have spoken too soon about getting all the files to compile with primitive projections -- I was going back and forth and forgot which state it was in.  Instead, at the moment, I'm up to CategoryTheory/lists.v.
