### ISSUE TITLE
Foundations should contain foundations and nothing else

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#350]
Following up on a conversation with Vladimir, I suggest to move out of the directory Foundations everything that is not in Basics. The contents of Basics can be moved one directory up, since Basics really means Foundations.
Besides the clarification this modification brings, it also brings more fine-grained dependencies for package-wise compilation.

**Comment by DanGrayson** [comment]
Sounds good to me.

What about moving "Tactics" to "Padics/Tactics" or somewhere?  It's not a mathematical topic, but its siblings are.

**Comment by vladimirias** [comment]
Did not see this message when I wrote mine :)

**Comment by DanGrayson** [comment]
I'll prepare a pull request for this.  Lots of files will be renamed, so others may wish not
to rename files in preparation for their pull requests.

**Comment by DanGrayson** [comment]
I'm working on separating Foundations into four top level packages, and it
seems to make sense for them to be linearly ordered as

   Basics < NumberSystems < Combinatorics < Algebra

and for none of the files within a package to require files from a later
package.

One obstruction to doing this currently is that NumberSystems/NaturalNumbers
requires Algebra/Domains_and_Fields and Algebra/Archimedean; it might be the
only obstruction.  That dependency involves results in
NumberSystems/NaturalNumbers about "nat" and its order operations both as a rig
and as an archimedean rig.  Probably it would be safe to postpone such high
level treatments of "nat" until later.

Let me know if anyone disagrees.

**Comment by benediktahrens** [comment]
On 01/11/2017 02:14 PM, Daniel R. Grayson wrote:
> I'm working on separating Foundations into four top level packages, and it
> seems to make sense for them to be linearly ordered as
> 
>    Basics < NumberSystems < Combinatorics < Algebra
> 
> and for none of the files within a package to require files from a later
> package.
> 
> One obstruction to doing this currently is that NumberSystems/NaturalNumbers
> requires Algebra/Domains_and_Fields and Algebra/Archimedean; it might be the
> only obstruction.  That dependency involves results in
> NumberSystems/NaturalNumbers about "nat" and its order operations both as a rig
> and as an archimedean rig.  Probably it would be safe to postpone such high
> level treatments of "nat" until later.
> 
> Let me know if anyone disagrees.

I was annoyed recently by the dependency of NaturalNumbers on the files
you mention, because it means that a lot of files need to be compiled
before one can do anything with natural numbers.
In my case, I wanted to do something with signatures, and could not
understand at first why Archimedean would be compiled for that.

So I would be very much in favour of the change you suggest. A file on
natural numbers should come "early" in UniMath.

**Comment by DanGrayson** [comment]
By contrast, the definition of the integers uses a lot from Algebra:
```
Definition hz : commrng := commrigtocommrng natcommrig .
```
So maybe a better plan is to use this ordering:

Basics < Combinatorics < Algebra < NumberSystems

but to put the natural numbers into Basics, and still to remove the rig and archrig stuff
from it.  Combinatorics includes FiniteSets, which depends on lots of facts about natural numbers.

By the way, the real numbers are a number system, right?

**Comment by vladimirias** [comment]
There is a lot of dependencies on algebra in number systems. They are not directly visible because of “Require Export”.

**Comment by vladimirias** [comment]
Splitting nat into two files, the first free from algebra and the second oriented towards statements that require algebra may be the way to go. Then the first nat (nat_basics?) will go to Foundations and the second (nat_algebra?) to number systems with number systems remaining after algebra.
