### ISSUE TITLE
Renaming of (co)products

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#366]
In the near future, the following renaming will happen:

- `Coproduct` and `Product` will be renamed into `BinCoproduct` and `BinProduct`, and similar for access functions
- `ArbitraryCoproduct` will be renamed into `Coproduct`, and analogously for products. Similar for access functions.

I document this here, because the renaming is likely to break some code, e.g., in pull requests. In particular, @tpannila might be affected.

**Comment by tpannila** [comment]
Good. The new names are much better. I will fix my pull requests to match the
new names when the renaming happens.

**Comment by mortberg** [comment]
I'll do the renaming now. Should have it finished before the end of the day.

**Comment by benediktahrens** [comment]
Done in #367 , closing.
