### ISSUE TITLE
Introducing "forall" for hProp

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#369]
I suggest that we renaim the current "forall" notation into the \Pi as it should be and introduce \forall for the dependent product of a family of hProp's with values in hProp - a generalization of the current himpl. 

It will then be similar to how we have two notations one for hexists and one  for total2.

**Comment by DanGrayson** [comment]
That's a good idea, but it will be slow work to look at every single forall and decide which
of them concern evident hProp's, or concern types for which it can be proved that they are hProps.

**Comment by vladimirias** [comment]
I do not suggest to do this work now. I only suggest to change the current notation current \forall to \Pi and to define the hProp  \forall for use in the new code.

**Comment by DanGrayson** [comment]
Sounds good.  I suppose you mean that both ∀ and forall both get totally replaced by Π now.

**Comment by vladimirias** [comment]
Right. Or at least the \forall so that the symbol is freed from the hProp product.

**Comment by DanGrayson** [comment]
Perhaps we need a policy afterwards that forall should not be used and either ∀ or Π should be used.  (I think we can't modify the definition of forall.)
