### ISSUE TITLE
Remove two `Admitted.` from Foundations/Combinatorics/FiniteSequences.v

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#371]
There are

```
Definition weqstnsum1_step {n} (f:stn (S n) -> nat) :
  weqstnsum1 f = weqstnsum1' f.
...
Admitted.
```
and
```
Definition flattenStep {X n} (x: stn (S n) -> Sequence X) :
  flatten (S n,,x) = concatenate (flatten (n,,x ∘ dni_lastelement)) (x (lastelement _)).
...
Admitted.
```

**Comment by DanGrayson** [comment]
That's an unfinished project.  Admitted is sometimes better than Abort, because one has proofs
down the line that depend on it and need to continue to work.

**Comment by benediktahrens** [comment]
On 06/21/2016 08:26 PM, Daniel R. Grayson wrote:
> That's an unfinished project.  Admitted is sometimes better than
> Abort, because one has proofs down the line that depend on it and
> need to continue to work.

I understand that it is convenient sometimes to postpone proofs. But I
think there should be a big warning somewhere, about the fact that there
are admitted proofs in some files.

Would it be a viable alternative to

- give a short name to the statement of the unfinished proof and
- put the statement in the hypotheses of the lemmas that depend on it,
until the earlier lemma is proven

?

Obviously this only works for proofs, not for constructions. But that
may be good enough.

**Comment by DanGrayson** [comment]
Why isn't "Admitted" a big enough warning?  Moreover, anyone can see what axioms are used with "Print Assumptions", so I don't see it being a problem.

**Comment by benediktahrens** [comment]
On 06/21/2016 09:05 PM, Daniel R. Grayson wrote:
> Why isn't "Admitted" a big enough warning?  

Because another person might not even use the admitted lemma, but one
that depends on (one that depends on) an admitted one.
The admitted lemma does not even need to be in the same file/package.

> Moreover, anyone can see
> what axioms are used with "Print Assumptions", so I don't see it
> being a problem.

I would find it a bit annoying if I had to check the assumptions of any
lemma I want to use from a formalized library, even if it only consists
in using that Coq command.
I don't see that as a workaround that scales well, and I believe that
the issue is important enough to deserve a general policy.


A slight variant of my earlier proposition is to put things that depend
on an admitted lemma in a section, where the admitted lemma is assumed
as a hypothesis.
Later, the hypothesis can be replaced by a lemma *of the same name*.
Then *nothing* else has to be changed in the rest of the code.
The Section mechanism of Coq will automatically take care of everything
as long as there is an admitted lemma.

**Comment by vladimirias** [comment]
Then it should remain in your fork and not be a part of Unimath. We should make very sure that there are no such things in any form in the UniMath proper especially now that new authors join in and will judge what the rules are by what they see in the existing files.

It would be good to also say it in the README.

**Comment by vladimirias** [comment]
Dan, not everybody knows that one can see all axioms with Print Assumptions. Admitted and the like really should not be allowed. Otherwise they will proliferate and soon it will be impossible to figure out what has been done and what has not.

There is no problem in keeping all unfinished stuff in private forks - this is one of the reasons we use forks in the first place.

**Comment by vladimirias** [comment]
Also, to run Print Assumptions one has to have UniMath installed on one’s machine. If I want to simply scroll through the files to see what has been done Print Assumptions won’t be available to me.

**Comment by DanGrayson** [comment]
Okay, those are good arguments.  I've submitted a pull request for the
coding style section
of the README:

https://github.com/UniMath/UniMath/pull/377
