### ISSUE TITLE
Remove `Admitted.` from Dedekind/Complements.v

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#372]
Remove this:
```
Definition isarchhz : isarchrng (X := hz) hzgth.
Proof.
...
Admitted.
```

**Comment by cathlelay** [comment]
Done.

**Comment by DanGrayson** [comment]
Done in what pull request?

**Comment by benediktahrens** [comment]
On 06/30/2016 02:07 AM, Daniel R. Grayson wrote:
> Done in what pull request?

In the one that has been around for ages, #349. More specifically, see
commit [1].

[1]
https://github.com/UniMath/UniMath/pull/349/commits/f89ebe701d70e074f2f92f8843c4aa8f938095a7
