### ISSUE TITLE
Remove `Admitted.``` in Foundations/Combinatorics/SimplicialSets.v

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#373]
Remove

```
Definition precatDelta : precategory .
Proof.
...
Admitted.
```

**Comment by DanGrayson** [comment]
This file is commented out in the list of files, so it doesn't ever get compiled.  It was an experiment of Vladimir.  I'll re-enable it and remove the "Admitted".

But it is a file in Foundations that requires files from CategoryTheory, breaking our convention that the list of "packages" can be linearly ordered.  Should it be put somewhere else?

**Comment by benediktahrens** [comment]
On 06/29/2016 10:31 PM, Daniel R. Grayson wrote:
> This file is commented out in the list of files, so it doesn't ever
> get compiled.  It was an experiment of Vladimir.  I'll re-enable it
> and remove the "Admitted".
> 
> But it is a file in Foundations that requires files from
> CategoryTheory, breaking our convention that the list of "packages"
> can be linearly ordered.  Should it be put somewhere else?

Yes, I think it should go into CategoryTheory, if Vladimir agrees.
Would you amend your PR accordingly?

**Comment by DanGrayson** [comment]
Sure.

**Comment by vladimirias** [comment]
It certainly should be taken out of foundations.

There are also two (I think) mistakes there. One is that simplicial sets are defined as covariant functors instead of contravariant (if I remember right) and there was another one which I can not recall right now.

**Comment by vladimirias** [comment]
Not to category theory. We may start a new large folder called “HomotopyTheory” and put it there.

**Comment by DanGrayson** [comment]
Sounds good to me.

**Comment by benediktahrens** [comment]
This `Admitted.` is still present.
