### ISSUE TITLE
Both PartD.v and UnivalenceAxiom.v contain a 'funextfun'

### ISSUE THREAD

**Issue by mvr** [UniMath/UniMath#381]
This leads to some very confusing error messages if some files import UnivalenceAxiom and some don't. One probably only wants to use the funextfun in PartD, for the nearby proof that it is a weak equivalence.

**Comment by vladimirias** [comment]
I think we should have only one axiom in the library - the univalence axiom. Then we should deduce a number of its standard corollaries such as UAP and funextfun and funextempty and use the UA only through the weakest corollary necessary.

The file with the UA and the deduction of these corollaries from it should go between BasicsB which is axiom free and BasicsC where funextempty is used.

**Comment by benediktahrens** [comment]
On 06/23/2016 09:10 PM, Vladimir Voevodsky wrote:
> I think we should have only one axiom in the library - the univalence
> axiom. Then we should deduce a number of its standard corollaries
> such as UAP and funextfun and funextempty and use the UA only through
> the weakest corollary necessary.

I disagree, for the following reason:
if the proof of a result `foo` only uses funext, then using the axiom
funext will make `Print Assumptions foo` show funext.
If instead one uses the corollary fuext, derived from univalence, then
`Print Assumptions foo` will show univalence.

I think that being able to get more fine-grained information from `Print
Assumptions` is worth having several axioms, even if some could (and
should somewhere) be derived from others.


I agree with the original request, however, that the axioms could be
organized a bit better.

**Comment by vladimirias** [comment]
We can then have the structure I suggested with the UA and all its corollaries being in a file between PartB and PartC and to have, in this file, first funext_lemma proved on the basis of UA and then right after it funext as an axiom. At the header of the file we will explain the reason for this structure.

Then it seems we will have both a better organization, clear statement that all of these axioms are corollaries of the UA and the axioms themselves that can be distinguished with "Print assumptions”.

**Comment by DanGrayson** [comment]
That sounds good to me.  Perhaps one could define funext_statement, as well, so that one
could have
```
Definition funext_statement := ... .

Theorem funext_theorem: funext_statement.
Proof. ... Defined.

Axiom funext_axiom: funext_statement.
```
Then the reader's eye would not have to scan the two statements to check them for equality.

**Comment by vladimirias** [comment]
LGTM

**Comment by andrejbauer** [comment]
The HoTT library has a similar arrangement. We also use type classes (which I think UniMath avoids) so that we automatically derive `funext` from `univalence` when univalence was assumed but `funext` is required.

**Comment by benediktahrens** [comment]
On 06/24/2016 09:56 PM, Daniel R. Grayson wrote:
> That sounds good to me.  Perhaps one could define funext_statement, as well, so that one
> could have
> ```
> Definition funext_statement := ... .
> 
> Theorem funext_theorem: funext_statement.
> Proof. ... Defined.
> 
> Axiom funext_axiom: funext_statement.
> ```
> Then the reader's eye would not have to scan the two statements to check them for equality.


That does not prevent users from choosing `funext_theorem` over
`funext_axiom` by accident.

A better arrangement, in my opinion, would be
```
Definition univalence_statement :=
Definition funext_statement :=

Lemma ua_implies_funext : univalence_statement -> funext_statement.
Proof. ... Defined.

Axiom ua : univalence_statement.
Axiom fe : funext_statement.
```
This still makes it possible, but slightly harder, to use univalence
when all one wants is funext.

**Comment by DanGrayson** [comment]
Good point.  My way wouldn't have worked anyway, with the theorem before the axiom.

Another way to fix it so funext_theorem isn't chosen by accident is to add "Local" to its
definition, so it doesn't get exported, but your way is clean.

**Comment by DanGrayson** [comment]
I can take care of this.

I slightly prefer univalenceAxiom to univalence_axiom.  What about other people?

**Comment by benediktahrens** [comment]
On 06/26/2016 02:09 PM, Daniel R. Grayson wrote:
> I can take care of this.
> 
> I slightly prefer univalenceAxiom to univalence_axiom.  What about other people?

Thanks!
I don't have an opinion on the naming.

b

**Comment by vladimirias** [comment]
I like Benedikt’s approach.

**Comment by vladimirias** [comment]
Where is univalence_axiom here:

> That does not prevent users from choosing `funext_theorem` over
> `funext_axiom` by accident.
> 
> A better arrangement, in my opinion, would be
> ```
> Definition univalence_statement :=
> Definition funext_statement :=
> 
> Lemma ua_implies_funext : univalence_statement -> funext_statement.
> Proof. ... Defined.
> 
> Axiom ua : univalence_statement.
> Axiom fe : funext_statement.
> ```
> This still makes it possible, but slightly harder, to use univalence
> when all one wants is funext.

?

PS Don’s we have funext? If so we should keep the name. I don’t like “fe”

**Comment by DanGrayson** [comment]
Benedikt named the axiom `ua`.  That seems too short to me.

**Comment by DanGrayson** [comment]
I like `funextAxiom`.

**Comment by vladimirias** [comment]
This is not a bad name since it is called UA in many texts. But I have never seen fe (other than in the Mendeleev table).

**Comment by benediktahrens** [comment]
My point was to illustrate the organization of the axioms, not to suggest naming. I used short names to keep my email short. In the code, other names should be used.



Am 27. Juni 2016 01:09:56 MESZ, schrieb "Daniel R. Grayson" <notifications@github.com>:

**Comment by DanGrayson** [comment]
How do we take this comment of Vladimir into account now?

```
  (** I do not know at the moment whether [funextfun] is equal (homotopic) to
  [funextfunAxiom]. It is advisable in all cases to use [funextfun] or,
  equivalently, [funextsec], since it can be produced from [funcontr] and
  therefore is well defined up to a canonical equivalence.  In addition it is a
  homotopy inverse of [toforallpaths] which may be true or not for
  [funextsecax]. *)
```

The problem is that `funextStatement` is not known to be a proposition.

**Comment by benediktahrens** [comment]
On 06/28/2016 02:28 AM, Daniel R. Grayson wrote:
> How do we take this comment of Vladimir into account now?
> 
> ```
>   (** I do not know at the moment whether [funextfun] is equal (homotopic) to
>   [funextfunAxiom]. It is advisable in all cases to use [funextfun] or,
>   equivalently, [funextsec], since it can be produced from [funcontr] and
>   therefore is well defined up to a canonical equivalence.  In addition it is a
>   homotopy inverse of [toforallpaths] which may be true or not for
>   [funextsecax]. *)
> ```
> 
> The problem is that `funextStatement` is not known to be a proposition.

We have never said what `funextStatement` is so far, have we?
Should it assert that `toforallpaths` is an equivalence?
The function `toforallpaths` itself can be applied to dependent and
nondependent functions, thus giving rise to two different
`funextStatement`s.

**Comment by DanGrayson** [comment]
Good idea.

One could also consider
```
Axiom fe1 : forall (X Y:UU) (f:X->Y), iscontr (Σ g, f ~ g).
```

**Comment by DanGrayson** [comment]
I've started the reorganization at https://github.com/DanGrayson/UniMath/tree/axiom-reorganization

**Comment by DanGrayson** [comment]
We currently have this:
```
Axiom uahp : ∀ P P':hProp,  (P -> P') -> (P' -> P) -> @paths hProp P P'.

Corollary uahp' : ∀ P Q, isaprop P -> isaprop Q -> (P -> Q) -> (Q -> P) -> P=Q.
```

It seems reasonable to replace the axiom uahp by a theorem and to make uahp' into
the preferred axiom.  The reason is that the implication UA -> uahp requires a
theorem from PartD, namely isapropisaprop, but we want to verify the
implication UA -> uahp earlier, between PartB and PartC, in the file
UnivalenceAxiom.v.

If, on the other hand, uahp is important to preserve as an axiom, I could move
the proof of isapropisaprop into PartB.

**Comment by DanGrayson** [comment]
Actually, no, moving the proof of isapropisaprop into PartB won't work, since it depends on
functional extensionality.  I could try move it into UnivalenceAxiom.v.

**Comment by vladimirias** [comment]
I don’t see why the proof of UA -> uahp would require isapropisaprop. It shouldn’t.

Whether to have uahp or uahp’ as an axiom seems unimportant. It is important however not to change things unless really necessary so I suggest that we keep uahp as an axiom.

**Comment by vladimirias** [comment]
Better leave it where it is.

**Comment by DanGrayson** [comment]
Here's why UA -> uahp requires isapropisaprop.  It's because hProp is the subtype of UU
defined by `isaprop`.  If P Q : hProp and we want to show P=Q, first we show `pr1 P = pr1 Q`.
That reduces us to showing that two proofs of `isaprop P` are equal.

It seems that taking uahp as the axiom would require too much change, so I propose leaving the pull request as is.  (The reason I want the implication UA -> uahp to be proven in UnivalenceAxiom.v is so it can be proven before stating any axioms at all.)
