### ISSUE TITLE
Submodule `lablgtk` still necessary?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#383]
As per #115 , the submodule was necessary to compile CoqIDE on MacOS because of some incompleteness of a homebrew recipe.
Is that still the case? If not, could we remove that stuff?

**Comment by DanGrayson** [comment]
Version 2.18.3_2 started including that file.  I'll take a look.

**Comment by DanGrayson** [comment]
To make it work I have to upgrade sub/coq to the latest trunk commit and to have you all install opam, which involves putting something in your .profile.  Probably installing opam is worthwhile anyway, since it's the ocaml package manager.  Coq's makefile now uses ocamlfind, which can be installed using opam.  Opam itself can be insalled using homebrew.

**Comment by benediktahrens** [comment]
On 06/26/2016 04:05 PM, Daniel R. Grayson wrote:
> To make it work I have to upgrade sub/coq to the latest trunk commit
> and to have you all install opam, which involves putting something in
> your .profile.  Probably installing opam is worthwhile anyway, since
> it's the ocaml package manager.  Coq's makefile now uses ocamlfind,
> which can be installed using opam.  Opam itself can be insalled using
> homebrew.


- I think we had agreed on targeting the stable releases of Coq.
- Your plan sounds like *more* cruft will end up on our system, not
less. I think the status quo is better then.
- Our plan once was to separate out the installation of Coq altogether.
Maybe that is actually the way to go.


But for the short term, I'd prefer doing nothing, after learning about
the options.

**Comment by DanGrayson** [comment]
Okay.

The newest version of coq available in the newest version of Ubuntu is 8.4pl4, which
probably won't compile our proofs, so it's probably best to continue building coq.

We'll wait for 8.5pl2 or 8.6.  (It may require ocamlfind, so we may have to add opam anyway.)

Close if you want to.

**Comment by benediktahrens** [comment]
On 06/26/2016 04:19 PM, Daniel R. Grayson wrote:
> Okay.
> 
> The newest version of coq available in the newest version of Ubuntu is 8.4pl4, which
> probably won't compile our proofs, so it's probably best to continue building coq.
> 
> We'll wait for 8.5pl2 or 8.6.  (It may require ocamlfind, so we may have to add opam anyway.)

I don't understand your last remark: I do have ocamlfind on my Debian
Jessie installation, but I certainly don't have opam. So opam is not a
prerequisite for having ocamlfind.

**Comment by DanGrayson** [comment]
Some of @cathlelay's proofs are broken by the latest version of coq on the trunk -- they all involve uses of patterns involving parentheses with `intros`.  We should probably have an ongoing project of testing the latest trunk version of coq against our code so we can alert them to bugs they introduce, or to alert ourselves to any intentional changes that they introduce.

**Comment by DanGrayson** [comment]
Yes, under ubuntu also `ocamlfind` is provided by the package `ocaml-findlib`.

Perhaps it's just something with homebrew on the mac and the version of ocaml it's installing.  I'll check ...

**Comment by DanGrayson** [comment]
I think it's just that the latest Coq makefile now uses ocamlfind, and that I've never had it on my mac via homebrew.  I guess the homebrew people figure there's no reason to install it if the user can install opam.

**Comment by vladimirias** [comment]
We should make it possible for people who have no idea what .profile is to use UniMath.

**Comment by DanGrayson** [comment]
That's possible.  The command `opam config env` prints out the environment settings required.
Instead of having the user incorporate them in advance by editing their .profile, we could have
our makefile access them, interpret them, and restart make under their influence.

**Comment by DanGrayson** [comment]
Let's do nothing on this until we upgrade to the next stable release of Coq.

**Comment by benediktahrens** [comment]
On 06/29/2016 09:29 PM, Daniel R. Grayson wrote:
> Let's do nothing on this until we upgrade to the next stable release of Coq.

Ok, sounds good.

**Comment by DanGrayson** [comment]
Now that we are on coq 8.6 we require ocamlfind for building.  I'll take a look at this issue again now.

**Comment by vladimirias** [comment]
Is 8.6 faster or slower for us than 8.5?

**Comment by DanGrayson** [comment]
I don't know, but it can't be too much slower if travis is still working.  I could time both of them on my machine, if you like.

**Comment by DanGrayson** [comment]
Vladimir, where is ocamlfind on your mac?  Type

   type ocamlfind

to find out.  If it's not there, you won't be able to rebuild the coq submodule after updating it to our latest version.

**Comment by vladimirias** [comment]
Yes, let’s do it. It is important.

**Comment by DanGrayson** [comment]
Will do.
