### ISSUE TITLE
abstract subproofs

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#397]
To make sure our code compiles on the trunk, I've had to make this change:
```
--- a/UniMath/CategoryTheory/lists.v
+++ b/UniMath/CategoryTheory/lists.v
@@ -409,7 +409,7 @@ simple refine (tpair _ _ _).
     apply funextfun; intro p; rewrite (paireta p);
     generalize (colimArrowCommutes (mk_ColimCocone hF c L ccL) _
                  (mk_cocone _ (omega_cocontConstProdFunctor_subproof
-                               hF c L ccL HcL (f,,hf))) n);
+                               hF HcL (f,,hf))) n);
     unfold flip, curry, colimIn; simpl; intro H;
     now rewrite <- (toforallpaths _ _ _ (toforallpaths _ _ _ H (pr2 p)) (pr1 p))).
 - abstract (
```

In 8.5pl1 the subproof had this type:
```
Import UniMath_DOT_CategoryTheory_DOT_covyonedaomega_cocontConstProdFunctor_subproof
     : ∀ (hF : chain HSET) (HcL : HSET)
       (cc : cocone (mapdiagram constprod_functor hF) HcL) 
       (u v : vertex nat_graph) (e : edge u v),
       dmor hF e ;; flip (curry (pr1 cc v)) = flip (curry (pr1 cc u))
```
, but on the trunk it has this type:
```
omega_cocontConstProdFunctor_subproof
     : ∀ (hF : chain HSET) (c : HSET) (L : cocone hF c),
       isColimCocone hF c L
       → ∀ (HcL : HSET)
       	 (cc : cocone (mapdiagram constprod_functor hF) HcL)
         (u v : vertex nat_graph) (e : edge u v),
         dmor hF e ;; flip (curry (pr1 cc v)) = flip (curry (pr1 cc u))

```

It is unsound to use abstracted subproofs by name, since the precise form of the abstraction
has turned out to be Coq-implementation dependent, and highly unlikely to be understood by a future proof assistant.  Can someone find a proof avoiding citing the subproof?

Shall we add something to the style guide saying not to use abstracted subproofs by name?

**Comment by DanGrayson** [comment]
I'll add something to the style guide ...

**Comment by mortberg** [comment]
Good catch! I don't know what I was thinking while writing this proof... I don't think one should ever rely on automatically generated names for arguments or lemmas. For example one should only use `intros` without giving names to the introduced arguments when the names are not used later.

**Comment by DanGrayson** [comment]
No, `intros` is okay if it's used in the opening of a proof, where the names are visible 2 lines above.  But my pull request from 3 days ago does add this advice:
```
diff --git a/UniMath/README.md b/UniMath/README.md
index 314d7a8..ae2a7b6 100644
--- a/UniMath/README.md
+++ b/UniMath/README.md
@@ -40,6 +40,10 @@ according to the following principles.
 * Do not use ```Fixpoint```.
 * Do not use ```destruct```, ```match```, square brackets with ```intros```, or
   nested square brackets with ```induction```.
+* Use ```as``` to name all new variables introduced by ```induction``` or
+  ```destruct```, if the corresponding type is defined in a remote location,
+  because different names might be used by Coq when the definition of the type
+  is changed.
 * Do not end a proof with ```Qed.```, except with ```Goal```, for that may prevent later computations.
 * Start all proofs with ```Proof.``` on a separate line and end it with
   ```Defined.``` on a separate line, as this makes it possible for us to generate
```

**Comment by DanGrayson** [comment]
... but perhaps we should add a similar rule for `intros` and `intro` for the case when the function is defined in a distant location.

**Comment by mortberg** [comment]
Ok, I agree. My point is that one should never rely on the automatic naming of variables as the naming heuristics might change with new version of Coq.

**Comment by DanGrayson** [comment]
Okay, I'll add something just about depending on automatic naming of variables.

That also applies, by the way, when you use `intros`, and you already have a local variable
of the same name as the parameter, in which case a number is appended automatically.

I'm no longer sure my rule above about `induction` and `destruct` is so good.  The naming
of variables introduced by `induction` is under our control, in the sense that when used
with the definition
```
Inductive total2 { T: Type } ( P: T -> Type ) := tpair : forall ( t : T ) ( p : P t ) , total2 P .
```
, `induction` will introduce variables called `t` and `p`.  But when switching to a record I wrote

```
Record total2 { T: Type } ( P: T -> Type ) := tpair { pr1 : T; pr2 : P pr1 }.
```
instead of
```
Record total2 { T: Type } ( P: T -> Type ) := tpair { t : T; p : P pr1 }.
```
so that `pr1` and `pr2` would be the names of the projections instead of `t` and `p`.  That might be 
unique enough situation that no further warning is required in the style guide.  Users aren't supposed to be introducing other inductive types, and we can simply refrain from renaming the parameters in the inductive types we have.

**Comment by benediktahrens** [comment]
@DanGrayson  you promised to add something about not referring to subproofs to the style guide. Do you still want to do that? Once this is done, this issue can be closed.

**Comment by DanGrayson** [comment]
Okay, will do.
