### ISSUE TITLE
"make" has to be run twice

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#40]
Starting from a fresh clone of the UniMath repository, typing "make" builds just "Coq", and
"make" must be run again to compile our files.

**Comment by benediktahrens** [comment]
The README says that it might be necessary for "make" to be run twice, but it does not say how one can know. Also, it seems to be needed consistently. 
Hence I think it would be less confusing for people if they were simply instructed to run
```bash
make && make
```
like it is done in the Travis script.

**Comment by DanGrayson** [comment]
That would be good, and it can't hurt.  I was trying on an experimental
branch
to fix that misfeature and ran into a problem.  I hope eventually to fix it.
