### ISSUE TITLE
Moving a file

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#406]
HLevel_n_is_of_hlevel_Sn.v should not be in category theory, it should be in Foundations.

**Comment by benediktahrens** [comment]
On 07/10/2016 12:45 AM, Vladimir Voevodsky wrote:
> HLevel_n_is_of_hlevel_Sn.v should not be in category theory, it should be in Foundations. 

Absolutely. However, we should first reorganize Foundations as per issue
#350 , and then move this file to the adequate spot.

**Comment by benediktahrens** [comment]
Duplicate of #523 , closing this one.
