### ISSUE TITLE
"bijective"

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#430]
In Basics/PartA the concept "bijective " is introduced. I am curious who have introduced it and whether it is used.

**Comment by DanGrayson** [comment]
It's my concept (we discussed it once before), and I use it twice in Ktheory: I think it corresponds nicely to one possible meaning of "universal property" -- there exists something, and any two are the same.  Yes, one could instead prove that the type of suitable things is contractible, but this way also seems mathematically intuitive.
