### ISSUE TITLE
A reference question for PartA

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#433]
The lemmas [ weq_transportf_adjointness ] and [ weq_transportb_adjointness ]
and the lemmas from [ equality_cases ] to [ negpathsii2ii1 ] in Basics/PartA are they from HoTT and are they added by Alex Kavvos?

**Comment by DanGrayson** [comment]
No, those are all mine.

**Comment by vladimirias** [comment]
Do you remember when you have added them?

**Comment by DanGrayson** [comment]
No, but git does.  For equality_cases see commit 8fede741941c6eec4300fa7b4b49fc1916a23061 from Sun Nov 8 12:18:33 2015 and for weq_transportf_adjointness  see commit 3481d5ab4b12b416c5a743ef1f8745a651260e47 from Tue Oct 20 15:02:25 2015.

**Comment by benediktahrens** [comment]
@DanGrayson : can this issue be closed?
