### ISSUE TITLE
plural type names

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#440]
Most of our type names are singular nouns, such as `hSet`, `hProp`, `abgr` and `rig`.  But for some reason all our subtype names are plural nouns.  I found these:

```
    subabgrs
    subabmonoids
    subgrs
    submonoids
    subrigs
    subrngs
    sub_precategories
    sub_precategory_morphisms
    sub_precategory_predicate_morphisms
    sub_precategory_predicate_objects
```

I'd like to make them all singular.  The point is that one reads `X : abgr` as "X is an abelian group" and one reads `X : @subabgrs G` as "X is an sub - abelian - group of G", with no plural, so the identifier name should reflect that.

In the same pull request I'd like to make the first argument of those things not optional, so that one can type `X : subabgr G`.  The single topic the PR would be devoted to is "make code such as `X : @subabgrs G` look nicer.

Discussion?

( #436 does this already for `hsubtypes`. )

**Comment by benediktahrens** [comment]
Sounds good to me. But let us first work on the queue of outstanding PRs.

**Comment by benediktahrens** [comment]
`sub_precategories` is another one.

**Comment by DanGrayson** [comment]
Listed that one, already.

**Comment by mortberg** [comment]
I just changed `preserves_colimit` to `preserves_colimits`... That was probably a mistake?

**Comment by DanGrayson** [comment]
No, that's a function, and it sounds like the way you would read it.  I was referring only
to names of types.

**Comment by DanGrayson** [comment]
This has been done, closing.
