### ISSUE TITLE
Policy on merging PRs

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#442]
We have some difficulty merging PRs in a timely manner. 
This might be because we do not have a policy (procedure) on how to handle PRs.
Possible guidelines are:
- Every non-trivial PR should have at least 2 reviewers (the first lgtm's, the second merges).
- Every non-trivial PR should sit at least 48 h before merging, to give people the possibility to look at it.
- A PR should be reviewed within 2 weeks. If that does not happen, people should be poked to do some reviewing.
- Conflicting PRs should be merged in the order they were filed, unless there are good reasons not to.

I intentionally don't give a definition of "non-trivial".
If you have any thoughts on this, I'd be happy to discuss.

**Comment by vladimirias** [comment]
LGTM :)

**Comment by DanGrayson** [comment]
G
