### ISSUE TITLE
do without Coq.Init

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#461]
It would be good to replace Coq.Init by something minimal for the purposes of UniMath, see https://github.com/UniMath/UniMath/pull/449#issuecomment-246539109 .

Coq is licensed by GNU LGPL 2.1, see https://github.com/coq/coq/blob/trunk/LICENSE , so if we copy the parts we need, we should propagate that license for that part.  Or we could rewrite the bit we use from scratch.

**Comment by vladimirias** [comment]
We worked hard with Coq people to be able to run UniMath with the of-the-shelf Coq. We should not go back to a special kind of Coq. On the other hand some solution that does not prevent people to use the of-the-shelf Coq with the UniMath code would be good.

Note also that this, as all our other restrictions, only applies to the code in the UniMath itself and should not prevent people from writing code using both UniMath and the standard library.

The best thing would be to have it as a part of the checks the PRs should pass.

*BTW* We should also add to such checks all we can concerning the automatic checking of the other rules - no Admitted or its  versions, no Inductive except in preamble.v and files in a special subdirectory (package, although the name “package” would be inappropriate here) where people can drop files that they want to contain some things such as the end part of hnat.v etc.

**Comment by DanGrayson** [comment]
Yes, we can have the build script test UniMath both with standard Coq.Init and with our new minimal Coq.Init.  Once Coq v8.5 becomes available in Ubuntu 14.04, we can also test the use of UniMath with Coq binaries as distributed with Ubuntu as part of the build script.

For disabling Admitted, etc., we could accomplish that by modifying the source code of Coq, in a fork of Coq in the UniMath organization.  Our customizations to Coq.Init could be there, too.  The build script would test it both ways.

**Comment by vladimirias** [comment]
This is not what I had in mind. This will be hard to update with changes in Coq and will require a constant attention to these versions.

It should be possible to write a script that does it avoiding the text in comments.

**Comment by DanGrayson** [comment]
Yes, good point.

**Comment by benediktahrens** [comment]
If I remember correctly, there was a discussion recently about the fact
that coqchk, the independent coq proof checker, reports all the axioms
available in a given set of files, even axioms that are never used.

In that discussion, that was seen as a misfeature, since the people were
only interested in the axioms that were used somewhere.

However, for our purposes this "spit out all axioms" feature of coqchk
seems well adapted - at least if "Admitted" theorems are reported as
axioms, which I think is the case.

**Comment by vladimirias** [comment]
This still sounds as a hack and we can not use it to report illegal uses of Inductive and other such things. If we start writing our own script then it will be easy to extend it to include various Coq features that may appear and that we don’t want to be used as well as remove features that we start to allow.

In general, it will be a small (hopefully!) piece of soft that we will have a complete control over and that we can develop in any direction we need.
