### ISSUE TITLE
Cloning lablgtk frequently fails on Travis

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#465]
We clone lablgtk every time, even when we don't compile CoqIDE.
Is there a way to not do that?

**Comment by DanGrayson** [comment]
Benedikt, we don't clone lablgtk every time, I think, because it's cloned only 
by this rule:
```
sub/lablgtk/README:
	git submodule update --init sub/lablgtk
```
Can we close this issue?

**Comment by benediktahrens** [comment]
On 09/21/2016 03:41 PM, Daniel R. Grayson wrote:
> Benedikt, we don't clone lablgtk every time, I think, because it's cloned only 
> by this rule:
> ```
> sub/lablgtk/README:
> 	git submodule update --init sub/lablgtk
> ```

No, see
https://travis-ci.org/UniMath/UniMath/jobs/161527555#L105

The cloning seems to be due to Travis' way of building the test script,
not because of our Makefile.

In this case, we can't do anything, of course, if we want to keep
lablgtk as a submodule (which, according to #383 , we do).

Unless there is a way to prevent Travis from cloning all the submodule
repositories automatically. This seems to be it:
https://stackoverflow.com/questions/10247200/how-to-tell-travis-to-skip-pulling-all-git-submodules-in

**Comment by DanGrayson** [comment]
Okay, see #466

**Comment by DanGrayson** [comment]
Another idea would be to have our own github fork of the lablgtk repository, which is not on github.  Then it would always be obtainable.
