### ISSUE TITLE
Question concerning Notation, Scope

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#468]
In Basics/PartA we have
```
Notation "p # x" := (transportf _ p x) (right associativity, at level 65) : transport.
Notation "p #' x" := (transportb _ p x) (right associativity, at level 65) : transport.
Delimit Scope transport with transport.
```
This notation hides some information (the type family) that is often a bit tricky to infer oneself when reading a statement.
Also, that information is often not inferred automatically by Coq when inputting a statement.
For both reading and writing, this notation is hence a nuissance rather than helpful, at least for me.
Nevertheless it seems to be activated by default. 

Questions:

- Do others like that notation?
- Would it be ok to deactivate it by default?

**Comment by DanGrayson** [comment]
Yes, it can be hard to read expressions printed out that way.  I'm indifferent, so feel free to open the scope only locally, or whatever, in the files that use it.  (Of course, in case of need, one could always insert `Close Scope transport` while debugging.)

**Comment by benediktahrens** [comment]
On 09/24/2016 04:57 PM, Daniel R. Grayson wrote:
> Yes, it can be hard to read expressions printed out that way.  I'm
> indifferent, so feel free to open the scope only locally, or
> whatever, in the files that use it.  (Of course, in case of need, one
> could always insert `Close Scope transport` while debugging.)

What would I need to write in order to have the scope closed by default?

**Comment by DanGrayson** [comment]
I just checked, it is closed by default, since there is no `Open Scope transport` statement.

(There used to be one, but I got tired of it.)

**Comment by benediktahrens** [comment]
On 09/24/2016 05:08 PM, Daniel R. Grayson wrote:
> I just checked, it is closed by default, since there is no `Open
> Scope transport` statement.
> 
> (There used to be one, but I got tired of it.)
> 

I find

Combinatorics/OrderedSets.v:Open Scope transport.

Also, when I work in precategories.v, the notation is activated by default.

I am very confused, help would be appreciated.

**Comment by benediktahrens** [comment]
On 09/24/2016 05:23 PM, Benedikt Ahrens wrote:
> 
> 
> On 09/24/2016 05:08 PM, Daniel R. Grayson wrote:
>> I just checked, it is closed by default, since there is no `Open
>> Scope transport` statement.
>>
>> (There used to be one, but I got tired of it.)
>>
> 
> I find
> 
> Combinatorics/OrderedSets.v:Open Scope transport.
> 
> Also, when I work in precategories.v, the notation is activated by default.
> 
> I am very confused, help would be appreciated.

Also,
```
Close Scope transport.
```
does not have any effect for me, it still shows the notation for
transportf afterwards.

The thing that does have the desired effect is
```
Undelimit Scope transport.
```

**Comment by benediktahrens** [comment]
The difference between the scope `transport` being open or closed is only whether `%transport` is printed or not. Indeed, the effect of `(foo)%transport` is to locally open the scope `transport` in the expression `foo`.

Also, I have the feeling that it is by accident that 
``` 
Undelimit Scope transport. 
```
does what I want.

**Comment by DanGrayson** [comment]
Oh, so "Open" is for parsing and "Delimit" is for printing.

In any case, you're right, there are some statements `Open Scope transport` that have to be changed to `Local Open Scope transport`.  The one you found in `OrderedSets` is the only one not in `Ktheory`.

**Comment by vladimirias** [comment]
It is a misleading notation because the role of the type family is crucial. In my opinion it should be removed. I don’t see how Coq can deterministically infer the type family.

**Comment by JasonGross** [comment]
The thing you want can be achieved by sticking the scope delimiting in a module, and only importing that module when you want to see/use it.

**Comment by DanGrayson** [comment]
Coq often succeeds in determining the type family for transport, as here:
```
UniMath/Foundations/Basics/PartA.v:750:      {p : pr1 x = pr1 y} (q : transportf _ p (pr2 x) = pr2 y) :
UniMath/Foundations/Basics/PartA.v:764:      (p : pr1 x = pr1 y) (q : transportf _ p (pr2 x) = pr2 y) :
UniMath/Foundations/Basics/PartA.v:765:  transportf (fun p' : pr1 x = pr1 y => transportf _ p' (pr2 x) = pr2 y)
UniMath/Foundations/Basics/PartA.v:781:  C x2 (transportf _ p y).
UniMath/Foundations/Basics/PartA.v:792:  tpair (fun y => C x2 y) (transportf _ p  (pr1 yz))
UniMath/Foundations/Basics/PartA.v:1303:  intros. apply (isweqtransportf _ (pathsinv0 e)).
UniMath/Foundations/Basics/PartA.v:1578:  Σ p : pr1 x = pr1 y, transportf _ p (pr2 x) = pr2 y.
UniMath/Foundations/Basics/PartA.v:1591:            tpair (fun p : pr1 x = pr1 y => transportf _ p (pr2 x) = pr2 y)
UniMath/Foundations/Basics/PartA.v:1594:                (fun (pq : Σ p : pr1 x = pr1 y, transportf _ p (pr2 x) = pr2 y) =>
UniMath/Foundations/Basics/PartD.v:374:                (fun y : Y => transportf _ (homotweqinvweq f y) (sy' y))).
UniMath/Foundations/Combinatorics/FiniteSequences.v:334:    exact (transportb _ e x).
UniMath/Foundations/Combinatorics/FiniteSequences.v:339:    exact (transportf _ e x).

UniMath/CategoryTheory/CocontFunctors.v:873:- apply (tpair _ (transportf _ (ifI_eq _ _ _) (x1 i))).
UniMath/CategoryTheory/functor_categories.v:148:    (fun x : pr1 F = pr1 G => transportf _ x (pr2 F) = pr2 G)
UniMath/CategoryTheory/functor_categories.v:499:    set (T:=@functtransportf _ _ (functor_on_objects F)).
UniMath/CategoryTheory/precomp_ess_surj.v:228:  transportf _ (Xphi b t) (kX t) a h =  k b a h.
UniMath/CategoryTheory/slicecat.v:182:                   (total2 (fun (p : a = b) => transportf _ p (pr2 af) = g))).
UniMath/CategoryTheory/slicecat.v:185:assert (weq2 : weq (total2 (fun (p : a = b) => transportf _ p (pr2 af) = g))
UniMath/CategoryTheory/total2_paths.v:65:  {p : pr1 x = pr1 y} (q : transportf _ p (pr2 x) = pr2 y) :
UniMath/CategoryTheory/total2_paths.v:77:  (p : pr1 x = pr1 y) (q : transportf _ p (pr2 x) = pr2 y) :
UniMath/CategoryTheory/total2_paths.v:78:  transportf (fun p' : pr1 x = pr1 y => transportf _ p' (pr2 x) = pr2 y)
UniMath/CategoryTheory/total2_paths.v:93:    (H2 : transportf (fun p : pr1 x = pr1 y =>  transportf _ p (pr2 x) = pr2 y )

UniMath/Ktheory/Bifunctor.v:119:      (e:f~g) (x:X) : transportf _ (funextsec _ _ _ e) (f x) = g x.
UniMath/Ktheory/Utilities.v:355:  transportf _ p ((f t)(x t))
UniMath/Ktheory/Utilities.v:356:  = (transportf (fun t => X t -> Y t) p (f t)) (transportf _ p (x t)).
```

**Comment by mortberg** [comment]
A trick that often proved useful for me to temporarily disable a notation is to write `set foo := transportf` (or `remember transportf as foo`). This will change `transportf` in the goal to `foo` and the notation will hence not be displayed. This only affects the goal but it can be quite useful when `Unset Printing Notations` is too much. This trick is also useful to disable the `=` notation for paths in order to see which type the equality is in (I sometimes get confused when there are a lot of implicit coercions).

**Comment by vladimirias** [comment]
This sounds really useful. Maybe we can make a place for such tricks to be recorded/archived?
