### ISSUE TITLE
bad name

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#471]
total2_subset is a bad name. I suggest carrier_subset, because it is the carrier that has been lifted to hSet from UU.

**Comment by vladimirias** [comment]
Do we have hfiber_subset definition for hfibers of functions between sets? It should be the usual hfiber with a proof that it is a set, so that it coerces into the hfiber under the function from hSet to UU?

**Comment by DanGrayson** [comment]
Re: "total2_subset is a bad name."

Since that's mine, I'll take care of it.

**Comment by DanGrayson** [comment]
Re: "Do we have hfiber_subset..."

I think not.  I'll add it, if you like.

**Comment by vladimirias** [comment]
Yes, it seems to be useful. I wonder how we did without it? Catherine, you must have had a need in the fiber that is a set?

**Comment by benediktahrens** [comment]
The offending name is still in use.

**Comment by DanGrayson** [comment]
I'll do this one this evening.

**Comment by DanGrayson** [comment]
The wanted function `hfiber_subset` (not a good name) is already there as `hfiber_hSet`.
