### ISSUE TITLE
need notation

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#472]
We need to decide on a good infix notation for the composition written in the diagrammatic order.

**Comment by benediktahrens** [comment]
On 09/26/2016 05:45 PM, Vladimir Voevodsky wrote:
> We need to decide on a good infix notation for the composition
> written in the diagrammatic order.

Are you talking about composition in a (pre)category, or about
composition of functions?

**Comment by mortberg** [comment]
For morphisms in (pre)categories we usually write `f ;; g` which I like. The code to introduce this notation is:

https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/precategories.v#L98

Note the two spaces around `;;` in the format, without this I think Coq will print the notation without any spaces.

**Comment by DanGrayson** [comment]
There are two diagrammatic orders, one derived from the diagram `X->Y->Z` and one derived from the diagram `Z<-Y<-X'.

**Comment by DanGrayson** [comment]
Since there two diagrammatic orders, I suggest introducing both ` g ⇴ f ` and `
f ⬰ g `. The latter one would be the same as ` f ∘ g `.  The arrow suggests the diagram aspect and the circle suggests the composition aspect.

**Comment by vladimirias** [comment]
There is only one diagrammatic order - the order that you obtain by following the arrows in the digram in the direction of the arrow. In your second diagram it is exactly the same as in the first.

How is  g ⇴ f called in the Agda mode?

**Comment by DanGrayson** [comment]
Re: "There is only one diagrammatic order - the order that you obtain by following the arrows in the digram in the direction of the arrow."

What do you mean, exactly?  I'll spell out what I meant.  It depends on whether the direction of the arrows in the diagram is leftward or rightward.  For example, in the diagram `Z <--g-- Y <--f-- X` the diagrammatic composition order would be `g o f`, but in the diagram `X --f--> Y --g--> Z` the diagrammatic composition order would be `f o g`.

**Comment by DanGrayson** [comment]
Re: "How is  g ⇴ f called in the Agda mode?"

It's accessible only from the right arrow menu with `\r`, row 4, entry 5, and there are 70 arrows in that menu.  But we can add a name as we did for `\chimney`.

**Comment by vladimirias** [comment]
No, not at all. There is only one diagrammatic order. In both diagrams that you drew it is first f and then g.

If I draw a square where all arrows go in one direction then one of them will point to the right and one to the left but the diagrammatic order will be unique - the one that you get when you follow the arrows in the direction that they point.

**Comment by vladimirias** [comment]
If we call it \dcirc then it is fine with me. We can always change the picture for \dcirc to something else later.

BTW it should be f \dcirc g not g \dcirc f for your diagrams.

**Comment by DanGrayson** [comment]
Re: " the one that you get when you follow the arrows in the direction that they point."

Oh.  Well, then there is still an arbitrary choice, for as you follow the arrows in the direction they point, you have the choice of appending each new name to the right of the sequence or to the left of the sequence.  Maybe you implicitly resolve that choice by pointing out that English is written left to right, so the former is more natural?

I'll implement `\dcirc` for you.

**Comment by vladimirias** [comment]
That’s right! There is a choice - what \circ does is one choice, what \dcirc will do is another.

Let’s not get into how to write things if one writes from right to left!

**Comment by DanGrayson** [comment]
Okay.  

By the way, emacs can do right-to-left for us, if we want, see https://www.gnu.org/software/emacs/manual/html_node/emacs/Bidirectional-Editing.html

**Comment by benediktahrens** [comment]
Dan, you promised to implement \dcirc. Is that still a plan of yours? Can we close this issue soon?

**Comment by DanGrayson** [comment]
Will do.

**Comment by vladimirias** [comment]
BTW I got used to \cdot (LATEX) while working on our paper. Can we have it? What is the Agda-mode name?

**Comment by DanGrayson** [comment]
It's also called \cdot in agda mode.  Do you want to replace the  one you were calling \dcirc?

**Comment by vladimirias** [comment]
> On Feb 21, 2017, at 9:57 PM, Daniel R. Grayson <notifications@github.com> wrote:
> 
> It's also called \cdot in agda mode. Do you want to replace the one you were calling \dcirc?
> 
> 

If \cdot is free then I suggest that we use it for the composition in categories.

**Comment by vladimirias** [comment]
I mean in precategory_data.

**Comment by DanGrayson** [comment]
It's free.  Benedikt?

**Comment by benediktahrens** [comment]
On 02/22/2017 11:45 PM, Daniel R. Grayson wrote:
> It's free.  Benedikt?

Sounds good with me.
Please keep the notation "f ;; g" available for now, *as parse-only*.
TypeTheory will need to be adapted, too.

**Comment by DanGrayson** [comment]
TypeTheory won't need to be adapted, because nothing will break.

**Comment by DanGrayson** [comment]
Benedikt, shall I also change the uses of ;; in files in CategoryTheory to \cdot?

**Comment by DanGrayson** [comment]
Benedikt, what if your Unicode notations for categories were in a scope?  Then they
could be turned on locally, on globally, or off, and you wouldn't need lines like this one scattered about:
```
Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
```
in several files.

**Comment by benediktahrens** [comment]
On 02/23/2017 04:03 AM, Daniel R. Grayson wrote:
> Benedikt, shall I also change the uses of ;; in files in CategoryTheory to \cdot?

Yes, that would be great!

**Comment by benediktahrens** [comment]
On 02/23/2017 04:49 AM, Daniel R. Grayson wrote:
> Benedikt, what if your Unicode notations for categories were in a scope?  Then they
> could be turned on locally, on globally, or off, and you wouldn't need lines like this one scattered about:
> ```
> Local Notation "f ;; g" := (compose f g) (at level 50, format "f  ;;  g").
> ```
> in several files.

I have not yet managed to understand the scope mechanism in Coq.

The one problem I have with Coq notations is that once they are
(globally) activated, one cannot deactivate them any more (at least this
is my understanding).

For the CT library my goal was to make it possible for others to choose
a different notation, e.g., a different order for composition. That is
why all the notation is local.

If the same flexibility can be achieved using scopes, then that is fine
with me.

However, I fear that one would still need a line such as
"Local Open Scope cdot-composition."
at the beginning of each file. But I agree that that would be an
improvement compared to the current situation.

**Comment by benediktahrens** [comment]
On 02/23/2017 02:54 AM, Daniel R. Grayson wrote:
> TypeTheory won't need to be adapted, because nothing will break.

Right, my message was a bit confused - there should have been an "or"
between "adapting TypeTheory" and "keeping ;; parse-only".

**Comment by DanGrayson** [comment]
Vladimir, were you ever interested in this notation for `funcomp`, which is in the current pull request?  Or was there some confusion on my part?
```
Notation "f ⇴ g" := (funcomp f g) (at level 50, left associativity, only parsing).
```
If not, I can remove it.

**Comment by mortberg** [comment]
I have a hard time seeing what that arrow is on my screen (it looks like a tiny black blob with a point thing on the right), maybe I'm using the wrong font but I really prefer a simple readable notation that works in most fonts (this is one argument for not using too esoteric unicode symbols). I should also add that I like "f ;; g", if you're used to programming it is natural to read it as "first do f, then do g". Also it looks good in most standard fonts.

**Comment by DanGrayson** [comment]
If we stop using ";;" in categories we can start using it for funcomp, in which case your explanation makes sense.  It's fine with me.  Do others concur?

**Comment by vladimirias** [comment]
What alternative notation do we have for the composition in the direct order?

**Comment by DanGrayson** [comment]
None, this would be the first.
