### ISSUE TITLE
Aborted proofs in UniMath

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#480]
Thanks to a question by Tomi I discovered that there are aborted proofs in FiniteSequences.

This raises three issues:
1. Please, in the future immediately let everybody know if you find aborted or admitted proofs. Such "proofs" are strictly forbidden in the UniMath.
2. Please immediately remove all statements without full proofs or complete the proofs as the very first priority. 
3. Please (@DanGdayson, @JasonGross?) write a script that will be run every time the make is run that will check that the words "abort" and "admit" do not occur in the .v files.

**Comment by mortberg** [comment]
The following script searches for the words Abort, Admitted and admit in all files in the UniMath subfolder:

``grep -r -E 'Abort|Admitted|admit' UniMath/``

Many of the results seems to be in comments though. I'm not sure how an automated procedure could take that into account, so maybe we should forbid these words from comments as well.

**Comment by DanGrayson** [comment]
We don't have a rule against aborted proofs, only against admitted proofs.  And there
is no reason to introduce such a rule, since an aborted proof results in no definitions.

**Comment by vladimirias** [comment]
There is a reason. UniMath is a library that should be clean. Aborted proofs are Ok in individual forks but there is no reason to have an aborted proof in the library.

**Comment by vladimirias** [comment]
BTW, Tomi, I plan to work on these proofs tomorrow. Hopefully I will be able to complete them. It requires some preliminary work in the standard finite sets file.

**Comment by JasonGross** [comment]
> Many of the results seems to be in comments though. I'm not sure how an automated procedure could take that into account, so maybe we should forbid these words from comments as well.

`Admitted` and `Abort` are always followed by a `.`, and then either by the end of the line or a whitespace character.  (I sincerely hope you never do something like `Admitted (* this is an admitted proof but we haven't ended the proof yet *) .`)  The tactic `admit` is usually followed by a `.` or `;` after optional whitespace, but not always.  Perhaps these are sufficiently distinguishing features?

**Comment by mortberg** [comment]
I don't think all Abort's are bad. It's sometimes instructive to start a Goal, show that something doesn't work and end with an Abort. I have used this for things that should hold by computation if there wasn't any Axiom's involved. See for example https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/Inductives/Lists.v#L224. If someone is trying use this definition of lists and run into problems with something not computing they can read the original file, find this example and first see that direct computation doesn't work and then see what I do afterwards to get it to work.

**Comment by mortberg** [comment]
@JasonGross But that will still find `(* Abort. *)`? The problem I had was that many Abort's are actually commented out, but a simple grep will not see this.

**Comment by benediktahrens** [comment]
On 10/24/2016 03:41 PM, Vladimir Voevodsky wrote:
> Thanks to a question by Tomi I discovered that there are aborted
> proofs in FiniteSequences.
> 
> This raises three issues:
> 
> 1. Please, in the future immediately let everybody know if you find
> aborted or admitted proofs. Such "proofs" are strictly forbidden in
> the UniMath.

It seems worth pointing out that there is a big difference between
'abort' and 'admit'.

Aborting a proof just discards the statement. In particular, the
statement is not taken as an axiom, and its name is not added to the
list of defined constants.

Now, one might still want to avoid aborted proofs in UniMath, because
they are potentially confusing to the reader.
But they are not a danger to consistency.

**Comment by vladimirias** [comment]
Right. I understood it from Dan’s message. Still this looks strange to me. Why put an aborted “proof” into the library? There may be a separate file with problems, statements whose proofs at the moment are not known, but such problems should not be in the form of aborted proofs.

**Comment by tpannila** [comment]
> BTW, Tomi, I plan to work on these proofs tomorrow. Hopefully I will be able to complete them. It requires some preliminary work in the standard finite sets file.

Good. When we have a formalization of finite sequences with all the basic accessor 
functions it should be easier to formalize polynomials, linear algebra, etc.

**Comment by benediktahrens** [comment]
On 10/25/2016 09:36 PM, Vladimir Voevodsky wrote:
> Right. I understood it from Dan’s message.

I sent my email a day ago. I don't know why it took more than 24 hours
to appear on Github.

> Still this looks strange to me. Why put an aborted “proof” into the 
> library? There may be a separate file with problems, statements
> whose proofs at the moment are not known, but such problems should
> not be in the form of aborted proofs.

Is there a better solution?

If we want to record conjectures, then these conjectures should also be
type-checked.

The two solutions that come to my mind are

Theorem foo : bar.
Abort.

or

Check bar.

But the second variant produces noise and looks much less like
'Conjecture' than the first one. Someone might even accidentially delete
the 'Check'.

So, to state a conjecture usefully in Coq only seems possible by using
Abort for the time being.


Putting all the conjectures in a separate file might be one way to clean
up in one sense, but will produce a mess of a different sort.

**Comment by DanGrayson** [comment]
One good reason to allow aborted proofs in the library is that substantial progress may have already been made toward the proof.  Putting the successful part of the proof into the library ensures that it will continue to work as people change other parts of UniMath.  Eventually the proof will be complete.

If you disallow partial proofs in the code, then you should also disallow partial proofs in comments, logically.  Partial proofs in comments are even worse, because they may stop working.

**Comment by vladimirias** [comment]
My preferred solution is:

Definition Conjecture_1 : UU := …. .

(it may, of course, have parameters).

**Comment by vladimirias** [comment]
Wasn’t your plan to move towards triangulated categories and t-structures?

**Comment by tpannila** [comment]
> Wasn’t your plan to move towards triangulated categories and t-structures?

It still is my plan but I have some other plans too.

**Comment by mortberg** [comment]
This is off topic, but @tpannila: If you're going to do linear algebra and polynomials in UniMath I would suggest you take a look at the Mathematical Components project (also referred to as SSReflect). They have a very well written and huge library of formalized mathematics in Coq (including a **lot** of theory about polynomials and linear algebra). This library was developed for the formalization of the odd order theorem about finite groups which is by far the largest formalization in mathematics done in Coq so far.

**Comment by benediktahrens** [comment]
May I suggest that you discuss such ideas on the unimath mailing list instead of on the issue tracker?
As a reminder, the address for that is univalent-mathematics@googlegroups.com.

**Comment by mortberg** [comment]
@benediktahrens: Excellent suggestion, I'll do that in the future.

**Comment by vladimirias** [comment]
The problem with transporting their ideas to UniMath is that they use the inductive types very freely.

**Comment by mortberg** [comment]
I agree that transporting the ideas from SSReflect to UniMath is not easy for multiple reasons. I just wanted to say that there is this huge and very carefully designed library with a lot of linear and abstract algebra that we can get inspiration from when developing these theories in UniMath. I have some more concrete ideas, but let's discuss this in a separate thread on the google group instead.

**Comment by vladimirias** [comment]
I have added two lemmas to the FiniteSequences and with them it should be easy to complete  some and probably all of the aborted proofs in FiniteSequences.

I don’t know who have started these proofs and suggest that the person who started them completes them using these lemmas and if any other difficulties arise point them out to the rest of us and we will try to find a solution.

Vladimir.

**Comment by DanGrayson** [comment]
Those `Abort`s are mine.  (I'd be happy to assign myself to an issue to deal with that later...)

"git blame" is the tool for discovering that, and it's accessible inside emacs this way:

```
C-x v g runs the command vc-annotate (found in global-map), which is an
interactive autoloaded Lisp function in ‘vc-annotate.el’.

It is bound to C-x v g, <menu-bar> <tools> <vc> <vc-annotate>.

(vc-annotate FILE REV &optional DISPLAY-MODE BUF MOVE-POINT-TO VC-BK)

Display the edit history of the current FILE using colors.

This command creates a buffer that shows, for each line of the current
file, when it was last edited and by whom.  Additionally, colors are
used to show the age of each line--blue means oldest, red means
youngest, and intermediate colors indicate intermediate ages.  By
default, the time scale stretches back one year into the past;
everything that is older than that is shown in blue.

With a prefix argument, this command asks two questions in the
minibuffer.  First, you may enter a revision number REV; then the buffer
displays and annotates that revision instead of the working revision
(type RET in the minibuffer to leave that default unchanged).  Then,
you are prompted for the time span in days which the color range
should cover.  For example, a time span of 20 days means that changes
over the past 20 days are shown in red to blue, according to their
age, and everything that is older than that is shown in blue.

If MOVE-POINT-TO is given, move the point to that line.

If VC-BK is given used that VC backend.

Customization variables:

‘vc-annotate-menu-elements’ customizes the menu elements of the
mode-specific menu.  ‘vc-annotate-color-map’ and
‘vc-annotate-very-old-color’ define the mapping of time to colors.
‘vc-annotate-background’ specifies the background color.
‘vc-annotate-background-mode’ specifies whether the color map
should be applied to the background or to the foreground.

[back]
```

**Comment by DanGrayson** [comment]
All but one of those Aborts in FiniteSequences is now gone.
