### ISSUE TITLE
UniMath does not compile

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#481]
Why am I getting this?

File "./UniMath/CategoryTheory/CocontFunctors.v", line 80, characters 0-56:
Error: Compiled library UniMath.CategoryTheory.RightKanExtension.vo makes inconsistent assumptions over library UniMath.Foundations.Basics.Preamble
make: *** [UniMath/CategoryTheory/CocontFunctors.vo] Error 1

while trying to run make?

**Comment by DanGrayson** [comment]
Something is not getting recompiled that should be, so it's best to start the
whole thing over with "make clean".  Perhaps you did "git pull" and things are now
a bit different from what they had been.
