### ISSUE TITLE
option?

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#482]
Do we have a name for the construction that takes X:UU to (coprod X unit) ?

**Comment by mortberg** [comment]
I don't think so. 

If one is doing category theory there is the `option_functor` defined for categories with binary coproducts and a terminal object:

 https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/limits/bincoproducts.v#L950

(when posting this I noticed that the has_homsets assumption is not used, so it should be removed)

**Comment by benediktahrens** [comment]
On 10/25/2016 02:06 PM, Vladimir Voevodsky wrote:
> Do we have a name for the construction that takes X:UU to (coprod X unit) ? 
> 

We call `option_functor` the functor given by binary coproduct with a
terminal object, see UniMath.CategoryTheory.limits.bincoproducts.

I don't remember seeing the function X \mapsto coprod X unit implemented.

**Comment by DanGrayson** [comment]
I can't find one.
