### ISSUE TITLE
bicategories copy as belonging to "system"

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#485]
Hi @mvr I have a problem making UniMath because the bicategories folder has read/write permissions that don't allow me to write to it except as a root.

**Comment by DanGrayson** [comment]
That's not a problem here on my computer.  Perhaps git doesn't even record permissions.  Use
a command like ` chmod u+w bicategories ` to fix it.  Use a command like `find CategoryTheory -not -perm -u+w -ls` to list all files under CategoryTheory that are not writable.

**Comment by mvr** [comment]
I lost the copy of UniMath I was working on, but re-cloning it I don't seem to have this problem...

**Comment by DanGrayson** [comment]
Is this issue still a problem, @vladimirias ?

**Comment by vladimirias** [comment]
I guess not. They have not been updated recently so it is hard to know.

**Comment by DanGrayson** [comment]
Well, let me if the problem recurs.

Closing the issue ...
