### ISSUE TITLE
Unicode notations

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#486]
I suggest that always when a unicode notation is introduced there is a comment saying how it should be written in the Agda mode. Maybe those who have introduced such notations can go through them and add such comments and also add this rule to README.

**Comment by DanGrayson** [comment]
#624 does much of this.

**Comment by benediktahrens** [comment]
I suggest adding a sentence to this extent to the style guide, and then close this issue.

**Comment by DanGrayson** [comment]
Will do.
