### ISSUE TITLE
direction of = in slicecategory

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#495]
How difficult would it be to change the direction of equality in the definition of a morphism h from f to g in slicecategory from the current h ;; g = f to f = h ;; g?

There are some reasons to consider the latter to be more natural.

**Comment by benediktahrens** [comment]
Slice categories are not used in any other file, neither in UniMath/UniMath nor in UniMath/TypeTheory. 
So it should be a minor change, and not difficult at all.

**Comment by benediktahrens** [comment]
resolved in #497
