### ISSUE TITLE
Own package for complexes?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#520]
I would like to discuss two suggestions concerning @tpannila 's work:

1. Would it make sense to create an own package for that material? The CT package is getting very big and long to compile.
2. Could the file CohomologyComplex.v be split into several files? We sometimes get Travis timeouts due to 10 minutes without output during the compilation of that file. A hacky alternative to that would be to insert a few commands in that file that produce output, such as a `Check` command.

**Comment by tpannila** [comment]
If I add `Unset Kernel Term Sharing.` to CohomologyComplex.v,  before the imports, line 14,
compilation time on my system goes from 4m24.307s to 2m54.998s. 
I can create a new package, HomologicalAlgebra, in my next PR.

**Comment by benediktahrens** [comment]
Both your suggestions sound excellent to me!

**Comment by benediktahrens** [comment]
done
