### ISSUE TITLE
total2_paths in CategoryTheory

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#524]
should have a different name e.g. total2_over_UU_paths and be in Foundations.

**Comment by benediktahrens** [comment]
@DanGrayson : is this reasonable to do?

**Comment by DanGrayson** [comment]
I'll do it.  He's referring to the entire file total2_paths.v, and it might be a good time to reduce duplication.

**Comment by benediktahrens** [comment]
There is no such file in CT, closing.
