### ISSUE TITLE
time 8.5 versus 8.6

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#531]
See https://github.com/UniMath/UniMath/issues/383#issuecomment-269926485

**Comment by mortberg** [comment]
I'm also curious about this, I saw that other people got significant speedups, see for instance https://sympa.inria.fr/sympa/arc/coq-club/2016-12/msg00092.html.

**Comment by DanGrayson** [comment]
Okay: 2217 seconds with 8.6 and 2213 seconds with 8.5, for the entire build.  For the file CohomologyComplex.v, 220 seconds with 8.6 and 264 seconds with 8.5.

**Comment by mortberg** [comment]
Ok, thanks! Is this on your laptop?

**Comment by DanGrayson** [comment]
Yes, that's on my Macbook Pro, in a Virtualbox virtual machine, running Ubuntu 16.04.
