### ISSUE TITLE
revisit some proofs in CategoryTheory

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#543]
Some proofs in CT were written by people who clearly did not know their stuff (me). Consequently, these proofs are long, roundabout, cumbersome. Somebody should write better proofs. Specifically, I am having in mind:

- Precomposition with an essentially surjective functor is essentially surjective (https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/precomp_ess_surj.v). Here it should be possible to get rid of the hypothesis of full faithfulness.
- Precomposition with a fully faithful functor is fully faithful (https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/precomp_fully_faithful.v).
- A functor category is univalent if the target category is (https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/functor_categories.v). The equivalence should probably be constructed as a composition of several equivalences, instead of via the grad theorem.

The current proofs are good in the sense that they survived upgrades of Coq without any significant changes. It is my hope that this property would be maintained.

**Comment by arnoudvanderleer** [comment]
@benediktahrens What is the status of this issue?
Are you sure that precomposition is essentially surjective if the functor is not fully faithful?
