### ISSUE TITLE
Local type-in-type

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#554]
After discussions with some of the Coq developers last week I learned that there is now support for local type-in-type in Coq. This means that type-in-type can be enabled for parts of a proof script and the universe checks will be disabled for definitions in this part. Printing assumptions for definitions defined in this part will then show that they have been compiled with this option, just like for axioms. 

Is this something we would like to use for UniMath? As far as I understand we use type-in-type because we don't have resizing rules or is there some other reason?

Something we have to take into account if we are going to switch off type-in-type is that compilation might take longer. Many other large developments reported serious speed-ups with 8.6, but not UniMath. As far as I understand this was mainly due to optimizations in the universe constraint checker which didn't affect UniMath at all as we are using type-in-type.

I should also add that there is no Coq command to easily enable this yet, but there seems to be a way to activate it locally in Module. So if we want to we can start experimenting with this feature in UniMath and give feedback to the Coq devs before they have completely integrated it.

**Comment by vladimirias** [comment]
I don’t think we should try anything like that unless we very clearly understand what this “local type-in-type” does.

Anders, can we start a conversation about it with the interested Coq developers? My first question is: does local type-in-type mean that the internal representation of terms can now have sub-terms assigned universe levels that are different from the ones that would follow from universe-level calculation rules?

**Comment by DanGrayson** [comment]
Anders, how do we find the new local type-in-type facility?  I've checked the CHANGES file in v8.6 and trunk with no luck.

**Comment by mortberg** [comment]
I don't know why it is not advertised anywhere, but you can try it out by making two files:
```
(* Foo.v *)
Definition foo (T : Type) : Type := T.
```
and 
```
(* Bar.v *)
Definition bar (T : Type) := T.
```

Next you compile Foo without type in type and Bar with:

> coqc Foo.v
> coqc -type-in-type Bar.v

Then you make a file Baz.v containing:
```
Require Import Foo.
Require Import Bar.

Print foo.
Print bar.

Print Assumptions foo.
Print Assumptions bar.

Definition moo (T : Type) := bar (foo T).
Print Assumptions moo.

Definition id (T : Type) (x : T) : T := x.

Definition oops := id _ id.
```

The last definition fails if you don't have type-in-type when loading this in emacs, with it it works.

**Comment by mortberg** [comment]
@ppedrot told me that you can do this more locally than on file by file basis as well, but I can't remember how. Maybe he can tell us. 

It would be nice if there were some vernacular commands for this.

**Comment by mortberg** [comment]
This was discussed in more detail here: https://coq.inria.fr/bugs/show_bug.cgi?id=5295

**Comment by ppedrot** [comment]
When I said on a file by file basis, I meant that you could use the `-type-in-type` flag on specific files you get to choose, while Coq lets you require them even if you're not currently using the flag.

From what I understand from your comments, you only use that rule for the resizing axioms. If so and If I were you, I'd simply put all the definitions that require this flag in one file at the very root of the development hierarchy, and special-case the compilation of that file in the Makefile by adding the `-type-in-type` flag to the command compiling it.

As for @vladimirias fears, this is no magic. The `-type-in-type` flag simply prevents Coq from checking that the constraints are correct. If you start mixing `-type-in-type` with a safe hierarchy, you should be aware that this can result in random anomalies if ever reducing terms leads to ill-typed expressions during conversion. To be safe, you must meta-theoretically ensure that this is not going to happen. A simple restriction that works is to only define collapsed inductive or record types and their recursors, which is typically what it needed for resizing. I've had a look at a resizing rule based on primitive records, and I convinced myself that this was safe. This was along the lines of:
```
(** Use -type-in-type for this file *)
Set Primitive Projections.
Record Resize@{i} (A : hProp@{i}) : Type₀ := { resize : A }.
(** Now resize : i ⊧ forall (A : hProp@{i}), Resize@{i} -> A *)
```

**Comment by DanGrayson** [comment]
Closing this issue, since it is covered by #648
