### ISSUE TITLE
Print Assumptions

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#563]
The "Print Assumptions" command is now useless for us, since Coq 8.6, but they seem to be resisting restoring the former behavior, see https://coq.inria.fr/bugs/show_bug.cgi?id=5295 .  Any suggestions?

**Comment by DanGrayson** [comment]
We may want to pursue this suggestion: "Since 8.6, it is indeed possible to use it only for one file that can be required in other safe modules, allowing for a well-delimited use of the flag."

It might be interesting to isolate our universe violations in separate files!

**Comment by vladimirias** [comment]
> On Jan 30, 2017, at 9:13 AM, Daniel R. Grayson <notifications@github.com> wrote:
> 
> We may want to pursue this suggestion: "Since 8.6, it is indeed possible to use it only for one file that can be required in other safe modules, allowing for a well-delimited use of the flag."
> 
> It might be interesting to isolate our universe violations in separate files!
> 
> —
> 
I wrote to Anders on a related subject (see below), but did not receive a reply:


Begin forwarded message:

> From: Vladimir Voevodsky <vladimir@ias.edu>
> Subject: Re: [UniMath/UniMath] Local type-in-type (#554)
> Date: January 24, 2017 at 5:53:55 PM EST
> To: UniMath/UniMath <reply@reply.github.com>
> Cc: "Prof. Vladimir Voevodsky" <vladimir@ias.edu>, UniMath/UniMath <UniMath@noreply.github.com>, Subscribed <subscribed@noreply.github.com>
> 
> I don’t think we should try anything like that unless we very clearly understand what this “local type-in-type” does.
> 
> Anders, can we start a conversation about it with the interested Coq developers? My first question is: does local type-in-type mean that the internal representation of terms can now have sub-terms assigned universe levels that are different from the ones that would follow from universe-level calculation rules?
> 
> 
> 
>

**Comment by mortberg** [comment]
Sorry, I've been very occupied and traveling a lot so I didn't have time to respond yet... Anyway this seems to be exactly what I was suggesting in https://github.com/UniMath/UniMath/issues/554. If type-in-type can be used more locally for a single file/Module in 8.6 and then hopefully for single Definitions in 8.7 I think it would be a good idea to start trying to have a more well-delimited use of the flag. But like Vladimir said in the other thread we should first understand how this works and as I said this will probably make UniMath compile slower as Coq will have to do more work.

**Comment by DanGrayson** [comment]
Now is our chance to understand how it works, by asking questions on the Coq bug thread that I linked to.  So let's pursue that now.

**Comment by vladimirias** [comment]
The “slower” issue may be not so important as we may have the “working mode” when we use the flag locally in the code but run the compiler with the type-in-type so that it does not check anything and the “finalized” mode when we don’t use type-in-type at the  compiler level. One can then use the finalized mode rarely only to check the consistency now and then.

However, it is essential to understand exactly what this local flag makes compiler/interpreter to do before we start applying it at the level of the whole library.

**Comment by vladimirias** [comment]
How Print Assumptions works?

**Comment by DanGrayson** [comment]
At the linked-to bug report thread I conjectured exactly how it works now, and my conjecture was accepted.  It was this: "Is that how type-in-type works now?  Modules export symbolic universe names and a list of constraints?  And the unsafe ones simply fail to export some needed constraints?"

**Comment by DanGrayson** [comment]
Actually, my conjecture was accepted with a modification: modules don't export universe constraints; definitions do.

**Comment by DanGrayson** [comment]
Here's a work-around: those of us who want to print assumptions can simply build with coq 8.5 instead of 8.6.  I'll do so, and that way we'll make sure our code works with both versions until 8.7 comes along.

So, since we have a work-around, I'll close this issue.
