### ISSUE TITLE
ElementsOp (and probably Elements?)

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#586]
@mweav: In the definition of the identity morphism, the equality from the axioms of presheaves is first inversed and then eqtohomot applied to it.
In the definition of the composition of morphisms the eqtohomot is first applied to the equality from the axioms of presheaves and then the resulting equality is inversed. 

It should be the same in both cases.

**Comment by DanGrayson** [comment]
resolved by #590, closing
