### ISSUE TITLE
equivalences.v

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#588]
In this file there are many definitions and results about adjunctions. They should be moved into a file called "adjunctions.v"

I could not find there a construction of an equivalence (which is defined as an adjoint equivalence) from two functors and two natural isomorphisms with identities (a "sloppy equivalence"). Is it somewhere else? If not, then both the definition of sloppy equivalences and the construction of an adjoint equivalence from a sloppy equivalence should be added.

**Comment by benediktahrens** [comment]
On 02/21/2017 01:03 PM, Vladimir Voevodsky wrote:
> In this file there are many definitions and results about
> adjunctions. They should be moved into a file called "adjunctions.v"
> 
> I could not find there a construction of an equivalence (which is
> defined as an adjoint equivalence) from two functors and two natural
> isomorphisms with identities (a "sloppy equivalence"). Is it
> somewhere else? If not, then both the definition of sloppy
> equivalences and the construction of an adjoint equivalence from a
> sloppy equivalence should be added.

Related issue:

There are a few more constructions on equivalences here:

https://github.com/UniMath/TypeTheory/blob/master/TypeTheory/Auxiliary/Auxiliary.v

(but the adjointification you mention is not there).

They should be upstreamed to UniMath/UniMath.

**Comment by benediktahrens** [comment]
Solved in #619 .
