### ISSUE TITLE
Classifying issues?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#597]
We have a long list of issues, and those issues are of various different kinds: some of them are about policy (e.g., #395), others are more concretely about specific problems in the code (e.g., #543) or about more general changes to the code (e.g., #583 ). Some are about technical enhancement of our setup ( #191, #192 ). 
I sometimes find myself with a few minutes available to do some work, and then I am interested in finding the second kind of issue. Others might be interested in quickly finding other kind of issues.
Could we classify our issues according to a set of criteria (maybe implemented via the labelling mechanism Github provides), so that they are more than just a list?

I suggest the following labels, to be refined and extended in discussion:
- requires a change to existing code
- requires new code
- policy
- package-specific issue (??)

For instance, one could have a label for every package, so that people can find issues related to packages they care about.

A few more points/questions:
- An issue can have several labels.
- Whether a label applies can change over time (e.g., an issue can be about policy and require change to the code when it is opened, and the second label can be removed when the code has been changed).
- Should there be a suitable label for every issue?

**Comment by DanGrayson** [comment]
Also, some issues are about long term projects underway.

For the type of issue that is ready to do some work on and get done, the type you would like to locate, I suggest calling it "just do".  That means we've discussed it, and we know what to do, and it's achievable.  Perhaps another one called "project".

Let's try to have not very many different labels.

**Comment by DanGrayson** [comment]
Re: "package-specific issue"

Should we have one label for each package?

**Comment by benediktahrens** [comment]
Done
