### ISSUE TITLE
eta expansion for pairs

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#605]
Hi,

I have a simple question. Is eta expansion for pairs available in UniMath ? If not, please tell me why.

Thanks

**Comment by benediktahrens** [comment]
On 02/23/2017 04:16 PM, Anthony Bordg wrote:
> Hi,
> 
> I have a simple question. Is eta expansion for pairs available in
> UniMath ? If not, please tell me why.

Please have this discussion on

univalent-mathematics@googlegroups.com

instead.
