### ISSUE TITLE
parenthesis and spaces

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#61]
I recalled the reason why I prefer to insert spaces around parenthesis as well as around all other strings: 
when I want to replace throughout the text "i" with "n" (or some other similar replacement) as the name used for a variable of type nat, it is very easy to do when all uses of "i" as a complete name are surrounded by spaces and very inconvenient to do otherwise. This does not disallow using ((( and ))) but does exclude (i and i).

**Comment by DanGrayson** [comment]
This doesn't seem to be an issue that we need to address, so I'm closing the issue.
