### ISSUE TITLE
Properties of the inverse structure of an abelian group

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#615]
Hi,

I'm not sure my message fits the "Issues" corner, but since it is not of general interest I don't think it fits the Google group.
Given an abelian group G, the morphism grinv G : G -> G should be a morphism of monoids, ie there should exist an inhabitant of the type ismonoidfun (grinv G). I did not find something like this in the library, am I missing something ?
Of course one can apply dirprodpair and it's easy to give a term of (grinv G 0) = 0, but I don't clearly see how to give a term of grinv G (x + y) = grinv G x + grinv G y, even if it's not difficult to find a term of 
grinv G x + grinv G y + x + y = 0.
Any suggestion ?
Thanks

**Comment by DanGrayson** [comment]
An issue here is intended to be a bug report, a planning discussion, or a feature request, so I'll close it.  But my advice is to first write out a proof in mathematical prose, and then enter it step by step into Coq.
