### ISSUE TITLE
coprod unicode: ⨿ or ∐

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#618]
It turns out I introduced the wrong notation for coprod.  The one called coproduct by unicode itself and typable with \coprod in agda is ∐, but the one I introduced is ⨿, which cannot be typed by agda.

Should be fixed.

**Comment by DanGrayson** [comment]
Actually, it can be typed in agda, by selection from a menu containing all of these:
```
\union	      ∪ ⋃ ∨ ⋁ ⋎ ⨈ ⊔ ⨆ ⋓ ∐ ⨿ ⊽ ⊻ ⊍ ⨃ ⊎ ⨄ ⊌ ∑ ⅀
```

**Comment by DanGrayson** [comment]
I now think we should reserve this big ∐ symbol for an indexed coproduct, as in `∐ i:I, X i` and continue using ⨿ for the binary coproduct.  Closing.

**Comment by vladimirias** [comment]
I think you can replace the selection from a menu by adding the sequential number of the symbol in the menu to the name as in \union3. However in my experiment it did not work with two digit number as required here.
