### ISSUE TITLE
Redefine now

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#621]
As pointed out in https://github.com/UniMath/UniMath/issues/609 the Coq version of the `now` tactic has various issues. It's doing a bit too much and it's using `case` which is not allowed in UniMath. I think it is nice to have a tactical like now for solving trivial goals generated by a tactic so I think we should have our own version of `now`.

**Comment by DanGrayson** [comment]
Here's the 8.6 source code for it, from Coq's file Tactics.v : 

```
Ltac easy :=
  let rec use_hyp H :=
    match type of H with
    | _ /\ _ => exact H || destruct_hyp H
    | _ => try solve [inversion H]
    end
  with do_intro := let H := fresh in intro H; use_hyp H
  with destruct_hyp H := case H; clear H; do_intro; do_intro in
  let rec use_hyps :=
    match goal with
    | H : _ /\ _ |- _  => exact H || (destruct_hyp H; use_hyps)
    | H : _ |- _ => solve [inversion H]
    | _ => idtac
    end in
  let do_atom :=
    solve [ trivial with eq_true | reflexivity | symmetry; trivial | contradiction ] in
  let rec do_ccl :=
    try do_atom;
    repeat (do_intro; try do_atom);
    solve [ split; do_ccl ] in
  solve [ do_atom | use_hyps; do_ccl ] ||
  fail "Cannot solve this goal".

Tactic Notation "now" tactic(t) := t; easy.
```

**Comment by DanGrayson** [comment]
I'll do this one.

**Comment by mortberg** [comment]
I discussed this with some Coq experts here and apparently the code for `now` above is very slow (probably because it is doing too complicated things). So exchanging it for something very simple should hopefully improve the compilation time of UniMath. 

I thinkt he SSReflect tactic `done` is a good place to start when designing our own `UniMath_easy` tactic:
```
Ltac done :=
  trivial; hnf; intros; solve
   [ do ![solve [trivial | apply: sym_equal; trivial]
         | discriminate | contradiction | split]
   | case not_locked_false_eq_true; assumption
   | match goal with H : ¬ _ |- _ ⇒ solve [case H; trivial] end ].
```

**Comment by benediktahrens** [comment]
On 03/02/2017 02:59 PM, Anders Mörtberg wrote:
> I discussed this with some Coq experts here and apparently the code for `now` above is very slow (probably because it is doing too complicated things). So exchanging it for something very simple should hopefully improve the compilation time of UniMath. 
> 
> I thinkt he SSReflect tactic `done` is a good place to start when designing our own `UniMath_easy` tactic:
> ```
> Ltac done :=
>   trivial; hnf; intros; solve
>    [ do ![solve [trivial | apply: sym_equal; trivial]
>          | discriminate | contradiction | split]
>    | case not_locked_false_eq_true; assumption
>    | match goal with H : ¬ _ |- _ ⇒ solve [case H; trivial] end ].
> ```
> 

You still have not made a good case for the need of such a tactic.

**Comment by mortberg** [comment]
I thought the conclusion of https://github.com/UniMath/UniMath/issues/609 was that it's nice to have a tactic that solves trivial subgoals (and displays nicely in red :)), but that the Coq `now` tactic was doing too much and hence led to difficulty to debug. Hence that we should redefine it. 

The reason I really want such a tactic is that I don't want to write trivial things making my proofs long and my fingers tired. For example I don't want to write `tac; apply idpath` all the time, it's much easier to write (and to read) `now tac`. The same goes for other simple things like symmetry, assumption (preferably this should only work when there is only one thing of the correct type in the context), etc. This way our formal proofs will look a little closer to normal proofs because we don't have to write trivial things.

**Comment by mortberg** [comment]
Note that `now` is currently used 1662 times in UniMath (I think Catherine and I are the main culprits). Changing all of these by hand would be a pain, redefining `now` so that it solves all (or most of these) would be a lot easier.

**Comment by benediktahrens** [comment]
On 03/02/2017 03:08 PM, Anders Mörtberg wrote:
> I thought the conclusion of
> https://github.com/UniMath/UniMath/issues/609 was that it's nice to
> have a tactic that solves trivial subgoals (and displays nicely in
> red :)), but that the Coq `now` tactic was doing too much and hence
> led to difficulty to debug. Hence that we should redefine it.
> 
> The reason I really want such a tactic is that I don't want to write
> trivial things making my proofs long and my fingers tired. For
> example I don't want to write `tac; apply idpath` all the time, it's
> much easier to write (and to read) `now tac`. The same goes for other
> simple things like symmetry, assumption (preferably this should only
> work when there is only one thing of the correct type in the
> context), etc. This way our formal proofs will look a little closer
> to normal proofs because we don't have to write trivial things.
> 

I thought that we had concluded that it was a bad idea to not put into
the proof code the information about which hypothesis proves the goal.

Contributors come and go, and we have to make sure that people who are
not the original authors can fix proofs when they break.
This gets more difficult the more info you omit from the proof script.

**Comment by mortberg** [comment]
Ok, so `assumption` should not be part of the tactic. But there are a lot of other trivial things that `now` should do.

**Comment by DanGrayson** [comment]
Hmm?  I would not agree that `assumption` should not be part of it.

**Comment by benediktahrens** [comment]
On 03/02/2017 03:18 PM, Anders Mörtberg wrote:
> Ok, so `assumption` should not be part of the tactic. But there are a
> lot of other trivial things that `now` should do.

Like what?

Could you give a complete specification?

**Comment by DanGrayson** [comment]
One specification for making a new "now" is to remove the "case" and all components from the existing tactic that don't break any of our code.

**Comment by mortberg** [comment]
The point of this thread is to have a discussion of what the complete specification of such a tactic should be. Things I want to be solved are:

- reflexivity
- symmetry then trivial
- split if the goals is a product and recursively solve the subgoals if they are trivial
- check if there is a proof of false in the context
- assumptions if there is only one solution

I can probably think of more things, but the easiest would probably be to experiment to write such a tactic and once we have something simple which solves all the 1662 cases currently in UniMath we can write down the specification. Ideally the tactic is going to be so simple that it's definition is its specification (which is almost the case for the `done` tactic above).

**Comment by vladimirias** [comment]
> On Mar 2, 2017, at 9:16 AM, Benedikt Ahrens <notifications@github.com> wrote:
> 
> Contributors come and go, and we have to make sure that people who are
> not the original authors can fix proofs when they break.
> This gets more difficult the more info you omit from the proof script.
> 

I think that this is a very important point. Any progress in this direction is worth the trouble.

**Comment by DanGrayson** [comment]
Re: "This gets more difficult the more info you omit from the proof script."

Well, we're not going to start writing each proof out as a single term with no holes and no implicit arguments.  It's always possible to back up to the earlier version to run Coq and see all the details of the previously found proof, so the information is never lost.  I often have to do that.
