### ISSUE TITLE
Remove two lines from .dir_locals

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#627]
Could we please remove these lines from .dir_locals.el:
```
	     (modify-syntax-entry ?' "w")
	     (modify-syntax-entry ?_ "w")
```

I very often want to erase an identifier to `_` but with these commands emacs erases the whole identifier when I press CTRL+BACKSPC and this is annoying me a lot. If someone likes this behavior they can just put these lines in their .emacs.

**Comment by DanGrayson** [comment]
No, the underscore is part of the identifier, and that syntax entry makes regular expressions include `\b` work properly.  If someone doesn't like this behavior, they can cancel it out by putting the appropriate lines in their .emacs file.

**Comment by mortberg** [comment]
How can I do that? The .dir_locals overwrite what ever modify-syntax-entry command I put in my .emacs?

**Comment by DanGrayson** [comment]
There are various syntax tables, and if you just try to change a syntax entry in your .emacs file, you'll change the wrong syntax table.

I tried this:
```
(add-hook 'coq-mode-hook 
	  (function 
	   (lambda()
	     (modify-syntax-entry ?' ".") 
	     (modify-syntax-entry ?_ "_"))))
```
which modifies the right syntax table, but it turns out the setting of the file-local variables by `.dir-locals.el` is done after the running of the functions in `coq-mode-hook`, so what I just tried didn't work.

So, I just add a new hook variable whose functions are run after the code in .dir-locals.el is run.  Hmm.

**Comment by DanGrayson** [comment]
I'll figure it out ...

**Comment by DanGrayson** [comment]
A related problem is that the file `TAGS` does not use the syntax table called `coq-mode-syntax-table`.

**Comment by mortberg** [comment]
Ok, for now I use a modified version of .dir_locals where I comment out these two lines and add some other things. This works pretty well, but I always have to be careful never to commit my changes. Another option would be that I never load .dir_locals and configure everything myself.

Regardless of what I do I would really prefer if the .dir_locals was as minimal as possible. We can then have a document in the wiki that explains various things people might want to put in their .emacs, the two lines I want to remove here fits into that category. I think this would be much better as everyone should be free to configure their emacs the way they want.

**Comment by DanGrayson** [comment]
Yes, everyone should feel free to configure their emacs the way they want, but for the most naive users it is best if they don't have to put anything into their .emacs file.  Also, the advantage of our current approach is that it doesn't interfere with emacs coq settings that users might have for coq developments outside of UniMath.  If it did, that would annoy them.

**Comment by benediktahrens** [comment]
What is the status of this issue, @mortberg @DanGrayson ? Can we close it?

**Comment by mortberg** [comment]
I don't think Dan ever found a solution to this?

I still think that what we have in .dir_locals should be minimal. This kind of changes is annoying to an experienced user who wants emacs to behave differently and an inexperienced user won't notice this at all.

**Comment by benediktahrens** [comment]
@mortberg : solution to what? It is hence not just a matter of removing two lines? Then the title of the issue should be changed.

**Comment by mortberg** [comment]
I suggest we remove the two lines, but Dan wanted to find a solution where I could modify my .emacs file so that .dir_locals wouldn't override them...

**Comment by benediktahrens** [comment]
@mortberg : would you still like to have those two lines removed from `.dir_locals.el`? 
@DanGrayson : any comments?

**Comment by DanGrayson** [comment]
I think emacs needs to have the correct syntax table for the coq language, and since the underscore can be part of an identifier name, emacs needs to be informed, always, even on Anders' computer.  Anders, if you want to delete up to an underscore, you can just use `zap-to-char` :

```elisp
M-z runs the command zap-to-char (found in global-map), which is an interactive
compiled Lisp function in ‘simple.el’.

It is bound to M-z.

(zap-to-char ARG CHAR)

Kill up to and including ARGth occurrence of CHAR.
Case is ignored if ‘case-fold-search’ is non-nil in the current buffer.
Goes backward if ARG is negative; error if CHAR not found.
```

**Comment by arnoudvanderleer** [comment]
@mortberg Does this resolve the issue?

**Comment by mortberg** [comment]
> @mortberg Does this resolve the issue?

I don't remember, but I also don't really care about this issue any more so feel free to close it.
