### ISSUE TITLE
A planning discussion for polynomials

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#629]
I need the basics on polynomials. If anyone agrees, I plan to write something on this.
Let me know if you have any suggestion.

**Comment by benediktahrens** [comment]
On 02/28/2017 08:27 PM, Anthony Bordg wrote:
> I need the basics on polynomials. If anyone agrees, I plan to write something on this.
> Let me know if you have any suggestion.  

Such general discussion is best done on the mailing list, not on the
issue tracker. You might find people there who can point you to previous
formalizations etc.

Thanks,
b
