### ISSUE TITLE
make PAdics compile

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#63]
PAdics does not compile at the moment. It should be adapted to compile with latest Coq/UniMath.
Some beautification would also be beneficial.

Anyone starting to work on this should comment in this issue, as to avoid duplication of efforts.

**Comment by rmatthes** [comment]
I have started work on this task on the basis of Benedikt's branch. My first commit makes the file `lemmas.v` compile again. This happens in my branch "repairpadics", see
[https://github.com/rmatthes/UniMath/tree/repairpadics](https://github.com/rmatthes/UniMath/tree/repairpadics)

**Comment by DanGrayson** [comment]
I've assigned Ralph to the issue (that's a good way for others to learn at a glance that someone is already working on an issue).

**Comment by rmatthes** [comment]
Four of the five vernacular files are fine now (in my branch mentioned above).
     spec    proof comments
      185      782       21 UniMath/PAdics/lemmas.v
      177     1774       37 UniMath/PAdics/fps.v
       58      457       12 UniMath/PAdics/frac.v
      219     2049       60 UniMath/PAdics/z_mod_p.v
      639     5062      130 total
But there are real problems with padics.v. Proof checking with `Defined.` takes ages, and at some point, also a `change`, so the development comes to  a halt.
Suggestions welcome.

**Comment by benediktahrens** [comment]
On 10/29/2017 09:36 PM, Ralph Matthes wrote:
> Four of the five vernacular files are fine now (in my branch mentioned above).
>      spec    proof comments
>       185      782       21 UniMath/PAdics/lemmas.v
>       177     1774       37 UniMath/PAdics/fps.v
>        58      457       12 UniMath/PAdics/frac.v
>       219     2049       60 UniMath/PAdics/z_mod_p.v
>       639     5062      130 total
> But there are real problems with padics.v. Proof checking with `Defined.` takes ages, and at some point, also a `change`, so the development comes to  a halt.
> Suggestions welcome.
> 


Here, the following works:

(* Coq hangs on this command on Oct. 29, 2017: apply idpath. Solution: *)
(*      apply hzplusladd.
      Fail (apply hzmultlmul).
      Fail (apply hzmultrmul).
*)
      exact (idpath _ ).

But that does not solve the problem with `Defined.`

**Comment by benediktahrens** [comment]
On 10/29/2017 09:36 PM, Ralph Matthes wrote:
> Four of the five vernacular files are fine now (in my branch mentioned above).
>      spec    proof comments
>       185      782       21 UniMath/PAdics/lemmas.v
>       177     1774       37 UniMath/PAdics/fps.v
>        58      457       12 UniMath/PAdics/frac.v
>       219     2049       60 UniMath/PAdics/z_mod_p.v
>       639     5062      130 total
> But there are real problems with padics.v. Proof checking with `Defined.` takes ages, and at some point, also a `change`, so the development comes to  a halt.
> Suggestions welcome.
> 

A very brief glimpse does not give me any idea of why type-checking
takes so much time in some `Defined.`.

Can you describe the significant changes to the proofs that you have
done so far?
(Looking at the diff is unhelpful, since too much has changed.)

**Comment by benediktahrens** [comment]
On 10/29/2017 09:36 PM, Ralph Matthes wrote:
> Four of the five vernacular files are fine now (in my branch mentioned above).
>      spec    proof comments
>       185      782       21 UniMath/PAdics/lemmas.v
>       177     1774       37 UniMath/PAdics/fps.v
>        58      457       12 UniMath/PAdics/frac.v
>       219     2049       60 UniMath/PAdics/z_mod_p.v
>       639     5062      130 total
> But there are real problems with padics.v. Proof checking with `Defined.` takes ages, and at some point, also a `change`, so the development comes to  a halt.
> Suggestions welcome.
> 

In the spirit of 'solution-oriented' work (as opposed to
'problem-oriented'), I suggest chopping the proofs whose `Defined.`
takes too long into smaller proofs by formulating intermediate lemmas.

**Comment by rmatthes** [comment]
There are no significant changes. I reformatted the proofs in bullet style and for human parsing of the proof scripts. And I solved all the problems that occurred due to the evolution of the UniMath library, in particular negated relations and elimination of propositional truncation.

Nothing remarkable in the compilation of the four files for which the process went well.

**Comment by rmatthes** [comment]
The current state of the development: 7 lemmas in padics.v take excessively long to verify the obtained proof, i.e., to execute `Defined.` Among them Lemma quotientprecarryplus, which is the only code given in the MSCS 2015 paper by Pelayo, Voevodsky and Warren on that formalization.

**Comment by rmatthes** [comment]
All is fine now.

**Comment by rmatthes** [comment]
This issue should be closed.
