### ISSUE TITLE
subsets

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#630]
It seems we have a choice: to represent a subset of a set X as a predicate X -> hProp or as an inclusion Y --> X, for some set Y.

Which would be best?

**Comment by mortberg** [comment]
The Coq standard library uses predicates (into Prop): 

https://coq.inria.fr/library/Coq.Sets.Ensembles.html

But maybe inclusions would be easier to work with, it is definitely worth a try.

I have some code in one of my branches that I will soon make a PR from where I prove that the set of sieves on an element of a category is a bounded lattice. I defined sieves as maps into hProp and to define union and intersection I use `hdisj` and `hconj`. I hence had to prove thing like `hconj P Q = hconj Q P` which all were easy using univalence for propositions. So the predicate approach will look similar to what I'm already doing and I think it will make heavy use of funext and propositional extensionality (univalence for propositions). Note that the ensembles library in Coq uses an extensionality axiom which I think is implied by funext and propext, but I didn't check this closely.

**Comment by benediktahrens** [comment]
On 02/28/2017 08:53 PM, Daniel R. Grayson wrote:
> It seems we have choice: to represent a subset of a set X as a
> predicate X -> hProp or as an inclusion Y --> X, for some set Y.
> 
> Which would be best?

Does the latter require working with quotients?

**Comment by DanGrayson** [comment]
No, equality of subsets amounts to equality of pairs (Y, i), where i : Y --> X is an inclusion.  Intersection will be pullback.  Commutativity of intersection will follow from univalence.  Etc.
