### ISSUE TITLE
Why is there both is_iso and is_isomorphism?

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#641]
While browsing through precategories.v I stumbled across:

https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/precategories.v#L318

Is there a good reason for this or can it be eliminated? It looks to me like it's just the same as is_iso (same implicit arguments and all).

**Comment by DanGrayson** [comment]
Sure looks like a synonym, not needed.

**Comment by benediktahrens** [comment]
On 03/06/2017 06:52 PM, Anders Mörtberg wrote:
> While browsing through precategories.v I stumbled across:
> 
> https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/precategories.v#L318
>
>  Is there a good reason for this or can it be eliminated? It looks to
> me like it's just the same as is_iso (same implicit arguments and
> all).
> 

It can be eliminated.

**Comment by mortberg** [comment]
Ok, this should be very easy to fix and I can do it. But maybe some of the PRs will be affected (I know my latest one on moving Elements/ElementsOp will), so it might be better to wait until some of them have been merged before doing this change.

**Comment by mortberg** [comment]
Resolved by https://github.com/UniMath/UniMath/pull/644
