### ISSUE TITLE
switch total2 to Record to make "apply" totally cool

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#643]
Here is the documentation of the tactic "apply":

"apply term

This tactic applies to any goal. The argument term is a term well-formed in the local context. The
tactic apply tries to match the current goal against the conclusion of the type of term. If it succeeds,
then the tactic returns as many subgoals as the number of non-dependent premises of the type of term.
If the conclusion of the type of term does not match the goal and the conclusion is an inductive type
isomorphic to a tuple type, then each component of the tuple is recursively matched to the goal in the
left-to-right order."

The last sentence would be totally cool for us if only total2 were isomorphic to a tuple type, because then, if we needed some sequence of projections `pr1` and `pr2` applied to a term `w` to fulfill the current goal, then we could just use `apply w` instead of something like `apply (pr1 (pr2 (pr1 (pr2 (pr1 w)))))`.  It would be if only `total2` were defined as a record instead of as an inductive type.  I have tested it, and that change would work for us.  All we have to do is to change the definition of `total2` and to delete the definitions of `pr1` and of `pr2`.

We have to switch `total2` to be a record soon, anyway, once we get primitive projections working, so we can have the benefit of eta-reduction for pairs.  I propose we do it now, so we can get the benefit of this cool feature of `apply`.

Yes, I know Foundations is "locked", but this is such a simple change, which we have to implement eventually anyway, that it should be possible to consider it and approve it in one minute.

**Comment by benediktahrens** [comment]
On 03/09/2017 05:40 PM, Daniel R. Grayson wrote:
> Here is the documentation of the tactic "apply":
> 
> "apply term
> 
> This tactic applies to any goal. The argument term is a term
> well-formed in the local context. The tactic apply tries to match the
> current goal against the conclusion of the type of term. If it
> succeeds, then the tactic returns as many subgoals as the number of
> non-dependent premises of the type of term. If the conclusion of the
> type of term does not match the goal and the conclusion is an
> inductive type isomorphic to a tuple type, then each component of the
> tuple is recursively matched to the goal in the left-to-right
> order."
> 
> The last sentence would be totally cool for us if only total2 were
> isomorphic to a tuple type, because then, if we needed some sequence
> of projections `pr1` and `pr2` applied to a term `w` to fulfill the
> current goal, then we could just use `apply w` instead of something
> like `apply (pr1 (pr2 (pr1 (pr2 (pr1 w)))))`.  It would be if only
> `total2` were defined as a record instead of as an inductive type.  I
> have tested it, and that change would work for us.  All we have to do
> is to change the definition of `total2` and to delete the definitions
> of `pr1` and of `pr2`.
> 
> We have to switch `total2` to be a record soon, anyway, once we get
> primitive projections working, so we can have the benefit of
> eta-reduction for pairs.  I propose we do it now, so we can get the
> benefit of this cool feature of `apply`.
> 
> Yes, I know Foundations is "locked", but this is such a simple
> change, which we have to implement eventually anyway, that it should
> be possible to consider it and approve it in one minute.
> 

I agree it sounds cool!

Do I understand correctly that it is as if all the projections were
declared coercions?

Do I understand correctly that it is mandatory to delete the projections
pr1 and pr2?
How does one then select the correct component if several components
have the right type?

**Comment by DanGrayson** [comment]
No, projections are not coercions.  It's just a feature of the "apply" tactic, and it goes in
left to right order.

Here is a totally cool tactic for finding the projection in advance of need:
```
Ltac Find t T x := assert (t : T); [ apply x | ].
```
For example, if `w` is of type `isWellOrder R`, you can find the component of `w`
of type `istotal R` and assign it to `tot` with this line:
```
    Find tot (istotal R) w.
```

**Comment by DanGrayson** [comment]
PS: The reason we would delete the definitions of `pr1` and `pr2` is that for records, the projection maps get defined automatically.

**Comment by DanGrayson** [comment]
PS: The tactic goes left to right and find the first one.  I assume it is depth first, too.

**Comment by mortberg** [comment]
This sounds very useful indeed! I wonder if some of the problem we've had with `apply` are partly due to `total2` not being a `Record`?

**Comment by DanGrayson** [comment]
That's worth an experiment ... I'm assigning myself to this issue to remind myself to do it.

**Comment by mortberg** [comment]
Great, please let us know the conclusion of your experiment. It would be nice if we don't have to use so many different tactics to apply lemmas (right now there is `apply`, `simple apply`, `refine`, `simple refine` and `exact`...). This is very confusing to me, so I wonder how it is for someone who's new to Coq and wants to learn to use UniMath...

**Comment by DanGrayson** [comment]
It turns out I already did the experiment: https://github.com/UniMath/UniMath/pull/624/commits/f0f87aa4f453dba65e46d4c54d6ef0f5fe00a6f1#diff-08bfdf23d5799b6834cc7e0a41fed918

Conclusion -- the bugs in "apply" are present even if total2 is a record.

**Comment by DanGrayson** [comment]
Here is a diff showing how proofs in a file I'm working on would look better if I could make use of the cool feature:
```
diff --git a/UniMath/Combinatorics/WellOrderedSets.v b/UniMath/Combinatorics/WellOrderedSets.v
index d477263..8fa01f8 100644
--- a/UniMath/Combinatorics/WellOrderedSets.v
+++ b/UniMath/Combinatorics/WellOrderedSets.v
@@ -11,6 +11,8 @@ Local Open Scope subtype.
 Local Open Scope logic.
 Local Open Scope set.
 
+Ltac Find t T x := assert (t : T); [ apply x | ].
+
 Definition WellOrdering (S:hSet) : hSet := ∑ (R : hrel_set S), isWellOrder R.
 
 Definition SubsetWithWellOrdering_set (X:hSet) : hSet
@@ -55,17 +57,19 @@ Proof.
   - change (R=R'). apply funextfun; intro s; apply funextfun; intro s'.
     apply (invmap (weqlogeq _ _)). split.
     { exact (le s s'). }
-    apply (squash_to_prop (pr21 w s s')). (* istotal *)
+    Find tot (istotal R) w.
+    apply (squash_to_prop (tot s s')).
     { apply propproperty. }
     intro r. induction r as [a|b].
     { intros _. exact a. }
     { intros c. assert (p : s = s').
-      { apply (pr211 w' s s').  (* isantisymm *)
+      { apply w'.               (* isantisymm *)
         - exact c.
         - apply le. exact b. }
       induction p.
-      apply (pr2111 w).         (* isrefl *) }
-  - apply propproperty.
+      apply w.                  (* isrefl *)
+    }
+  - apply proofirrelevance. apply propproperty.
 Defined.
 
 Definition wosub_le (X:hSet) : hrel (SubsetWithWellOrdering X)
@@ -83,7 +87,7 @@ Proof.
   + intros x xinS. exact xinS.
   + split.
     * intros s s' le. induction s, s'; exact le.
-    * intros s s' le. exact (pr2 s').
+    * intros s s' le. apply s'.
 Defined.
 
 Lemma wosub_le_eq (X:hSet) (S:hsubtype X) (R R':WellOrdering (carrier_set S)) :
@@ -138,18 +142,20 @@ Definition wosub_fidelity {X:hSet} {S T:SubsetWithWellOrdering X} (le : S ≼ T)
       (s s' : S) : s ≤ s' <-> wosub_inc le s ≤ wosub_inc le s'.
 Proof.
   split.
-  { intro l. exact (pr12 le s s' l). }
-  { intro l. apply (squash_to_prop (pr2122 S s s')).
-    { apply propproperty. }
+  { intro l. now apply le. }
+  { intro l.
+    Find tot (istotal (rel S)) (pr2 S).
+    apply (squash_to_prop (tot s s') (propproperty _)).
     change ((s ≤ s') ⨿ (s' ≤ s) → s ≤ s').
     intro c. induction c as [c|c].
     - exact c.
     - induction le as [le b].  induction b as [b b'].
       assert (k := b s' s c).
-      assert (k' := pr21122 T _ _ l k); clear k. simpl in k'.
+      Find anti (isantisymm (rel T)) (pr2 T).
+      assert (k' := anti _ _ l k); clear k. simpl in k'.
       assert (p : s = s').
       { apply subtypeEquality_prop. exact (maponpaths pr1 k'). }
-      induction p. exact (pr211122 S _). }
+      induction p. apply (pr2 S). }
 Defined.
 
 Local Lemma h1 {X} {S:SubsetWithWellOrdering X} {s t u:S} : s = t -> t ≤ u -> s ≤ u.
```

**Comment by DanGrayson** [comment]
I just did a time trial, and switching total2 to a record speeds up the build by 15%, which is a strong argument in favor of switching.

**Comment by DanGrayson** [comment]
A comment about using records in Preamble.v says this:

```
However, the use of "Inductive" allows us to obtain proof terms that are expressed in terms of
the eliminator total2_rect that, unlike the "match" construct that would appear in the proof terms
if we used "Record", has a known interpretation in the framework of the univalent model.
```

It's correct that "match" terms are introduced by induction on pairs if we use records, but it would be a Coq bug if they didn't behave the same way the eliminator does, so we can take them as covered by the univalent model.  Anyway, to get eta-reduction for pairs, we will need to switch, and we want that, too, and soon.

**Comment by vladimirias** [comment]
It’s too bad that we can not switch on the way. Is there any serious reason for it? Maybe we can ask for such a feature - inductive to record, one way flag?

**Comment by vladimirias** [comment]
Alternatively, can we write a total2_rec for the total2 defined as a record and then a tactic that will total2_rec and replace induction for total2? It shoud be possible to see the eta for pairs in the computational behavior of total2_rec, otherwise what does it mean?

**Comment by DanGrayson** [comment]
Re: "It’s too bad that we can not switch on the way. Is there any serious reason for it?"

Sorry, I don't understand the question.

**Comment by DanGrayson** [comment]
Re: "can we write a total2_rec for the total2 defined as a record"

We don't have to, it is provided:
```
Record total2 (T : Type) (P : T → Type) : Type := tpair { pr1 : T;  pr2 : P pr1 }


total2_rect = 
λ (T : Type) (P : T → Type) (P0 : (∑ y, P y) → Type)
(f : ∏ (pr1 : T) (pr2 : P pr1), P0 (pr1,, pr2)) (t : ∑ y, P y),
match t as t0 return (P0 t0) with
| x,, x0 => f x x0
end
     : ∏ (T : Type) (P : T → Type) (P0 : (∑ y, P y) → Type),
       (∏ (pr1 : T) (pr2 : P pr1), P0 (pr1,, pr2)) → ∏ t : ∑ y, P y, P0 t
```

**Comment by vladimirias** [comment]
Something like setting type-in-type on the way - once set it can not be undone but some code (e.g. Basics or a larger part of foundations or the future EssentialFoundations) can use total2 as an inductive type and then we switch to using it as a record. The behavior of the latter is a superset of the behavior of the former, so it should be possible. 

BTW the same applies to the eta for products.

**Comment by DanGrayson** [comment]
I don't see how you can have two definitions of total2 existing side by side, since they won't be judgmentally equal.

**Comment by vladimirias** [comment]
… another important BTW - Basics do not require type-in-type and maybe we can make it clear even with the existing Coq. 

It is not about “local type-in-type”, which is something that I don’t understand, but about turning the type-in-type at some point from which it is always on, about a “one-way” switching from using the universe system to not using it.

**Comment by vladimirias** [comment]
It must be a new option in Coq or a patch introducing “Switch to a Record” command for Coq. It can not be done with the current system.

**Comment by DanGrayson** [comment]
Perhaps what you really want is for "induction" to use the eliminator instead of "match", even when operating on records.  That might be a feature they'd be willing to add, eventually.  I see no way to have records and inductive types behave interchangeably, or to switch back and forth between them, since they would't be recognizable as being equal.

**Comment by mortberg** [comment]
That is very interesting! Any idea why?

I suspect that using Record's all over the place would make things a lot
faster. At the moment we need to use very long chains of projections to get
fields out of our structures, every time we write a long chain of pr1 and
pr2 Coq needs to infer a lot of things (the type and the family on the type
is implicit). If we instead would use Record's the projections would just
be a functions getting the field for us directly. Maybe this is one reason
why we are experiencing very slow proofs in for example SubstitutionSystems
and HomologicalAlgebra where we are using fairly complicated nested
structures.

--
Anders

**Comment by DanGrayson** [comment]
I have no idea why it's faster.  Maybe all the match terms instead of all the eliminators?

**Comment by vladimirias** [comment]
Actually using long records is slow. We build our structures as fairly balanced binary trees and working with them is faster.

Long sequences of pr’s should not appear anywhere. When one need to access a field inside a complex definition one has to write an access function. Such functions are fast.

**Comment by mortberg** [comment]
Good point. I actually try to always define constructor and accessor
functions when defining structures, so if I use the accessor functions
everywhere this should not be a problem for efficiency.


I was thinking of long chains of pr1 and pr2 because of Dan's first message
in this thread: "we could just use apply w instead of something like apply
(pr1 (pr2 (pr1 (pr2 (pr1 w)))))"

I think this kind of long chains of pr1/pr2 should produce very slow code
the more complicated the structures get.

--
Anders

**Comment by DanGrayson** [comment]
Re: "Long sequences of pr’s should not appear anywhere. When one need to access a field inside a complex definition one has to write an access function. Such functions are fast"

That comparison may not hold when we turn on primitive projections, which is supposed speed up the projections by not storing the types in them.

**Comment by DanGrayson** [comment]
Re: "I think this kind of long chains of pr1/pr2 should produce very slow code
the more complicated the structures get."

Not if the long chains are inside proofs that rarely get unfolded for comparison with others.

**Comment by mortberg** [comment]
Re: "Not if the long chains are inside proofs that rarely get unfolded for comparison with others."

Sure, but that's very difficult to control. As far as I understand it unification unfolds things using various heuristics that are badly understood and not documented. I think the only way to be sure that something is not going to be unfolded is to end it with `Qed`.

**Comment by mortberg** [comment]
Back to my original question: I think it would be very interesting to understand why changing total2 to a Record gives a 15% speedup. That's a massive speedup for a very tiny change and it is quite mysterious to me why this is the case.

**Comment by DanGrayson** [comment]
I just checked the travis run time in the pull request for the homological algebra package: 38 minutes with records, 46 minutes without.  The limit is 49 minutes, occasionally exceeded.

**Comment by benediktahrens** [comment]
On 03/10/2017 04:00 PM, Daniel R. Grayson wrote:
> I just checked the travis run time in the pull request for the
> homological algebra package: 38 minutes with records, 46 minutes
> without.  The limit is 49 minutes, occasionally exceeded.


Travis runtime depends on a lot of things. In particular, the machine it
runs on might not always be the same?

**Comment by DanGrayson** [comment]
Yes, travis times vary.  Here are some more: 46:13 44:07 41:29 39:56 40:00 44:26 42:53 40:46

**Comment by vladimirias** [comment]
Is the ‘Unset kernel term sharing” used in the Homological algebra package? If not, it can make the compilation time considerably shorter. 

PS If it is used and it is still 46 minutes it means that this package requires more work.

**Comment by DanGrayson** [comment]
Re: " If it is used and it is still 46 minutes it means that this package requires more work."

Yes, see the timing results in #625

**Comment by JasonGross** [comment]
> It's correct that "match" terms are introduced by induction on pairs if we use records

Does this change if you `Set NonRecursive Elimination Schemes ` before you define the record?  I thought that behavior was what happened whenever the eliminator isn't defined, and Coq doesn't define eliminators for records by default, but can be told to.

**Comment by DanGrayson** [comment]
No, that doesn't help, I tried it.
