### ISSUE TITLE
finite types

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#657]
MLTT79 includes finite types, but we limit ourselves to empty, unit, and bool.

Finite types are probably easy to justify mathematically.

So why not replace the following definitions, used in CategoryTheory, by the corresponding
inductive definitions?:

```
Definition two := stn 2.

Definition two_rec {A : UU} (a b : A) : stn 2 -> A.
Proof.
  intros A a b.
  induction 1 as [n p].
  induction n as [_|n _]; [apply a|].
  induction n as [_|n _]; [apply b|].
  induction (nopathsfalsetotrue p).
Defined.

Definition two_rec_dep (P : two -> UU):
  P (● 0) -> P (● 1) -> ∏ n, P n.
Proof.
  intros P a b n.
  induction n as [n p].
  induction n as [_|n _]. eapply stn_predicate. apply a.
  induction n as [_|n _]. eapply stn_predicate. apply b.
  induction (nopathsfalsetotrue p).
Defined.

Definition three := stn 3.

Definition three_rec {A : UU} (a b c : A) : stn 3 -> A.
Proof.
  intros A a b c.
  induction 1 as [n p].
  induction n as [_|n _]; [apply a|].
  induction n as [_|n _]; [apply b|].
  induction n as [_|n _]; [apply c|].
  induction (nopathsfalsetotrue p).
Defined.

Definition three_rec_dep (P : three -> UU):
  P (● 0) -> P (● 1) -> P (● 2) -> ∏ n, P n.
Proof.
  intros P a b c n.
  induction n as [n p].
  induction n as [_|n _]. eapply stn_predicate. apply a.
  induction n as [_|n _]. eapply stn_predicate. apply b.
  induction n as [_|n _]. eapply stn_predicate. apply c.
  induction (nopathsfalsetotrue p).
Defined.
```

**Comment by DanGrayson** [comment]
@benediktahrens , this suggestion concerns your code.

**Comment by benediktahrens** [comment]
A year or so ago I made an effort to get rid of the inductive types with two and three elements. 

I seem to remember that @peterlefanulumsdaine provided a general induction principle for `stn n` at around the same time.
Maybe all of the above code should be replaced by appealing to that induction principle?

I don't have a strong opinion on this question, and I would be happy either way.

**Comment by vladimirias** [comment]
This is an unnecessary complication  of the core type theory of the UniMath. I would understand, if you suggested to replace empty, unit and bool by stn 0, stn 1 and stn 2 to avoid having two standard types with 0,1 and 2 elements, but not the other way around.

**Comment by benediktahrens** [comment]
Can we close this issue? It seems like we do not want to introduce inductive finite types.
