### ISSUE TITLE
latex files in UniMath

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#663]
If I provide a latex file carefully exposing the proof of a theorem as formalized in a *.v file, I think it would make sense to include it in the same directory, and to add makefile that will convert it to a pdf file.

What do other people think?

I would particularly like to do something like this for Zorn's lemma and Zermelo's Well Ordering theorem, when I get them done.   Thus there would be two files, `WellOrderedSets.v` and `WellOrderedSets.tex` in `UniMath/Combinatorics`.

**Comment by mortberg** [comment]
Or you put the pdf on the arxiv and add a link? I'm not a huge fan of having tex files in the folders with Coq files.

**Comment by mortberg** [comment]
By the way, if your proofs of these results are particularly interesting or elegant then you can turn your tex file into a short paper and submit it as a Proof Pearl to the Journal of Automated Reasoning:

http://www.springer.com/computer/theoretical+computer+science/journal/10817

**Comment by benediktahrens** [comment]
I would prefer having non-Coq files outside the UniMath subdir, e.g., in /doc.

**Comment by DanGrayson** [comment]
What are the reasons for your preferences?

One reason it would be good to have the two files in the same place is that they are closely related, and when one changes, the other should change.  The eye can't help but notice both files are there.  Even better would be a single file from which the proof and the document can both be abstracted.

About 10 years ago I wrote up the 1904 proof of Zermelo that I am formalizing, here: http://www.math.illinois.edu/~dan/ShortProofs/WellOrdering.pdf

With details illuminated by the formalization, it could be much improved.

**Comment by benediktahrens** [comment]
I suggest that you put your documentation as comment in the Coq files instead. This makes it much more likely that the documentation is updated to stay in sync with the actual file contents than when you have two separate files.

**Comment by DanGrayson** [comment]
Okay, closing.
