### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#686]
I suggest that we rename all the .v files in UniMath/UniMath into starting with a small letter and subdirectories into starting with a capital. This way files, as seen in the GitHub, will be ordered alphabetically.

The same probably applies to UniMath/TypeTheory.

**Comment by DanGrayson** [comment]
They seem already to be alphabetically ordered:

<img width="455" alt="screen shot 2017-04-17 at 4 01 36 pm" src="https://cloud.githubusercontent.com/assets/700228/25104758/3407f568-2387-11e7-89dd-aa6e5275533a.png">

**Comment by benediktahrens** [comment]
@DanGrayson : your screenshot only shows capitalized file names, hence the order there is alphabetical.
What @vladimirias means can be seen, e.g., in CategoryTheory, where we have file names starting with a capital letter, and others starting with tiny letters.

**Comment by DanGrayson** [comment]
Oh, thanks, now I understand.  But since github always puts directories first, then files, there is no reason for us to treat directories and files differently.  So let's instead capitalize the files.

**Comment by siddharthist** [comment]
I'm working on this.

**Comment by DanGrayson** [comment]
Which way will you do it?

**Comment by siddharthist** [comment]
@DanGrayson I've begun with your suggestion, making everything totally consistent: `CapitalizedAtWordBoundaries`.

**Comment by arnoudvanderleer** [comment]
I believe in the meantime the standard has shifted to "all files and directories start with an uppercase letter", but that has the same effect. Can we close this issue then?
