### ISSUE TITLE
Reuse of \times symbol in a different scope

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#694]
The symbol \times is already used in the scope type_scope, I want to reuse it for the binary product of precategories as in the following sample of code,

Definition binprod_precategory (C D : precategory) : precategory.
Proof.
  refine (product_precategory bool _).
  intro x. induction x.
  - exact C.
  - exact D.
Defined.

Notation "C × D" := (binprod_precategory C D) (at level 38) : cat.

But I got an error "Error: Notation _ × _ is already defined at level 75 with arguments
at next level, at level 75 while it is now required to be at level 38
with arguments at next level, at next level."

I don't understand why I'm not able to reuse this symbol in the scope cat. Any suggestion ?

**Comment by DanGrayson** [comment]
Delete the level specification.

**Comment by AnthonyBordg** [comment]
In this case I got the error "Error: A left-recursive notation must have an explicit level", also I want to avoid the use of parentheses in the sequence F: C \times C \--> C  (for F a functor from C x C to C).

**Comment by DanGrayson** [comment]
Did it look like this?:
```
Notation "C × D" := (binprod_precategory C D) : cat.
```

**Comment by AnthonyBordg** [comment]
yes

**Comment by DanGrayson** [comment]
It works at my end.  Maybe push your code somewhere so we can see it.

**Comment by AnthonyBordg** [comment]
Dan, two comments before I eventually push the code in my branch :

- It seems strange that one is able to reuse a same symbol in two (or more) different scopes, but the second time one is not able to declare a precedence level !
- Without a declared precedence level, if now you want to declare a variable F of type C \times C \--> C then you will need parentheses, namely "Variable F : (C \times C) \--> C",  otherwise you will get an error later. This is not a big problem, but I would have been happy without these parentheses.

**Comment by DanGrayson** [comment]
The limitation on changing the precedence level must be due to the design of the parser, which probably doesn't know which scope is in effect, because some context is yet to be determined at a later stage.  For example, "type_scope" is not active unless a type is to occur in that position, and that sort of information a parser can't know.

But, no, the operator will have the same precedence level as before.  It will not lack a precedence level.

**Comment by AnthonyBordg** [comment]
Ok I see, thanks for your explainations. You may want to have a look at the code in my branch "Feynman" [https://github.com/AnthonyBordg/UniMath/blob/Feynman/UniMath/CategoryTheory/Feynman_categories.v](url) (the names of some notations need to be improved F being a variable).

**Comment by DanGrayson** [comment]
I checked out your branch, and for me, the following definition of your did work:
```
Notation "C × D" := (binprod_precat C D) : cat.
```

**Comment by vladimirias** [comment]
Why is binprod of precat in cat?

**Comment by DanGrayson** [comment]
The word to the right of ":" in a notation declaration is a scope name, not a type.

**Comment by benediktahrens** [comment]
This issue seems to be resolved, closing.
