### ISSUE TITLE
LaTeX for ≣

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#696]
File WellOrderedSets introduces a unicode symbol for which I have been unable to find a suitable LaTeX symbol:
```
UniMath/Combinatorics/WellOrderedSets.v:Notation "S ≣ T" := (wosub_equal S T) (at level 70) : wosubset.
```
I'd be grateful for any help finding a suitable LaTeX symbol to map this one to.
Alternatively, change this unicode symbol into one for which there is a LaTeX symbol.

**Comment by DanGrayson** [comment]
Maybe we could make one by putting two equal signs together.
