### ISSUE TITLE
"isconnectedunit" wrong name

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#698]
This property in the statement of this lemma is not connectedness, so the name of the lemma should be changed:
```
Lemma isconnectedunit : ∏ x x' : unit, x = x'.
```
Perhaps refer to this definition and terminology instead:
```
Definition isProofIrrelevant (X:UU) := ∏ x y:X, x = y.
```

**Comment by benediktahrens** [comment]
Solved by #799
