### ISSUE TITLE
identity_rect on trunk

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#70]
The recursion principle for "identity" on the trunk has been weakened so that even our simplest
proofs by induction no longer work:

```
$ /usr/local/bin/coqtop
Welcome to Coq 8.4pl4 (June 2014)

Coq < Check identity_rect.
identity_rect
     : forall (A : Type) (a : A) (P : forall a0 : A, identity a a0 -> Type),
       P a (identity_refl a) -> forall (y : A) (i : identity a y), P y i


$ ~/src/HoTT/UniMath/sub/coq/bin/coqtop
Welcome to Coq 8.5beta1 (January 2015)

Coq < Check identity_rect.
identity_rect
     : forall (A : Type) (a : A) (P : A -> Type),
       P a -> forall y : A, identity a y -> P y
```

**Comment by JasonGross** [comment]
This sounds like a bug that should be reported on the coq bug tracker.  (I do not think it was intentional.)

**Comment by DanGrayson** [comment]
I sent Hugo an email already, so I'll wait to see what he says.

**Comment by DanGrayson** [comment]
It seems that adding the command line option -indices-matter is a work-around.

**Comment by benediktahrens** [comment]
This issue is obsolete, closing.
