### ISSUE TITLE
Find a way to avoid need for `pr1`s when working with functors into sets

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#700]
Given a functor `F : A -> Set`, we would like to make `b : F Y` and `# F f b for f:X-->Y` well typed, see 
https://github.com/UniMath/UniMath/pull/607 and specifically https://github.com/UniMath/UniMath/pull/607#issuecomment-282178402 .

**Comment by mortberg** [comment]
This seems related to the problem that when we have `F : [C,D]` we always have to extract the functor manually using `pr1`.

**Comment by benediktahrens** [comment]
We understand why this is not (easily) possible, closing this issue.
