### ISSUE TITLE
Move category of sets into subdir "categories"

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#705]
That subdir is where all the instances of categories are stored.

**Comment by mortberg** [comment]
Would you move `category_hset_structures.v` as well? Or maybe we should merge it with `category_hset.v`? The only drawback of that is that `category_hset.v` would get a lot more dependencies, but maybe it is not too bad to have all the results on HSET in one place.

**Comment by benediktahrens** [comment]
On 05/07/2017 10:00 PM, Anders Mörtberg wrote:
> Would you move `category_hset_structures.v` as well? Or maybe we
> should merge it with `category_hset.v`? The only drawback of that is
> that `category_hset.v` would get a lot more dependencies, but maybe
> it is not too bad to have all the results on HSET in one place.
> 

Yes, that file should be moved as well.

I am not so sure about merging the two files on HSET. I cannot point to
a specific problem, but it makes me a bit wary when something as simple
as the definition of the catgory of sets depends formally on all those
(co)limits.

I actually think that we should go in the opposite direction, and
disentangle some of the dependencies we have. But that needs to be
discussed in a separate issue.

**Comment by mortberg** [comment]
One argument for merging the files is that it is easier for new users to find related things. If someone is looking for a particular result about HSET it is easier to find it if there is only one file about HSET. However one practical argument I see against merging is that if we do a change to the limits part of the file on HSET that will require the compilation also of the files that only rely on the basic stuff. I checked and 10 of the 28 files that rely on `category_hset.v` only require `category_hset.v` and not the one on limits.

**Comment by benediktahrens** [comment]
Done
