### ISSUE TITLE
A "calculus" for (commutative) diagrams

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#706]
I want to point out the following difficulty. 
When one does informal mathematics in a categorical way, one can rely on the resources of the diagrammatic thinking (the eye is a wonderful gift of natural evolution!) to quickly and easily evaluate that the commutativity of a diagram holds.  As you know Coq has no eye, hence you need to laboriously give him a witness that a diagram commutes. Even if it is trivial informally, the point is that it can be really tedious formally (in particular you need to take care of the associativity of multiple compositions).  To exemplify this difficulty, you can have a look at my last proofs in my file "Feynman_categories" [https://github.com/AnthonyBordg/UniMath/blob/Feynman/UniMath/CategoryTheory/Feynman_categories.v](url) . These proofs are really tedious despite the fact that I made them shorter by writing lemmas that rely themselves on previous preliminary lemmas.
So it seems an important point, at least for the file "category theory", to have definitions to rewrite in various ways commutative diagrams of different shapes involving isomorphisms.
In my file on Feynman categories (link above) I have started a section "commutative_diagrams" to provide tools to rewrite such commutative diagrams. So far, regarding the names, I use the following convention: it has two parts separated by "to", the first part indicates the shape of the diagram (a mere arrow, a triangle, a square, a pentagon, an hexagon etc...) as an input and the second part indicates the shape of the diagram as output, hence one can somehow guess the operation that is performed by the definition at hand. 
The point of this issue consists in discussing such definitions and their names. The names should be clear and coherent/homogeneous/systematic. Moreover, one probably needs two versions, one with "is_iso", the second with "iso". In such definitions there is also the possible use of parentheses in the input and output, knowing that the symbols used for composition are by default left-associative.

**Comment by benediktahrens** [comment]
Please use the mailing list for discussion - closing.
