### ISSUE TITLE
arrange for Travis to report run times

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#71]
... and record a few of them somewhere

**Comment by benediktahrens** [comment]
Travis runtimes are not deterministic, since they depend on the total workload of the host machine. 
The usefulness of recording and comparing runtimes is hence unclear.
Can we close this issue?

**Comment by DanGrayson** [comment]
CPU time shouldn't depend much on workload.

**Comment by benediktahrens** [comment]
I think the times are recorded, closing.
