### ISSUE TITLE
Ignoring warnings

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#713]
It was brought to my attention that we currently ignore all warnings when we compile UniMath. This seems a little dangerous as some warnings can be useful and point to things that should be changed as they might break in the future (an example of this was when we were introducing too many things in some places). In 8.6 there is now support for disabling specific warnings or even families of warnings (when a warning is printed it comes with its name and which family it belongs to), so we can probably come up with a more specific set of warnings that we want to ignore while keeping informative ones. 

Maybe @DanGrayson is up for experimenting with this as it involves modifying the Makefile?

**Comment by DanGrayson** [comment]
Good idea, I'll take a look.
