### ISSUE TITLE
Quick advertisement to prevent duplication of code on groupoid/subcat_of_isos/comma_cat 

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#718]
In my branch  [https://github.com/AnthonyBordg/UniMath/blob/Feynman/UniMath/CategoryTheory/Feynman_categories.v](url) it remains mainly to define the free monoidal cat then with the help of the preliminaries there the definition of Feynman categories should be a matter of a few lines.  
I will try to make a pull request as soon as possible, but I guess there is some long work involved for the free monoidal cat.
Thus, let me advertise that I have already defined the underlying groupoid of a category (ligne 1147), ie the subcategory of isos,  and I proved that it is a groupoid. I have also defined (the most general form of) comma categories (ligne 1198).
Hence if you need these notions in a near future, you can have a look.

**Comment by AnthonyBordg** [comment]
@DanGrayson , did you construct somewhere in your file 'Group' the (non abelian) group given by a set of generators and relations ?

**Comment by DanGrayson** [comment]
Yes, the function is `universalMarkedGroup`.  At the end of the file I apply it to
make the free group on a type and the free group on one generator.

But the construction uses a deprecated inductive definition, so I'm reworking it, using
the generalized associativity theorem, on my branch `free-monoids`.

**Comment by AnthonyBordg** [comment]
@DanGrayson Ok. I believe in order for me to define the free symmetric monoidal category on a category (on a groupoid in my case) I need to define the braid category, to define the latter I need to define Artin braid groups. There are two ways to define these groups, either as the fundamental groups of some spaces or  through a presentation by generators and relations. I don't think the first 'geometric' option would be allowed in UniMath since it requires higher inductive types (at least the 0-truncation), so it remains the second option.
Dan do you suggest to wait and  suggest that I do something else in the meantime ?
Maybe we can also ask @vladimirias  for his view.

**Comment by DanGrayson** [comment]
UniMath has 0-truncation, so that's not a problem.  But there still seems to be no way to construct the required space: the space of n-tuples of distinct points in the plane; but the notion of "distinct" pair of points is not one invariant under homotopy equivalence, so what do you do about that?

You could proceed by generators and relations.

**Comment by benediktahrens** [comment]
Please use the mailing list for discussion - closing.
