### ISSUE TITLE
(improved ?) readability of definitions

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#719]
When one does not need to encapsulate a definition in a 'Proof-Defined' block and uses directly  ':=' instead, then sometimes one skips the type information in the definition by writing something like 'Definition ident := body of the def'.

Should one write  systematically 'Definition ident : type := body of the def' to help the reader and increase the readability since in some cases it's not very straightforward to deduce the missing type information ?

**Comment by benediktahrens** [comment]
On 05/26/2017 05:01 PM, Anthony Bordg wrote:
> When one does not need to encapsulate a definition in a 'Proof-Defined'
> block and uses directly ':=' instead, then sometimes one skips the type
> information in the definition by writing something like 'Definition
> ident := body of the def'.
> 
> Should one write systematically 'Definition ident : type := body of the
> def' to help the reader and increase the readability since in some cases
> it's not very straightforward to deduce the missing type information ?

Yes, it is good practice to always specify the type.

**Comment by AnthonyBordg** [comment]
yes, I think so.

**Comment by mortberg** [comment]
Another reason to write the type explicitly is to make sure that types are put in the correct universe. I'm not sure what Coq's type inference will do if you don't give the type.

**Comment by DanGrayson** [comment]
Maybe you're thinking of the single case where one specifies `UU` as the type.  But actually, once we have type-in-type active for just one file, we'll have to use UU as a notation for Type, to make use of universe polymorphism.

**Comment by benediktahrens** [comment]
Resolved. Thanks for reporting. Closing.
