### ISSUE TITLE
check for unlisted proof files

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#723]
Proof files not listed in one of the files `UniMath/*/.package/files` will not be compiled by the `make` command, so our makefile should verify that there are none.

**Comment by benediktahrens** [comment]
I would like to have the fix amended such that it allows us to have untracked `*.v` files locally.
The check should only run on Travis.

**Comment by DanGrayson** [comment]
okay...

**Comment by DanGrayson** [comment]
Hmm, now I'm unsure about your request.  The default behavior should cater to the naive user, who should be warned, especially if they are preparing a pull request for us.  The first warning should not come from travis to us after they issue a pull request.

What if, instead, experienced users, like us, run
```sh
make -o enforce-listing-of-proof-files
```
?

**Comment by DanGrayson** [comment]
Another work-around is
```sh
make -k
```
, which allows further progress after an error.

**Comment by benediktahrens** [comment]
```
$ make -k install
```
does not work:
```
make: Target 'install' not remade because of errors.
```

**Comment by mortberg** [comment]
Maybe the best would be to emit a warning and not an error?

**Comment by DanGrayson** [comment]
Warnings will get buried in the rest of the build output and not seen by naive users.  And we want it to be an error so it fails when travis tries it.

**Comment by benediktahrens** [comment]
"We" want it to be an error on travis, not on "our" machines.

**Comment by mortberg** [comment]
I agree with @benediktahrens. I got annoyed today and just commented this test out from my Makefile in order for `make install` go through. If `make -k install` would work I would be happy with that as well.

**Comment by DanGrayson** [comment]
What if only *.v files committed to the repository must be listed in `.package/files`?

**Comment by benediktahrens** [comment]
On 06/07/2017 02:52 AM, Daniel R. Grayson wrote:
> What if only *.v files committed to the repository must be listed in
> |.package/files|?

That seems a very reasonable requirement!

**Comment by mortberg** [comment]
I agree, that seems like a reasonable compromise

**Comment by benediktahrens** [comment]
Resolved, closing.
