### ISSUE TITLE
topics

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#726]
I noticed that repositories can have "topic" tags, so I added some.  Let me know if there are any suggestions for additions, deletions, or amendments.

(See https://github.com/UniMath/UniMath .)

**Comment by AnthonyBordg** [comment]
@DanGrayson , good idea Dan. Is the order of appearance random ? Should the order reflect a general purpose ?

**Comment by DanGrayson** [comment]
I think the order is irrelevant.

**Comment by benediktahrens** [comment]
Resolved, closing.
