### ISSUE TITLE
is_univalent for precategories

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#742]
It is probably a little detail, but in the definition of `is_univalent` one uses an eta-expansion as follows

`Definition is_univalent (C : precategory) :=
  (∏ (a b : ob C), isweq (fun p : a = b => idtoiso p)) × (has_homsets C).`

,otherwise COQ would complain, not being able to infer the implicit arguments of idtoiso. But one could also write 

`Definition is_univalent_bis (C : precategory) :=
  (∏ (a b : ob C), isweq (idtoiso (a:=a) (b:=b))) × (has_homsets C).`

Is there any reason to prefer `is_univalent` to `is_univalent_bis` ?

**Comment by benediktahrens** [comment]
On 07/11/2017 01:19 PM, Anthony Bordg wrote:
> It is probably a little detail, but in the definition of |is_univalent|
> one uses an eta-expansion as follows
> 
> |Definition is_univalent (C : precategory) := (∏ (a b : ob C), isweq
> (fun p : a = b => idtoiso p)) × (has_homsets C).|
> 
> ,otherwise COQ would complain, not being able to infer the implicit
> arguments of idtoiso. But one could also write
> 
> |Definition is_univalent_bis (C : precategory) := (∏ (a b : ob C), isweq
> (idtoiso (a:=a) (b:=b))) × (has_homsets C).|
> 
> Is there any difference ? Is there any reason to prefer |is_univalent|
> to |is_univalent_bis| ?

Yes, the reason is given in the comment right above the definition.

**Comment by AnthonyBordg** [comment]
Benedikt, I saw this comment, but I don't know what I should exactly understand by 

> to force printing of object arguments

**Comment by benediktahrens** [comment]
You should understand by that that the eta expansion exhibits the object arguments `a` and `b` when Coq prints this. Without eta expansion, Coq woud only print 
```
isweq (idtoiso)
```

**Comment by benediktahrens** [comment]
Btw, you could simply test for yourself what would happen if you test the change you suggest.
