### ISSUE TITLE
2-categories

### ISSUE THREAD

**Issue by AnthonyBordg** [UniMath/UniMath#752]
There are at least two unfinished proofs in the bicategories file, [isaprop_is_bicategory] in bicategory.v and [Cat_is_lt2saturated] in Cat.v, both are inside commentaries though.
The first proof can be easily completed, for the second one I don't know.
What is the current status of the formalization of 2-categories ? Is the current formalization satisfactory, despite the fact that it seems unfinished ?

**Comment by benediktahrens** [comment]
The general consensus is that it would be better to define bi-categories analogously to categories, starting from a type of objects, a family of types of 1-morphisms, and a family of types of 2-morphisms. The reasoning is that then one can reuse some stuff one has already defined, e.g., the type `precategory_ob_mor`.
That approach allows for a better understanding of what properties are really needed for some structures (e.g., the definition of functor between bi-cats does not use the axioms of bi-cats).

This is the case for basically any concept in category theory, e.g., monoidal structure on a category: in formalization (in particular with propositions-as-types), it might be better to separate the three pieces - types, operations, and axioms - more than is usually done.

**Comment by AnthonyBordg** [comment]
@benediktahrens : Thanks. Do you want to open a new branch to start a new formalization of 2-categories ? If so, I will definitely contribute.

**Comment by benediktahrens** [comment]
Closing this issue - any further discussion should be held on the mailing list.
