### ISSUE TITLE
Update to Coq 8.7

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#767]
@DanGrayson : should this be part of your effort to isolate type-in-type usage, or should I file a PR for just the update (if that works smoothly - I have not tested yet).

**Comment by DanGrayson** [comment]
I tried, 8.7 beta 2, and it worked fine, and it would be a good idea to upgrade to 8.7.0 now, so we don't have to wait.

**Comment by benediktahrens** [comment]
On 10/18/2017 01:01 PM, Daniel R. Grayson wrote:
> I tried, 8.7 beta 2, and it worked fine, and it would be a good idea
> to upgrade to 8.7.0 now, so we don't have to wait.

I'll take care of this after upgrading ocaml...

**Comment by benediktahrens** [comment]
@DanGrayson : do you know by any chance if `Print Assumptions` works correctly in 8.7?

**Comment by DanGrayson** [comment]
`Print Assumptions` will "work" for us once we have only two lemmas compiled with type-in-type.  Those lemmas will appear as axioms.  When everything is compiled with type-in-type, then everything is an axiom, and that is the intended behavior.

**Comment by benediktahrens** [comment]
On 11/07/2017 10:37 PM, Daniel R. Grayson wrote:
> `Print Assumptions` will "work" for us once we have only two lemmas
> compiled with type-in-type.  Those lemmas will appear as axioms.
> When everything is compiled with type-in-type, then everything is an
> axiom, and that is the intended behavior.
> 

The intended behaviour is not the most useful behaviour for us :-(

**Comment by siddharthist** [comment]
Does Coq 8.7 obviate the need for resizing rules? It seems to have "cumulative inductive types", which I gather from slide 7 of [this presentation](https://lirias.kuleuven.be/bitstream/123456789/513812/3/PCuIC.pdf) is the rule
```
G |- T : Type{i}
------------------
G |- T : Type{i+1}
```
which at least seems to cover the case of `RR1`:
```
Resizing Rule RR1 (U1 U2 : Univ) (X : U1) (is : isaprop X) |- X : U2.
```

**Comment by DanGrayson** [comment]
No, the idea of resizing rules is to decrease the universe level, whereas the cumulativity rule for universes increases the universe level.

**Comment by siddharthist** [comment]
@DanGrayson Ah, I see. Thank you for clarifying!

**Comment by amintimany** [comment]
@siddharthist @DanGrayson The presentation linked above is an older version of the work. In the newer version (implemented in Coq) this rule ignores the sort of the inductive type (it happens to be sound to do so) and only considers indices (not parameters) and arguments of constructors for sub-typing analysis. This means that in certain cases it can also lower universe levels. The best example is the example of lists: ```list@{i} (A : Type@{k})``` is now definitionally equal to ```list@{j} (A : Type@{k})``` regardless of ```i```, ```j``` and ```k``` (so long as the two types are meaningful of course).

**Comment by DanGrayson** [comment]
Yes, thanks, that recent change to Coq will be extremely useful for us, as working to eliminate the wide use of type-in-type turned out to be too hard without it.

**Comment by siddharthist** [comment]
Another question: do recent versions of Coq (8.7, 8.6) compile UniMath without patches? I _think_ I just compiled the library successfully with 8.7. If this is the case, should we still ask people to build their own version of Coq (e.g. in INSTALL.md), or instead ask that they use a recent version (perhaps with the option to build the patched version)?

**Comment by benediktahrens** [comment]
On 12/05/2017 09:20 PM, Langston Barrett wrote:
> Another question: do recent versions of Coq (8.7, 8.6) compile
> UniMath without patches?

Yes, UniMath/UniMath does compile with unpatched 8.7.
Coq 8.6 is the one currently pulled in as a git submodule, so yes, 
UniMath also compiles with vanilla 8.6.

There is a problem compiling UniMath/TypeTheory with 8.7 
(https://github.com/UniMath/TypeTheory/issues/125). I have not looked at 
that problem yet.

> I _think_ I just compiled the library
> successfully with 8.7. If this is the case, should we still ask
> people to build their own version of Coq (e.g. in INSTALL.md), or
> instead ask that they use a recent version (perhaps with the option
> to build the patched version)?

It is possible to avoid building Coq when building UniMath, by setting a 
suitable option (see the Makefile), using instead a version of Coq (8.6, 
8.7) installed by different means.

For instance, on Windows OSs, it might be more feasible to install the 
binary version of Coq, and compile UniMath without compiling Coq.

**Comment by DanGrayson** [comment]
See also #785

**Comment by benediktahrens** [comment]
On 12/05/2017 09:46 PM, Daniel R. Grayson wrote:
> See also #785
> 

What exactly should we look at?

**Comment by siddharthist** [comment]
@benediktahrens Thanks for getting back to me so quickly. I guess my question is not about whether or not people have the _ability_ to use their own installations of Coq 8.6 and 8.7 (they do, that option is provided as an option to the Makefile), but whether that should be the _default_. It might reduce the maintenance burden on this project (we could remove the submodule and that part of the Makefile) just to ask people to have Coq already. The Coq project has plenty of documentation and support for installing it.

**Comment by palmskog** [comment]
@benediktahrens as established before, Coq 8.7.0 can't be compiled with the default OCaml (4.01.0) in Ubuntu Trusty used in Travis. My PR (#785) uses an alternative Ubuntu repo that installs OCaml 4.02.3, which enables using 8.7.0 in UniMath's Travis via the Git submodule. In lieu of a longer-term solution such as maintaining Docker images, this enables switching all Travis builds to 8.7.0.

**Comment by abooij** [comment]
@palmskog, actually I was just experimenting with docker images, see my [docker-based-ci](https://github.com/abooij/UniMath/tree/docker-based-ci) branch (only the latest commit is relevant, at the moment of writing). In that branch I use docker to run the "artful" ubuntu release, and install coq 8.6 that way (which shaves about a minute off of CI time). But we could definitely also use it to get a more recent version of ocaml easily, and then build whatever version of coq we want.

**Comment by DanGrayson** [comment]
#785 upgrades our travis script, using opam, to install a modern ocaml with which we can compile Coq 8.7.

**Comment by DanGrayson** [comment]
The current version is now 8.7.1, see https://coq.inria.fr/news/141.html

I'll submit a pull request, as the workshop should be over by now, or soon.
