### ISSUE TITLE
`make' should not fail with unlisted proof files

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#768]
I would like the Makefile to be changed such that 
```
$ make
```
compiles UniMath even though there are unlisted proof files in the directory.
Currently, not even
```
$ make -k
```
works.
The current behaviour will cause a huge headache during the UniMath school, in particular.

**Comment by benediktahrens** [comment]
Addendum: obviously, unlisted proof files should make the Travis test fail. But it shouldn't make it impossible for users to compile UniMath.

**Comment by DanGrayson** [comment]
will do

**Comment by DanGrayson** [comment]
I can't reproduce your problem.  I have a file `UniMath/foo.v` and `make` succeedss.

**Comment by benediktahrens** [comment]
On 10/18/2017 09:33 PM, Daniel R. Grayson wrote:
> I can't reproduce your problem.  I have a file `UniMath/foo.v` and `make` succeedss.
> 

What if you have a file `UniMath/CategoryTheory/foo.v`?

**Comment by DanGrayson** [comment]
Ah, now I get it:
```
make -j4
! ( git diff --stat master -- UniMath/Foundations | grep . )
error: *** file UniMath/CategoryTheory/foo.v not listed in appropriate file UniMath/*/.package/files
error: *** 1 unlisted proof files encountered
make: *** [Makefile:282: enforce-listing-of-proof-files] Error 1
```

I could fix this the same way I made the check for changes to foundations work -- by running it explicitly in the travis script.

We should also have a target `check-all`, which includes those two checks, so people can ensure that the travis run will succeed.

Another way would be perform this check just for unlisted files that are checked into git.  That might be better, because the ones checked in are the ones that will be seen by travis.  On the other hand, our software could be distributed by means other than git, to a system on which git doesn't even exist.

**Comment by benediktahrens** [comment]
On 10/18/2017 10:31 PM, Daniel R. Grayson wrote:
> Ah, now I get it:
> ```
> make -j4
> ! ( git diff --stat master -- UniMath/Foundations | grep . )
> error: *** file UniMath/CategoryTheory/foo.v not listed in appropriate file UniMath/*/.package/files
> error: *** 1 unlisted proof files encountered
> make: *** [Makefile:282: enforce-listing-of-proof-files] Error 1
> ```
> 
> I could fix this the same way I made the check for changes to foundations work -- by running it explicitly in the travis script.

That would be great!

> We should also have a target `check-all`, which includes those two checks, so people can ensure that the travis run will succeed.

That would be great, too!

> Another way would be perform this check just for unlisted files that are checked into git.  That might be better, because the ones checked in are the ones that will be seen by travis.  On the other hand, our software could be distributed by means other than git, to a system on which git doesn't even exist.

It is difficult to contribute to UniMath without using git. So maybe we
can require git on machines that are supposed to run those checks, since
the check is only useful if one wants to contribute to UniMath?

**Comment by DanGrayson** [comment]
Meanwhile, here is a good workaround:
```
make -o enforce-listing-of-proof-files
```

**Comment by benediktahrens** [comment]
This issue is solved, closing.
