### ISSUE TITLE
make sure Foundations looks a little better for the workshop in December

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#772]
check line length
  formatting style
  indentation
  notations
  bullets
  localize automatic introduction
  move or delete my decidable propostion stuff

**Comment by DanGrayson** [comment]
It's easy to use emacs regular expressions to convert lots of files simultaneously to better use of notations.  Should I do that outside of Foundations, or will there be too many conflicts?  I should be able to do it at least in Algebra, NumberSystems, MoreFoundations, Combinatorics.

**Comment by benediktahrens** [comment]
The only PR I am a bit worried about is Cathy's [1], but that is old and
its status unclear to me.

[1] seems to be at least partially superseded by a PR that was recently
merged, where Cathy gave two traditional definitions of Dedekind cuts.

[1] https://github.com/UniMath/UniMath/pull/536

**Comment by DanGrayson** [comment]
Well, I'll go ahead.  We can always figure that out later.

**Comment by DanGrayson** [comment]
Benedikt, do things look good enough now, in your opinion?

**Comment by benediktahrens** [comment]
On 10/26/2017 03:56 PM, Daniel R. Grayson wrote:
> Benedikt, do things look good enough now, in your opinion?
> 

If I say yes now, does that mean that I won't be able to suggest any
improvements before Dec 15?

**Comment by DanGrayson** [comment]
No, suggestions are always welcome.  Perhaps you close this issue now and reopen it at will when you find anything to suggest.

**Comment by benediktahrens** [comment]
Closing for the time being.
