### ISSUE TITLE
brew install camlp4 camlp5

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#79]
Paige has just compiled UniMath from scratch on MacOS 10.10, following the instructions in the README. 
She had to 
```bash
brew install ocaml camlp4 camlp5
```
rather than just
```bash
brew install ocaml 
```
Not having MacOS myself, I am reluctant to modify the installation instructions myself. Could you confirm and amend, if necessary?

**Comment by vladimirias** [comment]
I can partially confirm it. I have installed it on other machines and we did have to install camlp's. I don’t recall whether both 4 and 5 had to be installed.

It is a good idea to modify the instructions - I remember having a hard time trying to figure out what to do.

Vladimir.

**Comment by benediktahrens** [comment]
Actually, it should work with only camlp5 - the configure script asked for camlp4 as a fallback for camlp5. So it should say
```bash
brew install ocaml camlp5
```

**Comment by DanGrayson** [comment]
Yes, thanks, see https://github.com/UniMath/UniMath/pull/80
