### ISSUE TITLE
Rename gradth

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#792]
There is a very useful lemma called `gradth` in PartA:

https://github.com/UniMath/UniMath/blob/master/UniMath/Foundations/PartA.v#L1772

The name is not very good as it doesn't give any idea about what it actually proves. How about renaming it to `iso_to_weq`?

**Comment by rmatthes** [comment]
I thought this was rather an insider joke which therefore survived for so long. The instance for hSet used to be called `iso_set_isweq`, as seen [here](https://github.com/UniMath/UniMath/commit/e204c4).

**Comment by DanGrayson** [comment]
Good idea. Probably `iso_isweq` is a better name.

To maintain compatibility with publications, we should also have something like
```
Definition gradth := iso_isweq.
```
just afterward.

**Comment by siddharthist** [comment]
If you have [`ag`](https://github.com/ggreer/the_silver_searcher) installed, here's a little `bash` function to find-and-replace over a whole project:
```bash
sed_recurse() { ag -g '.*' -0 | xargs -0 sed -i "$1" }
```
You just feed it a `sed` regex like so: `sed_recurse 's/foo/bar/'`. Just make sure not to use it in the wrong directory 😄

**Comment by DanGrayson** [comment]
I prefer using this function in emacs, since it will run over just the relevant project files, and it will encounter the files in the logical order:
```
M-R runs the command tags-query-replace (found in global-map), which is an
interactive autoloaded compiled Lisp function in ‘etags.el’.

It is bound to M-R, <menu-bar> <edit> <replace> <tags-repl>.

(tags-query-replace FROM TO &optional DELIMITED FILE-LIST-FORM)

Do ‘query-replace-regexp’ of FROM with TO on all files listed in tags table.
Third arg DELIMITED (prefix arg) means replace only word-delimited matches.
If you exit (C-g, RET or q), you can resume the query replace
with the command M-,.
Fourth arg FILE-LIST-FORM non-nil means initialize the replacement loop.

If FILE-LIST-FORM is non-nil, it is a form to evaluate to
produce the list of files to search.

See also the documentation of the variable ‘tags-file-name’.
```

**Comment by siddharthist** [comment]
@DanGrayson That's a great trick! Emacs is a wonderful piece of software.
