### ISSUE TITLE
Reorder travis build jobs to get CI results faster

### ISSUE THREAD

**Issue by abooij** [UniMath/UniMath#795]
Currently, the biggest build job in Travis CI is to compile the `HomologicalAlgebra` package. It takes around 20 minutes. Luckily, packages are built in parallel. However, the total build time is still around an hour (give or take 30 minutes), because the `HomologicalAlgebra` build gets started very late in the process, and so much of the time is spent waiting for this one package to build.

If the `HomologicalAlgebra` package is built sooner, for example after `MoreFoundations KTheory`, this might reduce the total build time by up to 20 minutes, as the time spent compiling `HomologicalAlgebra` can now also be used to build other packages.

**Comment by DanGrayson** [comment]
Sounds like a good idea.

**Comment by benediktahrens** [comment]
Done
