### ISSUE TITLE
.dir-locals.el should set coq-prog-name only if BUILD_COQ is yes

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#810]
for a discussion, see #801

**Comment by DanGrayson** [comment]
Also, it should set -type-in-type for the file(s) that need it, i.e., for Resizing.v.  Otherwise we can't step through the file.

**Comment by benediktahrens** [comment]
@DanGrayson : I think you recently changed something that is related to this issue. Could you link to the change from here?

**Comment by DanGrayson** [comment]
Yes, see commit 62858926d4e34d0cf85297c7b04237d135a135c0

**Comment by peterlefanulumsdaine** [comment]
It seems like this issue can now be closed, fixed by 62858926d4e34d0cf85297c7b04237d135a135c0 merged in #1494?

**Comment by DanGrayson** [comment]
Yes, thanks!
