### ISSUE TITLE
Discrepancy between definitions of preorders and partial orders

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#843]
In Foundations/Sets, we have
```
Definition po (X : UU) : UU := ∑ R : hrel X, ispreorder R.
```
and
```
Definition PartialOrder (X : hSet) : UU := ∑ R : hrel X, isPartialOrder R.
```
Why is one defined for types, the other one for sets?

Relatedly, I would like to discourage
```
Definition Poset : UU := ∑ X, PartialOrder X.
```
and advertise the more verbose
```
Definition Poset : UU := ∑ X : hSet, PartialOrder X.
```
instead.

**Comment by abooij** [comment]
A partial order needs to be an hSet to ensure antisymmetry is a proposition. The concept of a non-hSet preorder makes sense, at least from a definition point of view. They were both introduced in 070aba4 in 2011.

**Comment by benediktahrens** [comment]
On 12/16/2017 01:40 PM, Auke Booij wrote:
> A partial order needs to be an hSet to ensure antisymmetry is a
> proposition. The concept of a non-hSet preorder makes sense, at least
> from a definition point of view. They were both introduced in 070aba4
> in 2011.
> 

Good point. But then the "isaset" condition should be a part of 
"isPartialOrder", shouldn't it?

**Comment by DanGrayson** [comment]
Re: " the "isaset" condition should be a part of "isPartialOrder", shouldn't it?"

Why?

**Comment by benediktahrens** [comment]
On 12/16/2017 10:08 PM, Daniel R. Grayson wrote:
> Re: " the "isaset" condition should be a part of "isPartialOrder", shouldn't it?"
> 
> Why?

This is the least surprising way to state the definition, since the
"isaset" condition is only necessitated by the antisymmetry.

It is hence natural to bundle those two into the property
`isantisymmetric`, and to define a partial order as an antisymmetric
preorder.

**Comment by DanGrayson** [comment]
Well, that's if you want to remember exactly what it is that prevents you from generalizing things to non-sets.  But a more prosaic mode of operation is to just formalize standard mathematics as written previously by humans in text books.  And there we always find that a partially ordered set is a set with a partial ordering of it.

So the current way is the way that makes sense from the point of view of exposition of mathematics as usually written.

We got into a similar sort of trouble when we let Vladimir isolate the condition on a category that the hom's be sets -- it was mathematically strange.

**Comment by benediktahrens** [comment]
On 12/17/2017 01:39 AM, Daniel R. Grayson wrote:
> Well, that's if you want to remember exactly what it is that prevents
> you from generalizing things to non-sets.  But a more prosaic mode of
> operation is to just formalize standard mathematics as written
> previously by humans in text books.  And there we always find that a
> partially ordered set is a set with a partial ordering of it.
> 
> So the current way is the way that makes sense from the point of view
> of exposition of mathematics as usually written.
> 
> We got into a similar sort of trouble when we let Vladimir isolate
> the condition on a category that the hom's be sets -- it was
> mathematically strange.
> 

And still, the notion of `precategory` seems to be useful, e.g., for 
those who consider the precategory of Lawvere theories.

But please proceed as you see fit.

**Comment by DanGrayson** [comment]
Thanks, closing.
