### ISSUE TITLE
Issue compiling Coq 8.7.1

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#847]
I had some issues compiling Coq 8.7.1 with UniMath. If I run `make` I get the following error while compiling Coq:

```
bin/coqtop -boot  -native-compiler -compile theories/Init/Notations.v  -noinit -R theories Coq  
opt: unknown option '-Oclassic'.
File "./theories/Init/Notations.v", line 96, characters 0-40:
Warning: Native compiler exited with status 2
[native-compiler-failed,native-compiler]
Warning: Removed file ./theories/Init/Notations.vo

Error: Could not compile the library to native code.
```

I fixed this manually by running `./configure -local -coqide no -native-compiler no` in sub/coq and recompiling using the Coq Makefile. I'm using ocaml 4.05.0-1.

Anyone else had this problem? Should I file an issue over at the Coq github page?

**Comment by abooij** [comment]
This looks like a `make clean` in the coq subdirectory would have helped as well.

**Comment by mortberg** [comment]
I tried that. I also tried `rm -rf sub/coq` and then re-download. It didn't help. It looks like the issue is with the "native compiler"...

**Comment by abooij** [comment]
I did not have your problem compiling the coq in the git submodule using ocaml 4.05.0-1 (Arch Linux).

**Comment by mortberg** [comment]
Very strange! I also use Arch Linux and I have the same version of ocaml... Let's see if someone else have any problem.

**Comment by rmatthes** [comment]
I have another issue compiling CoqIDE, i.e., with `make  BUILD_COQIDE=yes`. This is on Ubuntu 16.04 LTS (the current one), which has Ocaml 4.02.3 (no problem for compiling all for ProofGeneral).
The crucial lines seems to be:
`make -w -C sub/coq KEEP_ML4_PREPROCESSED=true VERBOSE=true READABLE_ML4=yes coqide-binaries bin/coqide`
make[1] : on entre dans le répertoire « [...]UniMath/sub/coq »
make --warn-undefined-variable --no-builtin-rules -f Makefile.build coqide-binaries bin/coqide
make[2] : on entre dans le répertoire « [...]UniMath/sub/coq »
Error: no rule to make target coqide-binaries (or missing .PHONY)

I do not use CoqIDE, so I cannot say when this misbehaviour started.

**Comment by abooij** [comment]
@rmatthes, does `make clean` inside `sub/coq/` help for you?

**Comment by DanGrayson** [comment]
The thorough way to clean is this command in the top level UniMath directory:
```
make INCLUDE=no git-clean
```

**Comment by rmatthes** [comment]
@abooij: I simply deleted the subdirectory before doing the Git operations.

I'll check Dan's advice and also on my Debian 10 installation at home.

**Comment by rmatthes** [comment]
Same problem with Debian 10, which also has Ocaml 4.02.3.

**Comment by DanGrayson** [comment]
I can't reproduce the original problem with Ubuntu 16.04 and with ocaml 4.05.0 installed with opam.

Anders, what OS are you on?

**Comment by mortberg** [comment]
I'm on Arch Linux. As @abooij is on the same OS and has no problem I'll close this. I probably did something hackish a long time ago that I can't remember which is now giving me trouble...

**Comment by mortberg** [comment]
I figured out the problem! There was an issue with the version of the `aspcud` solver I had which made `opam` say something like "External solver failed with inconsistent return value". I googled this and 
found https://github.com/ocaml/opam/issues/2203. I installed two more solvers (`gringo` and `clasp`) and everything works like a charm now.

**Comment by DanGrayson** [comment]
Great!

I don't seem to find proofgeneral in arch linux, despite this: https://aur.archlinux.org/packages/proofgeneral/

How did you get it?

**Comment by abooij** [comment]
@DanGrayson, The version you linked is what I use. It is quite common to use packages from the AUR, especially for somewhat more exotic software. It is quite useful to have a tool installed to help with installing AUR packages, such as `cower` or `yaourt`.

**Comment by DanGrayson** [comment]
Okay, how do I get it installed, if `pacman -Ss proofgeneral` doesn't find it, and `pacman --sync --needed proofgeneral` doesn't install it?

**Comment by DanGrayson** [comment]
@mortberg -- I just succeeded in having UniMath compile Coq under Arch Linux, with no problem.  I'll add a section to the INSTALL file for Arch Linux.

**Comment by abooij** [comment]
@DanGrayson, For installing AUR packages, it's easiest to use a tool like `cower` or `yaourt`. You'll have to install one of these packages manually. See e.g. the description on the [Arch wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages).

**Comment by DanGrayson** [comment]
Ah, well, I might as well just install ProofGeneral manually, in that case.  It's easy to do.
