### ISSUE TITLE
Change "isaprop" to "isatruthvalue"

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#87]
I suggest to change all of the occurrences of "isaprop" throughout UniMath to "isatruthvalue".

This will make some things a little long - later we can come up with convenient abbreviation - tvalue? 

I think it is philosophically correct to call types of h-level 1 truth-values (or even univalent truth-values as later we may also have strict truth values as types where all object are definitionally equal).

**Comment by benediktahrens** [comment]
On 04/03/2015 07:10 PM, Vladimir Voevodsky wrote:
> 
> I think it is philosophically correct to call types of h-level 1
> truth-values (or even univalent truth-values as later we may also
> have strict truth values as types where all object are definitionally
> equal).

Is it more correct than calling them propositions?

We do have a lot of code, both in UniMath as well as in other
repositories depending on UniMath - I have 3 repositories with code
depending on UniMath.
Changing "isaprop" to something else also means changing the names of
lemmas, and even though one can probably automate the search & replace,
it still costs some time to do that in all the repositories.
It would be good if that aspect were considered when thinking about
changing something in UniMath.
One solution would be to keep the old names as aliases for the new
names, but we also want to avoid a proliferation of names for one and
the same thing.

If we want anyone to use UniMath, we should keep backwards-incompatible
changes to a minimum, and have a good reason for any such change.

Benedikt

**Comment by vladimirias** [comment]
I agree with all your points and suggest that we have a reflection period for this of two weeks.

I am certainly thinking about automated change. This particular one should be really easy. Dan can probably write a script for doing it in all files in all subdirectories.

I also think that we should be aware of the work involved in adapting the higher level repositories to changes in the lower levels of UniMath and at the same time we should not lock ourselves away from being able to make such changes.

V.

**Comment by DanGrayson** [comment]
The mechanics of making such a change with emacs is easy.  One uses the
TAGS file created by "make" along with the emacs command M-x tags-query-replace .

**Comment by DanGrayson** [comment]
Suppose we make that change.  Then what use of the word "proposition" do we envision?  I'm thinking not of our code but of our mathematical speech.

**Comment by vladimirias** [comment]
> On Apr 8, 2015, at 8:46 PM, Daniel R. Grayson <notifications@github.com> wrote:
> 
> Suppose we make that change. Then what use of the word "proposition" do we envision? I'm thinking not of our code but of our mathematical speech.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/UniMath/UniMath/issues/87#issuecomment-91079786>.
> 
I do not know yet. There are some very interesting ideas by Fedor Part (cc-ed) about using a form of logic enriched type theory to be able to define structures such as semi-simplicial types. In general we do want strict Prop and something like subsets in Nuprl.

Vladimir.

**Comment by DanGrayson** [comment]
If there's a chance the "proposition" will still mean h-level 1 in the future, as it does now, then why not stick with isaprop until that's no longer true?

**Comment by vladimirias** [comment]
There is certainly no hurry with it. But it seems philosophically more correct to call type of h-level 1 “truth values” and leave this whole “propositions as types” business outside of our terminology.

There are mappings from propositions to types - various ones, but that does not make types into propositions or propositions into types.

**Comment by DanGrayson** [comment]
That's a good argument.  In other words, "proposition" may mean different things to different people, so we don't declare a stand on that.

For something briefer than "isatruthvalue" I recommend "isatval", which has the same length as "isaprop".  I'd be happy to implement that change using emacs, as I mentioned.  I've just checked that "isatval" is not present in our files now.

**Comment by benediktahrens** [comment]
Yes, you are right, we should be able to do changes to UniMath, even if
they are not backwards-compatible.
Please proceed as you see fit.

It would be good to have a list of the changes, in the form

old_name -> new_name

or similar. That would help adapting other repositories.

Benedikt

**Comment by benediktahrens** [comment]
I suggest collecting a few things that we want to rename in the whole of UniMath, and then do all of those renamings at once, when enough such suggestions are there.
Here is one that should be changed for precategories:

Suggestion by PLL: rename 
has_hom_sets -> isaset_homs

**Comment by DanGrayson** [comment]
How about all names containing "conus"?

**Comment by DanGrayson** [comment]
How about all names containing "weq", on the grounds that our equivalences
are not "weak"?

**Comment by DanGrayson** [comment]
How about ensuring consistent etymology?  Example: in "total2asstor" "ass"
refers to associativity,
but in "natplusassoc" it's "assoc".

**Comment by DanGrayson** [comment]
As a matter of style, I propose eliminating all spaces to the right of "("
and all
spaces to the left of ")" or ".".

**Comment by DanGrayson** [comment]
In "total2_paths_isaprop_equiv" it's "equiv" instead of "weq", so it's an
inconsistency.
We could replace all "weq" inside names by "equiv".

**Comment by DanGrayson** [comment]
What about changing "hz" to "ZZ", on the grounds that "h" adds no
information?  Similarly
for other gratuitous uses of "h", as in "hProp", "hSet" and "hq".

**Comment by DanGrayson** [comment]
... except Prop and Set are in the base system, so perhaps we stick with
hProp and hSet.

**Comment by vladimirias** [comment]
I think that we can resolve these renaming questions more efficiently in the fall at the IAS when we can discuss them in person.

**Comment by DanGrayson** [comment]
Okay.

**Comment by vladimirias** [comment]
The previous suggestions all sound good. About these ones I am not so sure. This particular way to define integers uses set-quotients that are defined using hProp. hProp itself is based on the concept of h-level. There are other variants of Prop such as strict Prop based on the use of strict equality in the proof-irrelevance condition. While we can not define strict Prop in the present version of Coq it will hopefully become possible in the future.

**Comment by DanGrayson** [comment]
That sounds like a good reason to keep hProp and hSet.  Are those what you were referring to with "these ones"?  Or do you think we might have a whole series of homotopy and strict pairs: hz and z, hq and q, etc.?

**Comment by vladimirias** [comment]
There can be many models for integers (e.g. we are going to start working next year on making the standard library compatible with the UniMath so the z from the standard library will become one of the possibilities). The same applies to hq.

**Comment by DanGrayson** [comment]
Okay.

**Comment by vladimirias** [comment]
Wait. Are we making the change now? Then we should at least leave “isaprop” as a notation. It is just so much shorter and while it might be philosophically more correct to say “isatruthvalue” it is longer to type.

**Comment by DanGrayson** [comment]
I don't know if we're making any changes now.  You said something about postponing until the Fall.

**Comment by DanGrayson** [comment]
Why not use "isatval" instead of "isatruthvalue"?  It's just as short as "isaprop".

**Comment by DanGrayson** [comment]
I would prefer to leave isaprop alone, since we like it, and forget about "truthvalue".

**Comment by vladimirias** [comment]
I am actually reluctant to make any such changes. There is really no need in them and it will only confuse people who have started to learn UniMath.

Changing has_hom_sets to isaset_hom is probably Ok since it has not been, yet, deeply integrated in other names and has not become familiar to many people. Changing “isaprop” is probably too much of a disruption.

I know I have suggested it myself as a result of one of those silly arguments on the HoTT list, but now, I feel that it was a bad idea.

**Comment by vladimirias** [comment]
We are in agreement then! Great.

**Comment by DanGrayson** [comment]
Great!

**Comment by DanGrayson** [comment]
The previous discussions about the term "proposition" seemed rather mild to me, and I like being able to say that type theory subsumes the notions of proposition and set.  So am glad we've decided to keep "isaprop".

I'm not much concerned about confusing people who have learned UniMath already, because there probably aren't many of them, and there are thousands of names, of which only a minority will have been learned by a typical user.
