### ISSUE TITLE
conflicting notations

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#879]
fix the conflicting notation declarations

    Reserved Notation "A ⇒ B" (at level 95, no associativity).
    Reserved Notation "c ⇒ X" (at level 50).

The latter is in the Ktheory package, so try to change it.

**Comment by siddharthist** [comment]
Was this fixed? https://github.com/UniMath/UniMath/pull/1015/files#diff-6b36ac8943037c02bf51cd57f739ce7fL113

**Comment by DanGrayson** [comment]
Yes, I fixed that, thanks!
