### ISSUE TITLE
Coqdoc html broken: no links, no fully qualified module names in TOC

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#890]
- links are not generated
- module names are not fully qualified in TOC

Reason, most likely, is that options are not passed to coqdoc properly.

**Comment by benediktahrens** [comment]
I have no clue why this has stopped working. I think the problem started with our switch to Coq8.7.
@DanGrayson could you look into this?

**Comment by DanGrayson** [comment]
Okay, I'll take a look ...

**Comment by benediktahrens** [comment]
Thanks for #892. 
The `html` target seems broken, too. This is a target from the included Makefile, not our own.

**Comment by DanGrayson** [comment]
Thanks, I've improved #892 to take care of that properly.
