### ISSUE TITLE
a weaker AC that doesn't imply LEM

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#897]
I asked Martín Escardó: "what if we replace AC by a new axiom AC' that splits only surjections X ↠ Y of types where Y has decidable equality? Then AC' does not imply LEM (I hope), and accepting it would be more comfortable. Moreover, AC' + LEM ⇒ AC, we get all the theorems we had before, but we have to cite two axioms instead of 1.  What about the Well Ordering Axiom? If every set can be well ordered, does that imply LEM?"

His reply: "Fred Richman mentioned this AC' axiom to me. He asked whether this already implies LEM (doubting it). The well ordering theorem should be equivalent to AC."

I intend to add this weaker axiom and see what happens.

**Comment by dimtsem** [comment]
I was wondering about *exactly* the principle which you call AC’ yesterday before my pull request when I realised that I will have to work with types with decidable equality and therefore asked myself whether imposing the split surjection form of the axiom of choice for only those types would suffice to prove the axiom of choice for ZF structures, without implying LEM. 

So this makes a lot of sense to me, and would be great to have. I also believe it should not imply LEM, though I have not thought about it much.

(I am interested in contributing to this if you need or want.)
