### ISSUE TITLE
minusgeh0 is useless

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#9]
minusgeh0 is useless because every nat is ge 0.

Definition minusgeh0 ( n m : nat ) ( is : natgeh n m ) : natgeh ( n - m ) 0%nat.

See

https://github.com/UnivalentMathematics/Foundations/blob/master/Packages/Foundations/hlevel2/hnat.v#L636

**Comment by abooij** [comment]
Looks like this was fixed in c1a68c12

**Comment by DanGrayson** [comment]
Maybe so.

Starting with `Definition natgehandminuslinv` there are about 225 lines commented out, including a proof that uses the useless `minusgeh0`.  What is that about?

**Comment by abooij** [comment]
This code was originally added in 736d9f714 as a comment, that is, before the removal of `minusgeh0` in c1a68c1. This code has always been a comment.

(I traced this all back using `git blame`.)

**Comment by DanGrayson** [comment]
Thanks!

I'll eventually take a look at the commented-out proofs, to see whether the comment should be deleted, and then we could resolve this issue.
