### ISSUE TITLE
testing with modern coq

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#930]
See issue #921 - Coq is tested against UniMath, so
our travis testing should ensure that UniMath builds also with the forthcoming version
of Coq, as well as with the past one.  For example, from coq 8.7 to 8.8 there is a change 
in the way the coq_makefile program works, and thus a change to our Makefile could break
the building.

**Comment by DanGrayson** [comment]
@Zimmi48 & @SkySkimmer  --  If we test UniMath also against a modern version of Coq in our travis testing, should it be the master branch of Coq?  Or is that too fragile?

**Comment by SkySkimmer** [comment]
Master should be fine, since we test unimath it should not get broken.
