### ISSUE TITLE
Remove duplicates invmap_eq and pathsweq1

### ISSUE THREAD

**Issue by langston-barrett** [UniMath/UniMath#951]
In `Foundations.PartA`:
```coq
Definition pathsweq1 {X Y : UU} (w : X ≃ Y) (x : X) (y : Y) :
  w x = y -> x = invmap w y
  := λ e, maponpaths pr1 (pr2 (weqproperty w y) (x,,e)).
```
In `Morefoundations.PartA`:
```coq
Lemma invmap_eq {A B : UU} (f : A ≃ B) (b : B) (a : A)
  : b = f a → invmap f b = a.
Proof.
  intro H.
  apply (invmaponpathsweq f).
  etrans. apply homotweqinvweq. apply H.
Defined.
```
Neither name is very good, but the second is considerably better.

**Comment by arnoudvanderleer** [comment]
@benediktahrens What would be a good resolution of this issue, since Foundations is not to be changed?

**Comment by benediktahrens** [comment]
@arnoudvanderleer : the constructions are not strictly the same, so I would not consider them redundant. My suggestion would be to close this issue.
