### ISSUE TITLE
Problem with the definition of subrig

### ISSUE THREAD

**Issue by siddharthist** [UniMath/UniMath#957]
I think the definition of a subrig is mistaken. In particular, it asks that the subtype is a submonoid with respect to _both_ addition and multiplication. This means that the subrig has to share a multiplicative identity with the parent rig. In particular, I can't define the trivial subrig that consists only of 0:
```coq
Definition trivialsubrig (X : rig) : @subrig X.
  intros X.
  use subrigpair.
  - intros x; use hProppair.
    + exact (x = 0)%rig.
    + apply setproperty.
  - cbn.
    split.
    + use issubmonoidpair.
      * intros a b; cbn.
        abstract (rewrite (pr2 a), (pr2 b); apply riglunax1).
      * reflexivity.
    + use issubmonoidpair.
      * intros a b; cbn.
        abstract (rewrite (pr2 a), (pr2 b); apply rigmult0x).
      * cbn.
        Set Printing All.
```
Am I mistaken/misunderstanding?

I believe the solution is to ask for a submonoid under +, but only ask for closure under *.

**Comment by siddharthist** [comment]
This came up when attempting to define ideals as subrigs closed under multiplication by rig elements. I was following Dummit and Foote, who use the weaker condition that the subset is a rig under the same operations (not necessarily with the same identity).  After reading the Wikipedia page, I see that either definition is commonly used, so I'll just adjust my definition of an ideal instead.

**Comment by DanGrayson** [comment]
Since 1 is part of the structure of a rig, it seems mandatory for subrigs to share it.
