### ISSUE TITLE
Upstream code on foundations and categories from UniMath/TypeTheory

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#980]
The file https://github.com/UniMath/TypeTheory/blob/master/TypeTheory/Auxiliary/Auxiliary.v contains stuff on
- Foundations (equivalences of types, transport
- Adjunctions and equivalences of categories
which should be upstreamed asap, to avoid (further) duplication of efforts (see #955 ).

**Comment by benediktahrens** [comment]
@siddharthist : would you be interested in upstreaming the category-theoretic part? I suggest merging your PR #955 first, and then you could replace, e.g., your composition-of-adj-eqs-is-adj-eq with the more general result from UniMath/TypeTheory.

**Comment by siddharthist** [comment]
Yes, I would!

And no worries on the previously-done results -- that was an exercise from a textbook that I wanted to complete, rather than a lemma I wanted to establish merely to move on to something using it.

**Comment by arnoudvanderleer** [comment]
@benediktahrens Has this been resolved by these pull requests?

**Comment by benediktahrens** [comment]
@arnoudvanderleer : I think this issue can be closed. If necessary, a new one on the same topic can be opened.
