### ISSUE TITLE
Reading Group Suggestions

### ISSUE THREAD

**Issue by gilbo** [UniMath/UniMath#984]
Hi all,

I'm sorry to post this as an issue.  I'm not quite sure where would be better to go with it.

I'm trying to run a reading group on the HoTT book using Coq (preferably unmodified) in order to "follow along" and do exercises.  I've figured out a lot of details (I'm definitely not a Coq wizard) but the universe management seems a bit mind-boggling.  In particular, I'm using the incantations from the beginning of the `Unimath/Foundations/Preamble.v` (I think I have that right)

```
Definition UU := Type.
Identity Coercion fromUUtoType : UU >-> Sortclass.
```

I went through and redefined all the basic types from Chapter 1 and so on using `UU` to avoid being pushed back into `Prop`, but I regularly run into messages about not being able to unify a type variable (eg `?T`) with `UU` or `Type`.  In particular, I can't form the relatively basic type `nat = nat` once both `=` and `nat` have been redefined using `UU`.

Do you have any recommendations on other approaches or repositories to refer to that might let us mostly avoid these issues and concentrate on understanding the majority of the material?

**Comment by DanGrayson** [comment]
What command line arguments do you give to Coq?  We use these, and some are needed:
```
-noinit -indices-matter -type-in-type -w -notation-overridden,-local-declaration,+uniform-inheritance,-deprecated-option -Q /Users/dan/src/ProofChecking/UniMath/UniMath UniMath
```
Replace /Users/dan/src/ProofChecking/UniMath by the correct path to the directory.

**Comment by gilbo** [comment]
I've just been using whatever emacs (spacemacs really) and proof general feed by default to coqtop.  I will try some of those out and let you know if I'm still getting odd errors.

Thank you for the help.

**Comment by DanGrayson** [comment]
We have provided a file `UniMath/.dir-locals.el` that sets the command line arguments appropriately for ProofGeneral.  Are you somehow avoiding its use?

**Comment by gilbo** [comment]
We're just using this very bare-bones repository I threw together:
https://github.com/gilbo/hott_reading_group

I added a `_CoqProject` file with most of the options you mentioned (I left various warnings on in case they end up being more useful to us pedagogically).  It seems to be working great!

Again, sorry for opening this as an issue here, but thank you so much for the help.

**Comment by arnoudvanderleer** [comment]
Closing this, as it has not seen activity in 6 years, and it seems that most of the questions have been resolved.
Depending on the question, some discussion can be conducted on the UniMath zulip nowadays.
