### ISSUE TITLE
auto and autorewrite

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#998]
Do we want to encourage or discourage the use of auto and autorewrite with or without hint databases (in the style guide at https://github.com/UniMath/UniMath/blob/master/UniMath/README.md )?

On the one hand, it saves proof writers time, so they'll like it.

On the other hand, it might make the proofs more fragile (if the behavior of Coq changes), and it might make it harder to transport UniMath to another proof assistant in the future.

**Comment by arnoudvanderleer** [comment]
Closing, as this should be part of the discussion in #853
